const ModalKeys = {
  login: 'login',
  viewAddress: 'viewAddress',
  feedback: 'feedback',
  feedbackSuccessTip: 'feedbackSuccessTip',
  register: 'register',
  verify_account: 'verify_account',
  createPendingOrderSuccess: 'createPendingOrderSuccess',
  reset: 'reset',
  resetingTips: 'resetingTips',
  depositProcessTips: 'depositProcessTips',
  payDeposit: 'payDeposit',
  sendDetail: 'sendDetail',
  bridgeDetail: 'bridgeDetail',
  receiveDetail: 'receiveDetail',
  browserDetail: 'browserDetail',
  leaveSurvey: 'leaveSurvey',
  transferProcessTips: 'transferProcessTips',
  lock: 'lock',
  unlock: 'unlock',
  signToView: 'signToView',
  choosePair: 'choosePair',
  chooseSwapPair: 'chooseSwapPair',
  switchNetwork: 'switchNetwork',
  registerPair: 'registerPair',
  registerPairProcess: 'registerPairProcess',
  registerToken: 'registerToken',
  cancelAllSpotOrders: 'cancelAllSpotOrders',
  spotOrderDetail: 'spotOrderDetail',
  swapOrderDetail: 'swapOrderDetail',
  gridDetail: 'gridDetail',
  gridFundsDetails: 'gridFundsDetails',
  gridGraph: 'gridGraph',
  gridMiningPreview: 'gridMiningPreview',
  copyGrid: 'copyGrid',
  dcaDetail: 'dcaDetail',
  dcaOrderDetail: 'dcaOrderDetail',
  personalSignTips: 'personalSignTips',
  exportData: 'exportData',
  m_leftBar: 'm_leftBar',
  m_rightBar: 'm_rightBar',
  m_messages: 'm_messages',
  pairInfo: 'pairInfo',
  swapPairCode: 'swapPairCode',
  swapPoolInfo: 'swapPoolInfo',
  earnMoreInfo: 'earnMoreInfo',
  earnOrderProgress: 'earnOrderProgress',
  earnDepositDetail: 'earnDepositDetail',
  earnWithdrawDetail: 'earnWithdrawDetail',
  earnClaimDetail: 'earnClaimDetail',

  sendOrderProgress: 'sendOrderProgress',
  bridgeUsdcOrderProgress: 'bridgeUsdcOrderProgress',

  assetModal: 'assetModal',
  manageTokens: 'manageTokens',
  manageTokensRemoveConfirm: 'manageTokensRemoveConfirm',
  tokenSitesModal: 'tokenSitesModal',
  fungibleUsdcModal: 'fungibleUsdcModal',
  swapDataWarning: 'swapDataWarning',
  swapQuoteTokenBalance: 'swapQuoteTokenBalance',
  swapSettings: 'swapSettings',

  reset_approval: 'reset_approval',

  terms_of_service: 'terms_of_service',
  tips_common: 'tips_common',
  tips_walletSign: 'tips_walletSign',
  tips_gridCancel: 'tips_gridCancel',
  tips_dcaCancel: 'tips_dcaCancel',
  tips_baseIsNotDefaultToken: 'tips_baseIsNotDefaultToken',
  tips_privyAccountBalance: 'tips_privyAccountBalance',
  tips_hideLimitOrderCanceledByInsufficientFee:
    'tips_hideLimitOrderCanceledByInsufficientFee',
  tips_limitOrderCanceledByPostOnly: 'tips_limitOrderCanceledByPostOnly',
  tips_LimitOrderMinTips: 'tips_LimitOrderMinTips',
  tips_StopLimitOrderMinTips: 'tips_StopLimitOrderMinTips',
  tips_hideMarketOrderCanceledByDepth: 'tips_hideMarketOrderCanceledByDepth',
  tips_incompatibleToken: 'tips_incompatibleToken',
  tips_partiallyFilledByLiquidity: 'tips_partiallyFilledByLiquidity',
  tips_region: 'tips_region',
  tips_eth_gas: 'tips_eth_gas',
  tips_localTime: 'tips_localTime',
  tips_accountChange: 'tips_accountChange',
  err_insufficientFee: 'err_insufficientFee',
  err_insufficientBalance: 'err_insufficientBalance',
  err_insufficientBalance_order: 'err_insufficientBalance_order',
  err_insufficientWalletBalance: 'err_insufficientWalletBalance',
  err_singleQuoteGridFailed: 'err_singleQuoteGridFailed',
  err_urlParse: 'err_urlParse',
  tips_blacklist: 'tips_blacklist',
  tips_signToViewTimeError: 'tips_signToViewTimeError',
  tips_walletBalanceError: 'tips_walletBalanceError',
  tips_DCAMinTips: 'tips_DCAMinTips',
  tips_DCAMinBlock: 'tips_DCAMinBlock',
  tips_userInterview: 'tips_userInterview',
  tips_thirdPartySite: 'tips_thirdPartySite',
  tips_scan: 'tips_scan',
  tips_wrap_wnwrap: 'tips_wrap_wnwrap',
  tips_swap_slippage: 'tips_swap_slippage',
  tips_excessiveBalance: 'tips_excessiveBalance',
  share: 'share',

  miningClaim_list: 'miningClaim_list',
  miningClaim_res: 'miningClaim_res',
  explanations: 'explanations',
  createAirdropRecipientsError: 'createAirdropRecipientsError',
  depthSlippageForCreatingSingleQuoteGrid:
    'depthSlippageForCreatingSingleQuoteGrid',

  privy_initialize: 'privy_initialize',
  tips_SwapMinTips: 'tips_SwapMinTips',
  tips_SwapSlippageTips: 'tips_SwapSlippageTips',
  tips_SwapMaxTips: 'tips_SwapMaxTips',
  tips_depth: 'tips_depth',

  // for app
  APP_CREATE_EARN_ORDER: 'APP_CREATE_EARN_ORDER',
  APP_CREATE_TURBO_RANGE_ORDER: 'APP_CREATE_TURBO_RANGE_ORDER',
  APP_CREATE_BRIDGE_USDC_ORDER: 'APP_CREATE_BRIDGE_USDC_ORDER',
  EARN_CLAIM_MODAL: 'EARN_CLAIM_MODAL',

  // for raffle
  insufficientPoints: 'insufficientPoints',
  ticketUnavailable: 'ticketUnavailable',
  ticketUnavailableList: 'ticketUnavailableList',
  raffleManualCheck: 'raffleManualCheck',
  raffleManualSuccess: 'raffleManualSuccess',
  raffleRangeCheck: 'raffleRangeCheck',
  raffleRangeSuccess: 'raffleRangeSuccess',
  raffleRandomGenerate: 'raffleRandomGenerate',
  raffleRandomCheck: 'raffleRandomCheck',
  raffleTickets: 'raffleTickets',
  raffleTeamTickets: 'raffleTeamTickets',
  raffleTotalTickets: 'raffleTotalTickets',
  raffleInviteTips: 'raffleInviteTips',
  raffleMyInvites: 'raffleMyInvites',
  raffleMyWinnings: 'raffleMyWinnings',
  raffleHistory: 'raffleHistory',
  rafflePoints: 'rafflePoints',
  rafflePointsTips: 'rafflePointsTips',
  raffleRules: 'raffleRules',
  firstTimePointsNotication: 'firstTimePointsNotication',
  roundResultDetail: 'roundResultDetail',
  roundResultSoloDetail: 'roundResultSoloDetail',
  roundResultTeamDetail: 'roundResultTeamDetail',
  raffleClaimRewards: 'raffleClaimRewards',
  raffleClaimRewardsSuccess: 'raffleClaimRewardsSuccess',
  raffleCreateTeam: 'raffleCreateTeam',
  raffleInviteTeam: 'raffleInviteTeam',
  raffleClaimTeamUpRewards: 'raffleClaimTeamUpRewards',
  raffleRewardTicketsGenerate: 'raffleRewardTicketsGenerate',
  raffleRewardTicketsClaimSuccess: 'raffleRewardTicketsClaimSuccess',
  raffleRewardTicketsClaimFailed: 'raffleRewardTicketsClaimFailed',
  raffleTeamDetails: 'raffleTeamDetails',
  rafflePoolPoints: 'rafflePoolPoints',
  raffleTeamPointsBreakdown: 'raffleTeamPointsBreakdown',
  raffleFlashEntryDetail: 'raffleFlashEntryDetail',
  raffleFlashVerifyResults: 'raffleFlashVerifyResults',
  raffleFlashOP: 'raffleFlashOP',
  raffleFlashOPInvite: 'raffleFlashOPInvite',
  raffleFlashOPOffer: 'raffleFlashOPOffer',
  raffleFlashOPFreeEntries: 'raffleFlashOPFreeEntries',

  kol_claim: 'kol_claim',
  kol_claim_history: 'kol_claim_history',
  kol_claim_success: 'kol_claim_success',

  INSUFFICIENT_FUNGIBLE_USDC: 'INSUFFICIENT_FUNGIBLE_USDC',
  sync_da_tips: 'sync_da_tips',
  usdc_supplied_chart_modal: 'usdc_supplied_chart_modal',

  tips_xstocks: 'tips_xstocks',

  // for copy trade
  tips_sol: 'tips_sol',

  turboRangeSetPriceRange: 'turboRangeSetPriceRange',
  turboRangeSetPriceRangeWEB: 'turboRangeSetPriceRangeWEB',
  turboRangeDepositProgress: 'turboRangeDepositProgress',
  turboRangeWithdrawProgress: 'turboRangeWithdrawProgress',
  turboRangeClaimProgress: 'turboRangeClaimProgress',
  turboRangeDetail: 'turboRangeDetail',
  turboRangeDepositDetail: 'turboRangeDepositDetail',
  turboRangeIncreaseInvestmentDetail: 'turboRangeIncreaseInvestmentDetail',
  turboRangeRewardDetail: 'turboRangeRewardDetail',
  turboRangeWithdrawDetail: 'turboRangeWithdrawDetail',
  turboRangeClaimConfirm: 'turboRangeClaimConfirm',
  turboRangeWithdrawConfirm: 'turboRangeWithdrawConfirm',
  turboRangeFAQ: 'turboRangeFAQ',
  turboRangeOutOfRangeTips: 'turboRangeOutOfRangeTips',
  turboRangeIncreaseInvestment: 'turboRangeIncreaseInvestment',
  turboRangeIncreaseProgress: 'turboRangeIncreaseProgress',
  turboRangeApyBacktest: 'turboRangeApyBacktest',
  turboRangePositionHistory: 'turboRangePositionHistory',
  turboRangeStrategyDetail: 'turboRangeStrategyDetail',
  turboRangeCreatePosition: 'turboRangeCreatePosition',
  turboRangeHourlyBreakdown: 'turboRangeHourlyBreakdown',
  turboRangeMoreMenu: 'turboRangeMoreMenu',

  bridgeUsdc: 'bridgeUsdc',
  bridgeUsdcChooseToken: 'bridgeUsdcChooseToken',
  bridgeUsdcProgress: 'bridgeUsdcProgress',
  send: 'send',
  sendV2: 'sendV2',
  receiveV2: 'receiveV2',
  ADDRESS_SCANNER: 'ADDRESS_SCANNER',
  estNetworkFeeDetail: 'estNetworkFeeDetail',
  chooseGasToken: 'chooseGasToken',
  insufficientGasPayTokenBalanceTips: 'insufficientGasPayTokenBalanceTips',
  insufficientGasPayTokenBalanceTipsForSwap:
    'insufficientGasPayTokenBalanceTipsForSwap',

  tips_intent_error: 'tips_intent_error',
  chooseUsdc: 'chooseUsdc',
  chooseUsdcWEB: 'chooseUsdcWEB',

  addFunds: 'addFunds',
  privateClientDesk: 'privateClientDesk',
  privateClientDeskHideEntryConfirm: 'privateClientDeskHideEntryConfirm',

  balanceManageMenu: 'balanceManageMenu',
  filterNetwork: 'filterNetwork',

  // Wallet confirmation modals (migrated from dg-wallet)
  WALLET_TURBO_RANGE_CONFIRM: 'WALLET_TURBO_RANGE_CONFIRM',
  WALLET_SWAP_CONFIRM: 'WALLET_SWAP_CONFIRM',
  WALLET_EARN_CONFIRM: 'WALLET_EARN_CONFIRM',
  WALLET_SEND_CONFIRM: 'WALLET_SEND_CONFIRM',
  WALLET_SIGNING_PROGRESS: 'WALLET_SIGNING_PROGRESS',
  WALLET_AUTO_LOCKED: 'WALLET_AUTO_LOCKED',
  WALLET_UPCOMING_LOCK: 'WALLET_UPCOMING_LOCK',
  WALLET_VIEW_ADDRESS: 'WALLET_VIEW_ADDRESS',
  WALLET_RECEIVE: 'WALLET_RECEIVE',

  // UED: Connect Wallet via JSON paste
  ued_connect_wallet: 'ued_connect_wallet',
};

export default ModalKeys;
