const DeGateTerms = 'https://app.degate.com/terms';
const PrivyTerms = 'https://www.privy.io/user-terms-of-service';

const en = {
  language: 'en-US',
  choose_token: 'Choose Token',
  recipient: 'Recipient',
  recent: 'Recent',
  price: 'Price',
  amount: 'Amount',
  available: 'Available',
  gas_fee: 'Gas Fee',
  Send: 'Send',
  Send_ETH: 'Send ETH',
  Internal_Transfer: 'Internal Transfer',
  transfer_tips:
    'Transfer token to another address within the DeGate Protocol.',
  transfer_ETH: 'Internal Transfer ETH',
  btn_max: 'Max',
  degate_insufficient_balance: 'Insufficient balance',
  max_digits_exceeded: 'Max digits exceeded',
  wallet_insufficient_balance: 'Insufficient balance in wallet',
  deGate_insufficient_fees: 'Insufficient DeGate Balance to pay for Gas Fee',
  token_search_placeholder: 'Search token, contract address',
  token: 'Token',
  degate_balance: 'DeGate Balance',
  tips_gas:
    'The gas fee for executing this on-chain transaction will be deducted directly from your DeGate balance.',
  tips_gas2:
    'Gas Fee covers on-chain costs for trade settlements. Excess fees are refunded.',
  Close: 'Close',
  Help: 'Help',
  no_token: 'Token Not Found',
  Cancel: 'Cancel',
  go_back: 'Go Back',
  Back: 'Back',
  copied: 'Copied',
  Confirm: 'Confirm',
  Create: 'Create',
  Abort: 'Abort',
  btn_confirm: 'Close',
  btn_got_it: 'Got it',
  wallet_cancelled_tips: 'You canceled the signature',
  connect_ledger: 'Connect Ledger',
  ledger_disconnect:
    "Failed to execute 'transferOut' on 'USBDevice': The device was disconnected.",
  wallet_tips: 'Please approve in browser wallet',
  wallet_ledger_tips: 'Please approve in Ledger hardware',
  wallet_metamask_tips: 'Please approve in MetaMask',
  wallet_walletconnect_tips:
    'Please go to your wallet to approve with WalletConnect',
  view_asset_key: 'View Asset Key',
  export_key_warning:
    'A leak of the Asset Key can result in asset loss. Please ensure its safekeeping.',
  export_key_confirm_btn: 'Continue to View',
  btn_buy_ETH: 'Buy ETH',
  btn_sell_ETH: 'Sell ETH',
  around: '~ ',
  need_help: 'Help',
  time_now: 'now',
  time_S_second: 'Ss',
  time_1_minute: '1 minute',
  time_1_hour: '1 hour',
  time_1_day: '1 day',
  time_1_year: '1 year',
  time_M_minutes: 'M minutes',
  time_M_m: 'Mm',
  time_H_hours: 'H hours',
  time_H_h: 'Hh',
  time_D_days: 'D days',
  time_D_d: 'Dd',
  time_Y_years: 'Y years',
  time_Y_y: 'Yy',
  personal_sign_reason: 'Possible Reasons',
  personal_sign_reason1: '1. MetaMask is connected to hardware wallet',
  personal_sign_reason2: '2. MetaMask version is outdated',
  personal_sign_reason3: '3. Others',
  personal_sign_btn: 'Sign Again',
  switch_wallet: 'Switch Account',
  switch_walletConnect_tips1:
    'If you wish to switch to another account in the same wallet software, please perform it directly from the wallet and cancel this request.',
  switch_walletConnect_tips2:
    'If you wish to use WalletConnect through a different wallet software, the system will disconnect from the existing connection first.',
  switch_walletConnect_continue: 'Disconnect and Continue',
  switch_metamask_tips: 'Please go to MetaMask to switch account.',
  switch_browser_wallet_tips: 'Please switch account in browser wallet.',
  period_expired: 'Expired',
  period_D_day_H_hour: 'Dd Hh',
  period_H_hour_M_minute: 'Hh Mm',
  login_success: 'Connect Success',
  advanced: 'Advanced',
  edit: 'Edit',
  save: 'Save',
  speed_up: 'Speed Up',
  continue: 'Continue',
  Submit: 'Submit',
  icon_copy: 'Copy address',
  icon_view_explorer: 'View on block explorer',
  upcoming_lock_tips:
    'Due to a period of inactivity, the Signature-free mode will be turned off for your security.',
  auto_locked_tips:
    'For your security, the Signature-free mode has been turned off after 15 minutes of inactivity.',
  keep: 'Keep',
  turn_off_now: 'Turn off Now',
  turn_on: 'Turn on',
  turn_on_signature_free_mode: 'Turn on Signature-free mode',
  turn_on_signature_free_mode_success: 'Signature-free Mode On',
  max_XXX: 'Max XXX',
  min_XXX: 'Min XXX',
  common_err: 'Something went wrong. Please try again later.',
  input_auto_corrected_tips:
    'Auto corrected your input after exceeding the maximum number of digits',
  maximum_decimal_reached: 'Maximum decimal places reached',
  verify_ownership: 'Verify Ownership',
  execute: 'Execute',
  sign_step1: 'Complete in Your Wallet',
  sign_step2: 'Complete 2nd Signature',
  sign_step3: 'Complete 3nd Signature',
  place_order: 'Place Order',
  create_spot_order: 'Place Order',
  create_grid_strategy: 'Create Grid Strategy',
  create_DCA_plan: 'Create DCA Plan',
  cancel_order: 'Cancel Order',
  end_grid_strategy: 'End Grid Strategy',
  end_DCA: 'End DCA Plan',
  complete_in_seconds: 'Complete in seconds',
  complete_in: 'Complete in ',
  me: 'me',
  eth_code_tips: 'Native token of Ethereum. No token contract address.',
  total: 'Total',
  order_amount: 'Order Amount',
  operation_has_expired: 'Operation has expired',
  Approve: 'Approve',
  tips_hide_forever: 'Don’t show again',
  Tips: 'Tip',
  Note: 'Note',
  Summary: 'Summary',
  Orders: 'Orders',
  Side: 'Side',
  Sell: 'Sell',
  Buy: 'Buy',
  now: 'Now',
  order_type: 'Order Type',
  limit_order: 'Limit',
  market_order: 'Market',
  required: 'Required',
  check_address_format: 'Check address format',
  start_time: 'Start Time',
  end_time: 'End Time',
  None: 'None',
  time_out: 'Time out. Please retry.',
  deposit_ETH: 'Add ETH',
  'ledger.connect_rule_1': '1. Connect Ledger to your device',
  'ledger.connect_rule_2': '2. Unlock in Ledger',
  'ledger.connect_rule_3': '3. Open Ethereum app in Ledger',
  'ledger.connect_rule_4':
    '4. Make sure Blind Signing/Contract Data and Browser Support are enabled',
  'ledger.unable_to_approve': 'Unable to Approve',
  'ledger.webusb_1tab_tips_desc_1':
    'This browser only supports a single "browser tab" for Ledger approval. Unable to approve as another tab is utilizing this feature.',
  'ledger.webusb_1tab_tips_desc_2':
    'Please try replugging the Ledger to restart the operation.',
  'ledger.locked_tips':
    'Please unlock Ledger, open the Ethereum app, and approve.',
  'ledger.account_not_match':
    'Wrong Ledger wallet detected. Please connect to the correct Ledger.',
  'ledger.ledger_choose_address': 'Choose an Address',
  'ledger.address': 'Address',
  'ledger.connect': 'Connect',
  'ledger.un_supported_title':
    'Ledger wallet connection not supported by current Browser',
  'ledger.un_supported_desc': 'Recommend using Chrome and Edge browsers.',
  'ledger.confirm_gas_fee': 'Confirm Gas Fee',
  'ledger.confirm_gas_fee_desc':
    'You are about to initiate a transaction on Ethereum, please confirm:',
  'ledger.max_gas_fee': 'Max Gas Fee',
  'ledger.edit_gas_fee': 'Edit Gas Fee',
  'ledger.max_fee': 'Gas Price (Gwei)',
  'ledger.max_base_fee': 'Max Base Fee (Gwei)',
  'ledger.max_base_fee_tips':
    'When your transaction gets included in the block, any difference between your max base fee and the actual base fee will be refunded.',
  'ledger.priority_fee': 'Priority Fee (Gwei)',
  'ledger.priority_fee_tips':
    'Priority fee (aka “miner tip”) goes directly to miners and incentivizes them to prioritize your transaction.',
  'ledger.gas_limit': 'Gas Limit:',
  'ledger.tx_speed_up_title': 'Speed Up Transaction',
  'ledger.tx_speed_up_desc':
    'You are about to speed up a transaction on Ethereum, please confirm:',
  'ledger.tx_cancel_title': 'Cancel Transaction',
  'ledger.tx_cancel_desc':
    'You are about to cancel a transaction on Ethereum, please confirm:',
  'ledger.fee_minimum_xxx': 'Cannot be less than XXX',
  'ledger.ledger_app_version_tips':
    "Update your Ledger's Ethereum app to version 1.9.19 or higher to preview the message before signing.",
  'operations.register_pair': 'Add Trading Pair',
  'operations.chain_cancel': 'Cancel Order On-Chain',
  'operations.chain_cancel_title':
    'This order cancellation request will be posted on-chain to guarantee the cancellation of the order.',
  'operations.chain_cancel_confirm': 'Confirm Cancel',
  'operations.chain_cancel_confirm_tips':
    'On-chain cancellation will incur a gas fee. Do you wish to proceed?',
  'operations.chain_cancel_grid_text_N':
    '<b>N orders</b> in this grid strategy will be submitted for on-chain cancellation.',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    'Please confirm again the on-chain cancellation gas fee of <b>AMOUNT ETH</b>.',
  claim_rewards: 'Claim Rewards',
  'operations.claim_desc':
    'Rewards will be credited to your DeGate balance via Internal Transfer, with gas fees deducted directly from the reward amount.',
  'operations.claim_desc_others':
    'This claim will be credited to your DeGate Balance through an internal transfer.',
  'operations.claim_rewards': 'Available Rewards',
  'operations.claim_err_amount': 'Insufficient amount available for claim',
  'operations.claim': 'Claim',
  'operations.Claimable': 'Claimable',
  'operations.Unclaimed': 'Unclaimed',
  'operations.claim_mining_rewards': 'Claim Mining Rewards',
  'operations.claim_rewards_desc':
    'Rewards will be sent to your account after deduction of gas fees',
  'operations.pay_deposit': 'Settlement',
  'operations.pay_deposit_title': 'Pending Payment',
  'operations.pay_deposit_desc_XXX_ETH':
    'You have a pending fund addition of XXX ETH.',
  'operations.pay_deposit_select_account': 'Pay From',
  Wallet_Balance: 'Wallet Balance',
  'operations.pay_deposit_tips_XXX_ETH': 'Pay XXX ETH',
  'operations.reset_account': 'Reset Asset Key',
  'operations.reset_desc':
    "The Asset Key resides in your browser cache. If your local environment's security is in question, please reset asset key.",
  'operations.reset_warning':
    'All operations, such as trading, sending, or internal transferring, are suspended during the reset.',
  'operations.reset_estimated_time': 'Estimated Time',
  'operations.reset_order_tips':
    'Once the reset is initiated, all open orders and grid strategies will be canceled.',
  'operations.reset_order_tips_btn2': 'Cancel',
  'operations.claim_dg_rewards': 'Claim DG Rewards',
  'operations.claim_REBASE': 'Claim REBASE',
  'operations.claim_REBASE_desc':
    'REBASE will be sent to your DeGate Balance via internal transfer.',
  'operations.claim_REBASE_tips':
    'Unclaimed REBASE is factored into the yield calculation.',
  'operations.view_yield_history': 'View Yield History',
  'operations.cancel_orders_on_chain': 'Cancel Orders On-chain',
  'operations.chain_cancel_dca_text_N':
    '<b>N orders</b> in this DCA plan will be submitted for on-chain cancellation.',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    'Please double confirm the on-chain cancellation gas fee of <b>AMOUNT ETH</b>.',
  'transfer.transfer_1_eth_ACCOUNT': 'Transfer 1 ETH to ',
  'transfer.internal_transfer_address_new_tips':
    'This address has no prior DeGate history. Transferring to this address will require additional gas fees.',
  address_placeholder: 'Enter address',
  'transfer.to_new_account_tips':
    'This address has no prior DeGate history. As the first asset receipt initiates additional on-chain data usage, performing this internal transfer will incur extra gas fees.',
  'transfer.confirm_internal_transfer': 'Confirm Internal Transfer',
  'transfer.internal_transfer_address_oneself_tips':
    'Internal transfer to yourself is not supported.',
  'transfer.transfer_max_err_XXX_USDT':
    'Internal transfer is limited to XXX USDT per transfer',
  'transfer.before': 'Before',
  'transfer.after': 'After',
  'transfer.recipient_cex_warning':
    'Warning: Please do not transfer to Centralized Exchange. You will lose the funds.',
  'withdraw.withdraw_max_tips': 'System limit exceeded',
  'dca.confirm_dca_plan': 'Confirm DCA Plan',
  'dca.number_of_orders': 'Number of Orders',
  'dca.amount_per_order': 'Amount per Order',
  'dca.time_scheduled': 'Time Scheduled',
  'dca.creating_the_plan': 'Creating the Plan...',
  'dca.maximum_price': 'Maximum Price',
  'dca.minimum_price': 'Minimum Price',
  'dca.do_not_close': 'Do NOT close or refresh this page.',
  'dca.frequency': 'Frequency',
  total_amount: 'Total Amount',
  'dca.daily': 'Daily',
  'dca.weekly': 'Weekly',
  'dca.every': 'Every ',
  'airdrop.review_airdrop': 'Review Airdrop',
  'airdrop.create_airdrop': 'Create Airdrop',
  'airdrop.recipients_number': 'No. of Recipients',
  'airdrop.airdrop_fee': 'Airdrop Fee',
  'airdrop.pay_airdrop_fee': 'Pay Airdrop Fee',
  'airdrop.send_airdrop_token': 'Send Airdrop Token',
  'airdrop.claim_airdrop': 'Claim Airdrop',
  'airdrop.retrieve': 'Retrieve',
  'countdown.create_countdown_plan': 'Create Countdown Plan',
  'countdown.countdown_display': 'Countdown Display',
  'countdown.max_30_days': 'Cannot be more than 30 days from now',
  'countdown.review_countdown_plan': 'Review Countdown Plan',
  'countdown.countdown_fee': 'Countdown Fee',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    'The system will initially exchange a portion of QUOTE for BASE using a market order, with an estimated slippage of SLIPPAGE.',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    'The system will initially exchange a portion of QUOTE for BASE using a market order, with an estimated slippage of SLIPPAGE. Investing with Dual Asset mode is recommended.',
  connected: 'Connected',
  browser_wallet: 'Browser Wallet',
  Convert_to_YYY: 'Convert to YYY',
  sell_XXX_to_YYY: 'Do you want to sell your XXX into YYY at market price?',
  you_sell: 'You sell',
  you_receive: 'You receive',
  est_receive: 'Est. Receive',
  est_slippage: 'Est. Slippage',
  No: 'No',
  closing_sell: 'Closing Sell',
  connect_wallet: 'Connect Wallet',
  Add: 'Add',
  Add_Funds: 'Add Funds',

  send_USDC_to_this_address: 'Send USDC to this address',
  Failed_to_proceed: 'Failed to proceed.',
  Please_select_the_Ethereum_network: 'Please select the Ethereum network.',
  NATIVE_USDC_ONLY: 'Native USDC token ONLY',
  NEVER_send_bridged_USDC: 'NEVER send bridged USDC',
  Network: 'Network',
  Arrival_Time: 'Arrival Time',
  Token_Contract: 'Token Contract',
  please_select_network: 'Please select network',
  maximum_amount: 'Max. Amount',
  Select: 'Select',
  cannot_send_to_yourself: 'Cannot send to yourself within DeGate network',
  max_amount_exceeded: 'Max. Amount exceeded',
  do_not_trasnfer_to_cex:
    'Please <b>DO NOT</b> transfer to centralized exchanges. You may lose your funds.',
  I_understand: 'I understand',
  Continue: 'Continue',
  chain_0: 'DeGate L2',
  chain_DeGate: 'DeGate L2',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum One',
  chain_421614: 'Arbitrum One',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',

  deposit_tips_region:
    'Please note that you are accessing DeGate in REGION. The trading and internal transfer features are unavailable after fund addition.',
  deposit_1_ETH: 'Add 1 ETH to your DeGate Balance',
  'account.deposit_contract_tips_over_AMOUNT':
    'Fund additions over AMOUNT USD require the Advanced method.',
  'account.deposit_contract_tips_only_all':
    'Only the Advanced method of fund addition is supported',
  Approved: 'Approved',
  'account.deposit_tips': 'You retain full custody of these funds.',
  'account.deposit_arrive_in_30s_s': 'Arrive in ~ 30 seconds',
  reset_approval_USDT: 'Reset USDT Approval',
  reset_approval_USDT_tips:
    'USDT requires resetting approval when spending limits are too low.',
  token_has_not_listed: 'This token has not been listed on DeGate.',
  list_now: 'List Now',
  Retry: 'Retry',
  switch_network: 'Switch Network',
  switch_to_MAINNET_in_metamask: 'Please switch to MAINNET in MetaMask',
  switch_to_MAINNET: 'Please switch to MAINNET',
  'account.pay_deposit_warning': 'Adding funds may incur additional gas fee',

  send_method: 'Method',
  Economy: 'Economy',
  Fast: 'Fast',
  Instant: 'Instant',
  less_than_X_hours: '< X hours',
  less_than_1_hour: '< 1 hour',
  Economy_tips:
    'DeGate processes Send requests at least every 4 hours, often sooner. For instance, if another user initiates a Fast Send, your Economy Send request will be processed immediately as well.',
  wrap: 'wrap',
  just_a_moment: 'Just a moment',
  wait_confirmation_from_wallet: 'Waiting for confirmation from wallet',
  s: 's',

  view_asset_key_tips: `<div>Here are the details of your Asset Key. <strong>Do NOT share</strong> withanyone to prevent potential asset loss.</div>`,
  personal_sign_tips: `<div>MetaMask requests you to sign again with <i>Personal Sign</i> method</div>`,
  sign_and_open_free_mode_tips: `Signing is not required as the Signature-free mode will be turned on after this action.<br /><br />To switch mode, navigate to &quot;Settings&quot; below the Trade Button.`,
  'trade.i_understand': `I understand the &nbsp;`,
  'trade.flow_of_funds_tips': `<h3>Flow of Funds</h3>Funds will go to your DeGate Balance, not yourwallet balance.<br /><br /><h3>About DeGate Balance</h3>DeGate Balance represents the value thatusers hold within the DeGate smart contract.<br />Users maintain complete custody of DeGate Balance thanks to the fullydecentralized DeGate smart contract.`,

  // 1.16
  email: 'Email',
  login_by_email: 'Login by Email',
  powered_by_privy: 'Powered by Privy',
  enter_confirmation_code: 'Enter confirmation code',
  check_email_tips:
    'Please check EMAIL for a message with your confirmation code.',
  did_no_get_an_email: 'Didn’t get an email?',
  resend_code: 'Resend',
  success: 'Success',
  privy_login_success: 'Login Successful',
  invalid_or_expired_verification_code: 'Invalid or expired verification code',
  too_many_requests: 'Too many requests. Please try again later.',
  view_address: 'View Address',
  email_address: 'Email Address',
  wallet_address: 'Wallet Address',
  export_private_key: 'Export Private Key',
  confirmation: 'Confirmation',
  privy_send_tips:
    'Do you confirm to send to the address linked to your Email Login?',
  privy_send_tips2:
    'To access this address, you <b>must</b> export its private key and import it into a third-party wallet, such as MetaMask.',
  Discard: 'Discard',

  // 1.17
  pay: 'Pay',
  receive: 'Receive',
  max_slippage: 'Max. Slippage',
  minimum_receive: 'Minimum Receive',
  available_network: 'Available Network',
  swap_deposit_not_support_yet:
    'Addition of this token is not supported yet; will be enabled in the future.',
  switch_address_tips: 'Do you want to switch address?',
  switch_address_tips_MetaMask: 'Please go to MetaMask to switch address.',
  Settings: 'Settings',

  // 1.20
  sync_to_app: 'Sync to DeGate App',
  sync_to_app_tips:
    'You are about to generate a QR code by signing with your wallet. <b>Do NOT</b> share the QR code with anyone.',
  sync_to_app_rules: 'Ensure the following:',
  sync_to_app_rules_1: '1. No one is nearby.',
  sync_to_app_rules_2: '2. No cameras are around.',
  sync_to_app_rules_3: '3. You are not live streaming or sharing your screen.',
  Generate: 'Generate',
  Scan_from_App: 'Scan from App',
  Scan_from_App_tips:
    'Open the DeGate App, go to "Sign in", select "Sync from DeGate Web," and scan the QR code within 60 seconds.',
  qr_code_expired: 'QR code expired. Please try again.',

  insufficient_degate_balance: 'Insufficient DeGate Balance',
  scan_qr_code: 'Scan QR Code',
  Claim_Commission: 'Claim Commission',
  Free: 'Free',

  send_XXX_to_this_address_ONLY_on_NETWORK:
    'Send XXX to this address <b>ONLY on NETWORK</b>',
  sign_in_with_email: 'Sign in with Email',
  sign_in_with_email_tips: `By signing into DeGate, you agree to the <a href=${DeGateTerms} target="_blank">DeGate’s Terms of Service</a> and <a href=${PrivyTerms} target="_blank">Privy’s Terms of Service</a>.`,

  'ledger.eth_app_not_opened': 'Please open Ethereum app in Ledger',
  'ledger.webusb_1tab_tips_desc_1_new':
    'Another browser tab is accessing your Ledger. Please approve there or reconnect your Ledger to use this tab.',

  connected_via: 'Connected via',
  supported_chains: 'Supported Chains',
  evm_address: 'EVM address',
  CHAIN_address: 'CHAIN address',

  My_CHAIN_Address: 'My CHAIN Address',
  From: 'From',
  To: 'To',
  Select_Network: 'Select Network',
  Route_not_available: 'Route not available',
  Select_Token: 'Select Token',
  Bridge_TOKEN: 'Bridge TOKEN',
  Token_on_DeGate_L2: 'Token on DeGate L2',
  Token_in_your_connected_address: 'Token in your connected address',
  Enter_address_on_CHAIN: 'Enter address on CHAIN',
  Sender: 'Sender',
  L2_Bridge: 'L2 Bridge',
  Receive: 'Receive',

  send_warning: 'DO NOT SEND TO CENTRALIZED EXCHANGE OR YOU WILL LOSE IT.',

  Deposit: 'Deposit',
  Withdraw: 'Withdraw',
  Est_Daily_Rewards: 'Est. Daily Rewards',
  Protocol: 'Protocol',

  // 1.24
  Bridge: 'Bridge',
  multi_chain: 'Multi-chain',
  multi_chain_tips:
    'A multi-chain token enhances user experience by allowing access to investments on any chain without complex fund bridging. It also covers network fees across all chains.',
  My_Address: 'My Address',
  funds_received_to_this_address_are_entirely_self_custodied:
    'Funds received to this address are entirely self-custodied.',
  available_balance: 'Available Balance',
  insufficient_multi_chain_usdc:
    'You don’t have enough <b>multi-chain USDC</b> to pay for the network fee.',
  est_network_fee: 'Est. Network Fee',
  amount_needed: 'Amount Needed',
  maximum_XXX: 'Maximum: $XXX',
  network_fee: 'Network Fee',
  network_fee_updated: 'Network Fee Updated',
  insufficient_USDC_in_your_$CHAIN_address:
    'Insufficient USDC in your $CHAIN address',

  or: 'or',
  Please_enter_a_valid_email_address: 'Please enter a valid email address',
  Copy: 'Copy',
  Invalid_SOL_rent: 'Insufficient SOL for rent',

  signing_in: 'Signing in…',
  This_process_may_take_about_10_seconds:
    'This process may take about 10 seconds.',
  next: 'Next',

  // copy trade
  ct: {
    Transfer_funds_into_your_Copy_Trade_account:
      'Transfer funds into your Copy Trade account?',
    Yes: 'Yes',
    funds_transfer: 'Funds Transfer',

    Deposit_from_CEX_Other_Wallets: 'Deposit from CEX/Other Wallets',
    Top_up_your_DeGate_Wallet: 'Top-up your DeGate Wallet',
    Transfer_funds_into_Copy_Trade_Account:
      'Transfer funds into Copy Trade Account',
    Deposit_into_DeGate_Wallet_then_transfer_into_Copy_Trade_Account_to_get_started:
      '<b>Deposit</b> into DeGate Wallet, then <b>transfer into</b> Copy Trade Account to get started.',
    To_top_up_balance_go_to_1_Deposit_from_CEX_Wallets:
      'To top up balance, go to 1) Deposit from CEX/Wallets.',
    Copy_Trade_Account: 'Copy Trade Account',
  },
  turboRange: {
    Turbo_Range: 'Turbo Range',
    price_range: 'Price Range',
    increase_investment: 'Increase Investment',
  },
  est_account_rent_CHAIN_NUM: '$NUM for CHAIN rent',
  est_transaction_cost_NUM: '$NUM for transaction cost',
  XXX_Refundable: 'XXX Refundable',
  Refundable_on_data_release: 'Refundable on data release',
  est_time: 'Est. Time',
  Mainnet: 'Mainnet',
  Testnet: 'Testnet',
  address_copied: 'Address copied',
  via_email_verification: 'Via Email Verification',
  send_confirmation_code: 'Send confirmation code',

  doc_title:
    'The Easy Way to Earn on Blockchains— No Bridging, No Gas Tokens | DeGate Wallet',
  doc_desc:
    'DeGate is a multichain crypto wallet that gives you easy access to earning opportunities onchain. 100% non-custodial, no gas tokens, no bridging.',
  doc_title_swap: 'Buy XXX -  Buy any token on one platform | DeGate Dex',
  doc_title_stocks: 'On-Chain Stocks Dashboard | Yield Insights & Strategies',
  doc_title_meme: 'Meme Signal Platform | Curated Signals & CopyTrade',
  doc_desc_stocks:
    'Discover yield opportunities and strategies for on-chain stocks.',
  doc_desc_meme:
    'Catch the hottest meme tokens — curated signals + copytrade tools to moon your portfolio fast.',

  please_confirm_within_10_seconds: 'Please confirm within 10 seconds.',
  confirmation_expired: 'Confirmation expired. Please try again.',
  signature_free_mode_tips:
    'In this mode, you can swap token without signing. To switch mode, click the settings icon in the top right.',
};
export default en;
