const DeGateTerms = 'https://app.degate.com/terms'; const PrivyTerms = 'https://www.privy.io/user-terms-of-service';

const zh = {
  language: 'zh-CN',
  choose_token: '选择币种',
  recipient: '接收方',
  recent: '最近使用',
  price: '价格',
  amount: '数量',
  available: '可用',
  gas_fee: '矿工费',
  Send: '发送',
  Send_ETH: '发送ETH',
  Internal_Transfer: '内部转账',
  transfer_tips: '在DeGate协议内将代币转账到其他地址',
  transfer_ETH: '内部转账ETH',
  btn_max: '最大',
  degate_insufficient_balance: '余额不足',
  max_digits_exceeded: '超出最大位数',
  wallet_insufficient_balance: '钱包余额不足',
  deGate_insufficient_fees: 'DeGate余额不足以支付矿工费',
  token_search_placeholder: '搜索币种、合约地址',
  token: '币种',
  degate_balance: 'DeGate余额',
  tips_gas: '执行交易上链所需的矿工费将会从您的DeGate余额扣除',
  tips_gas2: '矿工费用于支付交易的上链结算。多余的费用会被退还。',
  Close: '关闭',
  Help: '帮助',
  no_token: '未找到此币种',
  Cancel: '取消',
  go_back: '返回',
  Back: '返回',
  copied: '已复制',
  Confirm: '确认',
  Create: '创建',
  Abort: '放弃',
  btn_confirm: '我知道了',
  btn_got_it: '我知道了',
  wallet_cancelled_tips: '您已取消签名',
  connect_ledger: '连接Ledger',
  ledger_disconnect:
    "Failed to execute 'transferOut' on 'USBDevice': The device was disconnected.",
  wallet_tips: '请到钱包内授权',
  wallet_ledger_tips: '请到Ledger硬件中授权',
  wallet_metamask_tips: '请到MetaMask授权',
  wallet_walletconnect_tips: '请到WalletConnect钱包授权',
  view_asset_key: '查看资产密钥',
  export_key_warning: '泄露资产密钥将导致资产丢失，请务必妥善保管',
  export_key_confirm_btn: '继续查看',
  btn_buy_ETH: '买入ETH',
  btn_sell_ETH: '卖出ETH',
  around: '约',
  need_help: '帮助',
  time_now: '刚刚',
  time_S_second: 'S秒',
  time_1_minute: '1分钟',
  time_1_hour: '1小时',
  time_1_day: '1天',
  time_1_year: '1年',
  time_M_minutes: 'M分钟',
  time_M_m: 'M分钟',
  time_H_hours: 'H小时',
  time_H_h: 'H小时',
  time_D_days: 'D天',
  time_D_d: 'D天',
  time_Y_years: 'Y年',
  time_Y_y: 'Y年',
  personal_sign_reason: '可能原因',
  personal_sign_reason1: '1. Metamask连接了硬件钱包',
  personal_sign_reason2: '2. Metamask版本过低',
  personal_sign_reason3: '3. 其他原因',
  personal_sign_btn: '重新签名',
  switch_wallet: '切换账户',
  switch_walletConnect_tips1:
    '如果您想切换到当前钱包软件里的其他账户，请取消并到钱包内直接操作。',
  switch_walletConnect_tips2:
    '如果您想要更换到其他钱包软件来使用WalletConnect，系统会先断开当前钱包连接。',
  switch_walletConnect_continue: '断开连接并继续',
  switch_metamask_tips: '请在Metamask切换账户',
  switch_browser_wallet_tips: '请在手机钱包切换账户',
  period_expired: '已过期',
  period_D_day_H_hour: 'D天H小时',
  period_H_hour_M_minute: 'H小时M分钟',
  login_success: '已连接至钱包',
  advanced: '高级',
  edit: '编辑',
  save: '保存',
  speed_up: '加速',
  continue: '继续',
  Submit: '提交',
  icon_copy: '复制地址',
  icon_view_explorer: '区块链浏览器查看',
  upcoming_lock_tips: '您似乎离开了一会。为确保安全，即将关闭免签名模式。',
  auto_locked_tips: '您已离开超过15分钟，为确保安全，已为您关闭免签名模式。',
  keep: '保留',
  turn_off_now: '立即关闭',
  turn_on: '开启',
  turn_on_signature_free_mode: '开启免签名模式',
  turn_on_signature_free_mode_success: '免签名模式已开启',
  max_XXX: '最大为XXX',
  min_XXX: '最小为XXX',
  common_err: '似乎出了点问题，请稍后重试',
  input_auto_corrected_tips: '超过了最大位数限制，您的输入已被自动修改',
  maximum_decimal_reached: '超出最大小数位',
  verify_ownership: '验证身份',
  execute: '执行',
  sign_step1: '请到钱包内签名',
  sign_step2: '完成第二次签名',
  sign_step3: '完成第三次签名',
  place_order: '确认下单',
  create_spot_order: '创建订单',
  create_grid_strategy: '创建网格策略',
  create_DCA_plan: '创建定投计划',
  cancel_order: '取消订单',
  end_grid_strategy: '关闭网格策略',
  end_DCA: '关闭定投计划',
  complete_in_seconds: '立即完成',
  complete_in: '到账时间',
  me: '我',
  eth_code_tips: '以太坊原生代币，无合约地址',
  total: '总计',
  order_amount: '订单数量',
  operation_has_expired: '操作已过期',
  Approve: '授权',
  tips_hide_forever: '下次不再显示',
  Tips: '提示',
  Note: '提示',
  Summary: '摘要',
  Orders: '订单',
  Side: '方向',
  Sell: '卖出',
  Buy: '买入',
  now: '现在',
  order_type: '订单类型',
  limit_order: '限价',
  market_order: '市价',
  required: '必填',
  check_address_format: '请检查地址格式',
  start_time: '开始时间',
  end_time: '结束时间',
  None: '无',
  time_out: '超时请重试',
  deposit_ETH: '划入ETH',
  'ledger.connect_rule_1': '1. 将Ledger接入当前设备',
  'ledger.connect_rule_2': '2. 在Ledger内解锁',
  'ledger.connect_rule_3': '3. 在Ledger内打开Ethereum app',
  'ledger.connect_rule_4':
    '4. 确认已开启Blind Signing/Contract Data和Browser Support功能',
  'ledger.unable_to_approve': '无法完成授权',
  'ledger.webusb_1tab_tips_desc_1':
    '您正使用的浏览器仅支持单个“浏览器标签页”进行Ledger授权，其他标签页已占用该功能，因此无法完成授权。',
  'ledger.webusb_1tab_tips_desc_2': '请尝试拔出Ledger后插回，并重新发起操作。',
  'ledger.locked_tips': '请解锁Ledger，打开Ethereum app并完成授权',
  'ledger.account_not_match': '检查到错误的Ledger钱包，请连接至正确的Ledger',
  'ledger.ledger_choose_address': '选择地址',
  'ledger.address': '地址',
  'ledger.connect': '连接',
  'ledger.un_supported_title': '当前浏览器不支持Ledger连接',
  'ledger.un_supported_desc': '推荐使用Chrome, Edge浏览器',
  'ledger.confirm_gas_fee': '确认矿工费',
  'ledger.confirm_gas_fee_desc': '您即将在以太坊上发起交易，请确认：',
  'ledger.max_gas_fee': '最大矿工费',
  'ledger.edit_gas_fee': '编辑矿工费',
  'ledger.max_fee': '矿工费 (Gwei)',
  'ledger.max_base_fee': 'Max Base Fee (Gwei)',
  'ledger.max_base_fee_tips':
    '交易入块后，max base fee与实际base fee的差值将会退还。',
  'ledger.priority_fee': 'Priority Fee (Gwei)',
  'ledger.priority_fee_tips':
    'Priority fee（又名“矿工小费”）直接支付给矿工，并激励他们优先考虑打包您的交易。',
  'ledger.gas_limit': 'Gas Limit:',
  'ledger.tx_speed_up_title': '加速交易',
  'ledger.tx_speed_up_desc': '您即将在以太坊上加速交易，请确认：',
  'ledger.tx_cancel_title': '取消交易',
  'ledger.tx_cancel_desc': '您即将在以太坊上取消交易，请确认：',
  'ledger.fee_minimum_xxx': '不能少于XXX',
  'ledger.ledger_app_version_tips':
    '为了查看待签名消息，请升级您的Ledger Ethereum app至v1.9.19或更高',
  'operations.register_pair': '添加交易对',
  'operations.chain_cancel': '链上取消订单',
  'operations.chain_cancel_title': '取消订单请求将会被发到链上以确保取消成功。',
  'operations.chain_cancel_confirm': '确认取消',
  'operations.chain_cancel_confirm_tips': '链上取消需支付矿工费，是否继续？',
  'operations.chain_cancel_grid_text_N':
    '此网格策略中的<b>N个订单</b>的取消请求将被提交到链上',
  'operations.chain_cancel_grid_gas_AMOUNT_ETH':
    '请再次确认链上取消的矿工费为 <b>AMOUNT ETH</b>',
  claim_rewards: '领取奖励',
  'operations.claim_desc':
    '奖励将以内部转账计入您的DeGate余额。矿工费直接从奖励数量中扣除。',
  'operations.claim_desc_others': '挖矿奖励将通过内部转账发送到您的DeGate余额',
  'operations.claim_rewards': '可领取奖励',
  'operations.claim_err_amount': '可领取数量不足',
  'operations.claim': '领取',
  'operations.Claimable': '待领取',
  'operations.Unclaimed': '未领取',
  'operations.claim_mining_rewards': '领取挖矿奖励',
  'operations.claim_rewards_desc':
    '挖矿奖励将在扣除矿工费后通过内部转账发送到您的账户',
  'operations.pay_deposit': '付费入账',
  'operations.pay_deposit_title': '待支付',
  'operations.pay_deposit_desc_XXX_ETH': '您有XXX ETH待入账',
  'operations.pay_deposit_select_account': '支付方式',
  Wallet_Balance: '钱包余额',
  'operations.pay_deposit_tips_XXX_ETH': '支付 XXX ETH',
  'operations.reset_account': '重置资产密钥',
  'operations.reset_desc':
    '资产密钥存储在您本地浏览器缓存。如果怀疑本地环境有安全风险，请重置资产密钥。',
  'operations.reset_warning':
    '请注意：重置时，一切与资产相关的操作都将暂停使用，例如交易、发送资产、内部转账等。',
  'operations.reset_estimated_time': '预估时间',
  'operations.reset_order_tips':
    '一旦发起重置，所有进行中的订单会被<b>立即撤销</b>，请确认',
  'operations.reset_order_tips_btn2': '我再想想',
  'operations.claim_dg_rewards': '领取DG奖励',
  'operations.claim_REBASE': '领取REBASE',
  'operations.claim_REBASE_desc': 'REBASE将通过内部转账发到您的DeGate余额',
  'operations.claim_REBASE_tips': '未领取的REBASE也计入收益计算',
  'operations.view_yield_history': '查看分红历史',
  'operations.cancel_orders_on_chain': '链上取消订单',
  'operations.chain_cancel_dca_text_N':
    '此定投计划中的<b>N个订单</b>的取消请求将被提交到链上。',
  'operations.confirm_cancel_gas_AMOUNT_ETH':
    '请再次确认链上取消的矿工费为<b>AMOUNT ETH</b>。',
  'transfer.transfer_1_eth_ACCOUNT': '转账1 ETH到',
  'transfer.internal_transfer_address_new_tips':
    '该地址无DeGate使用记录，转账需支付更多矿工费',
  address_placeholder: '请输入地址',
  'transfer.to_new_account_tips':
    '该地址无DeGate使用记录，收到的首笔资产将触发额外的链上数据使用，因此这笔转账需支付更多矿工费。',
  'transfer.confirm_internal_transfer': '确认内部转账',
  'transfer.internal_transfer_address_oneself_tips': '不支持内部转账给自己',
  'transfer.transfer_max_err_XXX_USDT': '内部转账一次最多XXX USDT',
  'transfer.before': '修改前',
  'transfer.after': '修改后',
  'transfer.recipient_cex_warning':
    '警告：请勿转账到中心化交易所，您会损失资产。',
  'withdraw.withdraw_max_tips': '已超出系统限制',
  'dca.confirm_dca_plan': '确认定投计划',
  'dca.number_of_orders': '订单数',
  'dca.amount_per_order': '每笔订单金额',
  'dca.time_scheduled': '计划时间',
  'dca.creating_the_plan': '正在创建计划...',
  'dca.maximum_price': '最高买入价格',
  'dca.minimum_price': '最低卖出价格',
  'dca.do_not_close': '请不要关闭或刷新当前页面',
  'dca.frequency': '频率',
  total_amount: '总金额',
  'dca.daily': '每天',
  'dca.weekly': '每周',
  'dca.every': '每',
  'airdrop.review_airdrop': '预览空投',
  'airdrop.create_airdrop': '创建空投',
  'airdrop.recipients_number': '地址总数',
  'airdrop.airdrop_fee': '空投费',
  'airdrop.pay_airdrop_fee': '支付空投费',
  'airdrop.send_airdrop_token': '发送空投代币',
  'airdrop.claim_airdrop': '领取空投',
  'airdrop.retrieve': '取回',
  'countdown.create_countdown_plan': '创建首发计划',
  'countdown.countdown_display': '显示倒计时',
  'countdown.max_30_days': '从现在起最多30天',
  'countdown.review_countdown_plan': '检查首发计划',
  'countdown.countdown_fee': '首发费',
  grid_slippage_over_2_tips_SLIPPAGE_QUOTE_BASE:
    '系统将通过市价单将一部分QUOTE兑换为BASE，预计滑点为 SLIPPAGE。',
  grid_slippage_over_5_tips_SLIPPAGE_QUOTE_BASE:
    '系统将通过市价单将一部分QUOTE兑换为BASE，预计滑点为 SLIPPAGE。建议采用双资产模式进行投资。',
  connected: '已连接',
  browser_wallet: '手机钱包',
  Convert_to_YYY: '兑换成YYY',
  sell_XXX_to_YYY: '您是否想将XXX以市价卖成YYY？',
  you_sell: '卖出',
  you_receive: '收到',
  est_receive: '预估收到',
  est_slippage: '预计滑点',
  No: '不',
  closing_sell: '关闭卖出',
  connect_wallet: '连接钱包',
  Add: '添加',
  Add_Funds: '划入资金',

  send_USDC_to_this_address: '发送USDC到该地址',
  Failed_to_proceed: '无法继续',
  Please_select_the_Ethereum_network: '请选择以太坊网络',
  NATIVE_USDC_ONLY: '只接受原生USDC',
  NEVER_send_bridged_USDC: '请勿发跨链USDC',
  Network: '网络',
  Arrival_Time: '到账时间',
  Token_Contract: '币种合约',
  please_select_network: '请选择网络',
  maximum_amount: '最大数量',
  Select: '选择',
  cannot_send_to_yourself: '不支持在DeGate网络发给自己',
  max_amount_exceeded: '超出最大值',
  do_not_trasnfer_to_cex: '请<b>不要</b>转给中心化交易所，有可能丢失资金。',
  I_understand: '我已理解',
  Continue: '继续',
  chain_0: 'DeGate L2',
  chain_DeGate: 'DeGate L2',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum One',
  chain_421614: 'Arbitrum One',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',

  deposit_tips_region:
    '请注意：您正在从REGION访问DeGate，资金划入后无法交易和内部转账。',
  deposit_1_ETH: '向DeGate余额划入1 ETH',
  'account.deposit_contract_tips_over_AMOUNT': '金额超过AMOUNT美元需要高级方式',
  'account.deposit_contract_tips_only_all': '暂时仅支持高级资金划入方式',
  Approved: '已授权',
  'account.deposit_tips': '划入的资金仍由您完全掌控',
  'account.deposit_arrive_in_30s_s': '到账时间约30秒',
  reset_approval_USDT: '重置USDT授权',
  reset_approval_USDT_tips: 'USDT授权额度不够时需要先重置授权。',
  token_has_not_listed: '该币种还未上架DeGate',
  list_now: '立即上币',
  Retry: '重试',
  switch_network: '切换网络',
  switch_to_MAINNET_in_metamask: '请到Metamask切换至MAINNET',
  switch_to_MAINNET: '请切换至MAINNET',
  'account.pay_deposit_warning': '划入资金可能需要支付额外的矿工费',

  send_method: '发送方式',
  Economy: '经济',
  Fast: '快速',
  Instant: '立即',
  less_than_X_hours: '< X 小时',
  less_than_1_hour: '< 1 小时',
  Economy_tips:
    'DeGate每4小时至少处理一次发送请求，通常会更快。例如，如果另一个用户发起了快速发送，您的经济发送请求也会立即处理。',
  wrap: '跨链',
  just_a_moment: '请稍等',
  wait_confirmation_from_wallet: '等待钱包返回确认',
  s: '秒',

  view_asset_key_tips: `<div>以下为您的资产密钥。<strong>不要</strong>与任何人分享，以防止潜在的资产损失。</div>`,
  personal_sign_tips: 'Metamask请求以Personal Sign的形式重新签名',
  sign_and_open_free_mode_tips: `<div>本次操作后免签名模式将被开启，接下来无需签名。<br /><br />切换模式，请在交易按钮下方的“设置”中完成。</div>`,
  'trade.i_understand': '我已明白',
  'trade.flow_of_funds_tips': `<div><h3>资金流向</h3>资金将转入您的DeGate余额，而非您的钱包余额。<br /><br /><h3>关于DeGate余额</h3>DeGate余额是用户在DeGate智能合约中持有的资产。<br />用户完全掌控自己的DeGate余额，因为DeGate的智能合约是完全去中心化的。</div>`,

  email: '邮箱',
  login_by_email: '邮箱登录',
  powered_by_privy: 'Powered by Privy',
  enter_confirmation_code: '输入确认码',
  check_email_tips: '请检查您的邮箱EMAIL获取确认码',
  did_no_get_an_email: '没有收到邮件?',
  resend_code: '重新发送',
  success: '成功',
  privy_login_success: '登录成功',
  invalid_or_expired_verification_code: '确认码错误或失效',
  too_many_requests: '请求次数过多，请稍后尝试',
  view_address: '查看地址',
  email_address: '邮箱地址',
  wallet_address: '钱包地址',
  export_private_key: '导出私钥',

  confirmation: '确认',
  privy_send_tips: '您是否确认发送到与您的Email登录关联的地址？',
  privy_send_tips2:
    '要访问此地址，您<b>必须</b>导出其私钥并将其导入到第三方钱包，如MetaMask。',
  Discard: '放弃',

  // 1.17
  pay: '支付',
  receive: '收到',
  max_slippage: '最大滑点',
  minimum_receive: '最小收到',
  available_network: '支持网络',
  swap_deposit_not_support_yet: '暂不支持此币种划入，将会于未来版本支持。',
  switch_address_tips: '你想要切换地址吗？',
  switch_address_tips_MetaMask: '请在Metamask切换地址',
  Settings: '设置',

  // 1.20
  sync_to_app: '同步到 DeGate App',
  sync_to_app_tips:
    '您即将通过钱包签名生成二维码。<b>请勿</b>与任何人分享二维码。',
  sync_to_app_rules: '请确保以下事项：',
  sync_to_app_rules_1: '1. 周围没有其他人。',
  sync_to_app_rules_2: '2. 周围没有摄像头。',
  sync_to_app_rules_3: '3. 您未在进行直播或共享屏幕。',
  Generate: '生成',
  Scan_from_App: '从 App 扫描',
  Scan_from_App_tips:
    '打开 DeGate App，点击“登录”，选择“从DeGate网页版同步”，并在 60 秒内扫描二维码。',
  qr_code_expired: '二维码已过期，请重试。',

  insufficient_degate_balance: 'DeGate余额不足',
  scan_qr_code: '扫描二维码',
  Claim_Commission: '领取佣金',
  Free: '免费',

  send_XXX_to_this_address_ONLY_on_NETWORK:
    '<b>只支持在NETWORK</b>发送XXX到此地址',
  sign_in_with_email: '通过邮箱登录',
  sign_in_with_email_tips: `登录DeGate，表示您同意<a href=${DeGateTerms} target="_blank">DeGate的《服务条款》</a>和<a href=${PrivyTerms} target="_blank">Privy的《服务条款》</a>。`,

  'ledger.eth_app_not_opened': '请在Ledger打开Ethereum app',
  'ledger.webusb_1tab_tips_desc_1_new':
    '另一个浏览器标签页正在访问您的Ledger。请在那边授权或者用当前标签页重新连接Ledger。',

  connected_via: '连接账户',
  supported_chains: '支持的区块链',
  evm_address: 'EVM 地址',
  CHAIN_address: 'CHAIN 地址',

  My_CHAIN_Address: '我的CHAIN地址',
  From: '来自',
  To: '至',
  Select_Network: '选择网络',
  Route_not_available: '路径不可用',
  Select_Token: '选择币种',
  Bridge_TOKEN: '跨链 TOKEN',
  Token_on_DeGate_L2: 'DeGate L2上的币种',
  Token_in_your_connected_address: '连接地址上的币种',
  Enter_address_on_CHAIN: '请输入CHAIN的地址',
  Sender: '发送方',
  L2_Bridge: 'L2跨链',
  Receive: '收款',

  send_warning: '不要发给中心化交易所，这笔资金会丢失。',

  Deposit: '充值',
  Withdraw: '提现',
  Est_Daily_Rewards: '预计每日奖励',
  Protocol: '协议',

  //1.24
  Bridge: '跨链',
  multi_chain: '多链',
  multi_chain_tips:
    '多链代币提升了用户体验，使用户无需复杂的资金跨链操作即可在任何链上进行投资。它还可用于支付所有链上的网络费用。',
  My_Address: '我的地址',
  funds_received_to_this_address_are_entirely_self_custodied:
    '发送到此地址的资金完全由用户自行托管',
  available_balance: '可用余额',
  insufficient_multi_chain_usdc: '您没有足够的<b>多链USDC</b>来支付网络费',
  est_network_fee: '预估网络费',
  amount_needed: '所需数量',
  maximum_XXX: '最大：$XXX',
  network_fee: '网络费',
  network_fee_updated: '网络费已更新',
  insufficient_USDC_in_your_$CHAIN_address: '您的$CHAIN地址中没有足够的USDC',

  or: '或',
  Please_enter_a_valid_email_address: '请输入正确的邮件地址',
  Copy: '复制',
  Invalid_SOL_rent: '剩余SOL不足支付租金',
  signing_in: '登录中…',
  This_process_may_take_about_10_seconds: '此过程可能需要10秒。',

  next: '前往',

  ct: {
    Transfer_funds_into_your_Copy_Trade_account: '要将资金转入自动跟单账户吗？',
    Yes: '是',
    funds_transfer: '资金转移',

    Deposit_from_CEX_Other_Wallets: '从交易所/其他钱包充值',
    Top_up_your_DeGate_Wallet: '为您的 DeGate 钱包充值',
    Transfer_funds_into_Copy_Trade_Account: '资金转入到自动跟单账户',
    Deposit_into_DeGate_Wallet_then_transfer_into_Copy_Trade_Account_to_get_started:
      '先<b>存入</b> DeGate 钱包，再<b>转入</b>自动跟单账户即可开始。',
    To_top_up_balance_go_to_1_Deposit_from_CEX_Wallets:
      '若要充值余额，请先执行：1）从交易所/钱包充值',
    Copy_Trade_Account: '自动跟单账户',
  },
  turboRange: {
    Turbo_Range: '区间宝',
    price_range: '价格区间',
    increase_investment: '追加投入',
  },
  est_account_rent_CHAIN_NUM: '$NUM为CHAIN链租金',
  est_transaction_cost_NUM: '$NUM为交易费用',
  XXX_Refundable: 'XXX 可返还',
  Refundable_on_data_release: '数据释放时返还',
  est_time: '预估时间',
  Mainnet: '主网',
  Testnet: '测试网',
  address_copied: '地址已复制',
  via_email_verification: '邮箱验证',
  send_confirmation_code: '发送确认码',
  doc_title:
    '区块链轻松赚取收益的最佳方式 —— 无需跨链、无需 Gas 代币 | DeGate 钱包',
  doc_desc:
    'DeGate 是一款多链加密钱包，帮助你轻松获取链上收益机会。100% 非托管、无需 Gas 代币、无需跨链操作。',
  doc_title_swap:
    '购买 XXX —— 一个平台支持购买任意代币 | DeGate 去中心化交易所',
  doc_title_stocks: '链上股票仪表盘 | 收益洞察与投资策略',
  doc_title_meme: 'Meme 信号平台 | 精选交易信号 & 跟单 CopyTrade',
  doc_desc_stocks: '发现链上股票的收益机会与投资策略。',
  doc_desc_meme:
    '捕捉最热门的 Meme 代币 —— 精选信号 + 跟单工具，助你快速放大投资组合收益。',
  please_confirm_within_10_seconds: '请在10秒内完成确认',
  confirmation_expired: '确认已过期，请重新尝试。',
  signature_free_mode_tips:
    '在此模式下，您可以无需签名即可兑换代币。要切换模式，请点击右上角的设置图标。',
};
export default zh;
