const ja = {
  language: 'ja-JP',
  'kline.time_Line': '時間',
  'kline.time_1s': '1秒',
  'kline.time_5s': '5秒',
  'kline.time_15s': '15秒',
  'kline.time_30s': '30秒',
  'kline.time_1m': '1分',
  'kline.time_3m': '3分',
  'kline.time_5m': '5分',
  'kline.time_15m': '15分',
  'kline.time_30m': '30分',
  'kline.time_1H': '1時間',
  'kline.time_2H': '2時間',
  'kline.time_4H': '4時間',
  'kline.time_6H': '6時間',
  'kline.time_1D': '1日',
  'kline.time_1W': '1週間',
  'kline.time_1M': '1ヶ月',
  'kline.tab_line': 'チャート',
  'kline.tab_depth': '深さ',
  'kline.chartType_Bars': 'バー',
  'kline.chartType_Candles': 'ローソク足',
  'kline.chartType_Hollow_Candles': 'ろうそく足',
  'kline.chartType_Line': 'ライン',
  'kline.chartType_Area': 'エリア',
  'kline.chartType_Heikin_Ashi': '平均足',
  degate_account: 'DeGateアカウント',
  Trade: '取引',
  Order: '注文',
  Grid: 'グリッド戦略',
  Campaign: 'キャンペーン',
  DCA: 'DCA',
  Advanced: '高度な',
  Add: '追加',
  Add_Funds: '資金の追加',
  external_wallet_receive_guide:
    'DeGateウォレットに資産がありません。外部ウォレットから送金してください。',
  external_wallet_add_funds_guide:
    'DeGateに資金がありません。外部ウォレットから追加してください。',
  eth_added_1: '1 ETH 追加済み',
  eth_sent_1: '1 ETH 送信済み',
  Send: '送信',
  Internal_Transfer: '内部転送',
  Miscellaneous: 'その他',
  Mining: 'マイニング',
  Liquidity_Mining: '流動性マイニング',
  Analytics: '分析',
  Support: 'サポート',
  Help: 'ヘルプ',
  Tips: 'ヒント',
  Statistics: '統計',
  Coming_soon: '近日公開予定',
  Faucet: 'フォーセット',
  more: 'その他',
  hide: '非表示',
  change: '変更',
  'Wrong Network': 'ネットワークが違います',
  avbl: '利用可能残高:',
  insufficient_balance_AAA:
    'あなたのウォレットに十分なAAAがありません。確認して再度お試しください。',
  insufficient_balance: '残高が不足しています',
  wallet_denied_sign: 'メッセージ署名が拒否されました。',
  common_err: '問題が発生しました。後ほどもう一度お試しください。',
  common_err_ledger_version:
    'エラーが発生しました。Ledger Ethereumアプリが最新バージョン（1.9.10以降）であることを確認してください。または、後ほどもう一度お試しください。',
  network_1: 'イーサリアムメインネット',
  network_err: 'ネットワークエラーです。後ほどもう一度お試しください。',
  rate_limit_err: 'アクセス頻度が高すぎます。1分後に再試行してください。',
  error_InsufficientGasFunds: 'ウォレットのガス残高が不足しています',
  notification_transaction_send: 'トランザクションが送信されました',
  view_on_explorer: 'ブロックチェーンエクスプローラーで見る',
  view_address: 'アドレスを見る',
  switch_network: 'ネットワークを切り替える',
  switch_to_Arbitrum: '続行するには、Arbitrumに切り替えてください。',
  switch_to_MAINNET_in_metamask: 'MetaMaskでメインネットに切り替えてください',
  switch_to_MAINNET: 'メインネットに切り替えてください',
  switch_network_in_walletconnect:
    'ウォレットに移動し、WalletConnectでネットワークを切り替えてください',
  Retry: '再試行',
  wallet_tips: 'ブラウザウォレットで承認してください',
  wallet_ledger_tips: 'Ledgerハードウェアで承認してください',
  wallet_metamask_tips: 'MetaMaskで承認してください',
  wallet_walletconnect_tips:
    'ウォレットに移動し、WalletConnectで承認してください',
  wallet_cancelled_tips: '署名をキャンセルしました',
  Close: '閉じる',
  Closed: '終了',
  copied: 'コピーしました',
  Details: '詳細',
  view_details: '詳細を見る',
  turbo_range_view_live_status: 'リアルタイムステータスを表示',
  Share: '共有する',
  view_graph: 'チャートで見る',
  Dismiss: '閉じる',
  Cancel: 'キャンセル',
  End: '終了',
  End_grid: '終了',
  Confirm: '確認',
  Cancel_all: 'すべてキャンセル',
  cancel_all_tips: 'すべての未約定注文をキャンセルする',
  Submit: '送信',
  no_data: 'データなし',
  all_data_displayed: 'すべてのデータが表示されています',
  no_data_within_90_days: '90日以内のデータはありません',
  only_display_90_days: '過去90日間のデータのみを表示しています',
  displayed_90_days: '過去90日間のデータを表示しています',
  only_data_beyond_90_days_trade:
    '90日を超えるデータにアクセスするには、「すべて表示」を選択してから「データのエクスポート」機能を使用してください。',
  only_data_beyond_90_days_grid_detail:
    '過去90日を超えるデータの履歴クエリは現在サポートされていません',
  only_data_beyond_90_days_spot_history:
    '90日を超えるデータにアクセスするには、「データのエクスポート」機能を使用してください。',
  View: '表示',
  service_unavailable_for_region_REGION:
    'このサービスはREGIONではご利用いただけません。',
  service_unavailable: 'サービスは利用できません',
  service_error: '後ほどもう一度お試しください',
  service_maintenance: 'このサービスはメンテナンス中です。',
  connect_wallet: 'ウォレットを接続する',
  switch_address: 'アドレスを切り替える',
  wallet_wc: 'WalletConnectに接続しました',
  wallet_ledger: 'Ledgerに接続しました',
  register_dexAccount: '登録する',
  deposit_ETH: 'ETHを追加する',
  initialize: '初期化する',
  initialization: '初期化',
  invalid_signature: '無効な署名',
  possible_cause: '考えられる原因:',
  locale_time_error: 'デバイスの時間が正しくありません。',
  authorization_mode: '認証モード',
  authorization_mode_standard: '署名不要',
  authorization_mode_single_use: '常に署名する',
  turn_on: 'オンにする',
  turn_on_signature_free_mode: '署名不要モードをオンにする',
  signatre_free_mode: '署名不要モード',
  turn_on_signature_free_mode_tips:
    'このモードでは、署名せずに注文することができます。モードを切り替えるには、取引ボタンの下にある「設定」に移動します。',
  turn_on_signature_free_mode_tips_grid:
    'このモードでは、署名せずにグリッド戦略を作成することができます。モードを切り替えるには、取引ボタンの下にある「設定」に移動します。',
  turn_on_signature_free_mode_tips_dca:
    'このモードでは、署名せずにDCAプランを作成することができます。モードを切り替えるには、取引ボタンの下にある「設定」に移動します。',
  yes: 'はい',
  no: 'いいえ',
  free_mode_on: '署名不要モードオン',
  view_balance: '残高を見る',
  delete_asset_key: 'アセットキーを削除する',
  delete_asset_key_desc:
    'ブラウザからアセットキーが削除されると、署名不要モードはオフになります。',
  no_asset_key_tips: 'ブラウザにアセットキーが見つかりません',
  turn_off_standard_mode: '署名不要モードをオフにする',
  reset_asset_key: 'アセットキーをリセットする',
  view_asset_key: 'アセットキーを見る',
  lock_success: 'アセットキーが削除されました',
  reset: 'アセットキーをリセットする',
  delete: '消す',
  withdraw_ETH: 'ETHを送信する',
  transfer_ETH: 'ETHを内部転送する',
  history: '履歴',
  view_history: '履歴で見る',
  internal_transfer: '送金',
  assets_record_link: '履歴',
  other: 'その他',
  login_success: '接続に成功しました',
  Account: 'アカウント',
  Address: 'アドレス',
  Disconnect: '切断',
  copy_address: 'アドレスをコピーする',
  copy_grid: '戦略をコピーする',
  Copy: 'コピーする',
  btn_search: '検索',
  btn_reset: 'リセット',
  btn_confirm: '閉じる',
  btn_max: '最大',
  btn_ok: 'OK',
  spot_trade: 'スポット',
  grid_trade: 'グリッド',
  err_balance_title: '注文に失敗しました',
  err_balance_content:
    '利用可能な残高が不足しています。確認してもう一度お試しください。',
  order_failed: '注文数量が不足しています',
  insufficient_order_value: '注文額不足',
  grid_failed: '作成に失敗しました',
  err_eth_gas: 'イーサリアムネットワークが非常に混雑しています',
  err_insufficient_balance_TOKEN1: 'TOKEN1の残高が不足しています',
  err_insufficient_balance_TOKEN1_TOKEN2:
    'TOKEN1とTOKEN2の残高が不足しています',
  please_add_funds_before_ordering:
    '注文する前に、DeGate残高に資金を追加してください。',
  err_balance_content_spot:
    '残高不足のため、注文の размещение に失敗しました。',
  err_balance_content_grid:
    '残高不足のため、グリッド戦略の作成に失敗しました。',
  trade_min_volume_tips_XXX: '最小XXX',
  grid_min_volume_tips:
    '注文数量が最小額を満たしていません。もう一度お試しください。',
  trade_risk_orders_tips: '未決済注文が多すぎるため、注文を出せません',
  gas_token_tips: 'ガス料金トークンを選択',
  add_favorite_tooltip: 'お気に入りに追加',
  remove_favorite_tooltip: 'お気に入りから削除',
  expire_tips_X: 'この注文はXに期限切れになります。',
  today: '今すぐ',
  now: '今すぐ',
  time_D_day: 'Dd',
  time_D_day_H_hour: 'Dd Hh',
  time_last_24_hrs: '過去24時間',
  time_last_hour: '過去1時間',
  time_H_hour_M_minute: 'Hh Mm',
  time_M_minute_S_second: 'Mm Ss',
  time_S_second: 'Ss',
  around: '周辺',
  time_now: '今すぐ',
  time_before: '以前',
  time_before_ago: '前',
  time_1_minute: '1 minute',
  time_1_hour: '1 hour',
  time_1_day: '1 day',
  time_1_year: '1 year',
  time_M_minutes: 'M minutes',
  time_M_m: 'Mm',
  time_H_hours: 'H hours',
  time_H_h: 'Hh',
  time_D_days: 'D days',
  time_Y_years: 'Y years',
  time_Y_y: 'Yy',
  time_D_d: 'Dd',
  time_M_mo: 'Mmo',
  fee_change_tips: '価格が更新されました',
  no_pairs: '取引ペアが見つかりません',
  register_new_pair: '新しいペアを追加',
  register_pair: '取引ペアを追加',
  add_pair: 'ペアを追加',
  tips_hide_forever: '再度表示しない',
  Select_Token: 'トークンを選択',
  token: 'トークン',
  action: 'アクション',
  more_actions: 'その他',
  gas_fee: 'ガス料金',
  'orders.detail_gas': '実際のガス料金',
  trade_fee: '取引手数料',
  about_degate: 'DeGateについて',
  metrics: '指標',
  fees: '料金',
  document: 'ドキュメント',
  join_us: '参加する',
  feedback: 'フィードバック',
  email_optional: 'メールアドレス（オプション）',
  Upload: 'アップロード',
  feedback_upload_tip:
    'フィードバックをお共有ください。添付するには、ファイルをドラッグしてください。',
  feedback_upload_tip_mobile: 'フィードバックをお共有ください。',
  image_upload_tip: 'リリースを追加',
  feedback_success: 'あなたの意見は、私たちに届いています！',
  feedback_success_2: 'ありがとうございました',
  feedback_failed: '送信に失敗しました。後ほどもう一度お試しください。',
  image_upload_rule_1: 'PNG、JPG、JPEGのみサポートされています。',
  image_upload_rule_2: 'ファイルあたりの最大サイズは20MBです。',
  image_upload_rule_3: '最大5ファイル。',
  image_upload_rule_2_3:
    'ファイルあたりの最大サイズは20MBです。最大5ファイル。',
  no_pair: 'トークンペアが見つかりません',
  no_token: 'トークンが見つかりません',
  choose_base_token: '基準トークンを選択',
  choose_quote_token: 'クォートトークンを選択',
  get_test_token: 'テストネットトークンを取得',
  faucet: 'フォーセット',
  expire_in: '有効期限',
  expire_in_empty_err: '数字を入力してください',
  go_back: '戻る',
  max_XXX: '最大XXX',
  min_XXX: '最小XXX',
  fill_in: '入力してください',
  my_balance: 'マイ残高',
  deGate_insufficient_fees:
    'ガス料金の支払いに必要なDeGate残高が不足しています',
  wallet_balance: 'ウォレット残高',
  your_wallet_balance: 'ウォレットの残高',
  degate_balance: 'DeGate残高',
  wallet_insufficient_fees: 'ウォレットの残高が不足しています',
  wallet_insufficient_balance: '残高不足',
  insuffficient_wallet_balance: 'ウォレットの残高が不足しています',
  degate_insufficient_balance: '利用可能な残高が不足しています',
  open_discord: 'Discordコミュニティにアクセス',
  err_valid_until: 'デバイスの現地時間を標準時間に合わせてください',
  tips_gas:
    'このオンチェーントランザクションを実行するためのガス料金は、DeGate残高から直接差し引かれます。',
  maker_free: 'メーカー無料',
  trading_fee_rate: '取引手数料率',
  Free: '無料',
  stop_service_1: 'サイトはメンテナンス中です',
  stop_service_2: '推定復旧時間',
  stop_upgrade: 'テストネットの新しいバージョンは現在移行中です。',
  stop_trading_1: 'システムアップグレード',
  stop_trading_2: '取引は一時的に停止されています',
  sell: '売り',
  buy: '買い',
  SELL: '売却',
  BUY: '購入',
  Sell: '売り',
  Buy: '買い',
  sell_order: '売却注文',
  buy_order: '購入注文',
  edit: '編集',
  status_processing: '処理中',
  status_processed: '保留中',
  status_pending: '保留中',
  status_confirming: '確認中',
  status_success: '成功',
  status_completed: '完了',
  status_failed: '失敗',
  status_speeding_up: '高速化',
  status_canceling: 'キャンセル中',
  status_canceled: 'キャンセル済み',
  in_progress: '実行中',
  limit_order: '指値',
  market_order: '成行',
  stop_limit_order: '逆指値',
  balance: '残高',
  empty_connect: 'まずウォレットを接続してください',
  empty_register: 'まず初期化してください',
  empty_months3: '過去3か月間のデータはありません',
  show_months3: '過去3か月以内のデータのみを表示',
  view_all: 'すべて表示',
  H1: '1時間',
  D1: '1日',
  D5: '5日',
  M1: '1か月',
  M3: '3か月',
  M6: '6か月',
  YTD: '年初から今日まで',
  Y1: '1年',
  all: 'すべて',
  paste: '貼り付け',
  clear: 'クリア',
  total: '合計',
  amount: '金額',
  order_amount: '注文数量',
  price: '価格',
  order_total: '合計',
  filledAmount: '金額',
  tradeFilledTotal: '価値',
  orderFilledTotal: '合計',
  filledAmount_amount: '約定/数量',
  profit: '利益',
  incompatible_token:
    'このトークンの技術仕様は、DeGateプロトコルと互換性がありません。',
  next: '次へ',
  token_not_verified: '未確認',
  token_not_verified_tips:
    'コントラクトアドレス、アイコン、シンボルは未確認です。詐欺を避けるため、公式の情報源でコントラクトアドレスを確認してください。',
  token_verified: '確認済み',
  token_verified_tips:
    'コントラクトアドレス、アイコン、シンボルが一致しています。',
  deposit_tips_region:
    '現在、REGIONでDeGateにアクセスしています。資金の追加後は、取引機能と内部転送機能はご利用いただけません。',
  complete_time: '後で完了',
  unable_to_initialize: '初期化できません',
  filter_base: '基準',
  filter_quote: 'クォート',
  filter_type: 'タイプ',
  filter_role: 'ロール',
  option_maker: 'メイカー',
  option_taker: 'テーカー',
  start_data: '開始日',
  end_data: '終了日',
  added_to_favorites: 'お気に入りに追加済み',
  removed_to_favorites: 'お気に入りから削除済み',
  show_recents_50: '最新の50件のデータが表示されています。',
  terms_of_service: '利用規約',
  tips_small_unfilled:
    'システム設計で指定された精度に基づいて、注文の未約定分のわずかな部分がDeGate残高に返金されました。',
  notification: '通知',
  server_message_SystemRecovery:
    'システムの復旧後、注文ステータスが変更されたことをお知らせします。',
  learn_more: '詳細はこちら',
  connect_ledger: 'Ledgerに接続',
  ledger_disconnect:
    '「USBDevice」で「transferOut」の実行に失敗しました：デバイスが切断されました。',
  gas_fee_expired: 'ガス料金の有効期限が切れました。もう一度送信してください。',
  scroll_down_to_refresh: '更新するには、下にスクロールしてください。',
  release_to_refresh_immediately: '更新するには、リリースしてください。',
  no_more: 'これ以上のデータはありません',
  loading: '読み込み中...',
  force_withdrawing_token_tips:
    '強制引き出しリクエストが処理中のため、現在の操作は実行できません。',
  speed_up: '高速化',
  transaction_submitted: 'トランザクションが送信されました',
  tx_speed_up: 'トランザクションの高速化',
  tx_cancel: 'トランザクションのキャンセル',
  none: 'なし',
  Language: '言語',
  page: '/ページ',
  go_to: 'に移動',
  icon_indicators: 'インジケーター',
  icon_back: '戻る',
  icon_forward: '進む',
  icon_full_screen: '全画面表示',
  icon_exit_full_screen: '全画面表示を終了',
  icon_buy_sell_orders: '売買注文',
  icon_buy_orders: '購入注文',
  icon_sell_orders: '売却注文',
  icon_enable: 'クリックして有効にする',
  icon_disable: 'クリックして無効にする',
  icon_copy: 'アドレスをコピー',
  icon_view_explorer: 'ブロックエクスプローラーで表示',
  icon_display_by_profit: '利益順に表示',
  icon_display_by_time: '時間順に表示',
  icon_switch: '切り替え',
  eth_code_tips:
    'イーサリアムのネイティブトークン。トークンコントラクトアドレスはありません。',
  TBD: '後日決定',
  TVL: 'TVL',
  go_to_discord: 'またはDiscordに参加してチケットを作成する',
  release: 'リリース：',
  security: 'セキュリティ',
  colon: '：',
  zero_balance: '残高ゼロ',
  ledger_app_version_tips:
    '署名前にメッセージをプレビューするには、LedgerのEthereumアプリをバージョン1.9.19以上に更新してください。',
  ledger_contract_data_tips:
    'イーサリアムアプリの設定で、ブラインド署名またはコントラクトデータを有効にしてください',
  input_auto_corrected_tooltips:
    '最大桁数を超えたため、入力が自動修正されました',
  maximum_decimal_reached: '最大小数点以下桁数に達しました',
  verify_ownership: '所有権の確認',
  enable_trading: '取引を有効にする',
  learn_more_about_signatures_link: '署名について詳しくはこちら >',
  learn_more_about_signatures: '署名について詳しくはこちら',
  sign: '署名',
  sign_step1: 'ウォレットで完了',
  sign_step2: '2つ目の署名を完了',
  not_now: '後で行う',
  view_on_block_explorer: 'ブロックチェーンエクスプローラーで表示',
  view_in_history: '履歴を表示',
  continue_to_place_order: '注文の размещение を続ける',
  Save: '保存',
  sign_to_view: '表示するには署名してください',
  available_degate_balance: '利用可能なDeGate残高',
  Back: '戻る',
  token_has_not_listed: 'このトークンはDeGateにリストされていません。',
  list_now: '今すぐリストする',
  spread_15: 'スプレッド> 15%',
  connected: '接続済み',
  self_list_token: 'インスタントリスティング',
  claim_REBASE: 'REBASEを請求',
  time: '時間',
  time_updated: '更新時間',
  show_in_X_m: 'X分に表示',
  max_gas: '最大ガス料金',
  total_required: '合計必要額',
  Required: '必要額',
  available_balance: '利用可能な残高',
  please_add_funds: 'DeGate残高に資金を追加してください。',
  Side: 'サイド',
  pending: '保留中',
  active: 'アクティブ',
  ended: '終了',
  name: '名前',
  yield: '利回り',
  time_created: '作成日時',
  time_ended: '終了時間',
  frequency: '頻度',
  chain_cancel: 'オンチェーンでキャンセル',
  status: 'ステータス',
  status_chainCancelProgressing: 'オンチェーンキャンセル中',
  status_chainCancelCompleted: 'オンチェーンキャンセル済み',
  filled_total: '約定/合計',
  start_time: '開始時間',
  end_time: '終了時間',
  Summary: '概要',
  Orders: '注文',
  Tutorial: 'チュートリアル',
  top_winner_24h: '24時間トップランキング',
  ID: 'ID',
  Select: '選択',
  Create: '作成',
  Review: '確認',
  Airdrop: 'エアドロップ',
  Airdrops: 'エアドロップ',
  Countdown: 'カウントダウン',
  Day: '日',
  Hour: '時間',
  Minute: '分',
  Second: '秒',
  Days: '日数',
  Hours: '時間数',
  Minutes: '分数',
  Seconds: '秒数',
  Claim: '請求する',
  Expired: '期限切れ',
  Claimed: '請求済み',
  Welcome: 'ようこそ',
  gas_tips_for_amount_exceed_6_digits:
    '金額の桁数が6桁の名目制限を超えているため、追加料金が適用されました。',
  input_auto_corrected_minStep_tips:
    '最小精度を満たすように入力が自動修正されました',
  order_max_limit: '上限を超えました',
  order_min_limit: '下限に達していません',
  order_faild_min_limit:
    '注文の размещение に失敗しました：下限に達していません。',
  order_faild_max_limit: '注文の размещение に失敗しました：上限を超えました。',
  disconnect_m: '切断',
  'account.account_manage': 'セキュリティ',
  'account.account_manage_more': '認証モードとアセットキーについて >',
  'account.what_is_asset_key': '認証モードとアセットキーについて',
  'account.total_value': '総額',
  'account.hide_small_balances': '少額残高を非表示',
  'account.add_to_metamask': 'ウォレットにトークンを追加',
  'account.assets_balance_total': '合計',
  available: '利用可能',
  'account.assets_market': '価値',
  'account.transfer_to_degate_balance': 'DeGate残高に追加',
  'account.search_tokens': 'トークンを検索',
  'account.deposit_title':
    'アセットは、分散型DeGateアカウントに入金されます。これらのアセットは、お客様が完全に管理します。',
  'account.deposit_tips': 'これらの資金は、お客様が完全に管理します。',
  'account.deposit_confirm_btn': '追加',
  'account.deposit_approved_btn': '承認済み',
  'account.deposit_1_ETH': 'DeGate残高に1 ETHを追加',
  'account.deposit_status_pending': '保留中',
  'account.deposit_status_pay_pending': '支払い期限',
  'account.deposit_status_pay_waiting': '支払いがブロードキャストされました',
  'account.deposit_status_pay_confirming': '支払い確認中',
  'account.deposit_tips_block':
    'トランザクションはブロックに含まれるのを待っています',
  'account.deposit_status_pay_btn': '支払う',
  'account.pay_deposit_warning':
    '資金の追加には、追加のガス料金が発生する場合があります',
  'account.pay_deposit_warning_tips':
    'DeGateの補助金が完全に使用されているため、ユーザーは資金の追加にかかる費用を負担する必要がある場合があります。',
  'account.deposit_pending_tips':
    '5分以上保留中の場合は、ウォレットでトランザクションを高速化してください。',
  'account.deposit_pending_tips_ledger':
    '5分以上保留中の場合は、トランザクションを高速化してください。',
  'account.deposit_contract_tips_over_AMOUNT':
    'AMOUNT USDを超える資金の追加には、詳細設定の方法が必要です。',
  'account.deposit_contract_tips_only_all':
    '資金の追加には、詳細設定の方法のみがサポートされています',
  'account.suggest_100': '竕･$100を推奨',
  'account.suggest_100_tips':
    '指値注文を出すには、$100を超える金額をお勧めします。',
  'account.deposit_failed': '失敗',
  'account.deposit_failed_tips':
    '資金を追加するためのオンチェーントランザクションが失敗しました。',
  'account.payment_due': '支払い期限',
  'account.payment_due_tips':
    'DeGate残高に資金を入金するには、追加の支払いが必要です。',
  'account.register_token_code_placeholder':
    'コントラクトアドレスを入力してください',
  'account.register_token_code': 'コントラクトアドレス',
  'account.register_token_symbol': 'シンボル',
  'account.register_token_check': 'リスティングの進捗状況を確認する',
  'account.register_token_code_err_added': 'このトークンはリストされています',
  'account.register_token_next_step': '次へ',
  'account.register_token_tips1':
    'オンチェーントークンリスティングには権限は必要ありません。すぐにトークンをリストしてください。',
  'account.register_token_btn': 'トークンをリストする',
  'account.list_token': 'トークンをリストする',
  'account.withdraw_warning_XXX':
    '需要の増加により、現在、資金の送信にはXXXかかります。',
  'account.withdraw_status_pending': '処理中',
  'account.tansferred_1_ETH': '1 ETH転送済み',
  'account.transfer_status_sent': '送信済み',
  'account.transfer_status_received': '受信済み',
  'account.th_me': '自分',
  'account.th_tx_hash': 'トランザクションハッシュ',
  'account.th_time': '時間',
  'account.locked_order': '指値注文',
  Sending: '送信中',
  'account.locked_claimable': '請求可能',
  'account.locked_grid': 'グリッド戦略',
  'account.personal_sign_reason': '考えられる理由',
  'account.personal_sign_reason1':
    '1.MetaMaskはハードウェアウォレットに接続されています',
  'account.personal_sign_reason2': '2.MetaMaskのバージョンが古くなっています',
  'account.personal_sign_reason3': '3.その他',
  'account.personal_sign_btn': 'もう一度サインイン',
  'account.deposit_arrive_in_30s': '約30秒で到着します',
  'account.deposit_arrive_in_30s_s': '約30秒で完了します',
  'account.account_completed_time_XXX': '完了まで約XXX',
  'account.search_result_no_token': 'トークンが見つかりません',
  'account.search_result_invalid_code': '無効なコントラクトアドレスです',
  'account.search_result_not_listed':
    'トークンは現在DeGateに上場されていません',
  'account.search_result_tips_register':
    'トークン上場を完了するには、コントラクトアドレスを入力してください',
  'account.search_result_not_find': 'まだ見つかりませんか？',
  'account.search_pair_tips3': '資産の取引ペアがありません',
  'account.search_pair_tips3_add': 'ペアを追加してください',
  'account.register_token': '許可不要のトークン上場',
  'account.search_again': 'もう一度検索',
  'account.deposit_type': '手法',
  'account.deposit_type_standard': '標準',
  'account.switch_account_tips': '切り替え済み',
  'account.switch_account_tips_register': '最初に初期化してください。',
  'account.initialize_success': '初期化に成功しました',
  'account.approve': '承認',
  'account.reset_USDT': 'USDT承認をリセット',
  'account.reset_USDT_tips':
    '支出限度額が低すぎるため、USDTは承認のリセットが必要です。',
  'account.next_step': '次へ',
  'account.profit_total': '合計利益',
  'account.profit_history': '利益履歴',
  'account.tab_mining_rewards': 'マイニング報酬',
  'account.yield_total': '合計利回り',
  'account.yield_24h': '24時間利回り',
  claimable: '請求可能',
  'account.yield_history': '利回り履歴',
  'account.total_grid_profit': 'グリッド合計利益',
  'account.grid_strategies': 'グリッド戦略',
  'account.total_rewards': '合計報酬',
  'account.rewards_24h': '24時間報酬',
  'account.rewards': '報酬',
  'menu.register_err':
    'あなたのアドレスには、ブロックチェーンの取引記録がありません。オンチェーン取引を完了してから、もう一度お試しください。たとえば、ウォレットへのトークン転送を実行します。',
  'menu.reset_post_success_withOrders':
    'アセットキーのリセットが開始されました。すべての未約定注文とグリッド戦略はキャンセルされました。',
  'menu.reset_post_success': 'アセットキーのリセットが開始されました。',
  'menu.reset_processing_title': 'アセットキーのリセットが進行中です',
  'menu.reset_processing_desc': '完了するまでお待ちください',
  'trade.choose_token': 'トークンを選択',
  'trade.token_info': 'トークン情報',
  'trade.token_address': 'トークンアドレス',
  'trade.price_range_24h': '24時間価格帯',
  'trade.vol_24h': '24時間出来高',
  'trade.item_price_TOKEN': '価格 (TOKEN)',
  'trade.item_amount_TOKEN': '量 (TOKEN)',
  'trade.order_book_title': '注文板',
  'trade.order_book_total': '合計',
  latest_trades: '最新の取引',
  'trade.trade_history_time': '時間',
  'trade.market_placeholder_price': '市場価格',
  'trade.what_is_stop_limit': 'ストップリミット注文とは',
  'trade.what_is_stop_limit_link': 'ストップリミット注文とは >',
  'trade.placeholder_total': '合計',
  'trade.more_settings': '設定',
  'trade.expire_in_tips':
    '有効期限が切れると、注文は自動的にキャンセルされます。',
  'trade.period_day_s': '日',
  'trade.period_hour_s': '時間',
  'trade.period_minute_s': '分',
  'trade.period_err_input_tips': '有効な数字を入力してください',
  'trade.post_only_label': 'メーカのみ',
  'trade.post_only_tips':
    'メーカのみモードでは、注文板に入力されるのはメーカ注文のみとなります。注文の一部でもテイカー注文として約定できる場合、注文全体が返却されます。メーカのみモードの注文は、ガス料金や取引手数料は発生しません。',
  'trade.post_only_fail_title': '注文を作成できません',
  'trade.post_only_fail_desc':
    '価格を調整するか、「メーカのみ」モードを無効にしてください。',
  'trade.max_gas_fee_tips':
    '最大ガス料金は、取引決済のオンチェーンコストをカバーし、テイカーが支払います。メーカは無料です。超過料金は払い戻されます。',
  'trade.auto': '自動',
  'trade.custom': 'カスタム',
  'trade.enough_for_XX_trades': 'XX取引に十分',
  'trade.gas_fee_per_trade': '1取引あたりのガス料金',
  'trade.gas_fee_per_trade_tips':
    'テイカーは、オンチェーン決済を容易にするため、取引ごとにガス料金が発生します。コストは、イーサリアムネットワークの状況によって変動します。',
  'trade.max_number_of_trades': '最大取引回数',
  'trade.btn_buy_ETH': 'ETHを購入',
  'trade.btn_sell_ETH': 'ETHを売却',
  'trade.max_buy_fee_deducted_NUM':
    'ガス料金が差し引かれました。最大値はNUMです。',
  'trade.notification_limit_order_title': '指値注文',
  'trade.notification_stop_limit_order_title': 'ストップリミット注文',
  'trade.err_price': '価格を入力してください',
  'trade.err_amount_total': '金額または合計を入力してください',
  'trade.err_amount': '金額を入力してください',
  insufficientFee_gas_fee: 'ガス料金不足',
  'trade.err_insufficientFee_desc':
    '最大ガス料金の設定とDeGate残高を確認してください。',
  'trade.cancel_order_success': '注文キャンセル済み',
  'trade.pair_favorite': 'お気に入り',
  'trade.pair_search': 'トークン、コントラクトアドレスを検索',
  'trade.pair_last_price': '価格',
  'trade.pair_change': '変動率',
  'trade.url_parse_err_title': 'このペアは存在しません。',
  'trade.risk_tips': 'リスク警告',
  'trade.base_is_not_default_token_tips':
    'トレードする前に、詐欺を避けるために公式ソースを通じてトークンコントラクトアドレスを確認してください。',
  'trade.chain_cancel': 'オンチェーンで注文をキャンセル',
  'trade.chain_cancel_no_need_tips':
    'この注文はオンチェーンでのキャンセルは必要ありません。',
  'trade.chain_cancel_success': 'リクエストを送信しました',
  'trade.depth_empty': 'まだ注文はありません',
  'trade.depth_empty_asks': '売り注文はありません',
  'trade.depth_empty_bids': '買い注文はありません',
  'trade.depth_empty_tips':
    '注文板に十分な未約定注文がないため、成行注文が失敗しました',
  'trade.history_empty': 'まだ取引はありません',
  'trade.err_price_stable':
    '価格が無効になっています。もう一度お試しください。',
  'trade.price_warning':
    '入力した価格が市場価格から乖離しています。注文する前に確認してください',
  'trade.order_value_tips':
    '最小注文額は<b>QUOTE_A</b>または<b>BASE_A</b>で、MINUSD USDに相当します。この制限を回避するには、成行注文を使用してください。',
  'trade.order_value_tips_quote':
    '最小注文額は<b>QUOTE_A</b>で、MINUSD USDに相当します。この制限を回避するには、成行注文を使用してください。',
  'trade.order_value_tips_stable_quote':
    '最小注文額は<b>QUOTE_A</b>です。この制限を回避するには、成行注文を使用してください。',
  'trade.system_limit': 'システム制限を超えました',
  'trade.stop_limit_untriggered_tips':
    'ストップ価格に達していないため、注文は注文板に提出されていません。',
  'trade.stop_limit_triggered_tips_TIME': '注文はTIMEに注文板に提出されました',
  'trade.flow_of_funds': '資金の流れ',
  'trade.flow_of_funds_tip2':
    '注文が確定しました。注文資金は、ウォレットの残高ではなく、DeGate残高に送られます。',
  'orders.show_current_pair_orders': '他のペアを非表示',
  'orders.orderHistory': '注文履歴',
  'orders.th_time': '時間',
  'orders.th_average_price': '平均価格',
  'orders.th_stop_price': 'ストップ価格',
  'orders.th_limit_price': '指値価格',
  'orders.th_filled_price': '価格',
  'orders.th_filled_amount': '約定済み',
  'orders.th_filled_total': '合計',
  'orders.th_trade_reconciliation': '突合',
  'orders.th_trade_reconciliation_tips':
    'DeGateでのマッチングとオンチェーンでの決済に使用される計算モデルが異なるため、2つの計算結果にわずかな違いが生じる可能性があります。この場合、システムはオンチェーンの値を基準として使用し、DeGate残高の不足分を補います。',
  'orders.hide_cancelled_expired_orders': 'キャンセル/失効したものを非表示',
  'orders.status_open': 'オープン',
  'orders.status_pending': '保留中',
  'orders.status_completed': '約定済み',
  'orders.status_completed_part': '部分的に約定済み',
  'orders.status_expired': '失効',
  'orders.detail_price': '平均/価格',
  'orders.average_price': '平均価格',
  'orders.detail_type': '注文タイプ',
  'orders.detail_trade_fee': '取引手数料：',
  'orders.gas_preAuth': '最大ガス料金：',
  'orders.fee_reconciliation': '突合：',
  'orders.gas_paid': '支払われたガス料金：',
  'orders.gas': 'ガス料金：',
  'orders.trades_N': '取引（N）',
  'orders.detail_filled_total': '合計',
  'orders.detail_filled_detail': '取引詳細',
  'orders.detail_filled_time': '時間',
  'orders.order_maker_free': 'メーカ手数料無料',
  'orders.openOrders_empty': '未約定注文なし',
  'orders.export_orders_1_year': '最近1年間の注文データをエクスポートします。',
  'orders.export_trades_1_year': '最近1年間の取引データをエクスポートします。',
  'orders.export_data': 'データのエクスポート',
  'orders.export': 'エクスポート',
  'orders.export_processing': '処理中です。しばらくお待ちください。',
  'orders.export_tips_100_percent':
    'ファイルは、進捗状況が100%に達するとダウンロードされます',
  'orders.sign_to_view_balance': '残高を表示するにはサインインしてください',
  'orders.sign_to_view_history': '履歴を表示するにはサインインしてください',
  'orders.sign_to_view_security_options':
    'セキュリティオプションを表示するにはサインインしてください',
  'gridTrade.automatic_strategy': '自動',
  'gridTrade.manual_strategy': '手動',
  'gridTrade.placeholder_amount': '金額を入力してください',
  'gridTrade.low_price': '下限',
  'gridTrade.high_price': '上限',
  'gridTrade.initial_investment': '投資額',
  'gridTrade.grid_levels_tips':
    '価格帯内の未約定注文数を決定するために使用されます。',
  'gridTrade.profit_per_grid': 'グリッドあたりの利益',
  'gridTrade.profit_per_grid_tips':
    'グリッド戦略の収益性のための重要なパラメータです。 グリッドあたりの利益 = （高値 - 安値） / 安値。 高値と安値は、グリッド戦略内の2つの隣接するグリッド線の価格を指します。',
  'gridTrade.min_grid_volume_XXX_ETH': 'グリッドあたりの金額：最小XXX ETH',
  'gridTrade.min_grid_volume_err':
    '投資額を増やすか、グリッド数を減らしてください',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    '注文板に十分な注文がないため、このペアのグリッド戦略を作成できません。',
  'gridTrade.grid_to_spot_trade': '現物取引に移動',
  'gridTrade.grid_level_over_err': 'グリッド数を減らしてください',
  'gridTrade.grid_prices_err': '価格帯を広げてください',
  'gridTrade.grid_create_err': 'パラメータを調整して、もう一度お試しください。',
  'gridTrade.tips_grid_profit':
    '利益はDeGate残高に直接入金され、すぐに利用できます。',
  'gridTrade.tips_grid_balance_0_BASE':
    '市場価格の上昇により、このグリッド戦略下のすべての注文が買い注文になりました。したがって、BASEの現在の残高は0になりました。',
  'gridTrade.tips_grid_balance_0_BASE_2':
    '市場価格の上昇により、このグリッド戦略下のすべての注文が買い注文になりました。さらに、これらの注文の一部は部分的に約定されています。したがって、BASEの現在の残高は>0です。',
  'gridTrade.tips_grid_balance_0_QUOTE':
    '市場価格の下落により、このグリッド戦略下のすべての注文が売り注文になりました。したがって、QUOTEの現在の残高は0になりました。',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    '市場価格の下落により、このグリッド戦略下のすべての注文が売り注文になりました。さらに、これらの注文の一部は部分的に約定されています。したがって、QUOTEの現在の残高は> 0です。',
  'gridTrade.grid_param_err': 'グリッド戦略のパラメータを入力してください',
  'gridTrade.tv_buy': '購入',
  'gridTrade.tv_sell': '売却',
  'gridTrade.tv_waiting': '待機中',
  'gridTrade.chain_cancel_no_need_tips':
    'このグリッド戦略はオンチェーンでのキャンセルは必要ありません。',
  'gridTrade.grid_over_max_number_err':
    '実行中のグリッド戦略の最大数に達したため、新しいグリッドを作成できません。',
  'gridTrade.preview_orders_in_graph': '注文を表示',
  'gridTrade.greate_news': 'グッドニュース：',
  'gridTrade.min_amount_required_XXX': '最低XXXが必要です',
  'gridTrade.highest_grid_apy': '最高グリッドAPY',
  'gridTrade.for_the_last_7_days': '過去7日間',
  'gridTrade.min_investment': '最低投資額',
  'gridTrade.grid_need_XXX': 'グリッドの場合は$XXX',
  'gridTrade.mining_need_XXX': 'マイニングの場合は$XXX',
  'gridTrade.recommended_params_cannot_be_applied':
    '投資額が不足しているため、推奨パラメータを適用できません。手動モードで調整できます。',
  'gridTrade.copy_params_to_manual': 'パラメータを手動にコピー',
  'gridOrders.grid_recents': '私の最新の取引',
  'gridOrders.th_created_time': '作成時間',
  'gridOrders.grid_profit': 'グリッド利益',
  'gridOrders.grid_cancel': '終了',
  open_orders: '未約定注文',
  'gridOrders.tab_history_orders': '約定済み注文',
  'gridOrders.tab_trade_history': '取引履歴',
  'gridOrders.detail_current_balance': '現在残高',
  'gridOrders.detail_ending_balance': '終了残高',
  'gridOrders.detail_ending_balance_tips':
    'グリッド戦略が終了したときのアセット残高。',
  'gridOrders.detail_in_order_funds': '注文中の資金：',
  'gridOrders.detail_on_hold_funds':
    '保留中の資金（部分的に約定された注文から）：',
  'gridOrders.detail_transactions': '約定済み注文数',
  'gridOrders.detail_investment': '初期投資額',
  'gridOrders.detail_running_time': '期間',
  'gridOrders.detail_prices': '価格帯',
  number_of_grids: 'グリッド数',
  'gridOrders.detail_expire_time': '後で期限切れ',
  'gridOrders.detail_expire_time_tooltip':
    'このグリッド戦略内の注文は、有効期限が切れるとキャンセルされます。',
  'gridOrders.detail_valid_period': '有効期限設定',
  'gridOrders.open_orders_sell': '売却',
  'gridOrders.open_orders_buy': '購入',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': '合計',
  'gridOrders.history_orders_filled': '約定済み：',
  'gridOrders.history_orders_price': '価格：',
  'gridOrders.history_orders_time': '時間',
  'gridOrders.history_orders_filled_price': '平均価格',
  'gridOrders.history_orders_filled_amount': '約定済み',
  'gridOrders.history_orders_filled_total': '合計',
  'gridOrders.history_orders_profit_tips':
    '利益は、安く買って高く売るというサイクルを経て価格差から生まれます。例えば、1 ETH を 4000 USDC で購入するグリッド注文が約定した後、グリッド幅が 50 USDC の場合、システムは自動的に 4050 USDC で 1 ETH を売却する注文を新たに発注します。この注文も約定すると、50 USDC の利益が得られます。',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    'PRICE の買い注文が約定した後、利益が表示されます。',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    'PRICE の売り注文が約定した後、利益が表示されます。',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    'PRICE の注文は、約定するとここに表示されます',
  'gridOrders.grid_cancel_title': 'グリッド戦略の終了',
  'gridOrders.grid_cancel_content':
    'このグリッド戦略のすべての注文はすぐにキャンセルされます。',
  'gridOrders.grid_cancel_content2':
    '現在、このグリッド戦略でマイニング中です。このグリッド戦略を終了すると、すべてのマイニング報酬が没収され、関連するすべてのグリッド注文はすぐにキャンセルされます。',
  'gridOrders.copy_grid_title': '次のグリッド戦略のパラメータがコピーされます',
  'gridOrders.copy_grid_btn': 'パネルにコピー',
  'gridOrders.copy_grid_success': 'グリッド戦略がコピーされました',
  'gridOrders.grid_init_funds_XXX': '初期投資額: $XXX',
  'gridOrders.grid_init_funds_tips':
    'APYは、グリッド戦略作成時の初期配分額に基づいて計算されます。',
  'gridOrders.tab_m_trade': '取引',
  grid_apy: 'グリッドAPY',
  grid_apy_tips: 'グリッド取引のみによる年換算利益率。フロート利益は除く。',
  'gridOrders.tab_mining_profit': 'マイニングAPY',
  'gridOrders.tab_mining_profit_tips':
    '年率換算された採掘利益は、グリッド・ストラテジーの初期値と期間から計算されます。',
  'gridOrders.mining_rewards': '報酬:',
  'gridOrders.open_orders_empty_tips':
    'データの読み込み中はしばらくお待ちください',
  'gridOrders.market_value': '時価総額:',
  'gridOrders.market_value_details': '詳細',
  'gridOrders.fund_details': '資金詳細',
  'gridOrders.m_in_order_funds': '注文中の資金',
  'gridOrders.m_in_order_funds_tips':
    'このストラテジーのすべての未決済注文に含まれる資金の合計。',
  'gridOrders.m_on_hold_funds': '待機資金',
  'gridOrders.m_on_hold_funds_tips': '部分的に満たされた注文の結果。',
  'gridOrders.initial_value': '初期値',
  'mining.my_title': 'マイ・マイニング・プール',
  'mining.index_desc':
    'グリッド戦略を作成します。流動性のあるマイニング報酬でグリッドの利益を高めましょう。',
  'mining.apply': '新規プール申請',
  'mining.claimable_rewards_box': '請求可能な報酬',
  'mining.rewards_more': 'その他',
  'mining.tab_pools': 'マイニングプール',
  'mining.tab_my': '私のマイニング統計',
  'mining.pools_tab_live': 'ライブ',
  'mining.pools_tab_upcoming': '今後の予定',
  'mining.pools_funds': '合計TVL',
  'mining.pools_funds_tips':
    '最低注文金額120ドルを満たすグリッド注文の合計金額。',
  'mining.pools_mining_funds': 'マイニングTVL',
  'mining.mining_apr': 'APY',
  'mining.mining_apr_tips':
    'マイニング報酬とマイニングTVLから推定される年率収益率。',
  'mining.view_rule_link': 'マイニングルール',
  'mining.pools_info_to_confirm': '未定',
  'mining.pools_no_wait': '利用可能なマイニングプールはありません',
  'mining.my_mining_funds': 'マイ・マイニング・ファンド',
  'mining.my_mining_rewards': '私のマイニング報酬',
  'mining.my_th_profit_token_price': '最新価格',
  'mining.my_th_total_rewards': 'オールタイムリワード',
  'mining.my_th_24h_rewards': '24時間リワード',
  'mining.my_grids': 'マイ・マイニング',
  'mining.only_show_mining_grids': 'アクティブのみ',
  'mining.my_th_mining_status': 'マイニングステータス',
  'mining.status_framing': 'アクティブ',
  'mining.status_over_price': '価格範囲外',
  'mining.status_mining_over': 'マイニング終了',
  'mining.status_grid_closed': 'ストラテジー終了',
  'mining.status_grid_expired': 'ストラテジー終了',
  'mining.empty_no_faring_grids':
    '現在採掘可能なグリッドストラテジーはありません',
  'mining.go_mining_pool': 'マイニングプールへ移動',
  'mining.go_mining': 'マイニングを開始する',
  'mining.go_to_grid': 'グリッド戦略へ',
  'mining.mining_help': 'マイニングガイド',
  'mining.mining_available': '適格',
  'mining.mining_available_tips': '注文金額の基準を満たす',
  'mining.mining_unavailable': '不適格',
  'mining.mining_partially_available': '一部適格',
  'mining.mining_unavailable_tips': '注文価格の基準を満たしていない',
  'mining.mining_preview': 'マイニングプレビュー',
  'mining.mining_total_profit': 'マイニング報酬',
  'mining.mining_24h_profit': '24時間マイニング報酬',
  'mining.profit_unable_display': '該当なし',
  'mining.mining_funds': 'マイニング資金',
  'mining.mining_funds_tips':
    'この取引ペアのマイニング注文額基準を満たすすべてのグリッドストラテジーからの注文額の合計。',
  'mining.tab_mining_profit_details': '報酬詳細',
  'mining.tab_mining_orders': 'マイニング注文',
  'mining.th_rewards': '報酬',
  'mining.th_rewards_origin': '報酬ソース',
  'mining.th_rewards_origin_tips':
    'マイニング報酬は、グリッド注文価格が注文ブックの報酬価格範囲内（買値の最高値 * 0.99 ~ 売値の最安値 *1.01）にある場合に受け取ることができます。',
  'mining.th_rewards_origin_tips_stable':
    'マイニング報酬は、グリッド注文価格がオーダーブックの報酬価格範囲内（最高買い価格～最低売り価格）にあるときに受け取られます。',
  'mining.th_time': '時間',
  'mining.plan_title': 'ETH/USDCプール詳細',
  'mining.phase_cur': '現在のフェーズ',
  'mining.phase_range_N_XX': 'フェーズ N (XX)',
  'mining.phase_index_N': 'フェーズ N',
  'mining.phase_reward': 'デイリー報酬',
  'mining.phase_to_release': '発表予定',
  'mining.my_rewards': 'マイ・リワード',
  'mining.claimable_rewards': '利用可能',
  'mining.locked_rewards': 'ロック',
  'mining.locker_rewards_tips':
    'マイニング報酬は、グリッド・ストラテジーが12時間有効になってから請求できる。',
  'mining.claimed_success': '請求成功',
  'mining.claimed_tips': '内部送金ですぐに送られます。',
  'mining.claimed_view_btn': '確認する',
  'mining.mining_plan': '採掘スケジュール',
  'mining.phase_unpublished': '発表予定',
  'mining.all_pools': 'すべてのプール',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    'AMOUNT BASEを@価格で売る',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    'AMOUNT BASEの買い @ 価格相場',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': 'AMOUNT BASEを売る',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': '数量ベース購入',
  'notification.cancel_grid_desc_PAIR_PRICES': 'ペア：価格',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    '数量ベースを価格で売る',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    '合計金額でベースを売る',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    '合計金額でAMOUNT BASEを購入する',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    'BASEをTOTAL QUOTEで買う',
  'notification.cancel_limit': '指値注文取消',
  'notification.cancel_stop_limit': '逆指値注文取消',
  'notification.cancel_market': '成行注文取消',
  'notification.cancel_grid': 'グリッド戦略終了',
  'notification.cancel_limit_expired': '指値注文失効',
  'notification.cancel_stop_limit_expired': '逆指値注文失効',
  'notification.cancel_grid_expired': 'グリッド戦略終了',
  'notification.cancel_limit_order_for_gas_desc':
    '注文のガス代がなくなりました。一部注文が成立し、残りはキャンセルされました。',
  'notification.cancel_limit_order_for_gas_filled_amount': '充填',
  'notification.cancel_limit_order_for_gas_amount': '金額',
  'notification.view_history_orders': '注文履歴を見る',
  'notification.cancel_market_for_depth_title':
    'ご注文の一部が埋まり、キャンセルされました。',
  'notification.price_slippage_protection': '価格スリッページ防止機能',
  'notification.price_slippage_protection_desc':
    'DeGateの成行注文には、ボラティリティが高く流動性が低い場合に損失を限定するため、10%の価格スリッページ保護機能が自動的に含まれています。この保護を回避するには、指値注文を使用します。',
  'notification.cancel_market_for_depth_warning':
    'DeGate成行注文は価格保護メカニズムを導入しており、ユーザーは価格のボラティリティが高く、流動性が低い市場状況での損失を抑えることができます。価格保護機能を利用したくない場合は、指値注文をご利用ください。',
  'notification.dca_plan_ended': 'DCAプラン終了',
  'notification.cancel_dca_desc_PAIR': 'ペア',
  'notification.trade_limit_partially': '指値注文一部約定',
  'notification.trade_limit_filled': '指値注文',
  'notification.trade_market_partially': '成行注文が一部成立',
  'notification.trade_market_filled': '成行注文',
  'notification.trade_stop_limit_partially': '指値逆指値注文',
  'notification.trade_stop_limit_filled': '逆指値注文',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    '注文が成立した。トークンを受け取った。',
  'notification.mobile_trade_partially_AMOUNT_TOKEN': '注文が一部成立 注文金額',
  'info.overview': '概要',
  'info.accounts': '総ユーザー数',
  'info.pairs': '取引ペア',
  'info.turnover': '全時間取引高',
  'info.turnover_24': '24時間取引量',
  'info.dg_supply': 'DG循環供給',
  'info.top_movers_no_increased': '24時間以内に値上がりしたトークンなし',
  'info.top_movers_no_decreased': '24時間以内に値下がりしたトークンはない',
  'info.top_pairs': '上位ペア',
  Pair: 'ペア',
  'info.th_change': '24時間変化',
  'info.th_l_up_2': '＋2% 深さ',
  'info.th_l_down_2': '-2% 深さ',
  'info.th_turnover_24': '24時間出来高',
  'info.tvl': '合計値 ロック',
  'm.home': 'ホーム',
  'm.grid': 'グリッド',
  'm.browser_wallet': 'ブラウザウォレット',
  'm.choose_pair': 'ペアを選択',
  'm.orderBook_default': 'デフォルト',
  'm.orderBook_bids': '買い注文',
  'm.orderBook_asks': '売り注文',
  'm.decimals': '10進数',
  'm.lowest_price_24h': '24時間安値',
  'm.highest_price_24h': '24時間足高値',
  'm.vol_24h': '24時間足',
  'm.orderbook_buy': '買い',
  'm.orderbook_sell': '売り',
  'm.go_to_trade': '取引に進む',
  'm.choose_token': 'トークンを選択',
  'm.from_address': '送信者アドレス',
  'm.to_address': '受信者アドレス',
  'm.transfer_send': '送信',
  'm.transfer_receive': '受け取る',
  'm.my_grid': '私のグリッド戦略',
  'm.grid_profit_24': '24時間利益',
  trades_24h: '24時間取引',
  'm.grid_profit_total': '利益合計',
  'm.grid_over_prices': '値幅外',
  'm.create_grid': 'グリッド戦略の作成',
  'm.grid_history': '取引履歴',
  'm.grid_empty': 'アクティブなグリッド戦略なし',
  'm.grid_tutorial': 'グリッドチュートリアル',
  'm.grid_params_to_manual': 'パラメータをマニュアルにコピー',
  'm.balance_err': 'バランス不足 利用可能',
  'm.preview_grid': 'プレビュー注文',
  last_price: '最終価格',
  'm.grid_desc':
    'グリッド取引は、定義された範囲内での売買を自動化する取引戦略です。',
  'm.view_tutorial': 'チュートリアルを見る',
  'm.grid_profit_tips_sell':
    'この売り注文が完全に満たされたときに計算されます。',
  'm.grid_profit_tips_buy':
    'この買い注文が完全に満たされたときに計算されます。',
  'm.hot': 'ホット',
  'm.all': '全てを見る',
  'm.vol_24': '24時間足',
  'm.transfer_t1': '内部',
  'm.transfer_t2': '振替',
  'activity.th_date': '時間',
  'activity.th_type': 'タイプ',
  'activity.th_fee': '料金',
  'activity.th_content': '内容',
  'activity.type_register_token': 'トークン一覧',
  'activity.type_register_pair': 'ペア追加',
  'activity.type_pay_deposit': '入金決済',
  'activity.type_reset_account': 'アセットキーのリセット',
  on_chain_order_cancellation: 'オンチェーン注文キャンセル',
  'activity.count_N': 'カウント N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE': '売り注文',
  'activity.order_market_desc_SELL_AMOUNT_BASE': '売り金額ベース',
  'activity.reset_status_restting': 'リセット',
  'activity.to_trade': '取引',
  'dca.dca_plan': 'DCAプラン',
  'dca.dca_explain': 'ドルコスト平均法',
  'dca.daily': '日次',
  'dca.weekly': '週足',
  'dca.custom': 'カスタム',
  'dca.every': '毎',
  'dca.amount_per_order': '注文ごとの金額',
  'dca.price_limit': '価格制限',
  'dca.maximum_price': '最高価格',
  'dca.minimum_price': '最低価格',
  'dca.number_of_orders': '注文数',
  'dca.create_dca_plan': 'DCAプランの作成',
  'dca.max_gas_fee_per_order': '注文あたりの最大ガス料金',
  'dca.maximum_plan_order_limit_reached': 'プランの最大注文数に達しました。',
  'dca.end_time_should_be_set_after_the_current_time':
    '終了時刻は現在時刻より後に設定してください。',
  'dca.please_enter_amount_per_order': '注文ごとの金額を入力してください。',
  'dca.please_enter_maximum_price': '最大価格を入力してください',
  'dca.please_enter_minimum_price': '最低価格を入力してください。',
  'dca.order_placement_failed_open_order_limit_exceeded':
    '注文発注に失敗しました: 未決済注文の上限を超えました。',
  'dca.total': '合計',
  'dca.filled': '注文済み',
  'dca.received': '受信済み',
  'dca.time_to_end': '終了時間',
  'dca.cancel_on_chain': 'キャンセル',
  'dca.filled_amount': '記入/金額',
  'dca.status_executed': '実行済み',
  'dca.status_scheduled': '予約済み',
  'dca.status_failed': '失敗',
  'dca.order_cancled_by_user':
    'ユーザーがDCAプランを終了したため、注文がキャンセルされました。',
  'dca.order_cancled_by_access':
    'DeGateへのアクセスが制限されたため、注文がキャンセルされました。',
  'dca.order_cancled_by_gas': 'ガス料金不足のため、発注に失敗しました。',
  'dca.order_cancled_by_order_book':
    '注文ブックに一致する注文がないため、注文発注に失敗しました。',
  'dca.order_cancled_by_balance':
    'DeGate残高が不足しているため、注文発注に失敗しました。',
  'dca.order_cancled_by_min_value':
    '最低注文金額100ドルを満たしていないため、発注に失敗しました。',
  'dca.order_cancled_by_system_error':
    'システムエラーにより発注に失敗しました。',
  'dca.chain_cancel_no_need_tips':
    'このDCAプランでは、オンチェーンキャンセルは必要ありません。',
  'dca.end_dca_plan': 'DCAプランの終了',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    'このDCAプランの注文はすべて直ちにキャンセルされます。',
  'dca.no_active_dca_plan': 'アクティブなDCAプランはありません。',
  'dca.time_scheduled': '予定時刻',
  'campaign.event_period': 'イベント期間',
  'campaign.grid2401_time':
    '2024年1月22日20:00:00～2024年1月29日20:00:00 (UTC+8)',
  'campaign.event_has_ended': 'イベントは終了しました。',
  'campaign.current_apy': '現在の年率利回り',
  'campaign.grid_strategy_income':
    'グリッド・ストラテジー・インカム＋賞金プール・シェア',
  'campaign.tvl_participating': 'TVL参加',
  'campaign.share_of_tvl': 'TVLのシェア',
  'campaign.my_profit': '私の利益',
  'campaign.grid_strategy_profit': 'グリッド・ストラテジー利益',
  'campaign.share_of_prize_pool': '賞金プールのシェア',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    'グリッド・ストラテジーの利益が利用可能残高に追加されました。',
  'campaign.shared_income_from_usdc_prize_pool': 'USDC賞金プールからの共有収入',
  'campaign.is_black_tips': '賞金プールを共有する資格はありません。',
  'campaign.calculating': '計算',
  'campaign.claim_after_end': '賞金はイベント終了時に請求できます。',
  'campaign.how_to_participate': '参加方法',
  'campaign.rule': 'グリッド戦略を作成し、賞金プールを比例配分します。',
  'campaign.step1': 'ステップ1',
  'campaign.step2': 'ステップ2',
  'campaign.step3': 'ステップ3',
  'campaign.grid2401_step1':
    '資金を追加したり取引したりして、ETHとUSDCを準備する。',
  'campaign.grid2401_step2_PAIR':
    '以下のようにPAIRのグリッド戦略を設定します。',
  'campaign.grid2401_step2_desc1_pre': '価格帯： 発表予定',
  'campaign.grid2401_step2_desc2_pre': 'グリッドの数 未定',
  'campaign.copy_strategy': 'ストラテジーのコピー',
  'campaign.grid2401_step3':
    'イベント終了後、このイベントページで収益を請求することができます。イベント終了後30日以内にご請求ください。',
  'campaign.what_is_grid': 'グリッド戦略とは',
  'campaign.notes': '参加にあたって',
  'campaign.notes_1_title': '参加資格',
  'campaign.notes_1_desc':
    'グリッド・ストラテジーは、価格帯とグリッド数が作成時に要求されたものと全く同じ場合のみ対象となります。',
  'campaign.notes_2_title': '制限',
  'campaign.notes_3_title': '賞金請求',
  'campaign.notes_3_desc':
    '賞金請求はイベント終了時に可能となり、イベント終了後30日以内に請求することができます。',
  'campaign.faq': 'FAQ',
  'campaign.grid2401_faq_1': '1. 賞金はどのように計算されますか？',
  'campaign.grid2401_faq_2':
    '2. このイベントに関する質問はどこで受け付けていますか？',
  'campaign.grid2401_faq_3':
    '3. USDTを保有していますが、ETHとUSDCはどのように入手できますか？',
  'campaign.grid2401_faq_4':
    '4. グリッド戦略を通じて完了した取引に手数料を支払う必要がありますか？',
  'campaign.grid2401_faq_4_res':
    'DeGateでは、メーカー注文はすべて無料です。グリッドストラテジーで生成される注文は全てメーカー注文ですので、DeGateでのグリッドストラテジーの設定は完全に無料です。',
  'campaign.grid2401_faq_5':
    '5. グリッドストラテジーはイベント終了後も収益を生み出しますか？',
  'campaign.grid2401_faq_5_res':
    'はい、イベント終了後も、価格がストラテジーの範囲内であれば、ストラテジーは収益を生み続けます。また、イベント終了後も、グリッド・ストラテジーのパラメーターを調整することで、よりご自身の好みに合ったストラテジーを作成し、引き続き収益を得ることができます。',
  'campaign.grid2401_faq_others': 'その他のイベント詳細',
  'campaign.grid2401_faq_others_1':
    '1. 1ユーザーにつき1ウォレットのみ。悪質なシビル・リワード・ファーミングが検出された場合、DeGateは参加者のリワードをキャンセルする権利を有します。',
  'campaign.grid2401_faq_others_2':
    '2. イベント期間中、範囲外のグリッドもウェイト計算の一部としてカウントされます。',
  'campaign.grid2401_faq_others_3':
    '3. DeGate は、極端な状況（市場の変動など）において、イベントを早期に終了する権利を留保します。',
  'campaign.grid2401_faq_others_4':
    '4. イベント終了後30日以内に請求されなかった報酬は没収されます。',
  'campaign.invest_max_5000': '最高投資額5,000ドル',
  'campaign.invest_mininum': '最低投資額',
  'airdrop.create_airdrop': 'エアドロップを作成する',
  'airdrop.important_note':
    '重要：誰でも許可なくエアドロップを作成することができます。',
  'airdrop.my_airdrop': 'マイ・エアドロップ',
  'airdrop.time_limited': '期間限定',
  'airdrop.no_airdrop': 'まだエアドロップはありません',
  'airdrop.claim_airdrop': 'エアドロップを申請する',
  'airdrop.recipients_number': '受取人数',
  'airdrop.total_amount': '合計金額',
  'airdrop.retrieve': '回収',
  Unclaimed: '未請求',
  'airdrop.retrieve_successful': '回収成功',
  'airdrop.claim_successful': '請求成功',
  'airdrop.retrieve_unclaimed_airdrop': '未請求のエアドロップを検索する',
  'airdrop.airdrop_token': 'エアドロップ・トークン',
  'airdrop.token_not_meet_criteria':
    'このトークンはエアドロップの条件を満たしていません。',
  'airdrop.airdrop_list': 'エアドロップ一覧',
  'airdrop.download_template': 'テンプレートのダウンロード',
  'airdrop.click_or_drag_upload_list':
    'クリックまたはドラッグしてリストをアップロード',
  'airdrop.validation_passed': '有効期限',
  'airdrop.must_earlier_than_end_time': '終了時間前であること',
  'airdrop.cannot_more_than_2_years_from_now': '2年以上先であること',
  'airdrop.cannot_parse_file':
    'ファイルを解析できません。テンプレートをご利用ください。',
  'airdrop.format_requirement_not_met': 'フォーマット要件を満たしていません。',
  'airdrop.view_error_repost': 'エラーレポートを見る',
  'airdrop.error_report': 'エラー・レポート',
  'airdrop.line': 'ライン',
  'airdrop.reason': '理由',
  'airdrop.duplicated_address': '住所の重複',
  incorrect_address_format: '住所の書式が正しくない',
  'airdrop.incorrect_amount_format': '金額形式が正しくない',
  'airdrop.airdrop_plan_created': 'エアドロップ・プランの作成',
  'airdrop.max_50000': '最大50000アドレス',
  'airdrop.upload_file_rule': 'CSVのみ対応',
  'airdrop.to_check_airdrop_eligibility':
    'エアドロップを表示するための初期化完了',
  'airdrop.complete_initialization_to_claim_airdrops':
    'エアドロップ請求初期化完了',
  'airdrop.complete_initialization_to_view_airdrops':
    'エアドロップ閲覧初期化完了',
  'airdrop.you_are_eligible_for': '対象となります：',
  'airdrop.and_more': 'その他',
  'airdrop.congratulations': 'おめでとうございます！',
  'airdrop.airdrop_fee': 'エアドロップ料金',
  'countdown.countdown_plan': 'カウントダウンプラン',
  'countdown.create_countdown_plan': 'カウントダウン作成',
  'countdown.my_countdown_plan': '私の作品',
  'countdown.countdown_trading_pair': 'カウントダウン取引ペア',
  'countdown.countdown_display': 'カウントダウン表示',
  'countdown.token_not_meet_criteria':
    'このトークンはカウントダウンの条件を満たしていません。',
  'countdown.countdown_tips':
    '選択した取引ペアの取引ページにカウントダウンが表示されます。',
  'countdown.max_30_days': '今から30日以内',
  'countdown.review_countdown_plan': 'カウントダウンプラン',
  'countdown.countdown_fee': 'カウントダウン料金',
  'countdown.countdown_plan_created': 'カウントダウンプラン作成',
  'countdown.trading_will_start_in': '取引開始日',
  'countdown.trading_will_start_at_YYYY': '取引開始日時',
  'countdown.cannot_earlier_than_current_time':
    '現在時刻より前に約定することはできません。',
  'dca.price_limit_buy_tips':
    '有効化されると、買い注文は最大価格と同じかそれ以下の価格でのみ執行されます。この機能は手数料ゼロ機能と互換性があります。',
  'dca.price_limit_sell_tips':
    '有効化すると、売り注文は最低価格以上の価格でのみ執行されます。この機能は手数料ゼロ機能と互換性があります。',
  'dca.zero_fee': 'ゼロ・フィー',
  'dca.zero_fee_buy_tips':
    'ゼロフィーを有効にすると、DCA注文はメーカー指値注文として処理されます。発注後、注文ブックで最も高い買値が設定されます。注文がすぐに成立しない、または全く成立しない可能性があることにご留意ください。',
  'dca.zero_fee_sell_tips':
    'ゼロフィーを有効にすると、DCA注文はメーカー指値注文として処理されます。DCA注文はMaker-Onlyの指値注文として処理され、各売値は発注後のオーダーブックにおける最安値の売呼値に設定されます。注文が即時に成立しない、または全く成立しない可能性があることにご留意ください。',
  'dca.order_canceled_post_only_buy_failed':
    '注文ブックに買い注文がないため、注文発注に失敗しました。',
  'dca.order_canceled_post_only_sell_failed':
    '注文ブックに売り注文がないため、注文発注に失敗し、注文の売り価格が設定されない。',
  start_time_cannot_before_current_time:
    '開始時刻が現在時刻より前であることはできません。',
  start_time_must_before_end_time:
    '開始時刻は終了時刻より前でなければなりません。',
  list_token: 'トークン一覧',
  contract_address_does_not_exist: '契約アドレスが存在しません。',
  token_listed: 'このトークンは上場済みです。',
  XXX_is_listed: 'XXXをリストアップ中',
  view_progress: '進捗を見る',
  pair_create_tips: 'DeGateでは、取引ペアの即時追加が可能です。',
  base_token: '基本トークン',
  quote_token: 'クォート・トークン',
  existing_pair: '既存のペア',
  trade_now: '今すぐ取引',
  pair_XXX_added_successfully: 'XXXが正常に追加されました',
  qty_per_grid: 'グリッドあたりの数量',
  grid_minimum_not_reached: '最小値に達しない',
  total_profit: '利益合計',
  total_apy: '合計APY',
  float_profit: 'フロート利益',
  grid_profit_24h: '24時間グリッド利益',
  pnl: 'PnL',
  eligibility: '適格性',
  rewards: '報酬',
  view_mining_statistics: 'マイニング統計を見る',
  your_entry: '資金入力',
  refunded: '返還済み',
  large_price_spread: '大きな価格スプレッド',
  large_price_spread_tips:
    'オーダーブックに最安売り価格と最高買い価格の間に大きなスプレッドがあり、損失のリスクがあります。デュアルアセットモードでの投資を推奨します。',
  continue_anyway: 'それでも続行',
  insufficient_order_book_liquidity_decrease_investment:
    'オーダーブックの流動性が不十分です。投資を減らしてください。',
  initial_buy: '初回買い',
  closing_sell: '売却終了',
  No: 'いいえ',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    'DCA注文は、実行時に<b>$XXXの価格が$PRICEを下回る場合</b>に失敗します。',
  zero_fee: 'ゼロ手数料',
  minimum_order_value_is_VALUE: '最小注文額は<b>$VALUE</b>です。',
  Note: '注記',
  Continue: '続行',
  estimated_apy: '推定APY',
  based_on_data_from_last_7_days: '過去7日間のデータに基づく',
  top_gainers_24h: '24時間トップ上昇銘柄',
  top_losers_24h: '24時間トップ下落銘柄',
  listed_tokens: 'リストされたトークン',
  vol: 'ボリューム',
  let_s_go: '行こう',
  reject: '拒否',
  maximum_N_due_to_price_ticks: '価格刻みによる最大N',
  Saved: '保存済み',
  minimum_order_value_$100_$QUOTE: '最小注文額は<b>$100 $QUOTE</b>です。',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    '最小注文額は<b>$AMOUNT $QUOTE</b>（約$$100）です。',
  no_restriction_with_market_order: '<b>マーケットオーダー</b>では制限なし',
  go_to_market_order: 'マーケットオーダーに進む',
  Mining_Eligibility: 'マイニング適格性',
  How_to_earn_mining_rewards: 'マイニング報酬を得る方法',
  Order_Value: '注文額',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    'グリッド注文は、戦略作成時に<b>BV BASE</b>または<b>QV QUOTE</b>である必要があります。',
  'mining.mining_tips_QV_QUOTE':
    'グリッド注文は、戦略作成時に<b>QV QUOTE</b>である必要があります。',
  Mining_Price_Range: 'マイニング価格範囲',
  'mining.status_over_price_tips':
    'グリッド注文の価格は、オーダーブック内の最高買い価格 * 0.99から最低売り価格 * 1.01までの<b>マイニング価格範囲</b>内である必要があります。',
  'mining.status_over_price_tips_stable':
    'グリッド注文の価格は、オーダーブック内の最高買い価格から最低売り価格までの<b>マイニング価格範囲</b>内である必要があります。',
  Eligible_for_Mining: 'マイニングに適格',
  Mining_Satus: 'マイニングステータス',
  Mining_Satus_Mining: 'マイニング',
  Mining_Satus_Standby: '待機中',
  Mining_Satus_Ineligible: '非適格',
  mining_price_range: 'マイニング価格範囲',
  rewards_tips_stable:
    '戦略作成時にマイニング注文額の条件を満たしたグリッド注文は、マイニング価格範囲内（最高買い価格～最低売り価格）に収まればマイニング報酬を受け取れます。',
  rewards_tips:
    '戦略作成時にマイニング注文額の条件を満たしたグリッド注文は、マイニング価格範囲内（最高買い価格 * 0.99～最低売り価格 * 1.01）に収まればマイニング報酬を受け取れます。',
  wrap: 'ラップ',
  Wrap: 'ラップ',
  websites_for_more_information: '詳細情報のウェブサイト:',
  official_site: '公式サイト',
  wrap_site: 'ラップ/アンラップサイト',
  tips_third_party_site:
    'DeGateを離れ、サードパーティサイトにアクセスしようとしています:',
  wrap_unwrap: 'ラップ/アンラップ',
  Receive: '受け取る',
  Network: 'ネットワーク',
  Token_Contract: 'トークンコントラクト',
  Contract: 'コントラクト',
  please_select_network: 'ネットワークを選択してください',
  maximum_amount: '最大金額',
  send_USDC_to_this_address: 'このアドレスにUSDCを送金してください',
  arpa_airdrop: '$ARPAエアドロップ',
  Failed_to_proceed: '処理に失敗しました。',
  Please_select_the_Ethereum_network:
    'Ethereumネットワークを選択してください。',
  NATIVE_USDC_ONLY: 'ネイティブUSDCトークンのみ',
  NEVER_send_bridged_USDC: 'ブリッジされたUSDCを送らないでください',
  I_understand: '理解しました',
  recipient_address: '受取人アドレス',
  chain_0: 'DeGate L2',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum One',
  chain_421614: 'Arbitrum One',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    'このアクションを含むロールアップトランザクションはまだEthereum上に投稿されていません。それまでは、DGSCANはこのアクションを<b>表示しません</b>。',
  Best_Liquidity: '最高流動性',
  order_partially_filled: '注文が一部のみ約定',
  order_partially_filled_for_liquidity:
    'オーダーブックの流動性が突然低下したため、残りの注文がキャンセルされました。この保護措置により、不利な価格での約定が防止されます。',
  'orders.export_data_2_year': '過去2年間のデータをエクスポート',
  Community: 'コミュニティ',
  complete_in_seconds: '数秒で完了',
  failed_to_send: '送信に失敗しました。再度お試しください。',
  failed_to_send_try_other_networks:
    '送信に失敗しました。他のネットワークを試してください。',
  gas_fee_deducted: 'ガス料金控除済み:',
  sum_XXX: '合計 XXX',
  chart_control_7d: '7日',
  chart_control_30d: '30日',
  chart_control_all: 'すべて',
  chart_control_day: '日',
  chart_control_week: '週',
  chart_control_month: '月',
  Coming: '近日公開',
  leave_survey_title: 'こんにちは、DeGateを離れようとしているようです',
  leave_survey_subtitle:
    'あなたのフィードバックで私たちを改善する手助けをしてください。該当する項目をすべて選択してください。',
  leave_survey_not_leaving:
    '私は離れていません。すぐに戻ってきますよ、バカな！',
  leave_survey_other_is_fine:
    'Binance/OKX/Krakenなどが私には問題なく動作しています。',
  leave_survey_bad_experience: '取引の体験が好きではありません。',
  leave_survey_no_yield: '収益の機会を見つけられませんでした。',
  leave_survey_no_needed_token: '取引したいトークンが見つかりませんでした。',
  leave_survey_other_reason: 'その他（以下のボックスにご記入ください）',
  leave_survey_thanks_for_feedback: 'フィードバックありがとうございます。',
  Submitted: '提出済み',
  doc_title:
    'DeGate: 分散型オーダーブック取引所 | GRIDとDCAで無料の暗号通貨トレーディングボット',
  doc_desc:
    'DeGateは数百種類の暗号通貨を低手数料で取引できるトップの分散型オーダーブック取引所で、無料の指値注文取引、グリッド取引、DCAボットを提供しています。',
  doc_title_spot: '分散型オーダーブックDeGate DEX',
  doc_title_grid: '分散型グリッド取引ボットDeGate DEX',
  doc_title_dca: '分散型DCA取引ボットDeGate DEX',
  doc_title_swap: '',

  Notification: '通知',
  read_all: 'すべて読む',
  important: '重要',
  general: '一般',
  view_more: 'その他',
  thats_all: '今のところこれで以上です',
  XXX_fund_addition_processing: 'XXX 資金追加処理中',
  add_AMOUNT_XXX_to_DeGate: 'AMOUNT XXX を DeGate に追加',
  XXX_fund_addition_successful: 'XXX 資金追加が成功しました',
  XXX_send_successful: 'XXX の送信が成功しました',
  send_AMOUNT_XXX_to_DeGate: 'AMOUNT XXX を Ethereum に送信',
  send_AMOUNT_XXX_to_Ethereum: 'AMOUNT XXX を Ethereum に送信',
  you_have_received_a_new_airdrop: '新しいエアドロップを受け取りました！',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD:
    'AMOUNT XXX は YYYY-MM-DD 以降に請求可能です',
  MARKET_Chart: '市場チャート',
  grid_free: 'グリッド戦略の取引は<b>無料</b>です',
  maker_free_tips: 'メイカーの取引は<b>無料</b>です',
  Audit: '監査',
  Tool: 'ツール',
  About: '概要',

  // 1.16
  list_token_tips:
    'トークンをDeGateにリストするためにコントラクトアドレスを入力してください',
  login_to_view: 'ログインして表示',
  login_to_view_balance: 'ログインして残高を表示',
  login_to_view_history: 'ログインして履歴を表示',
  login_to_view_security_options:
    'セキュリティオプションを表示するにはログインしてください',
  i_accept: '同意する',
  degate_terms_of_service: 'DeGateの利用規約',
  privy_terms_of_service: 'Privyの利用規約',
  agree: '同意する',
  about_asset_key: 'アセットキーについて',
  explantion_asset_key_privy: `アセットキーは、最初のメールログイン時にユーザーのアドレスに紐付けられて生成されます。DeGateプロトコルは、このアセットキーを使用して取引を認証します。<h4>アセットキーのリセット</h4>ユーザーは任意でアセットキーをリセットできます。リセットの過程では以下が行われます：すべてのオープンオーダーおよびグリッド戦略がキャンセルされます。取引、送信、内部転送などのすべての操作が中断されます。リセットは、次回のzk-rollupがEthereumネットワーク上で完了した時点で完了します。<h4>アセットキーの表示</h4>DeGate SDKのユーザーは、SDKにアセットキーをインポートすることでdegate.comを使用せずにDeGateにアクセスすることができます。アセットキーのセキュリティを確保することが重要であり、決して他人と共有してはいけません。`,
  privy_account_balance_tips:
    '現在、DeGateをメールログインで使用していますが、これは少額取引向けです。',
  privy_account_balance_tips2:
    'セキュリティを強化するために、MetaMask、Ledger、imTokenなどの自己管理型ウォレットに切り替えることを強くお勧めします。',
  dont_show_again_for_30_days: '30日間このメッセージを表示しない',
  dont_show_again_for_60_days: '60日間このメッセージを表示しない',
  privy_feature_disabled_tips:
    'この機能はメールログインではサポートされていません。別のウォレット接続方法に切り替えてください。',
  Execution: '実行',
  Executed_Orders: '実行済み注文',
  Failed_Orders: '失敗した注文',
  Remaining_Orders: '残りの注文',
  avg_price: '平均価格',
  Campaigns: 'キャンペーン',
  all_Campaigns: 'すべてのキャンペーン',
  join_now: '今すぐ参加',
  pools: 'プール',
  you: 'あなた',
  per_day: '1日あたり',

  marketplace: 'マーケットプレイス',
  latest_grid_orders_filled: '最新のグリッド注文の約定',
  cumulative_grid_profit: '累積グリッド利益',
  total_fees_saved: '節約した総手数料',
  compared_to_CEX: 'CEXと比較',
  earn_XX_more_with_DeGate: 'DeGateでXX%多く稼ぐ',
  your_profit_with_CEX: 'CEXでの利益',
  total_fees_saved_with_DeGate: 'DeGateで節約した総手数料',
  earn_grid_profit_now: '今すぐグリッド利益を獲得',
  top_strategies: 'トップ戦略',
  ROI: 'ROI（投資収益率）',
  roi_desc: 'ROI = グリッド利益 ÷ 初期投資額',
  '24h_filled_orders': '24時間の約定注文数',

  // 1.17

  Swap: 'スワップ',
  liquidity: '流動性',
  market_cap: '時価総額',
  data_collected_from_DEX: 'DEXから収集したデータ',
  my_history: '履歴',
  pay: '支払い',
  receive: '受取',
  max_slippage: '最大スリッページ',
  minimum_receive: '最小受取額',
  minimum_TOKEN: '最小TOKEN',
  order_value_limit_reached: '注文価値上限に達しました',
  maximum_order_value_over_time_XXXX_USDC:
    '最大注文価値はXXXX USDCです。この上限は随時変動する可能性があります。',
  swap_order_placed: 'スワップ注文を配置しました',
  swap_order_filled: 'スワップ注文が約定しました',
  swap_order_failed: 'スワップ注文が失敗しました',
  swapping: 'スワップ中',
  available_network: '利用可能なネットワーク',

  minimum_receive_XXX_TOKEN: '最小受取額 XXX TOKEN',
  Website: 'ウェブサイト',
  Twitter: 'Twitter',
  Telegram: 'Telegram',
  status_filled: '約定',
  status_fail: '失敗',
  tips_DeGate_balance_1:
    'DeGate残高は、DeGate上でプライベートキーを使用して管理できる資産の総価値を表します。',
  tips_DeGate_balance_2:
    '資金をDeGate残高に追加すると、オーダーブックで即座に取引したり、同じネットワーク内の任意のアドレスに送金したりできます。',
  scan_SOLANA: 'Solscan',
  chain_SOLANA: 'Solana',

  swap_deposit_not_support_yet:
    'このトークンの追加はまだサポートされていません。今後有効になります。',
  insufficient_pool_liquidity: 'プールの流動性が不足しています',
  tips_DCAMinTips_limit_buy_XXX:
    '市場価格が$XXXを超えると注文が最小注文価値（$MIN USDC）を下回るため、実行に失敗する可能性があります。続行しますか？',
  tips_DCAMinTips_limit_sell_XXX:
    '市場価格が$XXXを下回ると注文が最小注文価値（$MIN USDC）を下回るため、実行に失敗する可能性があります。続行しますか？',
  no_live_mining_campaign: '現在、ライブマイニングキャンペーンはありません',
  minimum_quantity_per_grid_25: '最小グリッド数量：$25',
  minimum_investment: '最小投資額：',

  telegram_optional: 'Telegram ハンドル（任意）',
  feedback_tips:
    'フィードバックをお寄せください。返信をご希望の場合は、連絡先情報をご記入ください。',
  est_receive: '受信予定',
  swap_max_slippage_exceeded: '許容スリッページ上限を超えました',
  transaction_timeout: 'トランザクションがタイムアウトしました',
  please_increase_the_max_slippage_setting:
    '許容スリッページ設定を増やしてください',
  total_filled_orders: '合計成約注文数',
  message_limit_order_expired: '指値注文が期限切れとなりキャンセルされました',
  message_stop_limit_order_expired:
    '逆指値注文が期限切れとなりキャンセルされました',
  message_grid_expired: 'グリッド戦略が期限切れとなり終了しました',

  iframe_network_error_message:
    'ネットワーク問題によりチャートを表示できません',
  no_token_contract: 'トークンコントラクトなし',
  native_token_of_XXX_chain: 'XXXチェーンのネイティブトークン',
  N_found_in_Swap: 'スワップでNが見つかりました',
  N_found_in_Orderbook_Trade: 'オーダーブック取引でNが見つかりました',
  Show_all: 'すべて表示',
  sync_to_DeGate_app: 'DeGateアプリに同期',
  top_guns: 'トップトレーダー',
  moneybags: '資産家',
  strategy_value: '戦略価値',
  whales: 'クジラ（Whales）',
  hot_pairs: '注目ペア',
  apy_kings: 'APYキング',
  apy_king: 'APYキング（単数）',
  total_grid_capital: '総グリッド資本',
  including_grid_strategy_orders: 'グリッド戦略注文を含む',
  Grid_Strategy_Creation_Failed: 'グリッド戦略の作成に失敗しました',
  Grid_Strategy_Creation_Failed_1:
    'グリッド戦略の最初の買い注文が部分的に約定しましたが、オーダーブックの流動性が急落したため、残りはキャンセルされました。',
  Grid_Strategy_Creation_Failed_2:
    '詳細は「グリッド戦略の詳細」を確認してください。',
  grid_apy_estimate_tips:
    'APYの推定値は過去7日間のデータに基づいています<br/><br/>新しいグリッド戦略の価格範囲が、過去7日間の価格範囲を完全にカバーするか、または完全にカバーされている場合にのみ提供されます。\n<br/><br/>例えば、あなたの価格範囲が 5-10 の場合：\n<br/>過去の範囲が 6-9（完全にカバー）または 4-11（完全にカバーされる）なら推定可能\n過去の範囲が 8-12（部分的に重複）や 12-14（重複なし）の場合、推定は提供されません',
  auto_suggested_profit: '推奨グリッド利益：過去7日間のデータに基づいて計算',
  referral_code_optional: '紹介コード（オプション）',
  invalid_referral_code: '無効なコード',
  DeGate_Referral_Program: 'DeGate紹介プログラム',
  Referral_Program: '紹介プログラム',
  Referral_Program_Desc_V2:
    '認証パートナーとして参加し、ネットワークから継続的な手数料を獲得',
  Referral_Program_Desc_V2_text2: '透明性が高く、オンチェーンで長期的に構築',
  Referral_Program_Desc:
    'あなたの影響力を収益化し、緊密なエコシステムに参加しましょう。私たちは長期的な視点を大切にしています。私たちは心から願っています。あなたのコミュニティとDeGateが共に成長できることを。<br/> <br/>友達やフォロワーを招待し、手数料リベートを獲得することで、受動的な収入を得られます。取引量が多いほど、リベートも増加します！',
  Apply_Now: '今すぐ申し込む',
  Commission_Earned: '獲得済み手数料',
  Unclaimed_Commission: '未請求手数料',
  Invites: '招待数',
  Commission_Rate: '手数料率',
  referral_commission_rate_tips:
    '直接招待したユーザーからレベル1手数料、彼らが招待したユーザーからレベル2手数料を獲得できます。',
  Share_my_referral_link: '紹介リンクを共有',
  Claimable_Commission: '請求可能な手数料',
  Referral_Details: '紹介の詳細',
  Level: 'レベル',
  Level_1: 'レベル1',
  Level_2: 'レベル2',
  Type: 'タイプ',
  Activity: 'アクティビティ',
  Credited: '入金済み',
  referral_trading_fee: '取引手数料',
  referral_level_1_commission: 'レベル1手数料',
  referral_pending_commission_tips:
    'この金額は保留中であり、システムがUSDCに変換すると自動的に入金されます。',
  your_referral_link_is_expired: '紹介リンクの有効期限が切れています',
  claim_value: '価値',
  My_Invites: '招待履歴',
  Referee: '紹介者',
  Commission: '手数料',
  Transaction: 'トランザクション',
  Time_Joined: '参加日時',
  one_order: '1件の注文',
  N_Orders: 'N件の注文',
  Filled: '約定済み',
  out_of_range: '範囲外',

  show_chart: 'チャートを表示',
  please_enter_grid_parameters_first:
    'まずグリッドパラメータを入力してください',
  go_to_app_store: 'App Storeへ移動',
  go_to_google_play: 'Google Playへ移動',
  scan_to_download_app: 'スキャンしてアプリをダウンロード',
  get_DeGate_app_now: '今すぐDeGateアプリを入手！',
  install_beta_version: 'ベータ版をインストール',
  how_to_install_beta_version: 'ベータ版のインストール方法',
  download_testflight_from_app_store: 'App StoreからTestFlightをダウンロード',
  click_to_download_testflight: 'クリックしてTestFlightをダウンロード',
  come_back_for_next_step_after_testflight_is_installed:
    'TestFlightのインストール後、次のステップに進んでください。',
  download_DeGate_in_testflight: 'TestFlightでDeGateをダウンロード',
  click_to_download_DeGate: 'クリックしてDeGateをダウンロード',
  click_install: '「インストール」をクリック',
  low_liquidity: '警告：流動性が低い',
  low_liquidity_tips:
    '注文帳で低流動性が検出されました。潜在的な損失を避けるために確認してください。',
  min_receive_tips:
    '価格がさらに下落した場合、取引はキャンセルされます。以下が保証される最低受取額です。',
  est: '推定',
  hide_other_tokens: '他のトークンを非表示',
  share: '共有',
  more_trading_methods_here: 'ここで他の取引方法を確認',
  pool_liquidity: 'プールの流動性',
  '24h_pool_volume': '24時間プール取引量',
  mkt_cap: '時価総額',
  pool_info: 'プール情報',
  DEX: 'DEX',
  pool: 'プール',
  pool_address: 'プールアドレス',
  pool_created: 'プール作成日時',

  beta_test_tips:
    'この機能はベータテスト中です。テストに参加するにはお問い合わせください。',
  swap_success_receive_AMOUNT_TOKEN:
    'スワップ成功、AMOUNT_TOKENを受け取りました。',
  hide_balances_less_than_10: '$10未満の残高を非表示',
  Sender: '送信者',
  Recipient: '受信者',
  My_CHAIN_Address: '私のCHAINアドレス',
  CHAIN_Address: 'CHAINアドレス',
  From: '送信元',
  To: '送信先',
  send_status_help:
    '<b>処理中</b> <br />送信リクエストを処理しています。<br /><br /><b>成功</b> <br />資産が受信者のアドレスに送信されました。<br /><br /><b>確定</b><br /> 送信トランザクションを含むブロックが確定しました。',
  minimum_buy: '最低購入額',
  minimum_sell: '最低売却額',
  check_wallet_compatibility: '',
  wallet_incompatible: 'ウォレットの互換性を確認',
  wallet_incompatible_tips:
    '非標準のウォレット（例：MPCウォレット）を使用しています。DeGateは対応していません。標準ウォレットに切り替えてください。',
  initialization_desc_step3:
    '3回の署名リクエストが発生します。<br />署名は無料です。',

  records_are_unavailable_yet: '記録はまだ表示されていません',
  receive_history_tips:
    'アプリの「ホーム」タブでウォレットアドレスをコピーし、ブロックチェーンエクスプローラーで取引履歴をご確認ください',
  rate_limit_tips: 'リクエストが集中しています。時間をおいて再試行してください',
  Warning: '警告',
  Error_fetching_data: 'データの取得に失敗しました',
  Connection_Status: '接続状況',
  Market_Info: 'マーケット情報',
  Market_Info_tips:
    '例：価格、24時間変動率（％）、時価総額、流動性、取引量など',
  Last_updated: '最終更新',
  TIME_ago: '更新：○○前',
  Asset_Info: '資産の概要',
  Your_available_balance: '利用可能な残高',
  Disconnected: '接続が切断されました',
  Earn: '報酬を獲得',
  Portfolio: 'ポートフォリオ',
  My_Portfolio: 'あなたのポートフォリオ',
  My: 'マイページ',
  Total_Deposits: '合計預け入れ額',
  Claimable_Rewards: '受け取り可能な報酬',
  My_Deposit: 'あなたの預け入れ額',
  APY: '年利',
  Base_APY: '基本年利',
  Bonus_APY: '追加年利',
  native_Apy: 'チェーン独自の年利',
  Total_APY: '合計年利',
  performance_fee: 'パフォーマンス手数料',
  About_Vault: 'ボールトの概要',
  Protocol: 'プロトコル',
  Vault: 'ボールト',
  Asset: '資産',
  Chain_Details: 'チェーンの詳細情報',
  Deposit: '預け入れ',
  Withdraw: '引き出し',
  Est_Daily_Rewards: '予想される日次報酬',
  Accruing: '報酬が蓄積中',
  It_becomes_claimable_upon_maturity: '満期になると報酬を受け取れます',
  Tokens: 'トークン',
  Value: '現在の評価額',
  XXX_available_in: '利用可能：XXX',
  maximum_XXX: '上限額：$XXX',
  minimum_XXX: '最低：$XXX',
  earn_deposit_sol_balance_tips: '続行するには0.05 SOL以上が必要です',
  claim_rewards: '報酬を受け取る',
  Return: '戻る',
  usdc_supplied_from: 'USDCの提供元',
  multi_chain: 'マルチチェーン対応',
  multi_chain_tips:
    'マルチチェーントークンにより、複雑なブリッジ操作なしで複数チェーンにアクセス可能。ネットワーク手数料もカバーされます',
  multi_chain_balances: 'マルチチェーン残高',
  convert_to_multi_chain_usdc_tips:
    '「ブリッジ」で<b>マルチチェーンUSDC</b>に変換できます',
  Bridge: 'ブリッジ',
  multi_chain_usdc:
    '現在、マルチチェーンUSDCはSolanaおよびBaseネットワーク上のUSDCを指します',
  explantion_fees:
    '<h4>スワップ手数料率</h4><ul><li><a href="https://docs.degate.com/about-degate/swap">レート表</a>をご覧ください</li></ul> <br><h4>ネットワーク手数料</h4><ul><li>リアルタイムのオンチェーンコストに基づいて計算されます</li></ul>',
  search_history: '検索履歴',
  '24h_txns': '24時間の取引件数',
  Markets: 'マーケット',
  warning_excessive_balance_detected: '警告：残高が多すぎます',
  warning_excessive_balance_detected_tips1:
    '現在の DeGate アカウントは大量の資産を保管するように設計されていません。お客様の残高は推奨上限の XXX USD を超えています。',
  warning_excessive_balance_detected_tips2:
    'セキュリティ上の理由から、資産を減らすことを強くおすすめします',
  warning_excessive_balance_detected_tips2_app:
    '資産の保護のため、DeGateアプリをインストールし、アプリ内でウォレットを作成またはインポートしてください',
  download_app: 'アプリをダウンロード',
  receive_data_tips:
    '右上の「アドレスを表示」をタップし、それをブロックチェーンエクスプローラーに貼り付けて取引履歴を確認してください',
  verify_account: 'アカウントを認証する',
  est_network_fee: '推定ネットワーク手数料',
  arrival_time: '到着予定時間',
  gas_refund_tips:
    '返金はマルチチェーンUSDCまたはネイティブトークンのいずれかで行われる場合があります',
  network_fee: 'ネットワーク手数料',
  estimated_fee: '見積もり手数料',
  actual_fee: '実際の手数料',
  refund: '返金',
  Browser: 'ブラウザ',
  transaction_details: '取引詳細',
  smart_contract_interaction: 'スマートコントラクトの実行内容',
  interact_with: 'コントラクト操作',

  // 1.26

  Raffle: 'ラッフル',
  round_N: 'ラウンドN',
  pick_your_number: '番号を選んでください',
  win_1_million: '100万ドルを当てよう',
  participating: '参加中',
  become_a_millionaire_now: '今すぐ億万長者に',
  get_free_tickets: '無料チケットを獲得',
  verify_1_million_prize_fund: '100万ドルの賞金プールを検証',
  lucky_number: 'ラッキーナンバー',
  winning_bitcoin_block: '当選ビットコインブロック',
  block_hash: 'ブロックハッシュ',
  participated: '参加済み',
  ticket_redemption_phase_ends_in_XXX: 'チケット交換フェーズはXXXで終了',
  redemption: '交換',
  pending_draw: '抽選待ち',
  announcement: '発表',
  my_tickets_total: '自分のチケット / 合計',
  view_rules: 'ルールを見る',
  earn_up_to_200_thousand_dollars_bonus:
    '最大<b>20万ドルのボーナスを獲得！</b>',
  invite_friends_now: '<b>友達を招待</b>しよう！',
  prizes: '賞品',
  grand_prize: 'グランド賞',
  second_prize: '2等賞',
  third_prize: '3等賞',
  fourth_prize: '4等賞',
  fifth_prize: '5等賞',
  sixth_prize: '6等賞',
  seventh_prize: '7等賞',
  eighth_prize: '8等賞',
  draw_starts_once_the_bitcoin_block_is_confirmed:
    'ビットコインブロックが確定すると抽選が開始されます。',
  ticket_redemption_closed: 'チケット交換終了',
  congratulations: 'おめでとうございます！',
  you_ve_won: '当選しました',
  good_luck_for_next_round: '次のラウンドもがんばって！',
  you_weren_t_in_this_round: 'このラウンドには参加していません',
  join_the_next_round: '次のラウンドに参加しよう！',
  tickets_in_round_N: 'ラウンドNでのチケット',
  my_tickets: '自分のチケット',
  total_tickets: 'チケット総数',
  total_tickets_tips:
    'チケット交換フェーズが終了すると、チケット番号の暗号ハッシュをBaseチェーンに公開します。これにより、完全な透明性と改ざん防止が実現されます。',
  hash_of_total_tickets: 'チケット総数のハッシュ',
  hash_value_tips:
    'ハッシュ = SHA256(Ticket1,Ticket2,…,TicketN)。Ticket1からTicketNはこのラウンドで交換された全チケット（昇順）を表します。',
  verify_hash: 'ハッシュを検証',
  reviewing: '審査中',
  manual_review_in_progress_payout_will_follow_shortly:
    '手動審査中です。まもなく報酬が配布されます。',
  received: '受け取り済み',
  points: 'ポイント',
  no_prize_this_time: '今回は当選なし',
  all_winners: '全当選者',
  winning_ticket: '1枚の当選チケット',
  winning_tickets_N: 'N枚の当選チケット',
  Pick_your_ticket_number: '好きなチケット番号を選んでください',
  Manual: '手動',
  Range: '範囲指定',
  Random: 'ランダム',
  Feeling_lucky: '運試ししてみる？',
  Redeem: '交換する',
  Invalid_number: '無効な番号です',
  Ticket_already_taken:
    'この番号はすでに使用されています。別の番号を選んでください。',
  N_Ticket: 'N枚のチケット',
  N_Tickets: 'N枚のチケット',
  Points_needed: '必要ポイント',
  Points_available: '保有ポイント',
  Redemption_Successful: '交換成功',
  Ticket_Unavailable: 'チケットは使用不可',
  N_Ticket_Unavailable: 'N枚のチケットが使用不可',
  N_Tickets_Unavailable: 'N枚のチケットが使用不可',
  Looks_like_someone_just_grabbed_this_number:
    '誰かがこの番号を取ったようです。別の番号を選んでください。',
  Insufficient_Points: 'ポイント不足',
  You_have_0_point_and_cannot_redeem_tickets:
    'ポイントが0のためチケットを交換できません。',
  You_have_POINTS_points_and_can_redeem_a_maximum_of_TICKETS_tickets:
    'あなたはPOINTSポイントを保有しており、最大でTICKETS枚のチケットを交換可能です。',
  How_to_acquire_points: 'ポイントの獲得方法',
  Number_Start: '開始',
  Number_End: '終了',
  Please_enter_the_start_number_and_end_number:
    '開始番号と終了番号を入力してください',
  End_number_must_be_greater_than_start_number:
    '終了番号は開始番号より大きくなければなりません',
  Those_tickets_have_already_been_taken:
    'これらのチケットはすでに使用されています。',
  Looks_like_someone_just_grabbed_some_of_the_tickets:
    '誰かが一部のチケットを取得したようです。もう一度お試しください。',
  Number_of_tickets: 'チケット枚数',
  Generate: '生成する',
  Please_enter_the_number_of_tickets: 'チケット枚数を入力してください',
  N_random_tickets: 'N枚のランダムチケット',
  N_random_ticket: 'N枚のランダムチケット',
  Generate_Again: '再生成',
  Dashboard: 'ダッシュボード',
  My_Points: '自分のポイント',
  My_Participations: '自分の参加状況',
  N_rounds: 'Nラウンド',
  N_round: 'Nラウンド目',
  My_Winnings: '自分の当選履歴',
  Invite_Friends_and_Earn_20_Extra_on_Their_USDC_Winnings:
    '友達を招待して、彼らのUSDC当選額の<b>20％</b>を獲得',
  They_win_more_you_earn_more_and_there_is_no_cap:
    '彼らが勝てば勝つほど、あなたの報酬も増加。上限なし。',
  Invite_your_friends_to_DeGate:
    'DeGateに友達を招待しよう。彼らがラッフルでUSDCを当てるたび、あなたに20％が還元されます。',
  My_Referral_Link: '自分の紹介リンク',
  Copy_Link: 'リンクをコピー',
  Total_Invited: '招待人数',
  Total_Rewards: '自分の報酬',
  Points: 'ポイント',
  Tickets: 'チケット',
  Winnings: '当選額',
  Points_can_be_earned_by_using_the_DeGate_Swap_feature:
    'DeGateのスワップ機能でポイントを獲得できます。',
  Go_to_Swap: 'スワップへ移動',
  Winning: '当選',
  Redeem_tickets: 'チケット交換',
  Gift: 'ギフト',
  Rewards: '報酬',
  Invite_Rewards: '招待報酬',
  How_to_Join: '参加方法',
  Step_N: 'ステップN',
  Earn_points_by_swapping_on_DeGate: 'DeGateでスワップしてポイントを獲得',
  Use_your_points_to_redeem_raffle_tickets_during_the_redemption_phase:
    '獲得したポイントで、交換フェーズ中にラッフルチケットと交換',
  Check_the_results_after_the_round_ends_your_lucky_moment_might_be_waiting:
    'ラウンド終了後に結果を確認。ラッキーな瞬間が待っているかも！',
  Digits_Matched: '一致した桁数',
  All_Match: '全8桁一致',
  Matches_Last_N: '下N桁一致',
  Winner: '当選者',
  Prize: '賞品',
  FAQ: 'FAQ',
  Rules: 'ルール',
  How_does_it_Work: '仕組みについて',
  how_to_participate: '参加方法は？',
  N_Point: '+Nポイント',
  N_Points: '+Nポイント',
  You_just_earned_points_from_your_swap: 'スワップでポイントを獲得しました',
  Use_them_to_redeem_raffle_tickets_to_win_1_million_dollars:
    'ポイントを使ってラッフルチケットを交換しよう<br/><b>100万ドルを当てよう！</b>',
  Join_Raffle: 'ラッフルに参加する',
  please_enter_amount: '金額を入力してください',
  claim_prizes: '賞品を受け取る',
  claim_your_prizes: '当選した賞品を受け取る',
  all_unclaimed_usdc_will_be_sent_to_your_base_address_shortly:
    '未請求のUSDCはすぐにBaseアドレスに送金されます',
  Claim_your_invite_rewards: '招待報酬を受け取る',
  Claim_Invite_Rewards: '招待報酬を受け取る',
  amount_needed: '必要な金額',
  // 1.27
  download_apk: 'APKをダウンロード',
  download_app_get: 'GET',
  download_page_app_store: 'App Store',
  download_page_google_play: 'Google Play',
  download_page_apk: 'APK',
  download_page_scan_to_download: 'スキャンしてダウンロード',
  download_page_partners: 'パートナー',
  Matches_for_8th_Prize: '下1桁または下1桁±1',
  Select_Network: 'ネットワークを選択',
  All_Networks: 'すべてのネットワーク',
  Filtering_with_CHAIN_network: 'CHAINネットワークでフィルタリング中',
  Claim_History: '受取履歴',
  My_Dashboard: 'マイダッシュボード',
  Claim_Winnings: '当選金を受け取る',
  team_up_to_boost_your_odds_of_winning_1_million_usdc:
    'チームを組んで <div>WINNING 1,000,000 USDC!</div> の確率を高めよう',
  Create_a_Team_Now: '今すぐチームを作成',
  Leader: 'リーダー',
  Leader_Bonus: 'リーダーボーナス',
  Leader_Bonus_tips: 'チームが当選すると追加で10%のUSDCを獲得！',
  Team_Tickets: 'チームチケット',
  Create_Team: 'チームを作成',
  Enter_Team_Name: 'チーム名を入力',
  Please_enter_a_team_name: 'チーム名を入力してください',
  Name_already_taken_try_different_one:
    'その名前は既に使用されています。別の名前をお試しください。',
  Team_created: 'チームが作成されました',
  Invite: '招待',
  Invite_Team_Members: 'チームメンバーを招待',
  Team_Details: 'チーム詳細',
  Team_Points: 'チームポイント',
  Pool_My_Points: '自分のポイントをプール',
  Rewards_are_split_by_points_contributed:
    '報酬は寄与したポイント数に応じて分配されます。',
  pool_points_tips:
    '自分のポイントをチームプールに移します。報酬は各メンバーの貢献度に比例して配布されます。',
  Please_enter_a_number_that_is_a_multiple_of_10: '10の倍数を入力してください',
  Insufficient_points: 'ポイントが不足しています',
  Added_POINTS_points_to_TEAM: 'TEAM に POINTS ポイントを追加しました',
  Join_the_team_to_boost_your_odds_of_winning_1_million_usdc:
    'チームに参加して<br/> <b>WINNING <br/> 1,000,000 USDC!</b> の確率を高めよう',
  Congratulations_You_ve_joined_the_team:
    'おめでとうございます！チームに参加しました。',
  You_re_already_in_this_team: 'すでにこのチームに参加しています',
  Solo: 'ソロ',
  Team: 'チーム',
  Select_Team: 'チームを選択',
  My_Teams: 'マイチーム',
  team_tickets_total: 'チームチケット / 合計',
  how_it_works: '仕組み',
  how_to_play_as_a_team: 'チームで遊ぶ方法',
  invite_tips1:
    '彼らが抽選でUSDCを当てるたびに、あなたは追加で20%を獲得します。',
  invite_tips2:
    '彼らがスワップでポイントを獲得するたびに、あなたはそのポイントの20%を追加で得られます。',
  distribution: '分配',
  new_rule_1_1:
    '<b>1.ポイントを獲得</b><br/> <b>スワップで獲得</b><br/> DeGateでスワップするたびに自動でポイントが貯まります。',
  new_rule_2_1:
    '<b>2.勝つ方法</b><br/> <b>チケットを交換</b><br/> 交換フェーズ中に10ポイントで1枚のチケットと引き換えます。',
  new_rule_2_2:
    '<b>番号を選ぶ</b><br/>各チケットには固有の8桁番号（00000000–99999999）が割り振られます。自分で選ぶか、システムにランダムで選ばせることもできます。',
  new_rule_2_3:
    '<b>ラッキーナンバーを合わせる</b><br/>あなたのチケットをラウンドのラッキーナンバーと比較します。末尾から一致する桁数が多いほど賞金が大きくなります。',
  new_rule_2_4: '例えば、ラッキーナンバーが<b>12345678</b>の場合：',
  match_pattern: 'マッチパターン',
  winning_tickets: '当選チケット',
  represents_any_digit: '✱ は任意の数字を表します。',
  new_rule_3: '<b>3.証明可能な公正性</b>',
  new_rule_3_1:
    '<b>ブロックチェーンによるランダム性</b><br/>ラッキーナンバーは実際のビットコインブロック（交換終了後6番目のブロック）に基づいており、予測や変更はできません。',
  new_rule_3_2:
    '<b>オープンソースのアルゴリズム</b><br/>当選ビットコインブロックのハッシュをオープンソースコードでラッキーナンバーに変換しています — GitHubで確認・検証できます。',
  new_rule_3_3:
    '<b>賞金ファンドの証明</b><br/>1.2M USDC超が事前にプールされ、以下のウォレットアドレスで検証可能です: <a href="https://basescan.org/address/0xdB5c7E18FB657F6a8f193024D7F0Aa251Df8C7d6" target="_blank">0xdB5...8C7d6</a> と <a href="https://basescan.org/address/0x1c7F26c156caEA62Ad11F6a634051Df43129A656" target="_blank">0x1c7...9A656</a>',
  team_rule_1:
    '<b>1.チームに参加または作成</b><br/>チームを組んで1,000,000 USDCのグランドプライズ当選確率を高めよう。',
  team_rule_2:
    '<b>2.ポイントをプール</b><br/>各ラウンドでポイントをチームプールに追加。',
  team_rule_3:
    '<b>3.一緒に交換</b><br/>どのメンバーでもチームポイントを使ってチームのチケットを取得できます。',
  team_rule_4:
    '<b>4.無駄なし</b><br/>残ったチームポイントはラウンド終了時に自動でランダムチケットに変換されます。',
  team_rule_5:
    '<b>5.公平な分配</b><br/>チームが当選した場合、報酬は各メンバーのポイント寄与度に応じて分配されます。',
  prize: '賞金',
  all_8_digits: '8桁すべて一致',
  last_N_digits: '末尾N桁一致',
  no_luck: '当選なし',
  Team_Points_Breakdown: 'チームポイント内訳',
  member: 'メンバー',
  Points_Contributed: '寄与ポイント',
  you_didnt_win_this_round_better_luck_next_time:
    '今回は当たりませんでした — 次回に期待しましょう！',
  Rewards_Received: '受け取った報酬',
  Points_can_be_earned_by_using_the_DeGate_Swap:
    'ポイントは DeGate Swap の利用で獲得できます。',
  Add_to_Team: 'Team に追加',
  Team_Refund: 'Team から返金',
  Receive_from_Team: 'Team から受け取る',
  from_invitee_winnings: '招待者の当選から',
  from_invitee_points: '招待者のスワップから',
  draw_starts_once_the_winning_bitcoin_block_is_fully_confirmed:
    '当選ビットコインブロックが完全に確定すると抽選が開始されます。',
  Invite_Friends_and_Earn_20_Extra: '友達を招待して <b>20% 追加</b> を獲得',
  Team_Points_Available: '保有チームポイント',
  me: '私',
  Stocks: '株式',

  // 1.28
  est_account_rent_CHAIN_NUM: '$NUM（CHAIN のレンタル料）',
  est_transaction_cost_NUM: '$NUM（取引コスト）',
  filter_by_network: 'ネットワークで絞り込み',
  manage_tokens_title: 'トークン管理',
  manage_tokens_short: '管理',
  manage_menu_status_on: 'オン',
  manage_menu_status_off: 'オフ',
  manage_tokens_my_assets: 'マイアセット',
  manage_tokens_other_assets: 'その他のアセット',
  manage_tokens_add_btn: 'トークンを追加',
  manage_tokens_contract_address: 'コントラクトアドレス',
  manage_tokens_contract_address_placeholder: 'コントラクトアドレスを入力',
  manage_tokens_symbol: 'シンボル',
  manage_tokens_decimal: '小数点以下桁数',
  manage_tokens_not_found:
    'トークンが見つかりません。コントラクトアドレスとネットワークを確認してください。',
  manage_tokens_added: '{TOKEN}はすでにトークンリストに含まれています。',
  manage_tokens_remove_confirm_title: 'トークンを削除',
  manage_tokens_remove_confirm_desc:
    '{TOKEN}をトークンリストから削除しますか？',
  manage_tokens_remove_confirm_btn: '削除',
  Mainnet: 'メインネット',
  Testnet: 'テストネット',
  More_Services: 'その他のサービス',
  current_block: '現在のブロック',
  fully_confirmed: '完全に承認済み',
  create_account: 'アカウントを作成',
  create_account_tips:
    '初めてご利用の方はアカウントを作成してください。所要時間は約<b>30秒</b>です。',
  account_created: 'アカウントを作成しました',
  please_create_account_first: 'まずアカウントを作成してください',
  unable_to_create_account: 'アカウントを作成できません',
  this_asset_is_self_custodied_in_your_CHAIN_address:
    'この資産は自己保管で、あなたの <b>CHAIN アドレスにあります</b>',
  generate_wallet_address: 'DeGate はこれらの新しいチェーンに対応しました。',
  generate_wallet_address_tips:
    '「確認」をクリックしてウォレットアドレスを作成してください。',
  updating: '更新中',
  please_wait: 'お待ちください',
  close_this_window_to_resume_what_you_were_doing:
    'このウィンドウを閉じると作業を再開できます',
  Funds: '資金',
  Route: '経路',
  Meme: 'Meme',
  free_team_tickets: '無料のチームチケット',
  free_team_tickets_tips: 'マイルストーン達成でチームチケットが<b>2倍</b>',
  if_the_target_isn_t_met_this_round_progress_resets:
    '今ラウンドで目標を達成できない場合、進捗はリセットされます',
  n_tickets_to_claim: '受け取り可能なチケット N 枚',
  claim_bonus: 'ボーナスを受け取る',
  any_unclaimed_tickets_will_be_automatically_claimed_when_the_redemption_phase_ends:
    '引き換え期間が終了すると、未受け取りのチケットは自動で受け取られます。',
  n_tickets_claimed: 'N 枚のチケットを受け取りました',
  n_tickets_to_claim_m_claimed: '受け取り可能：N 枚（受け取り済み：M 枚）',
  all_n_tickets_claimed: 'N 枚すべてのチケットを受け取り済み',
  generate_N_tickets: 'チケットを N 枚生成',
  TRY_YOUR_LUCK_NOW: '今すぐ運試し',
  ENTER_WIN_BIG: '参加して大きく当てよう！',
  FEELING_LUCKY: '運は味方してる？',
  HIT_THAT_000000: '000000 を当てよう！',
  Enter: '参加する',
  N_Points_for_1_Entry: 'N ポイントで 1 回参加',
  awaiting: '待機中…',
  numbers_incoming: '番号がまもなく表示されます…',
  HOLD_TIGHT_GOOD_LUCK: 'そのままお待ちを—幸運を！',
  Entry: 'エントリー',
  Refund: '返金',
  how_to_earn_points: 'ポイントの獲得方法は？',
  how_to_earn_points_tips:
    'DeGateでスワップしたりMemeゲームに参加してポイントを獲得しましょう。',
  Go_to_meme: 'Meme へ移動',
  Verify: '認証',
  Winning_Block: '当選ブロック',
  Entry_Time: 'エントリー時間',
  Points_History: 'ポイント履歴',
  Raffle_History: '抽選履歴',
  Verify_Raffle_Results: '抽選結果を検証',
  Fair_play_proof_in_3_steps: '3ステップのフェアプレー証明',
  Proof_of_fair_play_in_3_steps: '公平性の証明（3ステップ）',
  verify_tips_1: '1. 「Secret」のフィンガープリントを公開',
  verify_tips_1_1:
    '抽選開始前に、Secret のハッシュ（その「指紋」）を公開します——このハッシュが変わらない限り Secret を差し替えることはできません。',
  verify_tips_2: '2. 次のブロックで決定',
  verify_tips_2_1:
    'Enter を押すと、Secret と次の Base ブロックから 6 桁のラッキーナンバーが生成されます。',
  verify_tips_3: '3. 公開して検証',
  verify_tips_3_1:
    '抽選記録を開き、「公開」と「検証」をタップ。ハッシュを事前公開のフィンガープリントと照合し、計算を再実行します—同じ番号なら不正なし。',
  verify_tips_4:
    'Secret を公開すると、次のエントリー用に新しいものが封印されます。',
  hash_of_secret: 'Secret のハッシュ',
  secret: 'Secret',
  winning_block: '当選ブロック',
  keccak256: 'keccak256(Secret, Block hash) % 1000000',
  hash_of_secret_for_next_entry: '次回エントリー用の Secret のハッシュ',
  proof: '証拠',
  entry_time: 'エントリー時間',
  not_revealed: '未公開',
  the_secret_is_a_system_generated_input_used_to_compute_the_lucky_number:
    'Secret はラッキーナンバーを計算するためのシステム生成の入力です。公正性を確保するため、DeGate はそのハッシュを事前に公開してコミットし、後から変更できないようにします。',
  the_next_block_on_base_chain_after_you_click_enter:
    'Enter を押した後の Base チェーンの次のブロック。',
  reveal_and_verify: '公開して検証',
  download_tickets: 'チケットをダウンロード',
  Total_Winnings: '総当選額',
  time_limited: '期間限定',
  Exclusive_Friend_Rewards: '友だち限定特典',
  Register_an_account_You_and_your_friend_get_10_FREE_entries_each:
    'アカウント登録 - <br/><b>あなたと友だちにそれぞれ無料エントリー 10 回</b>',
  Get_Rewards: '特典を受け取る',
  You_re_eligible_for_10_FREE_Entries:
    'あなたは<b>無料エントリー 10 回</b>の対象です',
  Expires_in_XXX: 'XXX 後に失効',
  Invite_a_friend_to_join_DeGate: '友だちを DeGate に招待する',
  invite_text_1:
    'DeGate の招待が来たよ—お互いに無料抽選エントリーが10回（最⼤ $5K）。期間限定だから、すぐ共有するね。',
  you_received: '受け取り済み',
  free_entries_10: '無料エントリー 10 回',
  Free_Entries_times_N: '無料エントリー：N',
  EXPIRED: '期限切れ',
  flash_op_create_account_tips:
    'アカウント作成 - あなたと友だちにそれぞれ無料エントリー10回',
  offer_is_expired: 'このオファーは期限切れです',
  offer_is_limited_to_new_users_only: '本オファーは新規ユーザー限定です',
  get_rewards_now: '今すぐ特典を受け取る',
  Later: '後で',
  so_close_try_again: '惜しい！もう一度挑戦しますか？',
  no_luck_try_again: '残念。もう一度試しますか？',
  no_route_fund:
    'ルートが見つかりません—金額を変えるか、後でもう一度お試しください。',
  trading_restriction_notice: '取引制限のお知らせ',
  trading_restriction_notice_tips:
    '<a href="https://assets.backed.fi/legal-documentation/restricted-countries" target="_blank">Backed</a> の制限対象国リストに基づき、お住まいの地域ではこのオンチェーン株式トークンを取引できません：',
  trading_restriction_notice_tips_2:
    'この制限は Backed が発行する一部のトークンにのみ適用されます。その他のトークンは引き続き取引できます。',
  btn_got_id: 'わかりました',
  Invalid_SOL_rent: 'レント用の SOL が不足しています',

  stocks: {
    Hot_Stocks: '注目銘柄',
    Last: '最終価格',
    Chg: '変動',
    Chg_Percent: '変動率',
    Stock_Heatmap: '株式ヒートマップ',
    Stock_Heatmap_AUM: '株式ヒートマップ（AUM）',
    Holders_per_Stock: '銘柄別ホルダー数',
    Holders_per_Stock_top_20: '銘柄別ホルダー数（Top 20）',
    Trades_per_Stock: '銘柄別取引件数',
    Trading_volume_DEX_per_Stock: '銘柄別 DEX 取引高',
    Trading_vol: '取引高',
    Daily_Trading_Accounts_per_Stock: '銘柄ごとの日次取引口座数',
    Token_Holders_AUM: 'トークン保有者数＆AUM',
    Issuer: '発行体',
    Onchain_AUM: 'オンチェーン AUM',
    Valuation: '評価額',
    Dex_Trading_Vol: '24時間 DEX 取引高',
    Onchain_Supply: 'オンチェーン供給量',
    Onchain_Holders: 'オンチェーン保有者数',
    Audit_URL: '監査URL',
    Dex_Liquidity: 'DEX 流動性',
    Websites: 'ウェブサイト',
    News_Flow: 'ニュースフロー',
    Trading_Vol_Dex_Liquidity: '取引高＆DEX 流動性',
    AUM_desc:
      'AUM（運用資産残高）は、発行者である Backed Fi がオンチェーンで発行した当該株式の USD 建て総価値を表します。',
    Onchain_Opportunity: 'オンチェーン機会',
    '24h APY': '24h APY（年率換算）',
    stocks_doc_title: 'オンチェーン株式ダッシュボード｜利回りインサイト＆戦略',
    total_aum: 'AUM 合計',
    total_unique_holders: 'ユニーク保有者総数',
    total_dex_volume: 'DEX 総取引高',
    total_tvl: 'オンチェーンプールの流動性',
    total_assets: 'xStock資産数',
    Trade_with_ZERO_FEES: '手数料ゼロで取引',
    Legal_Info: '法的情報',
  },
  swap_error: {
    Swap_failed_return_below_minimum_receive:
      'スワップ失敗：返戻額が最小受取額を下回りました。',
    Insufficient_liquidity_for_this_token_reduce_amount_and_try_again_later:
      'このトークンの流動性が不足しています。金額を減らして後でもう一度お試しください。',
    Swap_failed_price_impact_exceeds_limit:
      'スワップ失敗：価格インパクトが上限を超えました。',
    Swap_failed_honeypot_or_high_risk_token_detected:
      'スワップ失敗：ハニーポットまたは高リスクトークンを検出しました。',
    Swap_failed_insufficient_sol_for_rent:
      'スワップ失敗：レント用の SOL が不足しています。少額の SOL を入金して再試行してください。',
    Return_below_minimum_receive: '返戻額が最小受取額を下回っています',
    Insufficient_liquidity_for_this_token:
      'このトークンの流動性が不足しています',
    Price_impact_exceeds_limit: '価格インパクトが上限を超えています',
    Honeypot_or_high_risk_token_detected:
      'ハニーポットまたは高リスクトークンを検出しました。',
    Insufficient_sol_for_rent: 'レント用の SOL が不足しています',
    Swap_failed_insufficient_funds_for_gas:
      'スワップ失敗：ガス代の資金が不足しています。',
    Insufficient_funds_for_gas: 'ガス代の資金が不足しています',
    Estimated_network_fee_is_less_than_the_actual_amount_required:
      '見積りのネットワーク手数料が実際に必要な額を下回っています。',
  },
  gift: {
    Gift_Box: 'ギフトボックス',
    View_Gift_Box: 'ギフトボックスを見る',
    Download_App: 'アプリをダウンロード',
    Your_gift_awaits: 'あなたのギフトが準備できました',
    Open_Now: '今すぐ開く',
    Cash_Gift_for_CopyTrade: '自動コピートレード用現金ギフト',
    Receive_gift_in_DeGate_App: 'DeGateアプリでギフトを受け取る',
    This_gift_box_was_claimed_by_a_different_account_you_previously_used:
      'このギフトボックスは以前使用した別のアカウントで受け取られています',
    Youve_received_a_Cash_Gift_for_CopyTrade: '{GIFT TYPE} を受け取りました',
    has_been_sent_to_your_CopyTrade_account:
      '自動コピートレードアカウントへ送信されました',
    View_My_Account: 'マイアカウントを見る',
    claim_your_gift_please_create_a_DeGate_account:
      'ギフトを受け取るには、まずDeGateアカウントを作成してください',
    Total_Gift_Amount: 'ギフト総額',
    Expired_at_DATE: 'DATE に有効期限切れ',
    Gifts_claimed_CLAIMED_TOTAL: 'ギフト（CLAIMED/TOTAL 受け取り済み）',
    Today: '今日',
    Youve_received_your_gift_cash_Outgoing_transfers_will_be_enabled_after_your_Copy_Trade_bot_completes_its_first_trade:
      '現金ギフトを受け取りました。自動コピートレードボットが最初の取引を完了すると出金が可能になります。SourcesAsk ChatGPT',
    Others_were_faster_Try_again_next_time:
      '他の人に先を越されました。次回お試しください！',
    Connect_wallet_to_claim: '受け取るにはウォレットを接続してください',
    Expired_in_DATE: 'DATE に期限切れ',
  },
  turboRange: {
    Turbo_Range: 'Turbo Range',
    my_positions: 'マイポジション',
    my_turbo_range: 'マイターボレンジ',
    yesterday_yield: '昨日の収益',
    total_yield: '総収益',
    Details: '詳細',
    all_products: 'すべての商品',
    invert_USDC: 'USDCを投資する',
    apy_7D: '7日間APY',
    you_have_no_position: '保有ポジションがありません',
    invest: '投資する',
    create_position: 'ポジションを作成',
    price_range: '価格レンジ',
    earn_yield_while_TSLA_price_stays_in_your_range:
      '{TSLA}の価格があなたの設定したレンジ内にある間、利回りを獲得',
    earn_yield_while_price_stays_in_your_range:
      '価格が範囲内にある間に収益を得る',
    est_apy: '推定APY',
    estimated_annual_percentage_yield_based_on_last_7_days_data:
      '推定年利回り。直近7日間のデータに基づく。',
    est_annual_yield: '推定年間利回り',
    enter_amount_to_continue: '続行するには金額を入力してください',
    set_price_range: '価格レンジを設定',
    current_price: '現在価格',
    current: '現在',
    min_price: '最低価格',
    max_price: '最高価格',
    please_enter_an_amount: '金額を入力してください',
    maximum_500000: '最大 500000',
    adjust_the_input_to_proceed: '続行するには入力を調整してください',
    please_reduce_amount: '金額を減らしてください',
    not_enough_balance_to_proceed: '残高が不足して続行できません',
    processing_deposit_to_liquidity_pool: '流動性プールに入金処理中',
    you_can_close_this_window_we_ll_handle_it:
      'このウィンドウは閉じても構いません。あとは私たちが対応します。',
    investment_successful: '投資に成功しました',
    invested: '投資額',
    returned: '返還済み',
    view_my_position: '自分のポジションを見る',
    investment_failed: '投資に失敗しました',
    about_turbo_range: 'Turbo Range について',
    turbo_range_puts_your_funds_into_a_liquidity_pool_within_the_price_range_you_set_when_others_trade_in_that_range_you_earn_fees:
      '<b>Turbo Range</b> は、あなたが設定した価格レンジ内の流動性プールに資金を投入します。他の人がその範囲内で取引すると、手数料を獲得できます。',
    example: '例',
    let_s_say_you_invest_1000_USDC_in_the_TSLA_USDC_pool_and_set_a_range_of_270_330_TSLA_s_current_price_is_300:
      '例えば、1000 USDC を TSLA/USDC プールに投入し、270〜330 のレンジを設定するとします（TSLA の現在価格を 300 と仮定）。',
    step1: '1. 約 476 USDC を計算して約 1.59 TSLA を購入します。',
    step2: '2. 結果として、約 524 USDC と約 1.59 TSLA を保有します。',
    step3: '3. これらの資産は設定したレンジ内のプールに追加されます。',
    what_happens_in_different_price_scenarios: '価格の変動によってどうなる？',
    desc_1: '1. 価格が 270〜330 の間に留まる場合',
    desc_1_1: '取引手数料を稼ぎ続けます。',
    desc_2: '2. 価格が 270 を下回る場合',
    desc_2_1:
      'ポジションは約 3.43 TSLA と獲得済み手数料になります。価格の回復を信じるなら、そのまま保有できます。',
    desc_3: '3. 価格が 330 を上回る場合',
    desc_3_1:
      'ポジションは約 1023 USDC と獲得済み手数料になります。約 23 USDC の利益に加え、手数料も得ます。',
    underlying_on_chain_assets: '基盤オンチェーン資産',
    principal: '元本',
    unclaimed_yield: '未受取の利回り',
    in_range: 'レンジ内',
    out_of_range: 'レンジ外',
    total_pnl: '合計損益（P&L）',
    underlying_assets: '基盤資産',
    initial_principal: '初期元本',
    closed_principal: 'クローズ時の元本',
    principal_pnl: '元本の損益（P&L）',
    created_at: '作成日時',
    closed_at: '終了日時',
    claim_yield: '収益を受け取る',
    all_TSLA_will_be_converted_to_USDC: 'すべての{TSLA}は{USDC}に変換されます',
    est_receive: '受取見込み',
    claim_successful: '受け取りに成功しました',
    has_been_added_to_your_account: 'があなたのアカウントに追加されました',
    claim_failed: '受け取りに失敗しました',
    convert_TSLA_to_USDC_and_receive_USDC_only:
      '{TSLA} を {USDC} に換算し、{USDC} のみ受け取る',
    receive_both: '両方を受け取る',
    convert_TSLA_to_USDC_and_receive_USDC:
      '{TSLA} を {USDC} に換算し、{USDC} を受け取る',
    receive_TSLA: '{TSLA} を受け取る',
    withdrawing: '出金処理中',
    withdrawal_successful: '出金に成功しました',
    withdrawal_failed: '出金に失敗しました',
    Simple_Earn: 'シンプル運用',
    view_in_turbo_range: 'Turbo Range で表示',
    position_history: 'ポジション履歴',
    initial_investment: '初期投資',
    click_history_above_for_details: '詳細は上のICON履歴をクリックしてください',
    how_does_turbo_range_earn_yield:
      'Turbo Range はどうやって利回りを生むのですか?',
    transaction_in_progress: '取引 1 件を処理中',
    transaction_successful: '取引 1 件が成功しました',
    transaction_failed: '取引 1 件が失敗しました',
    N_transactions_in_progress: '取引 N 件を処理中',
    N_transactions_successful: '取引 N 件が成功しました',
    N_transactions_failed: '取引 N 件が失敗しました',
    position: 'ポジション',
    all_time_yield: '累計利回り',
    yesterday_apy: '昨日の APY（年率換算）',
    duration: '期間',
    all_time_apy: '累計 APY',
    updating: '更新中...',
    will_be_calculated_on_DATE: 'DATE に計算されます',
    returned_to_your_wallet: 'ウォレットに返金済み',
    principal_upon_closure: 'クローズ時の元本返還',
    est_apy_tips:
      'ここに表示される推定年率は、選択期間の過去データに基づいて算出されています。',
    invalid_range: '無効な範囲です',
    faq_1: '流動性プールとは？',
    faq_1_text:
      '流動性プールはブロックチェーン上に配置されたスマートコントラクトで、ETH と USDC のような 2 種のトークンを保有します。ユーザーはこのコントラクトを介して両トークンを直接交換できます。誰でも自分のトークンをプールに追加して流動性を提供し、取引手数料の分配を受け取れます。',
    faq_2: '流動性を提供して手数料収入を得るにはどうすればよいですか？',
    faq_3: 'Turbo Range に投資する利点は何ですか？',
    faq_3_text1:
      '伝統的な投資（TSLA 株を買って保有するなど）は、価格が上がったときにしか利益が出ません。Turbo Range は異なり、レンジ相場でも上昇相場でも収益を得られます。',
    faq_3_text2:
      '<b>レンジ：</b> 設定した価格帯の中で継続的に取引手数料を獲得できます',
    faq_3_text3: '<b>上昇：</b> 元本の価値が増え、手数料収入も継続します',
    put_simply: '端的に言えば：',
    put_simply_text:
      '価格が上がるときだけでなく、レンジ相場でも利益を得られます。',
    faq_4: 'DeGate は私の Turbo Range ポジションを操作しますか？',
    faq_4_text:
      'いいえ。Turbo Range のポジションはすべてオンチェーンで、あなた自身のウォレットに保管されています。資金にアクセスしたり引き出したりできるのはあなただけです。',
    faq_4_n: 'Turbo Range で押し目買いするには？',
    faq_4_n_text:
      '資産が 100 で取引されており、75 前後で積み増したい場合は、価格帯 50～100 の Turbo Range を作成できます。利点は、このレンジ内で価格が推移している間、Turbo Range が手数料収益を生み続け、平均取得単価の引き下げに役立つことです。',
    faq_4_n_text2:
      '価格が50まで下がったら、Turbo Rangeを必ずクローズしてください。クローズしない場合、価格が50を再び上回るとポジションは再び買い始めます。',
    faq_6: '価格がレンジ外に出たとき、Turbo Range は自動でクローズしますか？',
    faq_6_text:
      'いいえ、自動では閉じません。価格がレンジ内に戻れば、Turbo Range は利回りの生成を再開します。レンジ外に出たポジションを止めたい場合は手動でクローズしてください。',
    websites: 'ウェブサイト',
    liquidity_pool: '流動性プール',
    liquidity_pool_age: '流動性プールの稼働期間',
    total_value_locked_of_raydium: '{Raydium} のTVL（総ロック価値）',
    XX_as_of_DATE: '{DATE} 時点：{XX}',
    market_cap_of_paxg: '{PAXG} の時価総額',
    desc_xstocks:
      'TSLAx は Backed Assets (JE) Limited が発行する xStock です。xStock の発行はスイス法に準拠しており、2025 年 5 月 8 日にリヒテンシュタインの金融市場監督庁（FMA）から承認されました。',
    desc_gold:
      'PAXG は Paxos Trust Company によって発行されるデジタル資産です。各 PAXG はロンドンの LBMA 管理金庫に保管された純金 1 トロイオンスに裏付けられています。Paxos はニューヨーク州金融サービス局（NYDFS）の規制下にあります。',
    desc_btc:
      'cbBTC は Coinbase が発行するビットコイン担保型トークンです。各 cbBTC は Coinbase が保有する 1 BTC を表し、1:1 で償還可能です。Coinbase は米国の上場企業で、米国の規制監督下で運営されています。',
    desc_native_coin_ETH_NETWORK:
      '{ETH} は {NETWORK} ネットワークのネイティブトークンです。',
    legal_documentation: '法的文書',
    factsheet: 'ファクトシート',
    audit_reports: '監査報告書',
    Onesheet: 'ワンシート（概要）',
    on_chain_assets_and_protocol: 'オンチェーン資産とプロトコル',
    entry_price: 'エントリー価格',
    active_capital: '稼働資金',
    withdraw_and_close: '出金してクローズ',
    withdraw_and_claim: '出金して受け取る',
    incl_unclaimed_yield: '未受取の利回りを含む',
    capital_withdrawn: '引き出した元本',
    yield_claimed: '受け取った利回り',
    fee_pre_charged:
      'この手数料はポジションを開設した際に前払いされ、クローズ時にあなたのウォレットに返金されます。',
    price_is_out_of_range_see_tips:
      '価格がレンジ外です。ヒントを確認してください。',
    what_do_you_think_XXX_s_price_will_do_next:
      '{XXX}の価格はこのあとどう動くと思いますか…',
    rise_and_move_back_into_my_price_range: '上昇して私の価格レンジに戻る',
    move_sideways_around_the_current_price: '現在の価格付近で横ばいに推移する',
    keep_falling: '下落を続ける',
    if_you_think_XXX_s_price_will_rise_and_move_back_into_your_price_range:
      '{XXX}の価格が上昇してあなたの価格レンジに戻ると思うなら…',
    you_will: 'あなたが行うこと',
    hold_and_wait: '保有して様子を見る',
    if_you_think_XXX_s_price_will_move_sideways_around_the_current_price:
      '{XXX}の価格が現在の水準付近で横ばいになると思うなら…',
    close_your_position_and_open_a_new_one:
      'ポジションをクローズして新規に開く',
    close_position: 'ポジションをクローズ',
    if_you_think_XXX_s_price_will_keep_falling:
      '{XXX}の価格が下落を続けると思うなら…',
    close_position_and_withdraw_USDC: 'ポジションを閉じて USDC を出金',
    adjust_price_range: '価格レンジを調整',
    adjust_now: '今すぐ調整',
    increase_investment: '追加投資',
    increasing_investment: '追加投資中',
    investment_increased: '追加投資完了',
    investment_increase: '追加投資',
    increase_failed: '追加に失敗しました',
    total_principal: '合計元本',
    total_withdrawal_and_claim: '合計出金・受取',
    investModeSingle: 'シングル',
    investModeDual: 'デュアル',
    nagative_invest_tips:
      'このマイナス値は、ウォレットに返還された資金を示しています。詳細はポジション履歴をご覧ください。',
    APY_Backtest: 'APY バックテスト',
    Historical_APY_desc:
      'ここに表示される過去の年率換算利回り（APY）は、選択期間の過去データに基づくバックテスト結果です。その期間の開始時に投資していた場合に得られた APY を示します。',
    Historical_APY: '過去の APY',
    XXX_Overall_APY: 'XXX の総合 APY',
    Partially_in_range: '一部レンジ内',
    In_range: 'レンジ内',
    Out_of_range: 'レンジ外',

    // Strategies Marketplace
    strategies: '戦略広場',
    top_apy: 'トップAPY',
    hot_today: '本日の人気',
    best_returns: '最高リターン',
    roi: 'ROI (投資収益率)',
    total_return: '総リターン',
    connect_wallet_to_see_positions: 'ウォレットを接続してポジションを表示',
    re_open: '再開',
    view_details: '詳細を表示',
    copy: 'コピー',
    initial_price: '初期価格',
  },
  Product: '商品',
  filter: 'フィルター',
  Failed: '失敗',
  History_currently_unavailable: '履歴は現在利用できません。',
  History_currently_unavailable_tips:
    'ホームタブへ移動してウォレットアドレスをコピーし、ブロックチェーンエクスプローラーで取引履歴を確認してください。',
  Approval: '承認',
  Contract_Call: 'コントラクト呼び出し',
  Unlimited: '無制限',
  APY_1: '1 APY',
  External_Sites: '外部サイト',
  XXX_Refundable: 'XXX 返金可',
  Refundable_on_data_release: 'データ公開時に返金可',
  est_time: '予想時間',
  Refundable_when_position_is_closed: 'ポジションをクローズ時に返金可能',

  go_to_turbo_range: 'Turbo Range に移動',
  go_to_earn: 'Simple Earn へ移動',
  in_address: 'アドレス内',
  in_copy_trade: 'コピートレード内',
  source_network: '',
  destination_network: '',
  move_usdc_across_chains: 'USDC をチェーン間で 1:1 で移動',
  bridge_successful: 'ブリッジ成功',
  no_result_found: '結果が見つかりません',
  enter_address: 'アドレスを入力',
  scan: 'スキャン',
  check_address_format: 'アドレス形式を確認してください。',
  invalid_address: '無効なアドレス',
  estimated_network_fee: '概算ネットワーク手数料',
  incl_solana_rent_of_XXX: 'Solana のレンタル費 $XXX を含む',
  check_my_balance: '残高を確認',
  moving_your_USDC_to_destination_network: 'USDC を送信先ネットワークへ移動中…',
  you_don_t_have_enough_USDC_to_pay_for_the_network_fee:
    'ネットワーク手数料を支払うのに十分な USDC がありません。',
  change_fee_token: '手数料トークンを変更',
  estimated: '概算',
  actual: '実際',
  receive_usdc: 'USDC を受け取る',
  from_other_wallets: '他のウォレットから',
  bridge_usdc: 'USDC をブリッジ',
  consolidate_to_one_chain: '1 つのチェーンに集約',
  simple_earn_disabled_deposit_tips:
    'このボールトは担保資産の大きなボラティリティに晒されています。注意して進めてください。',
  Time_to_complete: '完了までの時間',
  You_Pay: 'お支払い額',
  Returned_to_your_wallet_when_position_is_closed:
    'ポジションをクローズするとウォレットに返金されます',
  Refundable_Fee: '返金可能な手数料',
  Fee_Refunded: '手数料返金済み',
  Claiming: '受け取り中',
  Reinvesting: '再投資中',
  Withdrawing: '出金中',
  Adding: '追加中',
  Cash_Buy: '購入',
  Buy_with_cash_card: '現金／カードで購入',

  est_gas_needed_for_network_fee:
    'ネットワーク手数料として $EST_GAS USDC を確保済み',
  available_amount: '利用可能額',
  current_balance: '現在残高',
  reserved_for_network_fee: 'ネットワーク手数料として確保',
  maximum_available: '最大利用可能額',
  use_max: '最大値を使用',
  edit_amount: '金額を編集',
  insufficient_network_fee: 'ネットワーク手数料が不足しています',
  separator_comma: '，',
  insufficient_network_fee_tips:
    'ネットワーク手数料として $FEE が必要です。$XXX、USDC、USDT、または他のトークンで支払えます。',
  pay_with_another_token: '別のトークンで支払う',

  History_is_currently_unavailable_for_CHAIN:
    '{CHAIN} の履歴は現在利用できません。詳しくはブロックチェーンエクスプローラーでご確認ください。',
  Check_on_Explorer: 'エクスプローラーで確認',
  Min: '最小',
  Max: '最大',
  enable_notifications: '通知を有効にしますか？',
  receive_notification_when_out_of_price_range:
    '価格がレンジ外になったら通知を受け取る',
  we_ll_notify_you_when_your_turbo_range_goes_out_of_range:
    'お使いの Turbo Range がレンジ外になったら通知します。',

  referral: 'リファラル',
  referral_code: 'リファラルコード',
  your_referrer: 'あなたの紹介者',
  please_confirm_within_10_seconds: '10秒以内に確認してください。',
  confirmation_expired: '確認の有効期限が切れました。もう一度お試しください。',

  select_Open_in_Default_Browser_from_the_menu:
    'メニューから「既定のブラウザで開く」を選択してください。',
  you_need_a_DeGate_account_to_continue:
    '続行するには DeGate アカウントが必要です。',
  claim_now: '今すぐ受け取る',
  please_wait_it_takes_xx_seconds:
    '少々お待ちください。所要時間は約 ~xx 秒です。',
  you_have_received_a_Turbo_Range_position_worth_XXX:
    '約 ~$XXX 相当の Turbo Range ポジションを受け取りました。',
  view_my_balance: '残高を表示',
  sorry_youve_already_claimed_once:
    '申し訳ありません。すでに一度受け取り済みです。',
  gift_card_expired: 'ギフトカードの有効期限が切れました',
  gift_card_has_not_been_activated: 'ギフトカードが有効化されていません',
  gift_card_has_been_claimed: 'ギフトカードはすでに受け取られました',
  please_open_this_page_on_your_mobile_phone:
    'このページをスマートフォンで開いてください',
  open_with_DeGate_App: 'DeGateアプリで開く',
  sign_in: 'サインイン',
  Show_more: 'もっと見る',
  signature_free_mode_tips:
    'このモードでは署名なしでトークンをスワップできます。モードを切り替えるには、右上の設定アイコンをクリックしてください。',
  invite_to_degate_experience_enhancement_program:
    'DeGate 体験強化プログラムにご招待',
  as_a_selected_user_youll_get: '選ばれたユーザーとして、次を受けられます：',
  a_smoother_app_experience: 'よりスムーズなアプリ体験',
  dedicated_one_on_one_support: '専任の1対1サポート',
  private_client_desk: 'プライベート・クライアント・デスク',
  private_client_desk_upperCase: 'プライベート・クライアント・デスク',
  through_this_desk_you_may:
    'このデスクを通じて、以下のサービスをご利用いただけます:',
  receive_priority_operational_support: '優先的な運営サポートを受ける',
  direct_communication_with_our_strategy_and_operations_team:
    '戦略・運営チームと直接連絡',
  early_access_to_new_products: '新製品への早期アクセス',
  access_exclusive_privileges_and_customized_benefits:
    '限定特典とカスタマイズされた特典にアクセス',
  private_client_desk_access_path_intro:
    'プライベート・クライアント・デスクは、以下の方法でアクセスできます:',
  private_client_desk_access_path_home_menu:
    'ホーム > メニュー > プライベート・クライアント・デスク',
  private_client_desk_access_path_home_settings:
    'ホーム > 設定 > プライベート・クライアント・デスク',
  private_client_desk_access_bottom_left_corner:
    '左下隅からプライベート・クライアント・デスクにアクセスできます',
  WhatsApp: 'WhatsApp',
  Signal: 'Signal',
  Email: 'メール',
  welcome_aboard: 'ようこそ！',
  youre_now_among_a_select_group_enjoying_an_enhanced_degate_experience:
    '強化された DeGate 体験を享受する選ばれたグループの一員になりました。',
  link_expired: 'リンクの有効期限が切れました',
  please_update_your_app_to_the_latest_version:
    '最新バージョンにアップデートしてください',
  chart_is_currently_unavailable: 'チャートは現在利用できません。',
};

export default ja;
