const kr = {
  language: 'kr-KR',
  'kline.time_Line': '시간',
  'kline.time_1s': '1s',
  'kline.time_5s': '5s',
  'kline.time_15s': '15s',
  'kline.time_30s': '30s',
  'kline.time_1m': '1m',
  'kline.time_3m': '3m',
  'kline.time_5m': '5m',
  'kline.time_15m': '15m',
  'kline.time_30m': '30m',
  'kline.time_1H': '1H',
  'kline.time_2H': '2H',
  'kline.time_4H': '4H',
  'kline.time_6H': '6H',
  'kline.time_1D': '1D',
  'kline.time_1W': '1W',
  'kline.time_1M': '1M',
  'kline.tab_line': '차트',
  'kline.tab_depth': '뎁스',
  'kline.chartType_Bars': '바',
  'kline.chartType_Candles': '캔들',
  'kline.chartType_Hollow_Candles': '투명 캔들',
  'kline.chartType_Line': '선',
  'kline.chartType_Area': '영역',
  'kline.chartType_Heikin_Ashi': 'Heikin Ashi',
  degate_account: 'DeGate 계정',
  Trade: '거래',
  Order: '주문',
  Grid: '그리드 전략',
  Campaign: '캠페인',
  DCA: 'DCA',
  Advanced: '고급',
  Add: '추가',
  Add_Funds: '자금 추가',
  external_wallet_receive_guide:
    'DeGate 지갑에 자산이 없습니다. 외부 지갑에서 이체해 주세요.',
  external_wallet_add_funds_guide:
    'DeGate에 자금이 없습니다. 외부 지갑에서 추가해 주세요.',
  eth_added_1: '1 ETH 추가됨',
  eth_sent_1: '1 ETH 전송됨',
  Send: '보내기',
  Internal_Transfer: '내부 전송',
  Miscellaneous: '기타',
  Mining: '마이닝',
  Liquidity_Mining: '유동성 마이닝',
  Analytics: '애널리틱스',
  Support: '고객지원',
  Help: '도움말',
  Tips: '팁',
  Statistics: '통계',
  Coming_soon: '곧 출시',
  Faucet: 'Faucet',
  more: '더 보기',
  hide: '숨기기',
  change: '변경',
  'Wrong Network': '잘못된 네트워크',
  avbl: '이용 가능:',
  insufficient_balance_AAA:
    '지갑에 AAA가 충분하지 않습니다. 확인 후 다시 시도해 주세요.',
  insufficient_balance: '잔액 부족',
  wallet_denied_sign: '메시지 서명이 거부되었습니다.',
  common_err: '문제가 발생했습니다. 나중에 다시 시도해 주세요.',
  common_err_ledger_version:
    '오류가 발생했습니다. Ledger Ethereum 앱이 최신 버전(1.9.10 이상)인지 확인해주세요. 또는 나중에 다시 시도해 주세요.',
  network_1: '이더리움 메인넷',
  network_err: '네트워크 오류. 나중에 다시 시도해 주세요.',
  rate_limit_err: '접속 빈도가 너무 높습니다. 1분 후에 다시 시도해 주세요.',
  error_InsufficientGasFunds: '지갑에 가스가 부족합니다',
  notification_transaction_send: '거래 전송됨',
  view_on_explorer: '블록체인 탐색기에서 보기',
  view_address: '주소 보기',
  switch_network: '네트워크 전환',
  switch_to_Arbitrum: '계속하려면 Arbitrum으로 전환해 주세요.',
  switch_to_MAINNET_in_metamask: 'MetaMask에서 MAINNET으로 전환해 주세요',
  switch_to_MAINNET: 'MAINNET으로 전환해 주세요',
  switch_network_in_walletconnect:
    '지갑으로 이동하여 WalletConnect로 네트워크를 전환하세요',
  Retry: '재시도',
  wallet_tips: '브라우저 지갑에서 승인해 주세요',
  wallet_ledger_tips: 'Ledger 하드웨어에서 승인해 주세요',
  wallet_metamask_tips: 'MetaMask에서 승인해 주세요',
  wallet_walletconnect_tips:
    'WalletConnect로 승인하려면 지갑으로 이동해 주세요',
  wallet_cancelled_tips: '서명을 취소했습니다',
  Close: '닫기',
  Closed: '닫힘',
  copied: '복사됨',
  Details: '세부 정보',
  view_details: '세부 정보 보기',
  turbo_range_view_live_status: '실시간 상태 보기',
  Share: '공유',
  view_graph: '차트에서 보기',
  Dismiss: '해제',
  Cancel: '취소',
  End: '종료',
  End_grid: '종료',
  Confirm: '확인',
  Cancel_all: '모두 취소',
  cancel_all_tips: '모든 미체결 주문 취소',
  Submit: '제출',
  no_data: '데이터 없음',
  all_data_displayed: '모든 데이터 표시됨',
  no_data_within_90_days: '90일 내 데이터 없음',
  only_display_90_days: '지난 90일 데이터만 표시 중',
  displayed_90_days: '지난 90일 데이터 표시',
  only_data_beyond_90_days_trade:
    '90일 이상의 데이터를 보려면 "모두 보기"를 선택한 후 "데이터 내보내기" 기능을 사용하세요',
  only_data_beyond_90_days_grid_detail:
    '최근 90일을 초과한 데이터에 대한 조회는 현재 지원되지 않습니다',
  only_data_beyond_90_days_spot_history:
    '90일 이상의 데이터를 보려면 "데이터 내보내기" 기능을 사용하세요',
  View: '보기',
  service_unavailable_for_region_REGION:
    '이 서비스는 REGION에서 사용할 수 없습니다.',
  service_unavailable: '서비스를 사용할 수 없습니다',
  service_error: '나중에 다시 시도해 주세요',
  service_maintenance: '이 서비스는 점검 중입니다.',
  connect_wallet: '지갑 연결',
  switch_address: '주소 전환',
  wallet_wc: 'WalletConnect로 연결됨',
  wallet_ledger: 'Ledger로 연결됨',
  register_dexAccount: '등록',
  deposit_ETH: 'ETH 추가',
  initialize: '초기화',
  initialization: '초기화 중',
  invalid_signature: '유효하지 않은 서명',
  possible_cause: '다음과 같은 원인이 있을 수 있습니다:',
  locale_time_error: '로컬 장치 시간이 정확하지 않습니다.',
  authorization_mode: '인증 모드',
  authorization_mode_standard: '무서명 모드',
  authorization_mode_single_use: '항상 서명',
  turn_on: '켜기',
  turn_on_signature_free_mode: '무서명 모드 켜기',
  signatre_free_mode: '무서명 모드',
  turn_on_signature_free_mode_tips:
    '이 모드에서는 서명 없이 주문을 할 수 있습니다. 모드를 전환하려면 거래 버튼 아래에 있는 "설정"으로 이동하세요.',
  turn_on_signature_free_mode_tips_grid:
    '이 모드에서는 서명 없이 그리드 전략을 생성할 수 있습니다. 모드를 전환하려면 거래 버튼 아래에 있는 "설정"으로 이동하세요.',
  turn_on_signature_free_mode_tips_dca:
    '이 모드에서는 서명 없이 DCA 플랜을 생성할 수 있습니다. 모드를 전환하려면 거래 버튼 아래에 있는 "설정"으로 이동하세요.',
  yes: '예',
  no: '아니요',
  free_mode_on: '무서명 모드 켜짐',
  view_balance: '잔액 보기',
  delete_asset_key: 'Asset Key 삭제',
  delete_asset_key_desc: 'Asset Key가 삭제되면 무서명 모드가 꺼집니다.',
  no_asset_key_tips: '브라우저에서 Asset Key를 찾을 수 없습니다',
  turn_off_standard_mode: '그리고 무서명 모드 끄기',
  reset_asset_key: 'Asset Key 재설정',
  view_asset_key: 'Asset Key 보기',
  lock_success: 'Asset Key 삭제됨',
  reset: 'Asset Key 재설정',
  delete: '삭제',
  withdraw_ETH: 'ETH 전송',
  transfer_ETH: 'ETH 내부 전송',
  history: '기록',
  view_history: '기록에서 보기',
  internal_transfer: '전송',
  assets_record_link: '기록',
  other: '기타',
  login_success: '연결 성공',
  Account: '계정',
  Address: '주소',
  Disconnect: '연결 끊기',
  copy_address: '주소 복사',
  copy_grid: '전략 복사',
  Copy: '복사',
  btn_search: '검색',
  btn_reset: '재설정',
  btn_confirm: '닫기',
  btn_max: '최대',
  btn_ok: '확인',
  spot_trade: 'SPOT',
  grid_trade: '그리드',
  err_balance_title: '주문 실패했습니다.',
  err_balance_content: '가용 잔액 부족. 확인 후 다시 시도해 주세요.',
  order_failed: '주문 실패',
  insufficient_order_value: '주문 가치 부족',
  grid_failed: '생성 실패',
  err_eth_gas: '이더리움 네트워크 혼잡 심각',
  err_insufficient_balance_TOKEN1: 'TOKEN1 잔액 부족',
  err_insufficient_balance_TOKEN1_TOKEN2: 'TOKEN1 및 TOKEN2 잔액 부족',
  please_add_funds_before_ordering:
    '주문 전에 DeGate 잔액에 자금을 추가해 주세요.',
  err_balance_content_spot: '잔액 부족으로 인해 주문을 할 수 없습니다.',
  err_balance_content_grid:
    '잔액 부족으로 인해 그리드 전략을 생성할 수 없습니다.',
  trade_min_volume_tips_XXX: '최소 XXX',
  grid_min_volume_tips:
    '주문당 수량이 최소 금액을 충족하지 않습니다. 다시 시도해 주세요.',
  trade_risk_orders_tips: '미체결 주문이 너무 많아 주문을 할 수 없습니다',
  gas_token_tips: '가스비 토큰 선택',
  add_favorite_tooltip: '즐겨찾기에 추가',
  remove_favorite_tooltip: '즐겨찾기에서 제거',
  expire_tips_X: '이 주문은 X에 만료됩니다.',
  today: '현재',
  now: '현재',
  time_D_day: 'Dd',
  time_D_day_H_hour: 'Dd Hh',
  time_last_24_hrs: '최근 24시간',
  time_last_hour: '최근 1시간',
  time_H_hour_M_minute: 'Hh Mm',
  time_M_minute_S_second: 'Mm Ss',
  time_S_second: 'Ss',
  around: '~',
  time_now: '현재',
  time_before: '이전',
  time_before_ago: '이전',
  time_1_minute: '1분',
  time_1_hour: '1시간',
  time_1_day: '1일',
  time_1_year: '1년',
  time_M_minutes: 'M분',
  time_M_m: 'Mm',
  time_H_hours: 'H시간',
  time_H_h: 'Hh',
  time_D_days: 'D일',
  time_Y_years: 'Y년',
  time_Y_y: 'Yy',
  time_D_d: 'Dd',
  time_M_mo: 'Mmo',
  fee_change_tips: '가격 업데이트',
  no_pairs: '거래 페어를 찾을 수 없음',
  register_new_pair: '새로운 페어 추가',
  register_pair: '거래 페어 추가',
  add_pair: '페어 추가',
  tips_hide_forever: '다시 표시하지 않기',
  Select_Token: '토큰 선택',
  token: '토큰',
  action: '작업',
  more_actions: '더 보기',
  gas_fee: '가스비',
  'orders.detail_gas': '실제 가스비',
  trade_fee: '거래 수수료',
  about_degate: 'DeGate 소개',
  metrics: '지표',
  fees: '수수료',
  document: '문서',
  join_us: '채용공고',
  feedback: '피드백',
  email_optional: '이메일 주소 (선택 사항)',
  Upload: '업로드',
  feedback_upload_tip:
    '피드백을 공유해 주세요. 첨부 파일을 드래그해서 올려주세요.',
  feedback_upload_tip_mobile: '피드백을 공유해 주세요.',
  image_upload_tip: '추가하려면 놓기',
  feedback_success: '제출해주신 의견을 잘 살펴보겠습니다!',
  feedback_success_2: '감사합니다',
  feedback_failed: '제출 실패. 나중에 다시 시도해 주세요.',
  image_upload_rule_1: 'PNG, JPG, JPEG만 지원됩니다.',
  image_upload_rule_2: '최대 파일 크기는 20MB입니다.',
  image_upload_rule_3: '최대 5개의 파일까지 가능합니다.',
  image_upload_rule_2_3: '최대 파일 크기는 20MB, 최대 5개의 파일입니다.',
  no_pair: '토큰 페어를 찾을 수 없음',
  no_token: '토큰을 찾을 수 없음',
  choose_base_token: '기본 토큰 선택',
  choose_quote_token: '견적 토큰 선택',
  get_test_token: '테스트넷 토큰 받기',
  faucet: 'Faucet',
  expire_in: '만료 시간',
  expire_in_empty_err: '숫자를 입력하세요',
  go_back: '돌아가기',
  max_XXX: '최대 XXX',
  min_XXX: '최소 XXX',
  fill_in: '채우기',
  my_balance: '내 잔액',
  deGate_insufficient_fees: '가스비를 지불할 DeGate 잔액이 부족합니다',
  wallet_balance: '지갑 잔액',
  your_wallet_balance: '내 지갑 잔액',
  degate_balance: 'DeGate 잔액',
  wallet_insufficient_fees: '지갑의 잔액이 부족합니다',
  wallet_insufficient_balance: '잔액 부족',
  insuffficient_wallet_balance: '지갑 잔액 부족',
  degate_insufficient_balance: '가용 잔액 부족',
  open_discord: '디스코드 커뮤니티로 이동',
  err_valid_until: '기기에 설정된 현지 시간을 표준 시간으로 조정해 주세요',
  tips_gas:
    '이 온체인 거래를 실행하기 위한 가스비는 DeGate 잔액에서 직접 차감됩니다.',
  maker_free: '메이커 무료',
  trading_fee_rate: '거래 수수료율',
  Free: '무료',
  stop_service_1: '사이트 점검 중',
  stop_service_2: '복구 예상 시간',
  stop_upgrade: '테스트넷의 새 버전이 현재 마이그레이션 중입니다.',
  stop_trading_1: '시스템 업그레이드',
  stop_trading_2: '거래가 일시적으로 중단되었습니다',
  sell: '매도',
  buy: '매수',
  SELL: '매도',
  BUY: '매수',
  Sell: '매도',
  Buy: '매수',
  sell_order: '매도 주문',
  buy_order: '매수 주문',
  edit: '편집',
  status_processing: '처리 중',
  status_processed: '대기 중',
  status_pending: '대기 중',
  status_confirming: '확인 중',
  status_success: '성공',
  status_completed: '확정',
  status_failed: '실패',
  status_speeding_up: '속도 높이는 중',
  status_canceling: '취소 중',
  status_canceled: '취소됨',
  in_progress: '진행 중',
  limit_order: '지정가',
  market_order: '시장가',
  stop_limit_order: '예약-지정가',
  balance: '잔액',
  empty_connect: '먼저 지갑을 연결해 주세요',
  empty_register: '먼저 초기화해 주세요',
  empty_months3: '지난 3개월 데이터가 없습니다',
  show_months3: '최근 3개월 데이터만 표시 중',
  view_all: '모두 보기',
  H1: '1시간',
  D1: '1일',
  D5: '5일',
  M1: '1개월',
  M3: '3개월',
  M6: '6개월',
  YTD: 'YTD',
  Y1: '1년',
  all: '전체',
  paste: '붙여넣기',
  clear: '지우기',
  total: '총액',
  amount: '수량',
  order_amount: '주문 금액',
  price: '가격',
  order_total: '총액',
  filledAmount: '수량',
  tradeFilledTotal: '가치',
  orderFilledTotal: '총액',
  filledAmount_amount: '체결/수량',
  profit: '수익',
  incompatible_token:
    '이 토큰의 기술 사양은 DeGate 프로토콜과 호환되지 않습니다.',
  next: '다음',
  token_not_verified: '확인되지 않음',
  token_not_verified_tips:
    '컨트랙트 주소, 아이콘, 기호가 확인되지 않았습니다. 공식 채널에서 컨트랙트 주소를 확인하여 사기를 방지하세요.',
  token_verified: '확인됨',
  token_verified_tips: '컨트랙트 주소, 아이콘, 기호가 일치합니다.',
  deposit_tips_region:
    'REGION에서 DeGate에 접속하고 있습니다. 자금 추가 후 거래 및 내부 이체 기능을 사용할 수 없습니다.',
  complete_time: '완료까지',
  unable_to_initialize: '초기화 불가',
  filter_base: '기본',
  filter_quote: '견적',
  filter_type: '유형',
  filter_role: '역할',
  option_maker: '메이커',
  option_taker: '테이커',
  start_data: '시작 날짜',
  end_data: '종료 날짜',
  added_to_favorites: '즐겨찾기에 추가됨',
  removed_to_favorites: '즐겨찾기에서 제거됨',
  show_recents_50: '최신 50개 데이터가 표시되었습니다.',
  terms_of_service: '서비스 약관',
  tips_small_unfilled:
    '시스템 설계에 지정된 정밀도에 따라 미체결된 일부 주문은 DeGate 잔액으로 반환됩니다.',
  notification: '알림',
  server_message_SystemRecovery:
    '시스템 복구 후 주문 상태에 변경 사항이 있습니다.',
  learn_more: '자세히 알아보기',
  connect_ledger: 'Ledger 연결',
  ledger_disconnect:
    "USBDevice의 'transferOut' 실행 실패: 장치가 연결 해제되었습니다.",
  gas_fee_expired: '가스비 만료됨. 다시 제출해 주세요.',
  scroll_down_to_refresh: '아래로 스크롤하여 새로 고침',
  release_to_refresh_immediately: '새로 고침을 위해 놓기',
  no_more: '더 이상 데이터 없음',
  loading: '로딩 중...',
  force_withdrawing_token_tips:
    '강제 인출 요청이 처리 중이므로 현재 작업을 수행할 수 없습니다.',
  speed_up: '속도 높이기',
  transaction_submitted: '거래 제출됨',
  tx_speed_up: '거래 속도 높이기',
  tx_cancel: '거래 취소',
  none: '없음',
  Language: '언어',
  page: '/페이지',
  go_to: '이동',
  icon_indicators: '지표',
  icon_back: '뒤로',
  icon_forward: '앞으로',
  icon_full_screen: '전체 화면',
  icon_exit_full_screen: '전체 화면 종료',
  icon_buy_sell_orders: '매수 및 매도 주문',
  icon_buy_orders: '매수 주문',
  icon_sell_orders: '매도 주문',
  icon_enable: '활성화하려면 클릭',
  icon_disable: '비활성화하려면 클릭',
  icon_copy: '주소 복사',
  icon_view_explorer: '블록 탐색기에서 보기',
  icon_display_by_profit: '수익별 표시',
  icon_display_by_time: '시간별 표시',
  icon_switch: '전환',
  eth_code_tips: '이더리움의 네이티브 토큰. 토큰 컨트랙트 주소가 없습니다.',
  TBD: '미정',
  TVL: 'TVL',
  go_to_discord: '디스코드에서 티켓 생성',
  release: '출시:',
  security: '보안',
  colon: ':',
  zero_balance: '잔액 없음',
  ledger_app_version_tips:
    'Ledger의 Ethereum 앱을 1.9.19 이상의 버전으로 업데이트하여 서명 전 메시지를 미리 보기하세요.',
  ledger_contract_data_tips:
    'Ethereum 앱 설정에서 Blind signing 또는 Contract data를 활성화하세요',
  input_auto_corrected_tooltips:
    '지정된 자릿수를 초과한 후 입력이 자동으로 수정되었습니다',
  maximum_decimal_reached: '최대 소수 자릿수에 도달했습니다',
  verify_ownership: '소유권 확인',
  enable_trading: '거래 활성화',
  learn_more_about_signatures_link: '서명에 대해 자세히 알아보기 >',
  learn_more_about_signatures: '서명에 대해 자세히 알아보기',
  sign: '서명',
  sign_step1: '지갑에서 완료',
  sign_step2: '두 번째 서명 완료',
  not_now: '지금은 하지 않기',
  view_on_block_explorer: '블록체인 탐색기에서 보기',
  view_in_history: '기록에서 보기',
  continue_to_place_order: '주문 계속하기',
  Save: '저장',
  sign_to_view: '서명하여 보기',
  available_degate_balance: '사용 가능한 DeGate 잔액',
  Back: '뒤로',
  token_has_not_listed: '이 토큰은 DeGate에 아직 상장되지 않았습니다.',
  list_now: '지금 상장',
  spread_15: '스프레드 > 15%',
  connected: '연결됨',
  self_list_token: '즉시 상장',
  claim_REBASE: '리베이스 청구',
  time: '시간',
  time_updated: '시간 업데이트됨',
  show_in_X_m: '약 ~X분 후 표시',
  max_gas: '최대 가스비',
  total_required: '총 필요 금액',
  Required: '필수',
  available_balance: '사용 가능한 잔액',
  please_add_funds: 'DeGate 잔액에 자금을 추가해 주세요.',
  Side: '구분',
  pending: '대기 중',
  active: '활성',
  ended: '종료됨',
  name: '이름',
  yield: '수익률',
  time_created: '생성 시간',
  time_ended: '종료 시간',
  frequency: '빈도',
  chain_cancel: '온체인 취소',
  status: '상태',
  status_chainCancelProgressing: '온체인 취소 중',
  status_chainCancelCompleted: '온체인 취소 완료',
  filled_total: '체결/총액',
  start_time: '시작 시간',
  end_time: '종료 시간',
  Summary: '요약',
  Orders: '주문',
  Tutorial: '튜토리얼',
  top_winner_24h: '24시간 상위 랭킹',
  ID: 'ID',
  Select: '선택',
  Create: '생성',
  Review: '검토',
  Airdrop: '에어드랍',
  Airdrops: '에어드랍',
  Countdown: '카운트다운',
  Day: '일',
  Hour: '시간',
  Minute: '분',
  Second: '초',
  Days: '일',
  Hours: '시간',
  Minutes: '분',
  Seconds: '초',
  Claim: '청구',
  Expired: '만료됨',
  Claimed: '청구 완료',
  Welcome: '환영합니다',
  gas_tips_for_amount_exceed_6_digits:
    '금액의 자릿수가 6자리를 초과하여 추가 요금이 부과되었습니다.',
  input_auto_corrected_minStep_tips:
    '최소 정밀도를 맞추기 위해 입력을 자동 수정했습니다.',
  order_max_limit: '최대 한도 초과',
  order_min_limit: '최소 한도 미달',
  order_faild_min_limit: '주문 배치 실패: 최소 한도 미달',
  order_faild_max_limit: '주문 배치 실패: 최대 한도 초과',
  disconnect_m: '연결 끊기',
  'account.account_manage': '보안',
  'account.account_manage_more': '인증 모드 및 Asset Key 정보 >',
  'account.what_is_asset_key': '인증 모드 및 Asset Key 정보',
  'account.total_value': '총 가치',
  'account.hide_small_balances': '소액 자산 숨기기',
  'account.add_to_metamask': '토큰을 지갑에 추가',
  'account.assets_balance_total': '총액',
  available: '사용 가능',
  'account.assets_market': '가치',
  'account.transfer_to_degate_balance': 'DeGate 잔액에 추가',
  'account.search_tokens': '토큰 검색',
  'account.deposit_title':
    '자산은 귀하의 탈중앙화 DeGate 계정에 입금됩니다. 이 자산에 대한 완전한 관리권(full custody)을 보유합니다.',
  'account.deposit_tips':
    '이 자금에 대한 완전한 관리권(full custody)을 보유합니다.',
  'account.deposit_confirm_btn': '추가',
  'account.deposit_approved_btn': '승인됨',
  'account.deposit_1_ETH': '1 ETH를 DeGate 잔액에 추가',
  'account.deposit_status_pending': '대기 중',
  'account.deposit_status_pay_pending': '결제 예정',
  'account.deposit_status_pay_waiting': '결제 전파됨',
  'account.deposit_status_pay_confirming': '결제 확인 중',
  'account.deposit_tips_block': '블록 포함 대기 중',
  'account.deposit_status_pay_btn': '결제',
  'account.pay_deposit_warning':
    '자금 추가 시 추가 가스비가 발생할 수 있습니다.',
  'account.pay_deposit_warning_tips':
    'DeGate의 보조금이 모두 소진되어 자금 추가에 대한 비용을 사용자가 부담해야 할 수 있습니다.',
  'account.deposit_pending_tips':
    '5분 이상 대기 중인 경우 지갑에서 거래 속도를 높이세요.',
  'account.deposit_pending_tips_ledger':
    '5분 이상 대기 중인 경우 거래 속도를 높이세요.',
  'account.deposit_contract_tips_over_AMOUNT':
    'AMOUNT USD를 초과하는 자금 추가는 고급 방법이 필요합니다.',
  'account.deposit_contract_tips_only_all':
    '고급 방법을 통한 자금 추가만 지원됩니다.',
  'account.suggest_100': '권장 금액 ≥ $100',
  'account.suggest_100_tips': '지정가 주문을 하려면 $100 이상을 권장합니다.',
  'account.deposit_failed': '실패',
  'account.deposit_failed_tips': '자금 추가를 위한 온체인 거래가 실패했습니다.',
  'account.payment_due': '결제 예정',
  'account.payment_due_tips':
    'DeGate 잔액에 자금을 추가하려면 추가 결제가 필요합니다.',
  'account.register_token_code_placeholder': '컨트랙트 주소 입력',
  'account.register_token_code': '컨트랙트 주소',
  'account.register_token_symbol': '기호',
  'account.register_token_check': '상장 진행 현황 확인',
  'account.register_token_code_err_added': '이 토큰이 상장되고 있습니다.',
  'account.register_token_next_step': '다음',
  'account.register_token_tips1':
    '온체인 토큰 상장을 위해 허가가 필요하지 않습니다. 바로 토큰을 상장하세요.',
  'account.register_token_btn': '토큰 상장',
  'account.list_token': '토큰 상장',
  'account.withdraw_warning_XXX':
    '수요 증가로 인해 현재 자금 전송에 약 ~ XXX가 소요됩니다.',
  'account.withdraw_status_pending': '처리 중',
  'account.tansferred_1_ETH': '1 ETH 전송됨',
  'account.transfer_status_sent': '보냄',
  'account.transfer_status_received': '받음',
  'account.th_me': '나',
  'account.th_tx_hash': '트랜잭션 해시',
  'account.th_time': '시간',
  'account.locked_order': '지정가 주문',
  Sending: '보내는 중',
  'account.locked_claimable': '청구 가능',
  'account.locked_grid': '그리드 전략',
  'account.personal_sign_reason': '다음과 같은 원인이 있을 수 있습니다.',
  'account.personal_sign_reason1': '1. MetaMask가 하드웨어 지갑에 연결됨',
  'account.personal_sign_reason2': '2. MetaMask 버전이 오래됨',
  'account.personal_sign_reason3': '3. 기타',
  'account.personal_sign_btn': '다시 서명',
  'account.deposit_arrive_in_30s': '약 ~30초 후 도착',
  'account.deposit_arrive_in_30s_s': '약 ~ 30초 후 도착',
  'account.account_completed_time_XXX': '~XXX 후 완료',
  'account.search_result_no_token': '토큰을 찾을 수 없음',
  'account.search_result_invalid_code': '잘못된 계약 주소',
  'account.search_result_not_listed':
    '이 토큰은 현재 DeGate에 상장되지 않았습니다.',
  'account.search_result_tips_register':
    '컨트랙트 주소를 입력하여 토큰 상장을 완료할 수 있습니다.',
  'account.search_result_not_find': '여전히 찾을 수 없나요?',
  'account.search_pair_tips3': '자산에 대한 거래 페어 없음',
  'account.search_pair_tips3_add': '페어를 추가하세요',
  'account.register_token': '비허가형 토큰 상장',
  'account.search_again': '다시 검색',
  'account.deposit_type': '방법',
  'account.deposit_type_standard': '표준',
  'account.switch_account_tips': '전환됨',
  'account.switch_account_tips_register': '먼저 초기화해 주세요.',
  'account.initialize_success': '초기화 성공',
  'account.approve': '승인',
  'account.reset_USDT': 'USDT 승인 재설정',
  'account.reset_USDT_tips':
    'USDT는 지출 한도가 낮을 때 승인 재설정이 필요합니다.',
  'account.next_step': '다음',
  'account.profit_total': '총 수익',
  'account.profit_history': '수익 기록',
  'account.tab_mining_rewards': '마이닝 보상',
  'account.yield_total': '총 수익률',
  'account.yield_24h': '24시간 수익률',
  claimable: '청구 가능',
  'account.yield_history': '수익률 기록',
  'account.total_grid_profit': '총 그리드 수익',
  'account.grid_strategies': '그리드 전략',
  'account.total_rewards': '총 보상',
  'account.rewards_24h': '24시간 보상',
  'account.rewards': '보상',
  'menu.register_err':
    '귀하의 주소에 블록체인 거래 기록이 없습니다. 온체인 거래를 완료하고 다시 시도하세요. 예를 들어, 토큰을 지갑으로 전송하세요.',
  'menu.reset_post_success_withOrders':
    'Asset Key 초기화가 시작되었습니다. 모든 미체결 주문 및 그리드 전략이 취소되었습니다.',
  'menu.reset_post_success': 'Asset Key 초기화가 시작되었습니다.',
  'menu.reset_processing_title': 'Asset Key 초기화 진행 중',
  'menu.reset_processing_desc': '완료될 때까지 기다려 주세요',
  'trade.choose_token': '토큰 선택',
  'trade.token_info': '토큰 정보',
  'trade.token_address': '토큰 주소',
  'trade.price_range_24h': '24시간 가격 범위',
  'trade.vol_24h': '24시간 거래량',
  'trade.item_price_TOKEN': '가격 (토큰)',
  'trade.item_amount_TOKEN': '수량 (토큰)',
  'trade.order_book_title': '호가',
  'trade.order_book_total': '총액',
  latest_trades: '체결',
  'trade.trade_history_time': '시간',
  'trade.market_placeholder_price': '시장가',
  'trade.what_is_stop_limit': '예약 지정가란?',
  'trade.what_is_stop_limit_link': '예약 지정가란? >',
  'trade.placeholder_total': '총액',
  'trade.more_settings': '설정',
  'trade.expire_in_tips': '주문은 만료 후 자동으로 취소됩니다.',
  'trade.period_day_s': '일',
  'trade.period_hour_s': '시간',
  'trade.period_minute_s': '분',
  'trade.period_err_input_tips': '유효한 숫자를 입력하세요',
  'trade.post_only_label': '메이커 전용',
  'trade.post_only_tips':
    '메이커 전용 모드는 오직 메이커 주문만 오더북에 진입할 수 있도록 보장합니다. 주문의 일부가 테이커 주문으로 체결될 수 있다면, 전체 주문이 반환됩니다. 메이커 전용 모드의 주문은 가스비나 거래 수수료가 없습니다.',
  'trade.post_only_fail_title': '주문을 생성할 수 없음',
  'trade.post_only_fail_desc':
    '가격을 조정하거나 "메이커 전용" 모드를 비활성화하세요.',
  'trade.max_gas_fee_tips':
    '최대 가스비는 온체인 거래 결제 비용을 커버하며, 테이커가 지불하고 메이커는 무료입니다. 초과 수수료는 환불됩니다.',
  'trade.auto': '자동',
  'trade.custom': '사용자 지정',
  'trade.enough_for_XX_trades': 'XX 거래에 충분함',
  'trade.gas_fee_per_trade': '거래당 가스비',
  'trade.gas_fee_per_trade_tips':
    '테이커는 온체인 결제를 촉진하기 위해 거래당 가스비를 부담하며, 비용은 이더리움 네트워크 상태에 따라 변동합니다.',
  'trade.max_number_of_trades': '최대 거래 수',
  'trade.btn_buy_ETH': 'ETH 매수',
  'trade.btn_sell_ETH': 'ETH 매도',
  'trade.max_buy_fee_deducted_NUM': '가스비 차감됨. 최대는 NUM입니다.',
  'trade.notification_limit_order_title': '지정가 주문이 배치되었습니다',
  'trade.notification_stop_limit_order_title':
    '예약 지정가 주문이 배치되었습니다',
  'trade.err_price': '가격을 입력하세요',
  'trade.err_amount_total': '금액 또는 총액을 입력하세요',
  'trade.err_amount': '금액을 입력하세요',
  insufficientFee_gas_fee: '가스비 부족',
  'trade.err_insufficientFee_desc':
    '최대 가스비 설정과 DeGate 잔액을 확인하세요.',
  'trade.cancel_order_success': '주문 취소됨',
  'trade.pair_favorite': '즐겨찾기',
  'trade.pair_search': '토큰, 컨트랙트 주소 검색',
  'trade.pair_last_price': '가격',
  'trade.pair_change': '변동',
  'trade.url_parse_err_title': '이 페어는 존재하지 않습니다.',
  'trade.risk_tips': '위험 경고',
  'trade.base_is_not_default_token_tips':
    '사기 방지를 위해 거래 전 공식 출처를 통해 토큰 컨트랙트 주소를 확인하세요.',
  'trade.chain_cancel': '온체인 주문 취소',
  'trade.chain_cancel_no_need_tips':
    '이 주문은 온체인 취소가 필요하지 않습니다.',
  'trade.chain_cancel_success': '요청이 전송되었습니다.',
  'trade.depth_empty': '아직 주문이 없습니다.',
  'trade.depth_empty_asks': '매도 주문 없음',
  'trade.depth_empty_bids': '매수 주문 없음',
  'trade.depth_empty_tips':
    '오더북의 미체결 주문 부족으로 인해 시장가 주문이 실패했습니다.',
  'trade.history_empty': '아직 거래가 없습니다.',
  'trade.err_price_stable': '가격이 유효하지 않습니다. 다시 시도하세요.',
  'trade.price_warning':
    '입력한 가격이 시장가와 편차가 있습니다. 주문을 배치하기 전에 확인해 주세요.',
  'trade.order_value_tips':
    '최소 주문 금액은 <b>QUOTE_A</b> 또는 <b>BASE_A</b>이며, MINUSD USD에 해당합니다. 이 제한을 우회하려면 시장가 주문을 사용하세요.',
  'trade.order_value_tips_quote':
    '최소 주문 금액은 <b>QUOTE_A</b>이며, MINUSD USD에 해당합니다. 이 제한을 우회하려면 시장가 주문을 사용하세요.',
  'trade.order_value_tips_stable_quote':
    '최소 주문 금액은 <b>QUOTE_A</b>입니다. 이 제한을 우회하려면 시장가 주문을 사용하세요.',
  'trade.system_limit': '시스템 한도 초과',
  'trade.stop_limit_untriggered_tips':
    '예약 가격에 도달하지 않아 오더북에 제출되지 않았습니다.',
  'trade.stop_limit_triggered_tips_TIME':
    '예약 가격에 도달하여 TIME에 오더북에 제출되었습니다.',
  'trade.flow_of_funds': '자금 흐름',
  'trade.flow_of_funds_tip2':
    '주문이 배치되었습니다. 주문 자금은 지갑 잔액 대신 DeGate 잔액으로 이동합니다.',
  'orders.show_current_pair_orders': '다른 페어 숨기기',
  'orders.orderHistory': '주문 내역',
  'orders.th_time': '시간',
  'orders.th_average_price': '평균 가격',
  'orders.th_stop_price': '예약 가격',
  'orders.th_limit_price': '지정가',
  'orders.th_filled_price': '가격',
  'orders.th_filled_amount': '체결',
  'orders.th_filled_total': '총액',
  'orders.th_trade_reconciliation': '조정',
  'orders.th_trade_reconciliation_tips':
    'DeGate와 온체인 정산에 사용된 다른 계산 모델로 인해 두 계산 결과에 약간의 차이가 발생할 수 있습니다. 이 경우 시스템은 온체인 값을 표준으로 사용하여 DeGate 잔액에서 부족분을 보충합니다.',
  'orders.hide_cancelled_expired_orders': '취소/만료 숨기기',
  'orders.status_open': '미체결',
  'orders.status_pending': '대기 중',
  'orders.status_completed': '체결됨',
  'orders.status_completed_part': '일부 체결됨',
  'orders.status_expired': '만료됨',
  'orders.detail_price': '평균/가격',
  'orders.average_price': '평균 가격',
  'orders.detail_type': '주문 유형',
  'orders.detail_trade_fee': '거래 수수료:',
  'orders.gas_preAuth': '최대 가스비:',
  'orders.fee_reconciliation': '조정:',
  'orders.gas_paid': '지불된 가스비:',
  'orders.gas': '가스비:',
  'orders.trades_N': '체결(N)',
  'orders.detail_filled_total': '총액',
  'orders.detail_filled_detail': '거래 세부 정보',
  'orders.detail_filled_time': '시간',
  'orders.order_maker_free': '메이커 수수료 무료',
  'orders.openOrders_empty': '미체결 주문 없음',
  'orders.export_orders_1_year': '최근 1년의 주문 데이터를 내보냅니다.',
  'orders.export_trades_1_year': '최근 1년의 거래 데이터를 내보냅니다.',
  'orders.export_data': '데이터 내보내기',
  'orders.export': '내보내기',
  'orders.export_processing': '처리 중입니다. 잠시 기다려 주세요.',
  'orders.export_tips_100_percent':
    '진행률이 100%에 도달하면 파일이 다운로드됩니다.',
  'orders.sign_to_view_balance': '잔액 보기 서명',
  'orders.sign_to_view_history': '기록 보기 서명',
  'orders.sign_to_view_security_options': '보안 옵션 보기 서명',
  'gridTrade.automatic_strategy': '자동',
  'gridTrade.manual_strategy': '수동',
  'gridTrade.placeholder_amount': '금액 입력',
  'gridTrade.low_price': '하한',
  'gridTrade.high_price': '상한',
  'gridTrade.initial_investment': '투자',
  'gridTrade.grid_levels_tips':
    '가격 범위 내 미체결 주문 수를 결정하는 데 사용됩니다.',
  'gridTrade.profit_per_grid': '그리드당 수익',
  'gridTrade.profit_per_grid_tips':
    '그리드 전략의 수익성에 중요한 매개변수입니다. 그리드당 수익 = (상한 가격 - 하한 가격) / 하한 가격. 상한 및 하한 가격은 그리드 전략 내의 인접한 두 그리드 라인의 가격을 나타냅니다.',
  'gridTrade.min_grid_volume_XXX_ETH': '그리드당 금액: 최소 XXX ETH',
  'gridTrade.min_grid_volume_err':
    '투자금 증액 또는 그리드 수 감소가 필요합니다',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    '오더북에 주문이 부족하여 이 페어에 대해 그리드 전략을 생성할 수 없습니다.',
  'gridTrade.grid_to_spot_trade': 'SPOT으로 이동',
  'gridTrade.grid_level_over_err': '그리드 수를 줄이세요',
  'gridTrade.grid_prices_err': '가격 범위를 확장하세요',
  'gridTrade.grid_create_err': '매개변수를 조정하고 다시 시도해 주세요.',
  'gridTrade.tips_grid_profit':
    '수익은 DeGate 잔액에 직접 적립되며 즉시 사용할 수 있습니다.',
  'gridTrade.tips_grid_balance_0_BASE':
    '시장가 상승으로 인해 모든 그리드 전략 주문이 매수 주문으로 변환되었습니다. 따라서 현재 BASE 잔액은 0입니다.',
  'gridTrade.tips_grid_balance_0_BASE_2':
    '시장가 상승으로 인해 모든 그리드 전략 주문이 매수 주문으로 변환되었으며, 일부 주문은 부분적으로 체결되었습니다. 따라서 현재 BASE 잔액은 0 이상입니다.',
  'gridTrade.tips_grid_balance_0_QUOTE':
    '시장가 하락으로 인해 모든 그리드 전략 주문이 매도 주문으로 변환되었습니다. 따라서 현재 QUOTE 잔액은 0입니다.',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    '시장가 하락으로 인해 모든 그리드 전략 주문이 매도 주문으로 변환되었으며, 일부 주문은 부분적으로 체결되었습니다. 따라서 현재 QUOTE 잔액은 0 이상입니다.',
  'gridTrade.grid_param_err': '그리드 전략 매개변수를 입력하세요',
  'gridTrade.tv_buy': '매수',
  'gridTrade.tv_sell': '매도',
  'gridTrade.tv_waiting': '대기 중',
  'gridTrade.chain_cancel_no_need_tips':
    '이 그리드 전략은 온체인 취소가 필요하지 않습니다.',
  'gridTrade.grid_over_max_number_err':
    '실행 중인 최대 그리드 전략 수에 도달하여 새 그리드를 생성할 수 없습니다.',
  'gridTrade.preview_orders_in_graph': '주문 표시',
  'gridTrade.greate_news': '좋은 소식:',
  'gridTrade.min_amount_required_XXX': '최소 XXX 필요',
  'gridTrade.highest_grid_apy': '최고 그리드 APY',
  'gridTrade.for_the_last_7_days': '최근 7일 동안',
  'gridTrade.min_investment': '최소 투자',
  'gridTrade.grid_need_XXX': '$XXX로 그리드',
  'gridTrade.mining_need_XXX': '$XXX로 채굴',
  'gridTrade.recommended_params_cannot_be_applied':
    '추천 매개변수를 적용할 수 없습니다. 수동 모드에서 조정하세요.',
  'gridTrade.copy_params_to_manual': '매개변수를 수동 모드로 복사',
  'gridOrders.grid_recents': '내 최신 거래',
  'gridOrders.th_created_time': '생성 시간',
  'gridOrders.grid_profit': '그리드 수익',
  'gridOrders.grid_cancel': '종료',
  open_orders: '미체결 주문',
  'gridOrders.tab_history_orders': '체결된 주문',
  'gridOrders.tab_trade_history': '거래 내역',
  'gridOrders.detail_current_balance': '현재 잔액',
  'gridOrders.detail_ending_balance': '종료 잔액',
  'gridOrders.detail_ending_balance_tips':
    '그리드 전략이 종료될 때의 자산 잔액',
  'gridOrders.detail_in_order_funds': '주문에 사용 중인 자금:',
  'gridOrders.detail_on_hold_funds': '부분 체결된 주문에서 보류 중인 자금:',
  'gridOrders.detail_transactions': '체결된 주문 수',
  'gridOrders.detail_investment': '초기 투자',
  'gridOrders.detail_running_time': '기간',
  'gridOrders.detail_prices': '가격 범위',
  number_of_grids: '그리드 수',
  'gridOrders.detail_expire_time': '만료',
  'gridOrders.detail_expire_time_tooltip':
    '그리드 전략 내 주문은 만료 시 자동으로 취소됩니다.',
  'gridOrders.detail_valid_period': '만료 설정',
  'gridOrders.open_orders_sell': '매도',
  'gridOrders.open_orders_buy': '매수',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': '총액',
  'gridOrders.history_orders_filled': '체결:',
  'gridOrders.history_orders_price': '가격:',
  'gridOrders.history_orders_time': '시간',
  'gridOrders.history_orders_filled_price': '평균 가격',
  'gridOrders.history_orders_filled_amount': '체결',
  'gridOrders.history_orders_filled_total': '총액',
  'gridOrders.history_orders_profit_tips':
    '수익은 저가 매수 후 고가 매도의 사이클을 통해 얻어집니다. 예를 들어, 1 ETH를 4000 USDC에 매수한 그리드 주문이 체결되면, 그리드 간격이 50 USDC일 때 시스템은 자동으로 4050 USDC에 1 ETH 매도 주문을 설정합니다. 이 주문이 체결되면 50 USDC의 수익이 발생합니다.',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    '매수가격 {PRICE}의 주문이 체결된 후 수익이 표시됩니다.',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    '매도가격 {PRICE}의 주문이 체결된 후 수익이 표시됩니다.',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    '가격 {PRICE}의 주문이 체결되면 여기에 표시됩니다',
  'gridOrders.grid_cancel_title': '그리드 전략 종료',
  'gridOrders.grid_cancel_content':
    '이 그리드 전략의 모든 주문이 즉시 취소됩니다.',
  'gridOrders.grid_cancel_content2':
    '현재 이 그리드 전략으로 채굴 중입니다. 이 전략을 종료하면 모든 채굴 보상이 상실되며 관련된 모든 그리드 주문이 즉시 취소됩니다.',
  'gridOrders.copy_grid_title': '다음 그리드 전략 매개변수가 복사됩니다',
  'gridOrders.copy_grid_btn': '패널로 복사',
  'gridOrders.copy_grid_success': '그리드 전략이 복사되었습니다',
  'gridOrders.grid_init_funds_XXX': '초기 투자 가치: $XXX',
  'gridOrders.grid_init_funds_tips':
    'APY는 그리드 전략 생성 시점의 초기 배분 가치를 기준으로 계산됩니다.',
  'gridOrders.tab_m_trade': '거래',
  grid_apy: '그리드 APY',
  grid_apy_tips: '오직 그리드 거래만으로 연간 수익률. 미실현 이익 제외.',
  'gridOrders.tab_mining_profit': '채굴 APY',
  'gridOrders.tab_mining_profit_tips':
    '채굴 보상과 채굴 TVL을 기준으로 계산된 연간 수익률.',
  'gridOrders.mining_rewards': '보상:',
  'gridOrders.open_orders_empty_tips': '데이터 로드 중입니다.',
  'gridOrders.market_value': '시장 가치:',
  'gridOrders.market_value_details': '세부 정보',
  'gridOrders.fund_details': '자금 세부 사항',
  'gridOrders.m_in_order_funds': '주문에 사용 중인 자금',
  'gridOrders.m_in_order_funds_tips':
    '이 그리드 전략의 모든 미체결 주문의 총 자금',
  'gridOrders.m_on_hold_funds': '보류 중 자금',
  'gridOrders.m_on_hold_funds_tips': '부분 체결된 주문의 결과',
  'gridOrders.initial_value': '초기 가치',
  'mining.my_title': '내 채굴 풀',
  'mining.index_desc':
    '그리드 전략 생성. 유동성 채굴 보상으로 그리드 수익을 높이세요.',
  'mining.apply': '새 풀 신청',
  'mining.claimable_rewards_box': '청구 가능한 보상',
  'mining.rewards_more': '및 기타',
  'mining.tab_pools': '채굴 풀',
  'mining.tab_my': '내 채굴 통계',
  'mining.pools_tab_live': '실시간',
  'mining.pools_tab_upcoming': '예정됨',
  'mining.pools_funds': '총 TVL',
  'mining.pools_funds_tips':
    '최소 주문 가치 $120을 충족하는 모든 그리드 주문의 총 가치',
  'mining.pools_mining_funds': '채굴 TVL',
  'mining.mining_apr': 'APY',
  'mining.mining_apr_tips':
    '채굴 보상과 채굴 TVL을 기준으로 계산된 연간 수익률',
  'mining.view_rule_link': '채굴 규칙',
  'mining.pools_info_to_confirm': '추후 결정됨',
  'mining.pools_no_wait': '사용 가능한 채굴 풀이 없습니다',
  'mining.my_mining_funds': '내 채굴 자금',
  'mining.my_mining_rewards': '내 채굴 보상',
  'mining.my_th_profit_token_price': '최신 가격',
  'mining.my_th_total_rewards': '역대 보상',
  'mining.my_th_24h_rewards': '24시간 보상',
  'mining.my_grids': '내 채굴',
  'mining.only_show_mining_grids': '활성 상태만',
  'mining.my_th_mining_status': '채굴 상태',
  'mining.status_framing': '활성',
  'mining.status_over_price': '가격 범위 초과',
  'mining.status_mining_over': '채굴 종료',
  'mining.status_grid_closed': '전략 종료',
  'mining.status_grid_expired': '전략 만료',
  'mining.empty_no_faring_grids': '현재 채굴 가능한 그리드 전략 없음',
  'mining.go_mining_pool': '채굴 풀로 이동',
  'mining.go_mining': '채굴 시작',
  'mining.go_to_grid': '그리드 전략으로 이동',
  'mining.mining_help': '채굴 가이드',
  'mining.mining_available': '자격 있음',
  'mining.mining_available_tips': '주문 가치 기준 충족',
  'mining.mining_unavailable': '자격 없음',
  'mining.mining_partially_available': '부분 자격 있음',
  'mining.mining_unavailable_tips': '주문 가치 기준 미충족',
  'mining.mining_preview': '채굴 미리보기',
  'mining.mining_total_profit': '채굴 보상',
  'mining.mining_24h_profit': '24시간 채굴 보상',
  'mining.profit_unable_display': 'N/A',
  'mining.mining_funds': '채굴 자금',
  'mining.mining_funds_tips':
    '이 거래 페어에 대한 채굴 주문 가치 기준을 충족하는 모든 그리드 전략의 총 주문 가치',
  'mining.tab_mining_profit_details': '보상 세부 사항',
  'mining.tab_mining_orders': '채굴 주문',
  'mining.th_rewards': '보상',
  'mining.th_rewards_origin': '보상 출처',
  'mining.th_rewards_origin_tips':
    '채굴 보상은 그리드 주문 가격이 오더북의 보상 가격 범위 (최고 매수가 * 0.99 ~ 최저 매도가 * 1.01) 내에 있을 때 제공됩니다.',
  'mining.th_rewards_origin_tips_stable':
    '채굴 보상은 그리드 주문 가격이 오더북의 보상 가격 범위 (최고 매수가 ~ 최저 매도가) 내에 있을 때 제공됩니다.',
  'mining.th_time': '시간',
  'mining.plan_title': 'ETH/USDC 풀 세부 사항',
  'mining.phase_cur': '현재 단계',
  'mining.phase_range_N_XX': '단계 N (XX)',
  'mining.phase_index_N': '단계 N',
  'mining.phase_reward': '일일 보상',
  'mining.phase_to_release': '추후 공지',
  'mining.my_rewards': '내 보상',
  'mining.claimable_rewards': '사용 가능',
  'mining.locked_rewards': '잠김',
  'mining.locker_rewards_tips':
    '그리드 전략이 12시간 동안 활성 상태인 후에만 채굴 보상을 청구할 수 있습니다.',
  'mining.claimed_success': '청구 성공',
  'mining.claimed_tips': '내부 전송을 통해 곧 전송됩니다',
  'mining.claimed_view_btn': '확인해 보세요',
  'mining.mining_plan': '채굴 일정',
  'mining.phase_unpublished': '추후 공지',
  'mining.all_pools': '모든 풀',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    'AMOUNT BASE @ PRICE QUOTE 매도',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    'AMOUNT BASE @ PRICE QUOTE 매수',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': 'AMOUNT BASE 매도',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': 'AMOUNT BASE 매수',
  'notification.cancel_grid_desc_PAIR_PRICES': 'PAIR: PRICES',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT': 'QUOTE로 BASE 매도',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    'TOTAL QUOTE로 BASE 매도',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT': 'QUOTE로 BASE 매수',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    'TOTAL QUOTE로 BASE 매수',
  'notification.cancel_limit': '지정가 주문 취소됨',
  'notification.cancel_stop_limit': '예약-지정가 주문 취소됨',
  'notification.cancel_market': '시장가 주문 취소됨',
  'notification.cancel_grid': '그리드 전략 종료됨',
  'notification.cancel_limit_expired': '지정가 주문 만료됨',
  'notification.cancel_stop_limit_expired': '예약-지정가 주문 만료됨',
  'notification.cancel_grid_expired': '그리드 전략 만료됨',
  'notification.cancel_limit_order_for_gas_desc':
    '가스비 부족으로 주문이 부분 체결된 상태에서 나머지는 취소되었습니다.',
  'notification.cancel_limit_order_for_gas_filled_amount': '체결됨',
  'notification.cancel_limit_order_for_gas_amount': '수량',
  'notification.view_history_orders': '주문 내역 보기',
  'notification.cancel_market_for_depth_title': '주문 부분 체결 및 취소됨',
  'notification.price_slippage_protection': '가격 슬리피지 보호',
  'notification.price_slippage_protection_desc':
    'DeGate 시장 주문은 높은 변동성과 낮은 유동성 상황에서 손실을 제한하기 위해 10%의 가격 슬리피지 보호를 자동으로 포함합니다. 이 보호를 우회하려면 지정가 주문을 사용하세요.',
  'notification.cancel_market_for_depth_warning':
    'DeGate 시장 주문은 가격 보호 메커니즘을 도입하여 높은 변동성과 낮은 유동성 상황에서 손실을 줄일 수 있습니다. 이 메커니즘을 사용하지 않으려면 지정가 주문 모드를 사용하세요.',
  'notification.dca_plan_ended': 'DCA 계획 종료',
  'notification.cancel_dca_desc_PAIR': 'PAIR',
  'notification.trade_limit_partially': '지정가 주문 부분 체결',
  'notification.trade_limit_filled': '지정가 주문 체결',
  'notification.trade_market_partially': '시장가 주문 부분 체결',
  'notification.trade_market_filled': '시장가 주문 체결',
  'notification.trade_stop_limit_partially': '예약-지정가 주문 부분 체결',
  'notification.trade_stop_limit_filled': '예약-지정가 주문 체결',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    '주문 체결. AMOUNT TOKEN 수령됨.',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    '주문 부분 체결. AMOUNT TOKEN 수령됨.',
  'info.overview': '개요',
  'info.accounts': '총 사용자',
  'info.pairs': '거래 페어',
  'info.turnover': '전체 거래량',
  'info.turnover_24': '24시간 거래량',
  'info.dg_supply': 'DG 유통 공급량',
  'info.top_movers_no_increased': '지난 24시간 동안 가격이 상승한 토큰 없음',
  'info.top_movers_no_decreased': '지난 24시간 동안 가격이 하락한 토큰 없음',
  'info.top_pairs': '상위 페어',
  Pair: '페어',
  'info.th_change': '24시간 변동',
  'info.th_l_up_2': '+2% 뎁스',
  'info.th_l_down_2': '-2% 뎁스',
  'info.th_turnover_24': '24시간 거래량',
  'info.tvl': 'Total Value Locked',
  'm.home': '홈',
  'm.grid': '그리드',
  'm.browser_wallet': '브라우저 지갑',
  'm.choose_pair': '페어 선택',
  'm.orderBook_default': '기본값',
  'm.orderBook_bids': '매수 주문',
  'm.orderBook_asks': '매도 주문',
  'm.decimals': '소수점',
  'm.lowest_price_24h': '24시간 최저가',
  'm.highest_price_24h': '24시간 최고가',
  'm.vol_24h': '24시간 거래량',
  'm.orderbook_buy': '매수',
  'm.orderbook_sell': '매도',
  'm.go_to_trade': '거래로 이동',
  'm.choose_token': '토큰 선택',
  'm.from_address': '발신자 주소',
  'm.to_address': '수신자 주소',
  'm.transfer_send': '보내기',
  'm.transfer_receive': '받기',
  'm.my_grid': '내 그리드 전략',
  'm.grid_profit_24': '24시간 수익',
  trades_24h: '24시간 거래 수',
  'm.grid_profit_total': '총 수익',
  'm.grid_over_prices': '가격 범위 초과',
  'm.create_grid': '그리드 전략 생성',
  'm.grid_history': '내역',
  'm.grid_empty': '활성 그리드 전략 없음',
  'm.grid_tutorial': '그리드 튜토리얼',
  'm.grid_params_to_manual': '매개변수를 수동설정으로 복사',
  'm.balance_err': '잔액 부족. 사용 가능:',
  'm.preview_grid': '주문 미리보기',
  last_price: '마지막 가격',
  'm.grid_desc':
    '그리드 거래는 정해진 범위 내에서 자동으로 매수 및 매도하는 거래 전략입니다.',
  'm.view_tutorial': '튜토리얼 보기',
  'm.grid_profit_tips_sell': '이 매도 주문이 완전히 체결되면 계산됩니다.',
  'm.grid_profit_tips_buy': '이 매수 주문이 완전히 체결되면 계산됩니다.',
  'm.hot': '인기',
  'm.all': '모두 보기',
  'm.vol_24': '24시간 거래량',
  'm.transfer_t1': '내부',
  'm.transfer_t2': '전송',
  'activity.th_date': '시간',
  'activity.th_type': '유형',
  'activity.th_fee': '수수료',
  'activity.th_content': '내용',
  'activity.type_register_token': '토큰 상장',
  'activity.type_register_pair': '페어 추가',
  'activity.type_pay_deposit': '입금 정산',
  'activity.type_reset_account': 'Asset Key 재설정',
  on_chain_order_cancellation: '온체인 주문 취소',
  'activity.count_N': '개수: N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    'AMOUNT BASE @PRICE QUOTE 매도',
  'activity.order_market_desc_SELL_AMOUNT_BASE': 'AMOUNT BASE 매도',
  'activity.reset_status_restting': '재설정 중',
  'activity.to_trade': '거래',
  'dca.dca_plan': 'DCA 플랜',
  'dca.dca_explain': '달러 비용 평균법',
  'dca.daily': '매일',
  'dca.weekly': '매주',
  'dca.custom': '사용자 지정',
  'dca.every': '매번',
  'dca.amount_per_order': '주문당 금액',
  'dca.price_limit': '가격 제한',
  'dca.maximum_price': '최대 가격',
  'dca.minimum_price': '최소 가격',
  'dca.number_of_orders': '주문 개수',
  'dca.create_dca_plan': 'DCA 플랜 생성',
  'dca.max_gas_fee_per_order': '주문당 최대 가스비',
  'dca.maximum_plan_order_limit_reached': '최대 계획 주문 개수에 도달했습니다.',
  'dca.end_time_should_be_set_after_the_current_time':
    '종료 시간은 현재 시간 이후로 설정되어야 합니다.',
  'dca.please_enter_amount_per_order': '주문당 금액을 입력하세요',
  'dca.please_enter_maximum_price': '최대 가격을 입력하세요',
  'dca.please_enter_minimum_price': '최소 가격을 입력하세요',
  'dca.order_placement_failed_open_order_limit_exceeded':
    '주문 배치 실패: 미체결 주문 한도 초과.',
  'dca.total': '총 금액',
  'dca.filled': '체결된 금액',
  'dca.received': '수령',
  'dca.time_to_end': '종료까지 남은 시간',
  'dca.cancel_on_chain': '온체인 취소',
  'dca.filled_amount': '체결/금액',
  'dca.status_executed': '실행됨',
  'dca.status_scheduled': '예정됨',
  'dca.status_failed': '실패',
  'dca.order_cancled_by_user':
    '사용자가 DCA 플랜을 종료했기 때문에 주문이 취소되었습니다.',
  'dca.order_cancled_by_access':
    'DeGate로의 액세스가 제한되어 주문이 취소되었습니다.',
  'dca.order_cancled_by_gas': '가스비 부족으로 주문 배치 실패',
  'dca.order_cancled_by_order_book':
    '오더북에 일치하는 주문이 없어 주문 배치 실패',
  'dca.order_cancled_by_balance': 'DeGate 잔액이 부족하여 주문 배치 실패',
  'dca.order_cancled_by_min_value':
    '최소 주문 가치 $100 미만으로 주문 배치 실패',
  'dca.order_cancled_by_system_error': '시스템 오류로 주문 배치 실패',
  'dca.chain_cancel_no_need_tips':
    '이 DCA 플랜은 온체인 취소가 필요하지 않습니다.',
  'dca.end_dca_plan': 'DCA 플랜 종료',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    '이 DCA 플랜의 모든 주문이 즉시 취소됩니다.',
  'dca.no_active_dca_plan': '활성 DCA 플랜 없음',
  'dca.time_scheduled': '예정 시간',
  'campaign.event_period': '이벤트 기간:',
  'campaign.grid2401_time':
    '2024년 1월 22일 20:00:00 - 2024년 1월 29일 20:00:00 (UTC+8)',
  'campaign.event_has_ended': '이벤트 종료됨',
  'campaign.current_apy': '현재 연간 수익률 (APY)',
  'campaign.grid_strategy_income': '그리드 전략 수익 + 상금 풀 배당',
  'campaign.tvl_participating': '참여 중인 TVL',
  'campaign.share_of_tvl': 'TVL 배당',
  'campaign.my_profit': '내 수익',
  'campaign.grid_strategy_profit': '그리드 전략 수익',
  'campaign.share_of_prize_pool': '상금 풀 배당',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    '그리드 전략 수익이 사용 가능한 잔액에 추가되었습니다.',
  'campaign.shared_income_from_usdc_prize_pool': 'USDC 상금 풀에서 공유된 수익',
  'campaign.is_black_tips': '상금 풀 배당 자격 없음',
  'campaign.calculating': '계산 중',
  'campaign.claim_after_end': '이벤트 종료 후 상금을 청구할 수 있습니다.',
  'campaign.how_to_participate': '참여 방법',
  'campaign.rule': '그리드 전략을 생성하여 상금 풀에서 비례적으로 배당 받기.',
  'campaign.step1': '1단계',
  'campaign.step2': '2단계',
  'campaign.step3': '3단계',
  'campaign.grid2401_step1':
    '자금 추가 또는 거래를 통해 ETH와 USDC를 준비하세요.',
  'campaign.grid2401_step2_PAIR': '아래와 같이 PAIR의 그리드 전략을 설정하세요',
  'campaign.grid2401_step2_desc1_pre': '가격 범위: 추후 공지',
  'campaign.grid2401_step2_desc2_pre': '그리드 개수: 추후 공지',
  'campaign.copy_strategy': '전략 복사',
  'campaign.grid2401_step3':
    '이벤트 종료 후, 이 이벤트 페이지에서 수익을 청구할 수 있습니다. 종료 후 30일 이내에 청구하세요.',
  'campaign.what_is_grid': '그리드 전략이란?',
  'campaign.notes': '참여 전에 주의하세요',
  'campaign.notes_1_title': '자격:',
  'campaign.notes_1_desc':
    '그리드 전략은 생성 시 가격 범위와 그리드 수가 정확히 요구된 조건과 일치해야만 유효합니다.',
  'campaign.notes_2_title': '한도:',
  'campaign.notes_3_title': '청구:',
  'campaign.notes_3_desc':
    '이벤트 종료 후 상금 청구가 가능하며, 종료 후 30일 이내에 유효합니다.',
  'campaign.faq': 'FAQ',
  'campaign.grid2401_faq_1': '1. 보상은 어떻게 계산되나요?',
  'campaign.grid2401_faq_2':
    '2. 이벤트에 대해 어디에서 질문하고 도움 받을 수 있나요?',
  'campaign.grid2401_faq_3':
    '3. USDT를 보유하고 있는데, 어떻게 ETH와 USDC를 얻을 수 있나요?',
  'campaign.grid2401_faq_4':
    '4. 그리드 전략을 통해 완료된 거래에 수수료가 발생하나요?',
  'campaign.grid2401_faq_4_res':
    'DeGate에서는 모든 메이커 주문이 무료입니다. 그리드 전략에 의해 생성된 주문은 모두 메이커 주문이므로, DeGate에서 그리드 전략을 설정하는 것은 완전히 무료입니다.',
  'campaign.grid2401_faq_5':
    '5. 이벤트가 종료된 후에도 그리드 전략이 계속 수익을 창출하나요?',
  'campaign.grid2401_faq_5_res':
    '네, 이벤트가 종료된 후에도 가격이 여전히 그리드 전략 범위 내에 있으면 해당 그리드 전략은 계속해서 수익을 창출합니다. 이벤트가 끝난 후에도 그리드 전략의 매개변수를 조정하여 자신의 선호에 맞춘 전략을 생성하고 계속해서 수익을 얻을 수 있습니다.',
  'campaign.grid2401_faq_others': '다른 이벤트 세부사항',
  'campaign.grid2401_faq_others_1':
    '사용자당 하나의 지갑만 허용됩니다. 부정한 방법으로 보상을 습득하는 행위가 감지되면 DeGate는 참가자의 보상을 취소할 권리를 보유합니다.',
  'campaign.grid2401_faq_others_2':
    '이벤트 기간 동안 범위를 벗어난 그리드도 가중치 계산의 일부로 간주됩니다.',
  'campaign.grid2401_faq_others_3':
    '극단적인 상황(예: 시장 변동성)에서 DeGate는 이벤트를 조기 종료할 권리를 보유합니다.',
  'campaign.grid2401_faq_others_4':
    '이벤트 종료 후 30일 이내에 청구되지 않은 보상은 몰수됩니다.',
  'campaign.invest_max_5000': '최대 $5000 투자',
  'campaign.invest_mininum': '최소 투자',
  'airdrop.create_airdrop': '에어드랍 생성',
  'airdrop.important_note':
    '중요: 누구나 에어드랍을 생성할 수 있으며 허가가 필요 없습니다.',
  'airdrop.my_airdrop': '내 에어드랍',
  'airdrop.time_limited': '시간 제한',
  'airdrop.no_airdrop': '에어드랍 없음',
  'airdrop.claim_airdrop': '에어드랍 청구',
  'airdrop.recipients_number': '수신자 수',
  'airdrop.total_amount': '총 금액',
  'airdrop.retrieve': '회수',
  Unclaimed: '미청구',
  'airdrop.retrieve_successful': '회수 성공',
  'airdrop.claim_successful': '청구 성공',
  'airdrop.retrieve_unclaimed_airdrop': '미청구된 에어드랍 회수',
  'airdrop.airdrop_token': '에어드랍 토큰',
  'airdrop.token_not_meet_criteria':
    '이 토큰은 에어드랍 기준을 충족하지 않습니다.',
  'airdrop.airdrop_list': '에어드랍 목록',
  'airdrop.download_template': '템플릿 다운로드',
  'airdrop.click_or_drag_upload_list': '클릭하거나 드래그하여 목록 업로드',
  'airdrop.validation_passed': '검증됨',
  'airdrop.must_earlier_than_end_time': '종료 시간 이전이어야 합니다.',
  'airdrop.cannot_more_than_2_years_from_now':
    '현재로부터 2년을 초과할 수 없습니다.',
  'airdrop.cannot_parse_file':
    '파일을 구문 분석할 수 없습니다. 템플릿을 사용하세요.',
  'airdrop.format_requirement_not_met': '형식 요구사항이 충족되지 않음',
  'airdrop.view_error_repost': '오류 보고서 보기',
  'airdrop.error_report': '오류 보고서',
  'airdrop.line': '라인',
  'airdrop.reason': '이유',
  'airdrop.duplicated_address': '중복된 주소',
  incorrect_address_format: '잘못된 주소 형식',
  'airdrop.incorrect_amount_format': '잘못된 금액 형식',
  'airdrop.airdrop_plan_created': '에어드랍 계획 생성됨',
  'airdrop.max_50000': '최대 50000개 주소',
  'airdrop.upload_file_rule': 'CSV만 지원',
  'airdrop.to_check_airdrop_eligibility':
    '에어드랍 보기를 위해 초기화를 완료하세요.',
  'airdrop.complete_initialization_to_claim_airdrops':
    '에어드랍 청구를 위해 초기화를 완료하세요.',
  'airdrop.complete_initialization_to_view_airdrops':
    '에어드랍 보기를 위해 초기화를 완료하세요.',
  'airdrop.you_are_eligible_for': '자격이 있습니다:',
  'airdrop.and_more': '더 보기',
  'airdrop.congratulations': '축하합니다!',
  'airdrop.airdrop_fee': '에어드랍 수수료',
  'countdown.countdown_plan': '카운트다운 플랜',
  'countdown.create_countdown_plan': '카운트다운 생성',
  'countdown.my_countdown_plan': '내 생성 목록',
  'countdown.countdown_trading_pair': '카운트다운 거래 쌍',
  'countdown.countdown_display': '카운트다운 표시',
  'countdown.token_not_meet_criteria':
    '이 토큰은 카운트다운 기준을 충족하지 않습니다.',
  'countdown.countdown_tips':
    '선택한 거래 쌍에 대해 거래 페이지에 카운트다운이 표시됩니다.',
  'countdown.max_30_days': '현재로부터 30일을 초과할 수 없습니다.',
  'countdown.review_countdown_plan': '카운트다운 계획 검토',
  'countdown.countdown_fee': '카운트다운 수수료',
  'countdown.countdown_plan_created': '카운트다운 계획 생성됨',
  'countdown.trading_will_start_in': '거래 시작까지',
  'countdown.trading_will_start_at_YYYY': 'YYYY에 거래가 시작됩니다.',
  'countdown.cannot_earlier_than_current_time': '현재 시간 이전일 수 없습니다.',
  'dca.price_limit_buy_tips':
    '활성화되면 매수 주문은 최대 가격 이하의 가격에서만 실행됩니다. 이 기능은 제로 수수료 기능과 호환됩니다.',
  'dca.price_limit_sell_tips':
    '활성화되면 매도 주문은 최소 가격 이상의 가격에서만 실행됩니다. 이 기능은 제로 수수료 기능과 호환됩니다.',
  'dca.zero_fee': '제로 수수료',
  'dca.zero_fee_buy_tips':
    '제로 수수료가 활성화되면, DCA 주문은 메이커 전용 지정가 주문으로 처리됩니다. 각 매수 가격은 배치 후 오더북의 최고 매수 가격으로 설정됩니다. 주문이 즉시 체결되지 않거나 전혀 체결되지 않을 수 있음을 유의하세요.',
  'dca.zero_fee_sell_tips':
    '제로 수수료가 활성화되면, DCA 주문은 메이커 전용 지정가 주문으로 처리됩니다. 각 매도 가격은 배치 후 오더북의 최저 매도 가격으로 설정됩니다. 주문이 즉시 체결되지 않거나 전혀 체결되지 않을 수 있음을 유의하세요.',
  'dca.order_canceled_post_only_buy_failed':
    '주문 배치 실패: 오더북에 매수 주문이 없어 주문의 매수 가격을 설정할 수 없음',
  'dca.order_canceled_post_only_sell_failed':
    '주문 배치 실패: 오더북에 매도 주문이 없어 주문의 매도 가격을 설정할 수 없음',
  start_time_cannot_before_current_time:
    '시작 시간은 현재 시간 이전일 수 없습니다.',
  start_time_must_before_end_time: '시작 시간은 종료 시간 이전이어야 합니다.',
  list_token: '토큰 상장',
  contract_address_does_not_exist: '컨트랙트 주소가 존재하지 않습니다.',
  token_listed: '이 토큰은 이미 상장되었습니다.',
  XXX_is_listed: 'XXX가 상장 중입니다.',
  view_progress: '진행 상황 보기',
  pair_create_tips:
    'DeGate에서는 승인이 필요하지 않으며, 거래 페어를 즉시 추가할 수 있습니다.',
  base_token: '기본 토큰',
  quote_token: '상대 토큰',
  existing_pair: '기존 페어',
  trade_now: '지금 거래',
  pair_XXX_added_successfully: 'XXX 추가 성공',
  qty_per_grid: '그리드당 수량',
  grid_minimum_not_reached: '최소 충족되지 않음',
  total_profit: '총 이익',
  total_apy: '총 APY',
  float_profit: '미실현 이익',
  grid_profit_24h: '24시간 그리드 이익',
  pnl: '손익(PnL)',
  eligibility: '자격',
  rewards: '보상',
  view_mining_statistics: '채굴 통계 보기',
  your_entry: '자금 입력',
  refunded: '반환됨',
  large_price_spread: '큰 가격 스프레드',
  large_price_spread_tips:
    '오더북에 표시된 최저 매도 가격과 최고 매수 가격 간에 큰 스프레드가 있으며, 손실 위험이 있습니다. 이중 자산 모드로 투자하는 것이 좋습니다.',
  continue_anyway: '계속하기',
  insufficient_order_book_liquidity_decrease_investment:
    '오더북 유동성이 부족합니다. 투자를 줄이세요.',
  initial_buy: '최초 매수',
  closing_sell: '종료 매도',
  No: '아니오',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    'DCA 주문은 실행 시점에 <b>$XXX가 $PRICE 이하로 떨어지면 실패합니다.</b>',
  zero_fee: '제로 수수료',
  minimum_order_value_is_VALUE: '최소 주문 금액은 <b>$VALUE</b>입니다.',
  Note: '참고',
  Continue: '계속하기',
  estimated_apy: '예상 APY',
  based_on_data_from_last_7_days: '지난 7일의 데이터 기준',
  top_gainers_24h: '24시간 최고 상승 종목',
  top_losers_24h: '24시간 최대 하락 종목',
  listed_tokens: '상장된 토큰',
  vol: '거래량(Vol)',
  let_s_go: '시작하기',
  reject: '거부',
  maximum_N_due_to_price_ticks: '최대 N(가격 단위 조정에 따라)',
  Saved: '저장됨',
  minimum_order_value_$100_$QUOTE: '최소 주문 금액은 <b>$100 $QUOTE</b>입니다.',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    '최소 주문 금액은 <b>$AMOUNT $QUOTE</b>(~$$100)입니다.',
  no_restriction_with_market_order: '<b>시장가 주문</b>에는 제한이 없습니다.',
  go_to_market_order: '시장가 주문으로 이동',
  Mining_Eligibility: '채굴 자격',
  How_to_earn_mining_rewards: '채굴 보상을 얻는 방법',
  Order_Value: '주문 가치',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    '그리드 주문은 전략 생성 시 <b>BV BASE</b> 또는 <b>QV QUOTE</b> 이상이어야 합니다.',
  'mining.mining_tips_QV_QUOTE':
    '그리드 주문은 전략 생성 시 <b>QV QUOTE</b> 이상이어야 합니다.',
  Mining_Price_Range: '채굴 가격 범위',
  'mining.status_over_price_tips':
    '그리드 주문 가격은 주문서의 최고 매수 가격 * 0.99에서 최저 매도 가격 *1.01 사이의 <b>채굴 가격 범위</b>에 포함되어야 합니다.',
  'mining.status_over_price_tips_stable':
    '그리드 주문 가격은 주문서의 최고 매수 가격에서 최저 매도 가격 사이의 <b>채굴 가격 범위</b>에 포함되어야 합니다.',
  Eligible_for_Mining: '채굴 자격 충족',
  Mining_Satus: '채굴 상태',
  Mining_Satus_Mining: '채굴 중',
  Mining_Satus_Standby: '대기 중',
  Mining_Satus_Ineligible: '자격 미충족',
  mining_price_range: '채굴 가격 범위',
  rewards_tips_stable:
    '전략 생성 시 채굴 주문 가치 기준을 충족하는 그리드 주문은 채굴 가격 범위(최고 매수 가격 ~ 최저 매도 가격)에 속할 경우 채굴 보상을 받습니다.',
  rewards_tips:
    '전략 생성 시 채굴 주문 가치 기준을 충족하는 그리드 주문은 채굴 가격 범위(최고 매수 가격 * 0.99 ~ 최저 매도 가격 * 1.01)에 속할 경우 채굴 보상을 받습니다.',
  wrap: '래핑',
  Wrap: '래핑',
  websites_for_more_information: '자세한 정보는 다음 웹사이트에서 확인하세요:',
  official_site: '공식 사이트',
  wrap_site: '래핑/언래핑 사이트',
  tips_third_party_site: '현재 DeGate를 떠나 제3자 사이트로 이동하려 합니다:',
  wrap_unwrap: '래핑/언래핑',
  Receive: '수신',
  Network: '네트워크',
  Token_Contract: '토큰 컨트랙트',
  Contract: '컨트랙트',
  please_select_network: '네트워크 선택',
  maximum_amount: '최대 금액',
  send_USDC_to_this_address: '이 주소로 USDC 전송',
  arpa_airdrop: '$ARPA 에어드랍',
  Failed_to_proceed: '진행 실패',
  Please_select_the_Ethereum_network: '이더리움 네트워크를 선택하세요.',
  NATIVE_USDC_ONLY: '네이티브 USDC 토큰만 사용 가능',
  NEVER_send_bridged_USDC: '브릿지된 USDC는 전송하지 마세요',
  I_understand: '이해했습니다',
  recipient_address: '수취인 주소',
  chain_0: 'DeGate L2',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum One',
  chain_421614: 'Arbitrum One',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    '이 작업을 포함하는 롤업 트랜잭션이 아직 이더리움에 게시되지 않았습니다. DGSCAN은 <b>표시되지 않습니다</b>.',
  Best_Liquidity: '최고 유동성',
  order_partially_filled: '주문이 부분 체결되었습니다',
  order_partially_filled_for_liquidity:
    '남은 주문은 오더북 유동성 급락으로 인해 취소되었습니다. 이 보호 조치는 불리한 가격에서 체결되는 것을 방지합니다.',
  'orders.export_data_2_year': '지난 2년간 데이터 내보내기',
  Community: '커뮤니티',
  complete_in_seconds: '몇 초 안에 완료',
  failed_to_send: '전송 실패. 다시 시도해 주세요.',
  failed_to_send_try_other_networks:
    '전송 실패. 다른 네트워크를 시도해 주세요.',
  gas_fee_deducted: '가스비 차감됨:',
  sum_XXX: '합계 XXX',
  chart_control_7d: '7일',
  chart_control_30d: '30일',
  chart_control_all: '전체',
  chart_control_day: '일(D)',
  chart_control_week: '주(W)',
  chart_control_month: '월(M)',
  Coming: '곧 제공 예정',
  leave_survey_title: '안녕하세요, DeGate를 떠나려고 하시네요.',
  leave_survey_subtitle:
    '더 나은 경험을 위해 의견을 주세요. 적용되는 모든 항목을 선택하세요.',
  leave_survey_not_leaving: '떠나지 않아요, 곧 돌아올 거예요.',
  leave_survey_other_is_fine: '바이낸스/OKX/크라켄 등이 잘 작동합니다.',
  leave_survey_bad_experience: '거래 경험이 마음에 들지 않습니다.',
  leave_survey_no_yield: '수익 기회를 찾지 못했습니다.',
  leave_survey_no_needed_token: '거래하고 싶은 토큰을 찾지 못했습니다.',
  leave_survey_other_reason: '기타(아래 칸에 알려주세요)',
  leave_survey_thanks_for_feedback: '의견 감사합니다',
  Submitted: '제출됨',
  doc_title:
    'DeGate: 분산형 주문서 거래소 | 무료 그리드 및 DCA 암호화폐 거래 봇',
  doc_desc:
    'DeGate는 수백 개의 암호화폐에 대해 낮은 수수료로 거래를 제공하는 탈중앙화 오더북 거래소입니다. 무료 지정가 주문 거래, 그리드 거래 및 DCA 봇을 제공합니다.',
  doc_title_spot: '| 탈중앙화 오더북 | DeGate DEX',
  doc_title_grid: '| 탈중앙화 그리드 트레이딩 봇 | DeGate DEX',
  doc_title_dca: '| 탈중앙화 DCA 트레이딩 봇 | DeGate DEX',
  doc_title_swap: '',

  Notification: '알림',
  read_all: '모두 읽기',
  important: '중요',
  general: '일반',
  view_more: '더 보기',
  thats_all: '현재로서는 여기까지가 전부입니다.',
  XXX_fund_addition_processing: 'XXX 자금 추가 처리 중',
  add_AMOUNT_XXX_to_DeGate: 'DeGate에 AMOUNT XXX 추가',
  XXX_fund_addition_successful: 'XXX 자금 추가 성공',
  XXX_send_successful: 'XXX 전송 성공',
  send_AMOUNT_XXX_to_DeGate: 'DeGate로 AMOUNT XXX 전송(내부 전송)',
  send_AMOUNT_XXX_to_Ethereum: '이더리움으로 AMOUNT XXX 전송',
  you_have_received_a_new_airdrop: '새로운 에어드랍을 받았습니다!',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD:
    'AMOUNT XXX는 YYYY-MM-DD 이후 청구 가능합니다.',
  MARKET_Chart: '시장 차트',
  grid_free: '<b>ZERO</b> 모든 그리드 전략에 대한 수수료',
  maker_free_tips: '<b>ZERO</b> 모든 메이커 주문에 대한 수수료',
  Audit: '오딧',
  Tool: '도구',
  About: '정보',
  list_token_tips: 'DeGate에 토큰을 상장하려면 컨트랙트 주소를 입력하세요',
  login_to_view: '보기 위해 로그인',
  login_to_view_balance: '잔액을 보기 위해 로그인',
  login_to_view_history: '기록을 보기 위해 로그인',
  login_to_view_security_options: '보안 옵션을 보기 위해 로그인',
  i_accept: '동의합니다',
  degate_terms_of_service: 'DeGate 서비스 약관',
  privy_terms_of_service: 'Privy 서비스 약관',
  agree: '동의',
  about_asset_key: 'Asset Key에 대해',
  explantion_asset_key_privy:
    'Asset Key는 사용자의 주소에 연결되어 있으며, 최초 이메일 로그인 시 생성됩니다. DeGate 프로토콜은 이 Asset Key를 사용하여 거래를 승인합니다.<br><br><h4>Asset Key 재설정</h4>사용자는 자유롭게 Asset Key를 재설정할 수 있습니다. 재설정 중:<br><br>1. 모든 미체결 주문 및 그리드 전략이 취소됩니다.<br>2. 거래, 송금 또는 내부 전송과 같은 모든 작업이 중단됩니다.<br><br>다음 zk-rollup이 이더리움 네트워크에 완료되면 재설정이 완료됩니다.<br><br><h4>Asset Key 보기</h4>DeGate SDK 사용자는 Asset Key가 필요하며, SDK에 이 Asset Key를 가져오면 degate.com을 사용하지 않고 DeGate에 접근할 수 있습니다. Asset Key의 보안을 보장하는 것이 중요하며, 누구와도 공유하지 말아야 합니다.',
  privy_account_balance_tips:
    '현재 이메일 로그인을 통해 DeGate를 사용하고 있으며, 이는 낮은 가격의 거래에만 적합합니다.',
  privy_account_balance_tips2:
    '보안을 강화하려면 MetaMask, Ledger, imToken과 같은 셀프 커스터디 지갑으로 전환하는 것을 강력히 권장합니다.',
  dont_show_again_for_30_days: '30일 동안 다시 표시하지 않기',
  dont_show_again_for_60_days: '60일 동안 다시 표시하지 않기',
  privy_feature_disabled_tips:
    '이 기능은 이메일 로그인에서 지원되지 않습니다. 다른 지갑 연결 방법으로 전환하세요.',
  Execution: '실행',
  Executed_Orders: '실행된 주문',
  Failed_Orders: '실패한 주문',
  Remaining_Orders: '남은 주문',
  avg_price: '평균 가격',
  Campaigns: '캠페인',
  all_Campaigns: '모든 캠페인',
  join_now: '지금 참여하기',
  pools: '풀(Pool)',
  you: '내 정보',
  per_day: '일일',

  marketplace: '마켓플레이스',
  latest_grid_orders_filled: '최근 체결된 그리드 주문',
  cumulative_grid_profit: '누적 그리드 이익',
  total_fees_saved: '절감된 총 수수료',
  compared_to_CEX: 'CEX와 비교',
  earn_XX_more_with_DeGate: 'DeGate로 XX% 더 많이 벌기',
  your_profit_with_CEX: '내 CEX 수익',
  total_fees_saved_with_DeGate: 'DeGate를 통해 절감된 총 수수료',
  earn_grid_profit_now: '지금 그리드 이익 얻기',
  top_strategies: '최고 전략',
  ROI: 'ROI',
  roi_desc: 'ROI = 그리드 이익 / 초기 투자',
  '24h_filled_orders': '24시간 동안 체결된 주문',

  // 1.17
  Swap: '스왑',
  liquidity: '유동성',
  market_cap: '시가총액',
  data_collected_from_DEX: 'DEX에서 수집된 데이터',
  my_history: '내 기록',
  pay: '결제',
  receive: '수령',
  max_slippage: '최대 슬리피지',
  minimum_receive: '최소 수령',
  minimum_TOKEN: '최소 TOKEN',
  order_value_limit_reached: '주문 가치 제한 도달',
  maximum_order_value_over_time_XXXX_USDC:
    '최대 주문 가치 XXXX USDC입니다. 이 한도는 시간이 지남에 따라 변동할 수 있습니다.',
  swap_order_placed: '스왑 주문 배치',
  swap_order_filled: '스왑 주문 체결',
  swap_order_failed: '스왑 주문 실패',
  swapping: '스왑 중',
  available_network: '사용 가능한 네트워크',
  minimum_receive_XXX_TOKEN: '최소 수령 XXX 토큰',
  Website: '웹사이트',
  Twitter: '트위터',
  Telegram: '텔레그램',
  status_filled: '체결됨',
  status_fail: '실패',
  tips_DeGate_balance_1:
    'DeGate 잔액은 DeGate에서 귀하의 개인 키(private keys)로 제어할 수 있는 자산의 총 가치를 나타냅니다.',
  tips_DeGate_balance_2:
    'DeGate 잔액에 자금을 추가하면 오더북을 통해 즉시 거래하거나 동일한 네트워크 내에서 자금을 다른 주소로 보낼 수 있습니다.',
  scan_SOLANA: 'Solscan',
  chain_SOLANA: 'Solana',
  swap_deposit_not_support_yet: '스왑 디포짓은 현재 지원되지 않습니다',
  insufficient_pool_liquidity: '유동성 부족',
  tips_DCAMinTips_limit_buy_XXX:
    '시장가가 $XXX를 초과하면 주문이 최소 주문 금액($MIN USDC) 이하로 설정되어 있어 실행에 실패할 수 있습니다. 계속 진행하시겠습니까?',
  tips_DCAMinTips_limit_sell_XXX:
    '시장가가 $XXX 미만으로 떨어지면 주문이 최소 주문 금액($MIN USDC) 이하로 설정되어 있어 실행에 실패할 수 있습니다. 계속 진행하시겠습니까?',
  no_live_mining_campaign: '활성화된 마이닝 캠페인이 없습니다',
  minimum_quantity_per_grid_25: '그리드 최소 금액: $25',
  minimum_investment: '최소 투자 금액:',

  telegram_optional: 'Telegram Handle (선택 사항)',
  feedback_tips:
    '피드백을 남겨주세요. 답변을 원하시면 연락처 정보를 함께 남겨주세요.',
  est_receive: '예상 수령',
  swap_max_slippage_exceeded: '최대 슬리피지 초과',
  transaction_timeout: '거래 시간 초과',
  please_increase_the_max_slippage_setting: '최대 슬리피지 설정을 늘려주세요.',
  total_filled_orders: '총 체결 주문 수',
  message_limit_order_expired: '지정가 주문이 만료되어 취소되었습니다.',
  message_stop_limit_order_expired: '스톱 리밋 주문이 만료되어 취소되었습니다.',
  message_grid_expired: '그리드 전략이 만료되어 종료되었습니다.',

  iframe_network_error_message:
    '네트워크 문제로 인해 차트를 표시할 수 없습니다.',
  no_token_contract: '토큰 컨트랙트 없음',
  native_token_of_XXX_chain: 'XXX 체인의 네이티브 토큰',
  N_found_in_Swap: '스왑에서 N 발견',
  N_found_in_Orderbook_Trade: '오더북 거래에서 N 발견',
  Show_all: '모두 보기',
  sync_to_DeGate_app: 'DeGate 앱과 동기화',
  top_guns: '탑건',
  moneybags: '머니백',
  strategy_value: '전략 가치',
  whales: '고래',
  hot_pairs: '인기 페어',
  apy_kings: 'APY 킹스',
  apy_king: 'APY 킹',
  total_grid_capital: '총 그리드 자본',
  including_grid_strategy_orders: '그리드 전략 주문 포함',
  Grid_Strategy_Creation_Failed: '그리드 전략 생성 실패',
  Grid_Strategy_Creation_Failed_1:
    '그리드 전략의 초기 매수 주문이 부분적으로 체결되었으며, 오더북 유동성이 갑작스럽게 감소함에 따라 나머지는 취소되었습니다.',
  Grid_Strategy_Creation_Failed_2:
    '그리드 전략 세부정보에서 자세한 정보를 확인하세요.',
  grid_apy_estimate_tips:
    'APY 추정치는 지난 7일 동안의 데이터를 기반으로 합니다.<br/><br/>이는 새로운 그리드 전략의 가격 범위가 지난 7일 동안의 기록 가격 범위를 완전히 포함하거나 완전히 포함될 경우에만 제공됩니다.<br/><br/>예를 들어, 가격 범위가 <b>5-10</b>이라고 가정할 경우:<br/>- 기록 가격 범위가 <b>6-9</b>(완전히 포함) 또는 <b>4-11</b>(완전히 포함됨)일 경우 추정이 이루어집니다.<br/>- 기록 가격 범위가 <b>8-12</b>(부분 겹침) 또는 <b>12-14</b>(겹침 없음)일 경우 정확하지 않기 때문에 추정이 제공되지 않습니다.',
  auto_suggested_profit:
    '그리드당 제안된 수익: 지난 7일 동안의 데이터를 사용해 계산됨.',
  referral_code_optional: '추천 코드 (선택 사항)',
  invalid_referral_code: '잘못된 코드',
  DeGate_Referral_Program: 'DeGate 추천 프로그램',
  Referral_Program: '추천 프로그램',
  Referral_Program_Desc_V2:
    '인증 파트너로 가입하고 네트워크로부터 지속적인 수수료를 받으세요',
  Referral_Program_Desc_V2_text2: '투명하고 온체인이며 장기적으로 구축됩니다.',
  Referral_Program_Desc:
    '여러분이 가진 영향력을 통해 긴밀하게 연결된 생태계에 참여하세요. 저희는 장기적 관점을 지향합니다. 여러분의 커뮤니티와 DeGate가 함께 성장하기를 진심으로 바랍니다. <br/> <br/> 친구/팔로워를 초대하고 커미션 리베이트를 얻어 불로소득을 창출하세요. 거래량이 많을수록 리베이트도 커집니다!',
  Apply_Now: '지금 신청하기',
  Commission_Earned: '적립된 커미션',
  Unclaimed_Commission: '미청구 수수료',
  Invites: '초대 수',
  Commission_Rate: '커미션 비율',
  referral_commission_rate_tips:
    '직접 초대한 사용자로부터 레벨 1 수수료를, 그들이 초대한 사용자로부터 레벨 2 수수료를 받습니다.',
  Share_my_referral_link: '내 추천 링크 공유하기',
  Claimable_Commission: '청구 가능한 커미션',
  Referral_Details: '추천 세부 정보',
  Level: '레벨',
  Level_1: '레벨 1',
  Level_2: '레벨 2',
  Type: '유형',
  Activity: '활동',
  Credited: '입금됨',
  referral_trading_fee: '거래 수수료',
  referral_level_1_commission: '레벨 1 수수료',
  referral_pending_commission_tips:
    '이 금액은 보류 중이며 시스템이 USDC로 변환하면 자동으로 입금됩니다.',
  your_referral_link_is_expired: '추천 링크가 만료되었습니다',
  claim_value: '값',
  My_Invites: '내 초대',
  Referee: '추천인',
  Commission: '커미션',
  Transaction: '거래',
  Time_Joined: '가입 시간',
  one_order: '1 주문',
  N_Orders: 'N 주문',
  Filled: '체결됨',
  out_of_range: '범위 밖',

  show_chart: '차트 표시',
  please_enter_grid_parameters_first: '먼저 그리드 매개변수를 입력하세요',
  go_to_app_store: '앱 스토어로 이동',
  go_to_google_play: '구글 플레이로 이동',
  scan_to_download_app: '앱 다운로드를 위해 스캔하세요',
  get_DeGate_app_now: '지금 DeGate 앱을 받으세요!',
  install_beta_version: '베타 버전 설치',
  how_to_install_beta_version: '베타 버전 설치 방법',
  download_testflight_from_app_store: '앱 스토어에서 TestFlight 다운로드',
  click_to_download_testflight: 'TestFlight 다운로드 클릭',
  come_back_for_next_step_after_testflight_is_installed:
    'TestFlight 설치 후 다음 단계로 이동하세요.',
  download_DeGate_in_testflight: 'TestFlight에서 DeGate 다운로드',
  click_to_download_DeGate: 'DeGate 다운로드 클릭',
  click_install: '"설치" 클릭',
  low_liquidity: '경고: 유동성이 낮음',
  low_liquidity_tips:
    '주문서에서 유동성이 낮음이 감지되었습니다. 손실을 방지하려면 확인하세요.',
  min_receive_tips:
    '가격이 더 미끄러지면 거래가 취소됩니다. 아래는 보장된 최소 수령 금액입니다.',
  est: '예상치',
  hide_other_tokens: '다른 토큰 숨기기',
  share: '공유하기',
  more_trading_methods_here: '더 다양한 거래 방법',
  pool_liquidity: '풀 유동성',
  '24h_pool_volume': '24시간 풀 거래량',
  mkt_cap: '시가총액',
  pool_info: '풀 정보',
  DEX: 'DEX',
  pool: '풀',
  pool_address: '풀 주소',
  pool_created: '풀 생성',

  beta_test_tips:
    '이 기능은 베타 테스트 중입니다. 테스트 참여를 원하시면 저희에게 연락해주세요.',
  swap_success_receive_AMOUNT_TOKEN: '스왑 성공, AMOUNT_TOKEN 받음',
  hide_balances_less_than_10: '10달러 미만의 잔액 숨기기',
  Sender: '보내는 사람',
  Recipient: '받는 사람',
  My_CHAIN_Address: '내 CHAIN 주소',
  CHAIN_Address: 'CHAIN 주소',
  From: '출발지',
  To: '도착지',
  send_status_help:
    '<b>처리 중</b> <br />전송 요청을 처리하는 중입니다.<br /><br /><b>성공</b> <br />자산이 수취인의 주소로 전달되었습니다.<br /><br /><b>최종 확정</b><br /> 전송 거래가 포함된 블록이 최종 확정되었습니다.',
  minimum_buy: '최소 구매',
  minimum_sell: '최소 판매',
  check_wallet_compatibility: '지갑 호환성 확인',
  wallet_incompatible: '지갑 호환되지 않음',
  wallet_incompatible_tips:
    '비표준 지갑(예: MPC 지갑)을 사용 중입니다. DeGate는 이를 지원하지 않습니다. 표준 지갑으로 전환해 주세요.',
  initialization_desc_step3:
    '세 번의 서명 요청을 받게 됩니다. 서명은 무료입니다.',

  records_are_unavailable_yet: '기록을 아직 확인할 수 없습니다',
  receive_history_tips:
    '앱의 홈 탭으로 이동하여 지갑 주소를 복사한 후 블록체인 익스플로러에서 기록을 확인하세요',
  rate_limit_tips: '요청이 너무 많습니다. 잠시 후 다시 시도해주세요',
  Warning: '경고',
  Error_fetching_data: '데이터를 가져오는 중 오류 발생',
  Connection_Status: '연결 상태',
  Market_Info: '시장 정보',
  Market_Info_tips: '예: 가격, 24시간 변동률(%), 시가총액, 유동성, 거래량...',
  Last_updated: '마지막 업데이트',
  TIME_ago: '~ 전에 업데이트됨',
  Asset_Info: '자산 정보',
  Your_available_balance: '사용 가능한 잔액',
  Disconnected: '연결 해제됨',
  Earn: '이자 적립',
  Portfolio: '포트폴리오',
  My_Portfolio: '내 포트폴리오',
  My: '내 정보',
  Total_Deposits: '총 예치액',
  Claimable_Rewards: '청구 가능한 보상',
  My_Deposit: '내 예치금',
  APY: '연 수익률(APY)',
  Base_APY: '기본 APY',
  Bonus_APY: '보너스 APY',
  native_Apy: '네이티브 APY',
  Total_APY: '총 APY',
  performance_fee: '성과 수수료',
  About_Vault: '볼트 정보',
  Protocol: '프로토콜',
  Vault: '볼트',
  Asset: '자산',
  Chain_Details: '체인 세부 정보',
  Deposit: '예치',
  Withdraw: '출금',
  Est_Daily_Rewards: '예상 일일 보상',
  Accruing: '적립 중',
  It_becomes_claimable_upon_maturity: '만기 시 보상 청구 가능',
  Tokens: '토큰',
  Value: '가치',
  XXX_available_in: 'XXX 사용 가능',
  maximum_XXX: '최대: $XXX',
  minimum_XXX: '최소: $XXX',
  earn_deposit_sol_balance_tips:
    '계속 진행하려면 최소 0.05 SOL을 보유해야 합니다',
  claim_rewards: '보상 청구하기',
  Return: '반환',
  usdc_supplied_from: 'USDC 공급처',
  multi_chain: '멀티체인',
  multi_chain_tips:
    '멀티체인 토큰은 복잡한 브리징 없이 모든 체인에서 투자에 접근할 수 있게 하여 사용자 경험을 향상시킵니다. 또한 모든 체인에서 발생하는 네트워크 수수료를 자동으로 커버합니다.',
  multi_chain_balances: '멀티체인 잔액',
  convert_to_multi_chain_usdc_tips:
    '<b>멀티체인 USDC</b>로 변환하려면 브리지를 이용하세요',
  Bridge: '브리지',
  multi_chain_usdc:
    '멀티체인 USDC는 현재 Solana 및 Base 네트워크의 USDC를 의미합니다',
  explantion_fees:
    '<h4>스왑 수수료율</h4><ul><li><a href="https://docs.degate.com/about-degate/swap">수수료율 등급표</a>를 참조하세요</li></ul><br><h4>네트워크 수수료</h4><ul><li>실시간 온체인 비용을 기준으로 계산됩니다.</li></ul>',
  search_history: '검색 기록',
  '24h_txns': '24시간 거래 수',
  Markets: '시장',
  warning_excessive_balance_detected: '경고: 과도한 잔액 감지됨',
  warning_excessive_balance_detected_tips1:
    '현재 DeGate 계정은 대량의 자산을 보관하도록 설계되지 않았습니다. 잔액이 권장 한도인 XXX USD를 초과했습니다.',
  warning_excessive_balance_detected_tips2:
    '자산 손실 위험을 줄이기 위해 즉시 보유 자산을 줄이세요',
  warning_excessive_balance_detected_tips2_app:
    '자산 보호를 위해 DeGate 앱을 설치하고 앱 내에서 지갑을 생성하거나 가져오는 것을 권장합니다',
  download_app: '앱 다운로드',
  receive_data_tips:
    "주소 보기'(오른쪽 상단)를 선택한 후, 블록체인 익스플로러에 붙여넣어 거래 내역을 확인하세요",
  verify_account: '계정 인증',
  est_network_fee: '예상 네트워크 수수료',
  arrival_time: '도착 예상 시간',
  gas_refund_tips:
    '환불 금액은 멀티체인 USDC 및/또는 네이티브 블록체인 토큰으로 반환될 수 있습니다',
  network_fee: '네트워크 수수료',
  estimated_fee: '예상 수수료',
  actual_fee: '실제 수수료',
  refund: '환불',
  Browser: '브라우저',
  transaction_details: '거래 상세 정보',
  smart_contract_interaction: '스마트 컨트랙트 상호작용',
  interact_with: '다음과 상호작용',

  Raffle: '추첨',
  round_N: 'N번째 라운드',
  pick_your_number: '번호 선택하기',
  win_1_million: '백만 달러에 도전하세요',
  participating: '참여 중',
  become_a_millionaire_now: '지금 백만장자가 되세요',
  get_free_tickets: '무료 티켓 받기',
  verify_1_million_prize_fund: '백만 달러 상금 풀 검증하기',
  lucky_number: '행운의 번호',
  winning_bitcoin_block: '당첨 비트코인 블록',
  block_hash: '블록 해시',
  participated: '참여 완료',
  ticket_redemption_phase_ends_in_XXX: '티켓 교환 마감까지 XXX',
  redemption: '교환',
  pending_draw: '추첨 대기 중',
  announcement: '발표',
  my_tickets_total: '내 티켓 / 전체 티켓',
  view_rules: '규칙 보기',
  earn_up_to_200_thousand_dollars_bonus: '최대 $200,000 보너스 받기',
  invite_friends_now: '친구를 지금 초대하세요!',
  prizes: '상금',
  grand_prize: '1등 상금',
  second_prize: '2등 상금',
  third_prize: '3등 상금',
  fourth_prize: '4등 상금',
  fifth_prize: '5등 상금',
  sixth_prize: '6등 상금',
  seventh_prize: '7등 상금',
  eighth_prize: '8등 상금',
  draw_starts_once_the_bitcoin_block_is_confirmed:
    '비트코인 블록이 확정되면 추첨이 시작됩니다.',
  ticket_redemption_closed: '티켓 교환 종료',
  congratulations: '축하합니다!',
  you_ve_won: '당첨되셨습니다',
  good_luck_for_next_round: '다음 라운드에 행운을 빕니다',
  you_weren_t_in_this_round: '이번 라운드에는 참여하지 않으셨습니다',
  join_the_next_round: '다음 라운드에 참여하세요!',
  tickets_in_round_N: 'N라운드의 티켓',
  my_tickets: '내 티켓',
  total_tickets: '전체 티켓 수',
  total_tickets_tips:
    '티켓 교환이 끝나면, 해당 라운드 티켓 번호의 암호학적 해시를 Base 체인에 게시하여 추첨의 투명성과 위변조 방지를 보장합니다.',
  hash_of_total_tickets: '전체 티켓 해시',
  hash_value_tips:
    'Hash = SHA256(Ticket1,Ticket2,…,TicketN), 여기서 Ticket1~N은 이번 라운드에서 교환된 모든 티켓이며 오름차순으로 정렬됩니다.',
  verify_hash: '해시 검증하기',
  reviewing: '검토 중',
  manual_review_in_progress_payout_will_follow_shortly:
    '수동 검토 중입니다. 곧 지급이 진행됩니다.',
  received: '수령 완료',
  points: '포인트',
  no_prize_this_time: '이번엔 당첨되지 않았습니다',
  all_winners: '전체 당첨자',
  winning_ticket: '1장의 당첨 티켓',
  winning_tickets_N: 'N장의 당첨 티켓',
  Pick_your_ticket_number: '원하는 티켓 번호 선택',
  Manual: '수동',
  Range: '범위',
  Random: '무작위',
  Feeling_lucky: '운을 시험해 보세요!',
  Redeem: '교환',
  Invalid_number: '잘못된 번호입니다',
  Ticket_already_taken: '이미 선택된 번호입니다. 다른 번호를 고르세요.',
  N_Ticket: 'N장의 티켓',
  N_Tickets: 'N장의 티켓',
  Points_needed: '필요한 포인트',
  Points_available: '사용 가능한 포인트',
  Redemption_Successful: '교환 완료',
  Ticket_Unavailable: '사용 불가한 티켓',
  N_Ticket_Unavailable: 'N장의 티켓 사용 불가',
  N_Tickets_Unavailable: 'N장의 티켓 사용 불가',
  Looks_like_someone_just_grabbed_this_number:
    '누군가 이 번호를 방금 선택했어요. 다른 번호를 골라주세요.',
  Insufficient_Points: '포인트가 부족합니다',
  You_have_0_point_and_cannot_redeem_tickets:
    '포인트가 없어 티켓을 교환할 수 없습니다',
  You_have_POINTS_points_and_can_redeem_a_maximum_of_TICKETS_tickets:
    '현재 보유한 POINTS 포인트로 최대 TICKETS장까지 교환 가능합니다.',
  How_to_acquire_points: '포인트는 어떻게 얻나요?',
  Number_Start: '시작',
  Number_End: '종료',
  Please_enter_the_start_number_and_end_number:
    '시작 번호와 끝 번호를 입력하세요',
  End_number_must_be_greater_than_start_number:
    '끝 번호는 시작 번호보다 커야 합니다',
  Those_tickets_have_already_been_taken: '해당 번호는 이미 선택되었습니다.',
  Looks_like_someone_just_grabbed_some_of_the_tickets:
    '누군가 일부 번호를 방금 선택했어요. 다시 시도하세요.',
  Number_of_tickets: '티켓 개수',
  Generate: '생성하기',
  Please_enter_the_number_of_tickets: '티켓 개수를 입력하세요',
  N_random_tickets: '무작위 N장의 티켓',
  N_random_ticket: '무작위 N장의 티켓',
  Generate_Again: '다시 생성하기',
  Dashboard: '대시보드',
  My_Points: '내 포인트',
  My_Participations: '나의 참여 내역',
  N_rounds: 'N라운드',
  N_round: 'N라운드',
  My_Winnings: '내 당첨 내역',
  Invite_Friends_and_Earn_20_Extra_on_Their_USDC_Winnings:
    '친구를 초대하고 친구의 USDC 당첨금의 20% 추가 보너스 받기',
  They_win_more_you_earn_more_and_there_is_no_cap:
    '친구가 많이 당첨될수록 보너스도 커져요 – 상한 없습니다.',
  Invite_your_friends_to_DeGate:
    '친구를 DeGate에 초대하세요. 친구가 추첨에서 USDC를 당첨받을 때마다, 당신은 20%의 추가 보너스를 받습니다.',
  My_Referral_Link: '내 추천 링크',
  Copy_Link: '링크 복사',
  Total_Invited: '총 초대한 인원',
  Total_Rewards: '내 보상',
  Points: '포인트',
  Tickets: '티켓',
  Winnings: '당첨금',
  Points_can_be_earned_by_using_the_DeGate_Swap_feature:
    'DeGate Swap 기능을 이용하면 포인트를 적립할 수 있어요.',
  Go_to_Swap: '스왑하러 가기',
  Winning: '당첨',
  Redeem_tickets: '티켓 교환',
  Gift: '선물',
  Rewards: '보상',
  Invite_Rewards: '초대 보상',
  How_to_Join: '참여 방법은?',
  Step_N: '단계 N',
  Earn_points_by_swapping_on_DeGate: 'DeGate에서 스왑하면 포인트가 적립됩니다',
  Use_your_points_to_redeem_raffle_tickets_during_the_redemption_phase:
    '교환 단계에서 포인트를 사용해 추첨 티켓을 받으세요',
  Check_the_results_after_the_round_ends_your_lucky_moment_might_be_waiting:
    '라운드 종료 후 결과를 확인하세요 — 행운의 순간이 기다리고 있을지도 몰라요!',
  Digits_Matched: '일치한 자리수',
  All_Match: '모든 8자리 일치',
  Matches_Last_N: '마지막 N자리 일치',
  Winner: '당첨자',
  Prize: '상금',
  FAQ: 'FAQ',
  Rules: '규칙',
  How_does_it_Work: '작동 방식은 어떻게 되나요?',
  how_to_participate: '어떻게 참여하나요?',

  N_Point: '(오류)',
  N_Points: '(오류)',
  You_just_earned_points_from_your_swap: '스왑을 통해 포인트를 획득했습니다.',
  Use_them_to_redeem_raffle_tickets_to_win_1_million_dollars:
    '이를 사용해 추첨 티켓을 교환하고 <br/><b>$1,000,000</b>을 노려보세요!',
  Join_Raffle: '추첨에 참여하기',
  please_enter_amount: '금액을 입력하세요',
  claim_prizes: '당첨금 수령',
  claim_your_prizes: '내 당첨금 수령하기',
  all_unclaimed_usdc_will_be_sent_to_your_base_address_shortly:
    '클레임되지 않은 USDC는 곧 Base 지갑 주소로 전송됩니다',
  Claim_your_invite_rewards: '초대 보상 수령',
  Claim_Invite_Rewards: '초대 보상 클레임',
  amount_needed: '필요 금액',

  download_apk: 'APK 다운로드',
  download_app_get: 'GET',
  download_page_app_store: 'App Store',
  download_page_google_play: 'Google Play',
  download_page_apk: 'APK',
  download_page_scan_to_download: '스캔하여 다운로드',
  download_page_partners: '파트너',
  Matches_for_8th_Prize: '마지막 숫자 또는 마지막 숫자 ± 1',
  Select_Network: '네트워크 선택',
  All_Networks: '모든 네트워크',
  Filtering_with_CHAIN_network: 'CHAIN 네트워크로 필터링 중입니다.',
  Claim_History: '보상 내역',
  My_Dashboard: '내 대시보드',
  Claim_Winnings: '상금 청구',
  team_up_to_boost_your_odds_of_winning_1_million_usdc:
    '팀을 만들어 당첨 확률을 높이세요 <div>1,000,000 USDC 당첨!</div>',
  Create_a_Team_Now: '지금 팀 생성하기',
  Leader: '리더',
  Leader_Bonus: '리더 보너스',
  Leader_Bonus_tips: '팀이 당첨되면 10% 추가 USDC를 획득하세요!',
  Team_Tickets: '팀 티켓',
  Create_Team: '팀 생성',
  Enter_Team_Name: '팀 이름 입력',
  Please_enter_a_team_name: '팀 이름을 입력하세요',
  Name_already_taken_try_different_one:
    '이미 사용 중인 이름입니다. 다른 이름을 시도하세요.',
  Team_created: '팀이 생성되었습니다',
  Invite: '초대',
  Invite_Team_Members: '팀원 초대',
  Team_Details: '팀 정보',
  Team_Points: '팀 포인트',
  Pool_My_Points: '내 포인트 풀에 추가',
  Rewards_are_split_by_points_contributed:
    '보상은 기여한 포인트에 따라 분배됩니다.',
  pool_points_tips:
    '내 포인트를 팀 풀에 전송하세요. 보상은 각 구성원의 기여도에 따라 분배됩니다.',
  Please_enter_a_number_that_is_a_multiple_of_10: '10의 배수 숫자를 입력하세요',
  Insufficient_points: '포인트가 부족합니다',
  Added_POINTS_points_to_TEAM: '팀에 POINTS 포인트 추가',
  Join_the_team_to_boost_your_odds_of_winning_1_million_usdc:
    '팀에 합류하여 <br/> <b>1,000,000 USDC 당첨 확률을 높이세요!</b>',
  Congratulations_You_ve_joined_the_team: '축하합니다! 팀에 합류했습니다.',
  You_re_already_in_this_team: '이미 이 팀에 속해 있습니다',
  Solo: '개인',
  Team: '팀',
  Select_Team: '팀 선택',
  My_Teams: '내 팀',
  team_tickets_total: '팀 티켓 / 총 티켓',
  how_it_works: '진행 방식',
  how_to_play_as_a_team: '팀 플레이 방법',
  invite_tips1: '팀원이 래플에서 USDC를 획득할 때마다 추가로 20%를 받습니다.',
  invite_tips2:
    '팀원이 스왑으로 포인트를 얻을 때마다 해당 포인트의 20%를 추가로 획득합니다.',
  distribution: '분배',
  new_rule_1_1:
    '<b>1. 포인트 획득</b><br/> <b>스왑으로 획득</b><br/> DeGate에서 스왑할 때마다 자동으로 포인트를 얻습니다.',
  new_rule_2_1:
    '<b>2. 당첨 방법</b><br/> <b>티켓 교환</b><br/> 교환 단계에서 10포인트를 사용해 티켓 1장을 얻으세요.',
  new_rule_2_2:
    '<b>번호 선택</b><br/> 각 티켓에는 고유한 8자리 번호(00000000–99999999)가 있습니다. 직접 선택하거나 시스템이 무작위로 선택하도록 할 수 있습니다.',
  new_rule_2_3:
    '<b>럭키 번호 일치</b><br/> 티켓 번호를 해당 회차의 럭키 번호와 비교하세요. 뒤에서부터 일치하는 숫자가 많을수록 상금이 커집니다.',
  new_rule_2_4: '예시: 럭키 번호가 <b>12345678</b>일 때:',
  match_pattern: '일치 패턴',
  winning_tickets: '당첨 티켓',
  represents_any_digit: '✱는 임의의 숫자를 나타냅니다.',
  new_rule_3: '<b>3. 검증 가능한 공정성</b>',
  new_rule_3_1:
    '<b>블록체인 기반 무작위성</b><br/> 럭키 번호는 교환 종료 후 6번째 비트코인 블록을 기반으로 합니다. 예측하거나 변경할 수 없습니다.',
  new_rule_3_2:
    '<b>오픈소스 알고리즘</b><br/> 당첨 비트코인 블록의 해시는 오픈소스 코드로 럭키 번호로 변환됩니다 — GitHub에서 확인하고 검증할 수 있습니다.',
  new_rule_3_3:
    '<b>상금 자금 증명</b><br/> 1.2M USDC 이상이 미리 로드되어 있으며 다음 지갑 주소에서 확인할 수 있습니다: <a href="https://basescan.org/address/0xdB5c7E18FB657F6a8f193024D7F0Aa251Df8C7d6" target="_blank">0xdB5...8C7d6</a> 및 <a href="https://basescan.org/address/0x1c7F26c156caEA62Ad11F6a634051Df43129A656" target="_blank">0x1c7...9A656</a>',
  team_rule_1:
    '<b>1. 팀 만들기 또는 참여하기</b><br/> 그랜드 프라이즈 1,000,000 USDC 당첨 확률을 높이기 위해 팀을 구성하세요.',
  team_rule_2:
    '<b>2. 포인트 풀에 추가</b><br/> 각 라운드마다 포인트를 팀 풀에 추가하세요.',
  team_rule_3:
    '<b>3. 함께 교환</b><br/> 팀원 누구나 팀 포인트를 사용해 티켓을 받을 수 있습니다.',
  team_rule_4:
    '<b>4. 낭비 없음</b><br/> 라운드 종료 시 남은 팀 포인트는 자동으로 무작위 티켓으로 전환됩니다.',
  team_rule_5:
    '<b>5. 공정 분배</b><br/> 팀이 당첨되면 기여한 포인트에 따라 보상이 분배됩니다.',
  prize: '상금',
  all_8_digits: '8자리 모두 일치',
  last_N_digits: '뒤에서 N자리 일치',
  no_luck: '아쉽게도 당첨되지 않음',
  Team_Points_Breakdown: '팀 포인트 내역',
  member: '구성원',
  Points_Contributed: '기여한 포인트',
  you_didnt_win_this_round_better_luck_next_time:
    '이번 라운드에서는 당첨되지 않았습니다 — 다음 기회에!',
  Rewards_Received: '획득한 보상',
  Points_can_be_earned_by_using_the_DeGate_Swap:
    'DeGate 스왑 사용 시 포인트를 얻을 수 있습니다.',
  Add_to_Team: '팀에 추가',
  Team_Refund: '팀 환급',
  Receive_from_Team: '팀 로부터 수령',
  from_invitee_winnings: '초대자 당첨 보상에서',
  from_invitee_points: '초대자 스왑 보상에서',
  draw_starts_once_the_winning_bitcoin_block_is_fully_confirmed:
    '당첨 비트코인 블록이 완전히 확정되면 추첨이 시작됩니다.',
  Invite_Friends_and_Earn_20_Extra: '친구 초대하고 <b>20% 추가</b> 획득',
  Team_Points_Available: '팀 포인트 사용 가능',
  me: '내 정보',
  Stocks: 'Stocks',

  // 1.28
  est_account_rent_CHAIN_NUM: '$NUM (CHAIN 임대료)',
  est_transaction_cost_NUM: '$NUM (거래 비용)',
  filter_by_network: '네트워크로 필터링',
  manage_tokens_title: '토큰 관리',
  manage_tokens_short: '관리',
  manage_menu_status_on: '켜기',
  manage_menu_status_off: '끄기',
  manage_tokens_my_assets: '내 자산',
  manage_tokens_other_assets: '기타 자산',
  manage_tokens_add_btn: '토큰 추가',
  manage_tokens_contract_address: '컨트랙트 주소',
  manage_tokens_contract_address_placeholder: '컨트랙트 주소 입력',
  manage_tokens_symbol: '심볼',
  manage_tokens_decimal: '소수점 자릿수',
  manage_tokens_not_found:
    '토큰을 찾을 수 없습니다. 컨트랙트 주소와 네트워크를 확인하세요.',
  manage_tokens_added: '{TOKEN}은(는) 이미 토큰 목록에 있습니다.',
  manage_tokens_remove_confirm_title: '토큰 제거',
  manage_tokens_remove_confirm_desc:
    '{TOKEN}을(를) 토큰 목록에서 제거하시겠습니까?',
  manage_tokens_remove_confirm_btn: '제거',
  Mainnet: '메인넷',
  Testnet: '테스트넷',
  More_Services: '더 많은 서비스',
  current_block: '현재 블록',
  fully_confirmed: '완전히 확정됨',
  create_account: '계정 만들기',
  create_account_tips:
    '첫 사용자는 계정을 생성해야 합니다. 과정은 약 <b>30초</b> 걸립니다.',
  account_created: '계정이 생성되었습니다',
  please_create_account_first: '먼저 계정을 생성해 주세요',
  unable_to_create_account: '계정을 생성할 수 없습니다',
  this_asset_is_self_custodied_in_your_CHAIN_address:
    '이 자산은 자가 보관되며, 귀하의 <b>CHAIN</b> 주소에 있습니다:',
  generate_wallet_address: 'DeGate가 이제 다음 신규 체인을 지원합니다.',
  generate_wallet_address_tips: '확인’을 클릭하여 지갑 주소를 생성하세요.',
  updating: '업데이트 중',
  please_wait: '잠시만 기다려 주세요',
  close_this_window_to_resume_what_you_were_doing:
    '이 창을 닫으면 하던 작업을 계속할 수 있습니다',
  Funds: '자금',
  Route: '경로',
  Meme: 'Meme',
  free_team_tickets: '무료 팀 티켓',
  free_team_tickets_tips: '마일스톤 달성 시 팀 티켓이 <b>2배</b>가 됩니다',
  if_the_target_isn_t_met_this_round_progress_resets:
    '이번 라운드에서 목표를 달성하지 못하면 진행도가 초기화됩니다',
  n_tickets_to_claim: '수령 가능 티켓 N장',
  claim_bonus: '보너스 받기',
  any_unclaimed_tickets_will_be_automatically_claimed_when_the_redemption_phase_ends:
    '교환 단계가 종료되면 미수령 티켓은 자동으로 수령됩니다.',
  n_tickets_claimed: '티켓 N장 수령 완료',
  n_tickets_to_claim_m_claimed: '수령 가능 N장 (수령됨 M장)',
  all_n_tickets_claimed: 'N장의 티켓을 모두 수령',
  generate_N_tickets: '티켓 N장 생성',
  TRY_YOUR_LUCK_NOW: '지금 운을 시험해 보세요',
  ENTER_WIN_BIG: '참가하고 큰 보상을 노리세요!',
  FEELING_LUCKY: '행운이 느껴지나요?',
  HIT_THAT_000000: '000000을 맞혀라!',
  Enter: '참가하기',
  N_Points_for_1_Entry: '1회 응모에 N 포인트',
  awaiting: '대기 중…',
  numbers_incoming: '번호가 곧 표시됩니다…',
  HOLD_TIGHT_GOOD_LUCK: '잠시만요—행운을 빌어요!',
  Entry: '응모',
  Refund: '환불',
  how_to_earn_points: '포인트는 어떻게 얻나요?',
  how_to_earn_points_tips:
    'DeGate에서 스왑하거나 Meme 게임에 참여해 포인트를 적립하세요.',
  Go_to_meme: 'Meme로 이동',
  Verify: '인증',
  Winning_Block: '당첨 블록',
  Entry_Time: '참가 시간',
  Points_History: '포인트 기록',
  Raffle_History: '추첨 기록',
  Verify_Raffle_Results: '추첨 결과 검증',
  Fair_play_proof_in_3_steps: '3단계 공정성 증명',
  Proof_of_fair_play_in_3_steps: '3단계의 공정성 입증',
  verify_tips_1: '1. Secret의 ‘지문’ 공개',
  verify_tips_1_1:
    '추첨 시작 전에 Secret의 해시(‘지문’)를 게시합니다 — 그 해시가 바뀌지 않으면 Secret을 바꿀 수 없습니다.',
  verify_tips_2: '2. 다음 블록에서 결정됩니다',
  verify_tips_2_1:
    'Enter를 누르면 Secret와 다음 Base 블록으로 6자리 행운 번호가 산출됩니다.',
  verify_tips_3: '3. 공개 및 검증',
  verify_tips_3_1:
    '추첨 기록을 열어 ‘공개’와 ‘검증’을 탭하세요. 해당 해시를 게시된 지문과 비교하고 계산을 다시 실행하세요 — 같은 숫자면 조작이 없는 것입니다.',
  verify_tips_4: 'Secret을 공개하면 다음 응모를 위해 새 Secret이 봉인됩니다.',
  hash_of_secret: 'Secret의 해시',
  secret: 'Secret',
  winning_block: '당첨 블록',
  keccak256: 'keccak256(Secret, Block hash) % 1000000',
  hash_of_secret_for_next_entry: '다음 응모용 Secret의 해시',
  proof: '증명',
  entry_time: '참가 시간',
  not_revealed: '미공개',
  the_secret_is_a_system_generated_input_used_to_compute_the_lucky_number:
    'Secret은 행운 번호를 계산하기 위해 시스템이 생성한 입력입니다. 공정성을 위해 DeGate는 해시를 사전에 공개해 고정하여 이후 변경이 불가능하게 합니다。',
  the_next_block_on_base_chain_after_you_click_enter:
    'Enter를 누른 후 Base 체인의 다음 블록.',
  reveal_and_verify: '공개 및 검증',
  download_tickets: '티켓 다운로드',
  Total_Winnings: '총 당첨 금액',
  time_limited: '기간 한정',
  Exclusive_Friend_Rewards: '친구 전용 보상',
  Register_an_account_You_and_your_friend_get_10_FREE_entries_each:
    '계정 등록 - <br/><b>본인과 친구가 각자 무료 응모 10회</b>',
  Get_Rewards: '보상 받기',
  You_re_eligible_for_10_FREE_Entries: '<b>무료 응모 10회</b> 대상입니다',
  Expires_in_XXX: 'XXX 후 만료',
  Invite_a_friend_to_join_DeGate: '친구를 DeGate에 초대',
  invite_text_1:
    'DeGate 초대가 왔어 — 우리 각자 무료 응모 10회(최대 $5K 당첨 가능). 기간 한정이라 바로 보낼게!',
  you_received: '받았습니다',
  free_entries_10: '무료 응모 10회',
  Free_Entries_times_N: '무료 응모: N',
  EXPIRED: '만료됨',
  flash_op_create_account_tips:
    '계정 만들기 - 본인과 친구가 각자 무료 응모 10회',
  offer_is_expired: '이 혜택은 만료되었습니다',
  offer_is_limited_to_new_users_only: '이 혜택은 신규 사용자에게만 제공됩니다',
  get_rewards_now: '지금 보상 받기',
  Later: '나중에',
  so_close_try_again: '거의 성공! 다시 시도할까요?',
  no_luck_try_again: '운이 없네요. 다시 시도할까요?',
  no_route_fund:
    '경로를 찾을 수 없습니다 — 금액을 바꾸거나 나중에 다시 시도하세요.',
  trading_restriction_notice: '거래 제한 안내',
  trading_restriction_notice_tips:
    '<a href="https://assets.backed.fi/legal-documentation/restricted-countries" target="_blank">Backed</a>의 제한 국가 목록에 따라, 귀하의 지역에서는 이 온체인 주식 토큰을 거래할 수 없습니다:',
  trading_restriction_notice_tips_2:
    '이 제한은 Backed가 발행한 일부 토큰에만 적용되며, 다른 토큰은 계속 거래할 수 있습니다.',
  btn_got_id: '알겠습니다',
  Invalid_SOL_rent: '렌트 비용을 지불하기에 SOL이 부족합니다',

  stocks: {
    Hot_Stocks: '인기 종목',
    Last: '최종가',
    Chg: '변동',
    Chg_Percent: '변동률',
    Stock_Heatmap: '주식 히트맵',
    Stock_Heatmap_AUM: '주식 히트맵(AUM)',
    Holders_per_Stock: '종목별 보유자 수',
    Holders_per_Stock_top_20: '종목별 보유자 수 (Top 20)',
    Trades_per_Stock: '종목별 거래 건수',
    Trading_volume_DEX_per_Stock: '종목별 DEX 거래량',
    Trading_vol: '거래량',
    Daily_Trading_Accounts_per_Stock: '종목별 일일 거래 계정 수',
    Token_Holders_AUM: '토큰 보유자 & AUM',
    Issuer: '발행사',
    Onchain_AUM: '온체인 AUM',
    Valuation: '평가가치',
    Dex_Trading_Vol: '24시간 DEX 거래량',
    Onchain_Supply: '온체인 공급량',
    Onchain_Holders: '온체인 보유자 수',
    Audit_URL: '감사 URL',
    Dex_Liquidity: 'DEX 유동성',
    Websites: '웹사이트',
    News_Flow: '뉴스 흐름',
    Trading_Vol_Dex_Liquidity: '거래량 & DEX 유동성',
    AUM_desc:
      'AUM(운용자산)은 발행사 Backed Fi가 온체인으로 발행한 이 종목의 총 USD 가치를 의미합니다.',
    Onchain_Opportunity: '온체인 기회',
    '24h APY': '24시간 APY(연이율)',
    stocks_doc_title: '온체인 주식 대시보드 | 수익률 인사이트 및 전략',
    total_aum: '총 AUM',
    total_unique_holders: '고유 보유자 총수',
    total_dex_volume: '총 DEX 거래량',
    total_tvl: '온체인 풀 유동성',
    total_assets: 'xStock 자산 수',
    Trade_with_ZERO_FEES: '수수료 제로로 거래',
    Legal_Info: '법적 정보',
  },
  swap_error: {
    Swap_failed_return_below_minimum_receive:
      '스왑 실패: 반환 금액이 최소 수령 수량보다 적습니다.',
    Insufficient_liquidity_for_this_token_reduce_amount_and_try_again_later:
      '해당 토큰의 유동성이 부족합니다. 금액을 줄이거나 나중에 다시 시도하세요.',
    Swap_failed_price_impact_exceeds_limit:
      '스왑 실패: 가격 영향이 한도를 초과했습니다.',
    Swap_failed_honeypot_or_high_risk_token_detected:
      '스왑 실패: 허니팟 또는 고위험 토큰이 감지되었습니다.',
    Swap_failed_insufficient_sol_for_rent:
      '스왑 실패: 렌트 비용을 위한 SOL이 부족합니다. 소량의 SOL을 입금한 후 다시 시도하세요.',
    Return_below_minimum_receive: '최소 수령 수량보다 반환 금액이 적습니다',
    Insufficient_liquidity_for_this_token: '해당 토큰의 유동성이 부족합니다',
    Price_impact_exceeds_limit: '가격 영향이 한도를 초과했습니다',
    Honeypot_or_high_risk_token_detected:
      '허니팟 또는 고위험 토큰이 감지되었습니다.',
    Insufficient_sol_for_rent: '렌트 비용을 위한 SOL이 부족합니다',
    Swap_failed_insufficient_funds_for_gas:
      '스왑 실패: 가스비를 위한 자금이 부족합니다.',
    Insufficient_funds_for_gas: '가스비를 위한 자금이 부족합니다',
    Estimated_network_fee_is_less_than_the_actual_amount_required:
      '예상 네트워크 수수료가 실제 필요 금액보다 낮습니다.',
  },
  gift: {
    Gift_Box: '선물 상자',
    View_Gift_Box: '선물 상자 보기',
    Download_App: '앱 다운로드',
    Your_gift_awaits: '선물이 준비되었습니다',
    Open_Now: '지금 열기',
    Cash_Gift_for_CopyTrade: '자동 카피트레이드용 현금 선물',
    Receive_gift_in_DeGate_App: 'DeGate 앱에서 선물 받기',
    This_gift_box_was_claimed_by_a_different_account_you_previously_used:
      '이 선물 상자는 이전에 사용한 다른 계정에서 이미 수령되었습니다',
    Youve_received_a_Cash_Gift_for_CopyTrade: '{GIFT TYPE}을(를) 받았습니다',
    has_been_sent_to_your_CopyTrade_account:
      '자동 카피트레이드 계정으로 전송되었습니다',
    View_My_Account: '내 계정 보기',
    claim_your_gift_please_create_a_DeGate_account:
      '선물을 받으려면 먼저 DeGate 계정을 생성하세요',
    Total_Gift_Amount: '선물 총액',
    Expired_at_DATE: 'DATE에 만료됨',
    Gifts_claimed_CLAIMED_TOTAL: '선물 (CLAIMED/TOTAL 수령됨)',
    Today: '오늘',
    Youve_received_your_gift_cash_Outgoing_transfers_will_be_enabled_after_your_Copy_Trade_bot_completes_its_first_trade:
      '현금 선물을 받으셨습니다. 자동 카피트레이드 봇이 첫 거래를 완료하면 출금이 가능해집니다.',
    Others_were_faster_Try_again_next_time:
      '다른 사람이 더 빨랐어요. 다음에 다시 시도해 보세요!',
    Connect_wallet_to_claim: '수령하려면 지갑을 연결하세요',
    Expired_in_DATE: 'DATE에 만료됨',
  },
  turboRange: {
    Turbo_Range: 'Turbo Range',
    my_positions: '내 보유 포지션',
    my_turbo_range: '내 터보 레인지',
    yesterday_yield: '어제 수익',
    total_yield: '총 수익',
    Details: '상세 정보',
    all_products: '전체 상품',
    invert_USDC: 'USDC 투자',
    apy_7D: '7일 APY',
    you_have_no_position: '보유 포지션이 없습니다',
    invest: '투자하기',
    create_position: '포지션 생성',
    price_range: '가격 범위',
    earn_yield_while_TSLA_price_stays_in_your_range:
      '{TSLA} 가격이 설정한 구간에 머무는 동안 수익을 적립',
    earn_yield_while_price_stays_in_your_range:
      '가격이 범위 내에 머무는 동안 수익 창출',
    est_apy: '예상 APY',
    estimated_annual_percentage_yield_based_on_last_7_days_data:
      '예상 연간 수익률(APY). 최근 7일 데이터 기준.',
    est_annual_yield: '예상 연간 수익',
    enter_amount_to_continue: '계속하려면 금액을 입력하세요',
    set_price_range: '가격 범위 설정',
    current_price: '현재 가격',
    current: '현재',
    min_price: '최저 가격',
    max_price: '최고 가격',
    please_enter_an_amount: '금액을 입력하세요',
    maximum_500000: '최대 500000',
    adjust_the_input_to_proceed: '계속하려면 입력을 조정하세요',
    please_reduce_amount: '금액을 줄여주세요',
    not_enough_balance_to_proceed: '잔액이 부족하여 진행할 수 없습니다',
    processing_deposit_to_liquidity_pool: '유동성 풀에 예치 처리 중',
    you_can_close_this_window_we_ll_handle_it:
      '이 창을 닫아도 됩니다. 나머지는 저희가 처리하겠습니다.',
    investment_successful: '투자 성공',
    invested: '실제 투자액',
    returned: '반환됨',
    view_my_position: '내 보유 포지션 보기',
    investment_failed: '투자 실패',
    about_turbo_range: 'Turbo Range 소개',
    turbo_range_puts_your_funds_into_a_liquidity_pool_within_the_price_range_you_set_when_others_trade_in_that_range_you_earn_fees:
      '<b>Turbo Range</b>는 사용자가 설정한 가격 구간의 유동성 풀에 자금을 예치합니다. 다른 사용자가 해당 구간에서 거래하면 수수료를 벌 수 있습니다.',
    example: '예시',
    let_s_say_you_invest_1000_USDC_in_the_TSLA_USDC_pool_and_set_a_range_of_270_330_TSLA_s_current_price_is_300:
      '예를 들어 1000 USDC를 TSLA/USDC 풀에 예치하고, 구간을 270~330으로 설정한다고 가정해 봅시다 (현재 TSLA 가격이 300이라고 가정).',
    step1: '1. 약 476 USDC를 계산하여 약 1.59 TSLA를 구매합니다.',
    step2: '2. 결과적으로 약 524 USDC와 약 1.59 TSLA를 보유하게 됩니다.',
    step3: '3. 이 자산들은 설정한 구간의 풀에 추가됩니다.',
    what_happens_in_different_price_scenarios:
      '가격 시나리오별로 어떤 일이 일어나나요?',
    desc_1: '1. 가격이 270~330 사이에 머무르면',
    desc_1_1: '계속 거래 수수료를 받습니다.',
    desc_2: '2. 가격이 270 아래로 떨어지면',
    desc_2_1:
      '포지션이 약 3.43 TSLA와 받은 수수료로 변환됩니다. 가격 회복을 믿는다면 그대로 보유하세요.',
    desc_3: '3. 가격이 330을 넘으면',
    desc_3_1:
      '포지션이 약 1023 USDC와 수수료로 변환됩니다. 약 23 USDC의 이익과 수수료를 얻게 됩니다.',
    underlying_on_chain_assets: '기반 온체인 자산',
    principal: '원금',
    unclaimed_yield: '미수령 수익',
    in_range: '구간 내',
    out_of_range: '구간 밖',
    total_pnl: '총 손익(P&L)',
    underlying_assets: '기초 자산',
    initial_principal: '초기 원금',
    closed_principal: '종료 원금',
    principal_pnl: '원금 손익(P&L)',
    created_at: '생성 일시',
    closed_at: '종료 일시',
    claim_yield: '수익 받기',
    all_TSLA_will_be_converted_to_USDC: '모든 {TSLA}는 {USDC}로 전환됩니다',
    est_receive: '예상 수령',
    claim_successful: '수령 성공',
    has_been_added_to_your_account: '계정에 추가되었습니다',
    claim_failed: '수령 실패',
    convert_TSLA_to_USDC_and_receive_USDC_only:
      '{TSLA}를 {USDC}로 전환하고 {USDC}만 수령',
    receive_both: '둘 다 수령',
    convert_TSLA_to_USDC_and_receive_USDC:
      '{TSLA}를 {USDC}로 전환하고 {USDC} 수령',
    receive_TSLA: '{TSLA} 수령',
    withdrawing: '출금 중',
    withdrawal_successful: '출금 성공',
    withdrawal_failed: '출금 실패',
    Simple_Earn: '단일 코인 예치',
    view_in_turbo_range: '구간 전략 상품에서 보기',
    position_history: '포지션 기록',
    initial_investment: '초기 투자',
    click_history_above_for_details:
      '자세한 내용은 위의 ICON 기록을 클릭하세요',
    how_does_turbo_range_earn_yield: '구간 전략 상품은 수익을 어떻게 내나요?',
    transaction_in_progress: '거래 1건 진행 중',
    transaction_successful: '거래 1건 성공',
    transaction_failed: '거래 1건 실패',
    N_transactions_in_progress: '거래 N건 진행 중',
    N_transactions_successful: '거래 N건 성공',
    N_transactions_failed: '거래 N건 실패',
    position: '포지션',
    all_time_yield: '누적 수익',
    yesterday_apy: '어제의 APY',
    duration: '기간',
    all_time_apy: '누적 APY',
    updating: '업데이트 중...',
    will_be_calculated_on_DATE: 'DATE에 계산됩니다',
    returned_to_your_wallet: '지갑으로 반환됨',
    principal_upon_closure: '종료 시 반환 원금',
    est_apy_tips:
      '여기 표시된 예상 연이율(APY)은 선택한 기간의 과거 데이터에서 산출되었습니다.',
    invalid_range: '잘못된 범위입니다',
    faq_1: '유동성 풀이란?',
    faq_1_text:
      '유동성 풀은 블록체인에 배포된 스마트 컨트랙트로, ETH와 USDC 같은 두 토큰을 보유합니다. 사용자는 이 컨트랙트를 통해 두 토큰 간을 직접 거래할 수 있습니다. 누구나 자신의 토큰을 풀에 예치해 유동성을 제공하고 거래 수수료를 지분대로 받을 수 있습니다.',
    faq_2: '유동성을 제공해 수수료를 벌려면 어떻게 해야 하나요?',
    faq_3: 'Turbo Range에 투자하면 어떤 장점이 있나요?',
    faq_3_text1:
      '전통적인 투자(예: TSLA 주식을 매수해 보유)는 가격이 오를 때만 수익이 납니다. Turbo Range는 달라서, 횡보장과 상승장 모두에서 수익을 얻을 수 있습니다.',
    faq_3_text2:
      '<b>횡보:</b> 설정한 가격 범위에서 계속 거래 수수료를 벌 수 있습니다',
    faq_3_text3:
      '<b>상승:</b> 원금 가치가 증가하고, 거래 수수료도 계속 벌게 됩니다',
    put_simply: '한마디로 말해:',
    put_simply_text:
      '가격이 오를 때뿐 아니라 횡보할 때도 수익을 낼 수 있습니다.',
    faq_4: 'DeGate가 제 Turbo Range 포지션을 통제하나요?',
    faq_4_text:
      '아니요. Turbo Range 포지션은 모두 온체인에 기록되며 사용자의 지갑에 보관됩니다. 자금에 접근하거나 출금할 수 있는 사람은 본인뿐입니다.',
    faq_4_n: 'Turbo Range로 저가 매수하려면 어떻게 하나요?',
    faq_4_n_text:
      '자산이 100에 거래 중이고 75 부근에서 모으고 싶다면 50–100 가격 범위의 Turbo Range를 생성하면 됩니다. 이 범위에서 가격이 움직이는 동안 Turbo Range는 지속적으로 수익(수수료 수익)을 발생시켜 평균 진입가를 낮추는 데 도움이 됩니다.',
    faq_4_n_text2:
      '가격이 50까지 떨어지면 Turbo Range를 반드시 종료하세요. 종료하지 않으면 가격이 50을 다시 상향 돌파할 때 포지션이 다시 매수를 시작합니다.',
    faq_6: '가격이 범위를 벗어나면 Turbo Range가 자동으로 종료되나요?',
    faq_6_text:
      '아니요, 자동으로 닫히지 않습니다. 가격이 범위로 돌아오면 Turbo Range는 수익 생성을 재개합니다. 범위를 벗어난 포지션을 멈추려면 수동으로 종료해야 합니다.',
    websites: '웹사이트',
    liquidity_pool: '유동성 풀',
    liquidity_pool_age: '유동성 풀 가동 기간',
    total_value_locked_of_raydium: '{Raydium}의 총 예치 가치(TVL)',
    XX_as_of_DATE: '{DATE} 기준: {XX}',
    market_cap_of_paxg: '{PAXG} 시가총액',

    desc_xstocks:
      'TSLAx는 Backed Assets (JE) Limited가 발행한 xStock입니다. xStock 발행은 스위스 법을 준수하며 2025년 5월 8일 리히텐슈타인 금융시장감독청(FMA)의 승인을 받았습니다.',
    desc_gold:
      'PAXG는 Paxos Trust Company가 발행한 디지털 자산입니다. 각 PAXG는 런던의 LBMA 금고에 보관된 순금 1 트로이온스로 담보됩니다. Paxos는 뉴욕주 금융서비스국(NYDFS)의 규제를 받습니다.',
    desc_btc:
      'cbBTC는 Coinbase가 발행한 비트코인 담보 토큰입니다. 각 cbBTC는 Coinbase가 보유한 1개의 비트코인을 나타내며 1:1로 상환 가능합니다. Coinbase는 미국 상장 기업이며 미국 규제 감독 하에 운영됩니다.',
    desc_native_coin_ETH_NETWORK:
      '{ETH} 는 {NETWORK} 네트워크의 네이티브 토큰입니다.',
    legal_documentation: '법적 문서',
    factsheet: '팩트시트',
    audit_reports: '감사 보고서',
    Onesheet: '원시트(요약)',
    on_chain_assets_and_protocol: '온체인 자산 및 프로토콜',
    entry_price: '진입 가격',
    active_capital: '운용 자본',
    withdraw_and_close: '출금하고 종료',
    withdraw_and_claim: '출금 및 청구',
    incl_unclaimed_yield: '미수령 수익 포함',
    capital_withdrawn: '인출된 자본',
    yield_claimed: '수령된 수익',
    fee_pre_charged:
      '이 수수료는 포지션 개설 시 선차감되었으며, 종료 시 지갑으로 반환됩니다.',

    price_is_out_of_range_see_tips:
      '가격이 범위를 벗어났습니다. 팁을 확인하세요.',
    what_do_you_think_XXX_s_price_will_do_next:
      '{XXX}의 가격이 다음에 어떻게 움직일 것 같나요…',
    rise_and_move_back_into_my_price_range: '상승하여 내 가격 범위로 다시 진입',
    move_sideways_around_the_current_price: '현재 가격 부근에서 횡보',
    keep_falling: '계속 하락',
    if_you_think_XXX_s_price_will_rise_and_move_back_into_your_price_range:
      '{XXX}의 가격이 상승해 내 가격 범위로 되돌아온다고 생각한다면…',
    you_will: '당신이 할 일',
    hold_and_wait: '보유하고 기다리기',
    if_you_think_XXX_s_price_will_move_sideways_around_the_current_price:
      '{XXX}의 가격이 현재 가격 주변에서 횡보할 것 같다면…',
    close_your_position_and_open_a_new_one: '포지션을 청산하고 새로 열기',
    close_position: '포지션 청산',
    if_you_think_XXX_s_price_will_keep_falling:
      '{XXX}의 가격이 계속 하락할 것 같다면…',
    close_position_and_withdraw_USDC: '포지션을 청산하고 USDC 인출',
    adjust_price_range: '가격 범위 조정',
    adjust_now: '지금 조정',
    increase_investment: '추가 투자',
    increasing_investment: '추가 투자 중',
    investment_increased: '추가 투자 완료',
    investment_increase: '추가 투자',
    increase_failed: '추가 실패',
    total_principal: '총 원금',
    total_withdrawal_and_claim: '총 출금 및 수령',
    investModeSingle: '단일 자산',
    investModeDual: '이중 자산',
    nagative_invest_tips:
      '이 음수 값은 지갑으로 반환된 자금을 나타냅니다. 자세한 내용은 포지션 기록을 참조하세요。',
    APY_Backtest: 'APY 백테스트',
    Historical_APY_desc:
      '여기 표시된 과거 연간 수익률(APY)은 선택한 기간의 과거 데이터로 산출한 백테스트 결과로, 해당 기간 시작 시점에 투자했을 때의 APY를 반영합니다.',
    Historical_APY: '과거 APY',
    XXX_Overall_APY: 'XXX 전체 APY',
    Partially_in_range: '부분 범위 내',
    In_range: '범위 내',
    Out_of_range: '범위 밖',

    // Strategies Marketplace
    strategies: '전략 광장',
    top_apy: '최고 APY',
    hot_today: '오늘의 인기',
    best_returns: '최고 수익률',
    roi: 'ROI (투자 수익률)',
    total_return: '총 수익',
    connect_wallet_to_see_positions: '지갑을 연결하여 포지션 보기',
    re_open: '다시 열기',
    view_details: '세부 정보 보기',
    copy: '복사',
    initial_price: '초기 가격',
  },
  Product: '상품',
  filter: '필터',
  Failed: '실패',
  History_currently_unavailable: '현재 기록을 사용할 수 없습니다.',
  History_currently_unavailable_tips:
    '홈 탭으로 이동해 지갑 주소를 복사하고, 블록체인 탐색기에서 거래 내역을 확인하세요.',
  Approval: '승인',
  Contract_Call: '컨트랙트 호출',
  Unlimited: '무제한',
  APY_1: '1 APY',
  External_Sites: '외부 사이트',
  XXX_Refundable: 'XXX 환불 가능',
  Refundable_on_data_release: '데이터 공개 시 환불 가능',
  est_time: '예상 시간',
  Refundable_when_position_is_closed: '포지션 종료 시 환불 가능',

  go_to_turbo_range: '구간 전략 상품으로 이동',
  go_to_earn: '심플 적립으로 이동',
  in_address: '주소에',
  in_copy_trade: '복사매매 내',
  source_network: '',
  destination_network: '',
  move_usdc_across_chains: 'USDC를 체인 간 1:1 비율로 이동',
  bridge_successful: '브리지 성공',
  no_result_found: '결과 없음',
  enter_address: '주소 입력',
  scan: '스캔',
  check_address_format: '주소 형식을 확인하세요.',
  invalid_address: '유효하지 않은 주소',
  estimated_network_fee: '예상 네트워크 수수료',
  incl_solana_rent_of_XXX: 'Solana 렌트 비용 $XXX 포함',
  check_my_balance: '내 잔액 확인',
  moving_your_USDC_to_destination_network: 'USDC를 대상 네트워크로 이동 중…',
  you_don_t_have_enough_USDC_to_pay_for_the_network_fee:
    '네트워크 수수료를 지불하기에 USDC가 부족합니다.',
  change_fee_token: '수수료 토큰 변경',
  estimated: '예상',
  actual: '실제',
  receive_usdc: 'USDC 받기',
  from_other_wallets: '다른 지갑에서',
  bridge_usdc: 'USDC 브리지',
  consolidate_to_one_chain: '한 개 체인으로 합치기',
  simple_earn_disabled_deposit_tips:
    '본 볼트는 담보 자산의 변동성이 큽니다. 주의해서 진행하세요.',
  Time_to_complete: '완료까지 시간',
  You_Pay: '결제 금액',
  Returned_to_your_wallet_when_position_is_closed:
    '포지션 종료 시 지갑으로 반환됩니다',
  Refundable_Fee: '환불 가능한 수수료',
  Fee_Refunded: '수수료 환불 완료',
  Claiming: '수령 중',
  Reinvesting: '재투자 중',
  Withdrawing: '출금 중',
  Adding: '추가 중',
  Cash_Buy: '구매',
  Buy_with_cash_card: '현금/카드로 구매',

  est_gas_needed_for_network_fee: '네트워크 수수료로 $EST_GAS USDC 예약됨',
  available_amount: '사용 가능 금액',
  current_balance: '현재 잔액',
  reserved_for_network_fee: '네트워크 수수료로 예약됨',
  maximum_available: '최대 사용 가능',
  use_max: '최대 사용',
  edit_amount: '금액 편집',
  insufficient_network_fee: '네트워크 수수료가 부족합니다',
  separator_comma: ',',
  insufficient_network_fee_tips:
    '네트워크 수수료 $FEE 가 필요합니다. $XXX, USDC, USDT 또는 다른 토큰으로 지불할 수 있습니다.',
  pay_with_another_token: '다른 토큰으로 결제',

  History_is_currently_unavailable_for_CHAIN:
    '{CHAIN}의 기록을 현재 사용할 수 없습니다. 자세한 내용은 블록체인 탐색기에서 확인하세요.',
  Check_on_Explorer: '탐색기에서 확인',
  Min: '최소',
  Max: '최대',
  enable_notifications: '알림을 켜시겠어요?',
  receive_notification_when_out_of_price_range:
    '가격이 범위를 벗어나면 알림 받기',
  we_ll_notify_you_when_your_turbo_range_goes_out_of_range:
    '사용 중인 Turbo Range 가 범위를 벗어나면 알려드려요.',

  referral: '추천',
  referral_code: '추천 코드',
  your_referrer: '추천인',
  please_confirm_within_10_seconds: '10초 이내에 확인해 주세요.',
  confirmation_expired: '확인이 만료되었습니다. 다시 시도해 주세요.',

  select_Open_in_Default_Browser_from_the_menu:
    '메뉴에서 “기본 브라우저로 열기”를 선택하세요.',
  you_need_a_DeGate_account_to_continue: '계속하려면 DeGate 계정이 필요합니다.',
  claim_now: '지금 받기',
  please_wait_it_takes_xx_seconds: '잠시만 기다려 주세요. 약 ~xx초 걸립니다.',
  you_have_received_a_Turbo_Range_position_worth_XXX:
    '~$XXX 상당의 Turbo Range 포지션을 받았습니다.',
  view_my_balance: '내 잔액 보기',
  sorry_youve_already_claimed_once: '죄송합니다. 이미 한 번 수령하셨습니다.',
  gift_card_expired: '기프트 카드가 만료되었습니다',
  gift_card_has_not_been_activated: '기프트 카드가 아직 활성화되지 않았습니다',
  gift_card_has_been_claimed: '기프트 카드는 이미 수령되었습니다',
  please_open_this_page_on_your_mobile_phone:
    '이 페이지를 휴대폰에서 열어 주세요',
  open_with_DeGate_App: 'DeGate 앱으로 열기',
  sign_in: '로그인',
  Show_more: '더 보기',
  signature_free_mode_tips:
    '이 모드에서는 서명 없이 토큰을 스왑할 수 있습니다. 모드를 바꾸려면 오른쪽 상단의 설정 아이콘을 클릭하세요。',
  invite_to_degate_experience_enhancement_program:
    'DeGate 경험 향상 프로그램에 초대되었습니다',
  as_a_selected_user_youll_get: '선정된 사용자로서 다음을 받게 됩니다:',
  a_smoother_app_experience: '더욱 원활한 앱 경험',
  dedicated_one_on_one_support: '전담 1:1 지원',
  private_client_desk: '프라이빗 클라이언트 데스크',
  private_client_desk_upperCase: '프라이빗 클라이언트 데스크',
  through_this_desk_you_may:
    '이 데스크를 통해 다음과 같은 혜택을 누리실 수 있습니다:',
  receive_priority_operational_support: '우선 운영 지원 제공',
  direct_communication_with_our_strategy_and_operations_team:
    '전략 및 운영 팀과 직접 소통',
  early_access_to_new_products: '신제품 조기 체험',
  access_exclusive_privileges_and_customized_benefits:
    '독점 특권 및 맞춤형 혜택 이용',
  private_client_desk_access_path_intro:
    '다음 경로로 프라이빗 클라이언트 데스크에 액세스할 수 있습니다:',
  private_client_desk_access_path_home_menu:
    '홈 > 메뉴 > 프라이빗 클라이언트 데스크',
  private_client_desk_access_path_home_settings:
    '홈 > 설정 > 프라이빗 클라이언트 데스크',
  private_client_desk_access_bottom_left_corner:
    '왼쪽 하단에서 프라이빗 클라이언트 데스크에 액세스할 수 있습니다',
  WhatsApp: 'WhatsApp',
  Signal: 'Signal',
  Email: '이메일',
  welcome_aboard: '환영합니다',
  youre_now_among_a_select_group_enjoying_an_enhanced_degate_experience:
    '이제 향상된 DeGate 경험을 누리는 선택된 그룹에 속합니다.',
  link_expired: '링크가 만료되었습니다',
  please_update_your_app_to_the_latest_version: '최신 버전으로 업데이트하세요',
  chart_is_currently_unavailable: '차트를 현재 사용할 수 없습니다.',
};
export default kr;
