const map = {
  Info: {
    from: 'Info',
    to: 'Analytics',
    zh: '数据',
    zh2: '数据',
    en: 'Analytics',
    en2: 'Analytics',
  },
  deposit: {
    from: 'deposit',
    to: 'Add',
    zh: '划入',
    zh2: '划入',
    en: 'Add',
    en2: 'Add',
  },
  withdraw: {
    from: 'withdraw',
    to: 'Send',
    zh: '发送',
    zh2: '发送',
    en: 'Send',
    en2: 'Send',
  },
  transfer: {
    from: 'transfer',
    to: 'Internal_Transfer',
    zh: '内部转账',
    zh2: '内部转账',
    en: 'Internal Transfer',
    en2: 'Internal Transfer',
  },
  btn_all: {
    from: 'btn_all',
    to: 'history',
    zh: '历史',
    zh2: '历史',
    en: 'History',
    en2: 'History',
  },
  time_D_d: {
    from: 'time_D_d',
    to: 'time_D_day',
    zh: 'D天',
    zh2: 'D天',
    en: 'Dd',
    en2: 'Dd',
  },
  code: {
    from: 'code',
    to: 'Address',
    zh: '地址',
    zh2: '地址',
    en: 'Address',
    en2: 'Address',
  },
  side_buy: {
    from: 'side_buy',
    to: 'Buy',
    zh: '买入',
    zh2: '买入',
    en: 'Buy',
    en2: 'Buy',
  },
  side_sell: {
    from: 'side_sell',
    to: 'Sell',
    zh: '卖出',
    zh2: '卖出',
    en: 'Sell',
    en2: 'Sell',
  },
  btn_buy: {
    from: 'btn_buy',
    to: 'Buy',
    zh: '买入',
    zh2: '买入',
    en: 'Buy',
    en2: 'Buy',
  },
  btn_sell: {
    from: 'btn_sell',
    to: 'Sell',
    zh: '卖出',
    zh2: '卖出',
    en: 'Sell',
    en2: 'Sell',
  },
  sign_to_view_success: {
    from: 'sign_to_view_success',
    to: 'status_success',
    zh: '成功',
    zh2: '成功',
    en: 'Success',
    en2: 'Success',
  },
  option_all: {
    from: 'option_all',
    to: 'all',
    zh: '全部',
    zh2: '全部',
    en: 'All',
    en2: 'All',
  },
  cancel: {
    from: 'cancel',
    to: 'Cancel',
    zh: '取消',
    zh2: '取消',
    en: 'Cancel',
    en2: 'Cancel',
  },
  trade: {
    from: 'trade',
    to: 'Trade',
    zh: '交易',
    zh2: '交易',
    en: 'Trade',
    en2: 'Trade',
  },
  add_funds_trade: {
    from: 'add_funds_trade',
    to: 'Trade',
    zh: '交易',
    zh2: '交易',
    en: 'Trade',
    en2: 'Trade',
  },
  filter_side: {
    from: 'filter_side',
    to: 'Side',
    zh: '方向',
    zh2: '方向',
    en: 'Side',
    en2: 'Side',
  },
  order_type: {
    from: 'order_type',
    to: 'filter_type',
    zh: '类型',
    zh2: '类型',
    en: 'Type',
    en2: 'Type',
  },
  status_ended: {
    from: 'status_ended',
    to: 'ended',
    zh: '已关闭',
    zh2: '已关闭',
    en: 'Ended',
    en2: 'Ended',
  },
  status_active: {
    from: 'status_active',
    to: 'active',
    zh: '运行中',
    zh2: '运行中',
    en: 'Active',
    en2: 'Active',
  },
  status_closed: {
    from: 'status_closed',
    to: 'ended',
    zh: '已关闭',
    zh2: '已关闭',
    en: 'Ended',
    en2: 'Ended',
  },
  status_expired: {
    from: 'status_expired',
    to: 'Expired',
    zh: '已过期',
    zh2: '已过期',
    en: 'Expired',
    en2: 'Expired',
  },
  disconnect_wallet: {
    from: 'disconnect_wallet',
    to: 'disconnect_m',
    zh: '断开',
    zh2: '断开',
    en: 'Disconnect',
    en2: 'Disconnect',
  },
  'account.account_withdraw': {
    from: 'account.account_withdraw',
    to: 'Send',
    zh: '发送',
    zh2: '发送',
    en: 'Send',
    en2: 'Send',
  },
  'account.assets_symbol': {
    from: 'account.assets_symbol',
    to: 'token',
    zh: '币种',
    zh2: '币种',
    en: 'Token',
    en2: 'Token',
  },
  'account.assets_opr': {
    from: 'account.assets_opr',
    to: 'action',
    zh: '操作',
    zh2: '操作',
    en: 'Action',
    en2: 'Action',
  },
  'account.assets_search_placeholder': {
    from: 'account.assets_search_placeholder',
    to: 'trade.pair_search',
    zh: '搜索币种、合约地址',
    zh2: '搜索币种、合约地址',
    en: 'Search token, contract address',
    en2: 'Search token, contract address',
  },
  'account.deposit_status_confirming': {
    from: 'account.deposit_status_confirming',
    to: 'status_confirming',
    zh: '确认中',
    zh2: '确认中',
    en: 'Confirming',
    en2: 'Confirming',
  },
  'account.register_token_name': {
    from: 'account.register_token_name',
    to: 'name',
    zh: '名称',
    zh2: '名称',
    en: 'Name',
    en2: 'Name',
  },
  'account.th_amount': {
    from: 'account.th_amount',
    to: 'amount',
    zh: '数量',
    zh2: '数量',
    en: 'Amount',
    en2: 'Amount',
  },
  'account.th_status': {
    from: 'account.th_status',
    to: 'status',
    zh: '状态',
    zh2: '状态',
    en: 'Status',
    en2: 'Status',
  },
  'account.th_tx_address': {
    from: 'account.th_tx_address',
    to: 'Address',
    zh: '地址',
    zh2: '地址',
    en: 'Address',
    en2: 'Address',
  },
  'account.withdraw_processing_tips': {
    from: 'account.withdraw_processing_tips',
    to: 'Sending',
    zh: '正在发送',
    zh2: '正在发送',
    en: 'Sending',
    en2: 'Sending',
  },
  'account.locked_withdraw': {
    from: 'account.locked_withdraw',
    to: 'Sending',
    zh: '正在发送',
    zh2: '正在发送',
    en: 'Sending',
    en2: 'Sending',
  },
  'account.deposit_type_advanced': {
    from: 'account.deposit_type_advanced',
    to: 'Advanced',
    zh: '高级',
    zh2: '高级',
    en: 'Advanced',
    en2: 'Advanced',
  },
  'account.deposit_approve_btn': {
    from: 'account.deposit_approve_btn',
    to: 'account.approve',
    zh: '授权',
    zh2: '授权',
    en: 'Approve',
    en2: 'Approve',
  },
  'account.tab_yield': {
    from: 'account.tab_yield',
    to: 'yield',
    zh: '分红',
    zh2: '分红',
    en: 'Yield',
    en2: 'Yield',
  },
  'account.claim': {
    from: 'account.claim',
    to: 'Claim',
    zh: '领取',
    zh2: '领取',
    en: 'Claim',
    en2: 'Claim',
  },
  'menu.menu_balance': {
    from: 'menu.menu_balance',
    to: 'balance',
    zh: '余额',
    zh2: '余额',
    en: 'Balance',
    en2: 'Balance',
  },
  'menu.menu_history': {
    from: 'menu.menu_history',
    to: 'history',
    zh: '历史',
    zh2: '历史',
    en: 'History',
    en2: 'History',
  },
  'menu.menu_security': {
    from: 'menu.menu_security',
    to: 'security',
    zh: '安全',
    zh2: '安全',
    en: 'Security',
    en2: 'Security',
  },
  'trade.price': {
    from: 'trade.price',
    to: 'price',
    zh: '价格',
    zh2: '价格',
    en: 'Price',
    en2: 'Price',
  },
  'trade.tab_buy': {
    from: 'trade.tab_buy',
    to: 'BUY',
    zh: '买入',
    zh2: '买入',
    en: 'BUY',
    en2: 'BUY',
  },
  'trade.tab_sell': {
    from: 'trade.tab_sell',
    to: 'SELL',
    zh: '卖出',
    zh2: '卖出',
    en: 'SELL',
    en2: 'SELL',
  },
  'trade.tab_limit_order': {
    from: 'trade.tab_limit_order',
    to: 'limit_order',
    zh: '限价',
    zh2: '限价',
    en: 'Limit',
    en2: 'Limit',
  },
  'trade.tab_market_order': {
    from: 'trade.tab_market_order',
    to: 'market_order',
    zh: '市价',
    zh2: '市价',
    en: 'Market',
    en2: 'Market',
  },
  'trade.tab_stop_limit_order': {
    from: 'trade.tab_stop_limit_order',
    to: 'stop_limit_order',
    zh: '止盈止损',
    zh2: '止盈止损',
    en: 'Stop Limit',
    en2: 'Stop Limit',
  },
  'trade.type_limit_order': {
    from: 'trade.type_limit_order',
    to: 'limit_order',
    zh: '限价',
    zh2: '限价',
    en: 'Limit',
    en2: 'Limit',
  },
  'trade.type_market_order': {
    from: 'trade.type_market_order',
    to: 'market_order',
    zh: '市价',
    zh2: '市价',
    en: 'Market',
    en2: 'Market',
  },
  'trade.type_stop_limit_order': {
    from: 'trade.type_stop_limit_order',
    to: 'stop_limit_order',
    zh: '止盈止损',
    zh2: '止盈止损',
    en: 'Stop Limit',
    en2: 'Stop Limit',
  },
  'trade.placeholder_price': {
    from: 'trade.placeholder_price',
    to: 'price',
    zh: '价格',
    zh2: '价格',
    en: 'Price',
    en2: 'Price',
  },
  'trade.placeholder_amount': {
    from: 'trade.placeholder_amount',
    to: 'amount',
    zh: '数量',
    zh2: '数量',
    en: 'Amount',
    en2: 'Amount',
  },
  'trade.period_day': {
    from: 'trade.period_day',
    to: 'Days',
    zh: '天',
    zh2: '天',
    en: 'Days',
    en2: 'Days',
  },
  'trade.period_hour': {
    from: 'trade.period_hour',
    to: 'Hours',
    zh: '小时',
    zh2: '小时',
    en: 'Hours',
    en2: 'Hours',
  },
  'trade.period_minute': {
    from: 'trade.period_minute',
    to: 'Minutes',
    zh: '分钟',
    zh2: '分钟',
    en: 'Minutes',
    en2: 'Minutes',
  },
  'trade.max_peroid_XXX': {
    from: 'trade.max_peroid_XXX',
    to: 'max_XXX',
    zh: '最大为XXX',
    zh2: '最大为XXX',
    en: 'Max XXX',
    en2: 'Max XXX',
  },
  'trade.peroid_D_day': {
    from: 'trade.peroid_D_day',
    to: 'time_D_day',
    zh: 'D天',
    zh2: 'D天',
    en: 'Dd',
    en2: 'Dd',
  },
  'trade.peroid_D_day_H_hour': {
    from: 'trade.peroid_D_day_H_hour',
    to: 'time_D_day_H_hour',
    zh: 'D天H小时',
    zh2: 'D天H小时',
    en: 'Dd Hh',
    en2: 'Dd Hh',
  },
  'trade.peroid_H_hour_M_minute': {
    from: 'trade.peroid_H_hour_M_minute',
    to: 'time_H_hour_M_minute',
    zh: 'H小时M分钟',
    zh2: 'H小时M分钟',
    en: 'Hh Mm',
    en2: 'Hh Mm',
  },
  'trade.peroid_M_minute': {
    from: 'trade.peroid_M_minute',
    to: 'time_M_m',
    zh: 'M分钟',
    zh2: 'M分钟',
    en: 'Mm',
    en2: 'Mm',
  },
  'trade.period_expired': {
    from: 'trade.period_expired',
    to: 'status_expired',
    zh: '已过期',
    zh2: '已过期',
    en: 'Expired',
    en2: 'Expired',
  },
  'trade.max_gas_fee': {
    from: 'trade.max_gas_fee',
    to: 'max_gas',
    zh: '最大矿工费',
    zh2: '最大矿工费',
    en: 'Max Gas Fee',
    en2: 'Max Gas Fee',
  },
  'trade.pair_all': {
    from: 'trade.pair_all',
    to: 'all',
    zh: '全部',
    zh2: '全部',
    en: 'All',
    en2: 'All',
  },
  'trade.user_limit': {
    from: 'trade.user_limit',
    to: 'insufficient_balance',
    zh: '余额不足',
    zh2: '余额不足',
    en: 'Insufficient balance',
    en2: 'Insufficient balance',
  },
  'trade.user_limit_with_gas': {
    from: 'trade.user_limit_with_gas',
    to: 'insufficient_balance',
    zh: '余额不足',
    zh2: '余额不足',
    en: 'Insufficient balance',
    en2: 'Insufficient balance',
  },
  'orders.openOrders': {
    from: 'orders.openOrders',
    to: 'open_orders',
    zh: '当前订单',
    zh2: '当前订单',
    en: 'Open Orders',
    en2: 'Open Orders',
  },
  'trade.pair_market': {
    from: 'trade.pair_market',
    to: 'Pair',
    zh: '交易对',
    zh2: '交易对',
    en: 'Pair',
    en2: 'Pair',
  },
  'orders.th_orderType': {
    from: 'orders.th_orderType',
    to: 'filter_type',
    zh: '类型',
    zh2: '类型',
    en: 'Type',
    en2: 'Type',
  },
  'orders.th_orderDir': {
    from: 'orders.th_orderDir',
    to: 'Side',
    zh: '方向',
    zh2: '方向',
    en: 'Side',
    en2: 'Side',
  },
  'orders.th_price': {
    from: 'orders.th_price',
    to: 'price',
    zh: '价格',
    zh2: '价格',
    en: 'Price',
    en2: 'Price',
  },
  'trade.placeholder_stop_price': {
    from: 'trade.placeholder_stop_price',
    to: 'orders.th_stop_price',
    zh: '触发价',
    zh2: '触发价',
    en: 'Stop Price',
    en2: 'Stop Price',
  },
  'trade.placeholder_limit_price': {
    from: 'trade.placeholder_limit_price',
    to: 'orders.th_limit_price',
    zh: '委托价',
    zh2: '委托价',
    en: 'Limit Price',
    en2: 'Limit Price',
  },
  'orders.th_amount': {
    from: 'orders.th_amount',
    to: 'amount',
    zh: '数量',
    zh2: '数量',
    en: 'Amount',
    en2: 'Amount',
  },
  'orders.th_status': {
    from: 'orders.th_status',
    to: 'status',
    zh: '状态',
    zh2: '状态',
    en: 'Status',
    en2: 'Status',
  },
  'orders.th_trade_fee': {
    from: 'orders.th_trade_fee',
    to: 'trade_fee',
    zh: '手续费',
    zh2: '手续费',
    en: 'Trading Fee',
    en2: 'Trading Fee',
  },
  'orders.th_gas': {
    from: 'orders.th_gas',
    to: 'gas_fee',
    zh: '矿工费',
    zh2: '矿工费',
    en: 'Gas Fee',
    en2: 'Gas Fee',
  },
  'orders.th_maker_taker': {
    from: 'orders.th_maker_taker',
    to: 'filter_role',
    zh: '角色',
    zh2: '角色',
    en: 'Role',
    en2: 'Role',
  },
  'orders.side_buy': {
    from: 'orders.side_buy',
    to: 'Buy',
    zh: '买入',
    zh2: '买入',
    en: 'Buy',
    en2: 'Buy',
  },
  'orders.side_sell': {
    from: 'orders.side_sell',
    to: 'Sell',
    zh: '卖出',
    zh2: '卖出',
    en: 'Sell',
    en2: 'Sell',
  },
  'orders.status_canceled': {
    from: 'orders.status_canceled',
    to: 'status_canceled',
    zh: '已取消',
    zh2: '已取消',
    en: 'Canceled',
    en2: 'Canceled',
  },
  'orders.detail_amount': {
    from: 'orders.detail_amount',
    to: 'filledAmount_amount',
    zh: '已成交/订单数量',
    zh2: '已成交/订单数量',
    en: 'Filled/Amount',
    en2: 'Filled/Amount',
  },
  'orders.detail_total_fee': {
    from: 'orders.detail_total_fee',
    to: 'trade_fee',
    zh: '手续费',
    zh2: '手续费',
    en: 'Trading Fee',
    en2: 'Trading Fee',
  },
  'orders.detail_max_gas': {
    from: 'orders.detail_max_gas',
    to: 'max_gas',
    zh: '最大矿工费',
    zh2: '最大矿工费',
    en: 'Max Gas Fee',
    en2: 'Max Gas Fee',
  },
  'orders.detail_filled_price': {
    from: 'orders.detail_filled_price',
    to: 'price',
    zh: '价格',
    zh2: '价格',
    en: 'Price',
    en2: 'Price',
  },
  'orders.detail_filled_amount': {
    from: 'orders.detail_filled_amount',
    to: 'amount',
    zh: '数量',
    zh2: '数量',
    en: 'Amount',
    en2: 'Amount',
  },
  'orders.detail_filled_fee': {
    from: 'orders.detail_filled_fee',
    to: 'trade_fee',
    zh: '手续费',
    zh2: '手续费',
    en: 'Trading Fee',
    en2: 'Trading Fee',
  },
  'orders.detail_filled_gas': {
    from: 'orders.detail_filled_gas',
    to: 'gas_fee',
    zh: '矿工费',
    zh2: '矿工费',
    en: 'Gas Fee',
    en2: 'Gas Fee',
  },
  'orders.order_maker': {
    from: 'orders.order_maker',
    to: 'option_maker',
    zh: 'Maker',
    zh2: 'Maker',
    en: 'Maker',
    en2: 'Maker',
  },
  'orders.order_taker': {
    from: 'orders.order_taker',
    to: 'option_taker',
    zh: 'Taker',
    zh2: 'Taker',
    en: 'Taker',
    en2: 'Taker',
  },
  'gridTrade.grid_tutorial': {
    from: 'gridTrade.grid_tutorial',
    to: 'Tutorial',
    zh: '教程',
    zh2: '教程',
    en: 'Tutorial',
    en2: 'Tutorial',
  },
  'gridTrade.min_grid_volume_XXX': {
    from: 'gridTrade.min_grid_volume_XXX',
    to: 'trade_min_volume_tips_XXX',
    zh: '最少为XXX',
    zh2: '最少为XXX',
    en: 'Min XXX',
    en2: 'Min XXX',
  },
  'gridTrade.grid_chain_cancel': {
    from: 'gridTrade.grid_chain_cancel',
    to: 'chain_cancel',
    zh: '链上取消',
    zh2: '链上取消',
    en: 'Cancel On-Chain',
    en2: 'Cancel On-Chain',
  },
  'gridOrders.grid_running': {
    from: 'gridOrders.grid_running',
    to: 'active',
    zh: '运行中',
    zh2: '运行中',
    en: 'Active',
    en2: 'Active',
  },
  'gridOrders.grid_history': {
    from: 'gridOrders.grid_history',
    to: 'ended',
    zh: '已关闭',
    zh2: '已关闭',
    en: 'Ended',
    en2: 'Ended',
  },
  'gridOrders.th_stragety': {
    from: 'gridOrders.th_stragety',
    to: 'Grid',
    zh: '网格策略',
    zh2: '网格策略',
    en: 'Grid Strategy',
    en2: 'Grid Strategy',
  },
  'gridTrade.price_range': {
    from: 'gridTrade.price_range',
    to: 'gridOrders.detail_prices',
    zh: '价格区间',
    zh2: '价格区间',
    en: 'Price Range',
    en2: 'Price Range',
  },
  'gridTrade.grid_levels': {
    from: 'gridTrade.grid_levels',
    to: 'number_of_grids',
    zh: '网格数',
    zh2: '网格数',
    en: 'Number of Grids',
    en2: 'Number of Grids',
  },
  'gridTrade.detail_grid_levels': {
    from: 'gridOrders.detail_grid_levels',
    to: 'number_of_grids',
    zh: '网格数',
    zh2: '网格数',
    en: 'Number of Grids',
    en2: 'Number of Grids',
  },
  'gridOrders.th_profit': {
    from: 'gridOrders.th_profit',
    to: 'profit',
    zh: '收益',
    zh2: '收益',
    en: 'Profit',
    en2: 'Profit',
  },
  'account.tab_grid_profit': {
    from: 'account.tab_grid_profit',
    to: 'gridOrders.grid_profit',
    zh: '网格收益',
    zh2: '网格收益',
    en: 'Grid Profit',
    en2: 'Grid Profit',
  },
  'account.profit_24h': {
    from: 'account.profit_24h',
    to: 'm.grid_profit_24',
    zh: '24小时收益',
    zh2: '24小时收益',
    en: '24h Profit',
    en2: '24h Profit',
  },
  'orders.tradeHistory': {
    from: 'orders.tradeHistory',
    to: 'gridOrders.tab_trade_history',
    zh: '历史成交',
    zh2: '历史成交',
    en: 'Trade History',
    en2: 'Trade History',
  },
  'gridOrders.th_current_balances': {
    from: 'gridOrders.th_current_balances',
    to: 'gridOrders.detail_current_balance',
    zh: '当前余额',
    zh2: '当前余额',
    en: 'Current Balance',
    en2: 'Current Balance',
  },
  'gridOrders.th_ending_balances': {
    from: 'gridOrders.th_ending_balances',
    to: 'gridOrders.detail_ending_balance',
    zh: '结束余额',
    zh2: '结束余额',
    en: 'End Balance',
    en2: 'End Balance',
  },
  'gridOrders.th_orders': {
    from: 'gridOrders.th_orders',
    to: 'gridOrders.detail_transactions',
    zh: '订单完成总数',
    zh2: '订单完成总数',
    en: 'Number of Filled Orders',
    en2: 'Number of Filled Orders',
  },
  'gridOrders.th_running_time': {
    from: 'gridOrders.th_running_time',
    to: 'gridOrders.detail_running_time',
    zh: '运行时长',
    zh2: '运行时长',
    en: 'Duration',
    en2: 'Duration',
  },
  'gridOrders.detail_start_time': {
    from: 'gridOrders.detail_start_time',
    to: 'time_created',
    zh: '创建时间',
    zh2: '创建时间',
    en: 'Time Created',
    en2: 'Time Created',
  },
  'gridOrders.detail_end_time': {
    from: 'gridOrders.detail_end_time',
    to: 'time_ended',
    zh: '结束时间',
    zh2: '结束时间',
    en: 'Time Ended',
    en2: 'Time Ended',
  },
  'gridOrders.open_orders_amount': {
    from: 'gridOrders.open_orders_amount',
    to: 'amount',
    zh: '数量',
    zh2: '数量',
    en: 'Amount',
    en2: 'Amount',
  },
  'gridOrders.open_orders_price': {
    from: 'gridOrders.open_orders_price',
    to: 'price',
    zh: '价格',
    zh2: '价格',
    en: 'Price',
    en2: 'Price',
  },
  'gridOrders.status_closed': {
    from: 'gridOrders.status_closed',
    to: 'ended',
    zh: '已关闭',
    zh2: '已关闭',
    en: 'Ended',
    en2: 'Ended',
  },
  'gridOrders.status_running': {
    from: 'gridOrders.status_running',
    to: 'active',
    zh: '运行中',
    zh2: '运行中',
    en: 'Active',
    en2: 'Active',
  },
  'gridOrders.status_expired': {
    from: 'gridOrders.status_expired',
    to: 'status_expired',
    zh: '已过期',
    zh2: '已过期',
    en: 'Expired',
    en2: 'Expired',
  },
  'gridOrders.history_orders_dir': {
    from: 'gridOrders.history_orders_dir',
    to: 'Side',
    zh: '方向',
    zh2: '方向',
    en: 'Side',
    en2: 'Side',
  },
  'gridOrders.history_orders_type': {
    from: 'gridOrders.history_orders_type',
    to: 'filter_type',
    zh: '类型',
    zh2: '类型',
    en: 'Type',
    en2: 'Type',
  },
  'gridOrders.history_orders_amount': {
    from: 'gridOrders.history_orders_amount',
    to: 'amount',
    zh: '数量',
    zh2: '数量',
    en: 'Amount',
    en2: 'Amount',
  },
  'gridOrders.history_orders_profit': {
    from: 'gridOrders.history_orders_profit',
    to: 'profit',
    zh: '收益',
    zh2: '收益',
    en: 'Profit',
    en2: 'Profit',
  },
  'gridOrders.tab_m_mining': {
    from: 'gridOrders.tab_m_mining',
    to: 'Mining',
    zh: '挖矿',
    zh2: '挖矿',
    en: 'Mining',
    en2: 'Mining',
  },
  'gridOrders.tab_m_summary': {
    from: 'gridOrders.tab_m_summary',
    to: 'Summary',
    zh: '摘要',
    zh2: '摘要',
    en: 'Summary',
    en2: 'Summary',
  },
  'gridOrders.mining_orders_side': {
    from: 'gridOrders.mining_orders_side',
    to: 'Side',
    zh: '方向',
    zh2: '方向',
    en: 'Side',
    en2: 'Side',
  },
  'gridOrders.mining_orders_status': {
    from: 'gridOrders.mining_orders_status',
    to: 'status',
    zh: '状态',
    zh2: '状态',
    en: 'Status',
    en2: 'Status',
  },
  'mining.index_title': {
    from: 'mining.index_title',
    to: 'Liquidity_Mining',
    zh: '流动性挖矿',
    zh2: '流动性挖矿',
    en: 'Liquidity Mining',
    en2: 'Liquidity Mining',
  },
  'mining.claim': {
    from: 'mining.claim',
    to: 'Claim',
    zh: '领取',
    zh2: '领取',
    en: 'Claim',
    en2: 'Claim',
  },
  'mining.pools_th_open_time': {
    from: 'mining.pools_th_open_time',
    to: 'start_time',
    zh: '开始时间',
    zh2: '开始时间',
    en: 'Start Time',
    en2: 'Start Time',
  },
  'mining.pools_th_end_time': {
    from: 'mining.pools_th_end_time',
    to: 'end_time',
    zh: '结束时间',
    zh2: '结束时间',
    en: 'End Time',
    en2: 'End Time',
  },
  'mining.mining_rule': {
    from: 'mining.mining_rule',
    to: 'mining.view_rule_link',
    zh: '挖矿规则',
    zh2: '挖矿规则',
    en: 'Mining Rules',
    en2: 'Mining Rules',
  },
  'mining.my_th_profit_token': {
    from: 'mining.my_th_profit_token',
    to: 'token',
    zh: '币种',
    zh2: '币种',
    en: 'Token',
    en2: 'Token',
  },
  'mining.my_th_grid': {
    from: 'mining.my_th_grid',
    to: 'Grid',
    zh: '网格策略',
    zh2: '网格策略',
    en: 'Grid Strategy',
    en2: 'Grid Strategy',
  },
  'mining.my_th_create_time': {
    from: 'mining.my_th_create_time',
    to: 'time_created',
    zh: '创建时间',
    zh2: '创建时间',
    en: 'Time Created',
    en2: 'Time Created',
  },
  'account.grid_profit_24h': {
    from: 'account.grid_profit_24h',
    to: 'grid_profit_24h',
    zh: '24小时网格收益',
    zh2: '24小时网格收益',
    en: '24h Grid Profit',
    en2: '24h Grid Profit',
  },
  'mining.my_24h_profit': {
    from: 'mining.my_24h_profit',
    to: 'mining.mining_24h_profit',
    zh: '24小时挖矿收益',
    zh2: '24小时挖矿收益',
    en: '24h Mining Rewards',
    en2: '24h Mining Rewards',
  },
  'mining.my_th_funds': {
    from: 'mining.my_th_funds',
    to: 'mining.mining_funds',
    zh: '挖矿资金',
    zh2: '挖矿资金',
    en: 'Mining Funds',
    en2: 'Mining Funds',
  },
  'mining.phase_start': {
    from: 'mining.phase_start',
    to: 'start_time',
    zh: '开始时间',
    zh2: '开始时间',
    en: 'Start Time',
    en2: 'Start Time',
  },
  'mining.phase_end': {
    from: 'mining.phase_end',
    to: 'end_time',
    zh: '结束时间',
    zh2: '结束时间',
    en: 'End Time',
    en2: 'End Time',
  },
  'mining.daily_rewards': {
    from: 'mining.daily_rewards',
    to: 'mining.phase_reward',
    zh: '每日奖励',
    zh2: '每日奖励',
    en: 'Daily Rewards',
    en2: 'Daily Rewards',
  },
  'account.assets_balance_locked': {
    from: 'account.assets_balance_locked',
    to: 'mining.locked_rewards',
    zh: '冻结',
    zh2: '冻结',
    en: 'Locked',
    en2: 'Locked',
  },
  'notification.cancel_limit_order_title': {
    from: 'notification.cancel_limit_order_title',
    to: 'notification.cancel_market_for_depth_title',
    zh: '订单部分成交并已取消',
    zh2: '订单部分成交并已取消',
    en: 'Order Partially Filled and Canceled',
    en2: 'Order Partially Filled and Canceled',
  },
  'm.trade': {
    from: 'm.trade',
    to: 'Trade',
    zh: '交易',
    zh2: '交易',
    en: 'Trade',
    en2: 'Trade',
  },
  'm.balance': {
    from: 'm.balance',
    to: 'balance',
    zh: '余额',
    zh2: '余额',
    en: 'Balance',
    en2: 'Balance',
  },
  'm.advanced_settings': {
    from: 'm.advanced_settings',
    to: 'trade.more_settings',
    zh: '设置',
    zh2: '设置',
    en: 'Settings',
    en2: 'Settings',
  },
  'trade.order_book_depth_decimal': {
    from: 'trade.order_book_depth_decimal',
    to: 'm.decimals',
    zh: '小数位',
    zh2: '小数位',
    en: 'Decimal',
    en2: 'Decimal',
  },
  'trade.register_pair_modal_btn_trade': {
    from: 'trade.register_pair_modal_btn_trade',
    to: 'm.go_to_trade',
    zh: '去交易',
    zh2: '去交易',
    en: 'Go to Trade',
    en2: 'Go to Trade',
  },
  'm.grid_trades_24': {
    from: 'm.grid_trades_24',
    to: 'trades_24h',
    zh: '24小时成交',
    zh2: '24小时成交',
    en: '24h Trades',
    en2: '24h Trades',
  },
  'gridTrade.confirm_btn': {
    from: 'gridTrade.confirm_btn',
    to: 'm.create_grid',
    zh: '创建网格策略',
    zh2: '创建网格策略',
    en: 'Create Grid Strategy',
    en2: 'Create Grid Strategy',
  },
  'gridTrade.preview_orders': {
    from: 'gridTrade.preview_orders',
    to: 'm.preview_grid',
    zh: '预览订单',
    zh2: '预览订单',
    en: 'Preview Orders',
    en2: 'Preview Orders',
  },
  'info.th_price': {
    from: 'info.th_price',
    to: 'last_price',
    zh: '最新价格',
    zh2: '最新价格',
    en: 'Last Price',
    en2: 'Last Price',
  },
  'activity.th_status': {
    from: 'activity.th_status',
    to: 'status',
    zh: '状态',
    zh2: '状态',
    en: 'Status',
    en2: 'Status',
  },
  'activity.th_opr': {
    from: 'activity.th_opr',
    to: 'action',
    zh: '操作',
    zh2: '操作',
    en: 'Action',
    en2: 'Action',
  },
  'activity.type_chain_cancel': {
    from: 'activity.type_chain_cancel',
    to: 'on_chain_order_cancellation',
    zh: '链上取消订单',
    zh2: '链上取消订单',
    en: 'On-Chain Order Cancellation',
    en2: 'On-Chain Order Cancellation',
  },
  'activity.type_claim': {
    from: 'activity.type_claim',
    to: 'Claim',
    zh: '领取',
    zh2: '领取',
    en: 'Claim',
    en2: 'Claim',
  },
  'dca.open_order_limit_exceeded': {
    from: 'dca.open_order_limit_exceeded',
    to: 'dca.order_placement_failed_open_order_limit_exceeded',
    zh: '下单失败：进行中订单达到上限',
    zh2: '下单失败：进行中订单达到上限',
    en: 'Order placement failed: open order limit exceeded.',
    en2: 'Order placement failed: open order limit exceeded.',
  },
  'dca.orders': {
    from: 'dca.orders',
    to: 'Orders',
    zh: '订单',
    zh2: '订单',
    en: 'Orders',
    en2: 'Orders',
  },
  'dca.status_canceled': {
    from: 'dca.status_canceled',
    to: 'status_canceled',
    zh: '已取消',
    zh2: '已取消',
    en: 'Canceled',
    en2: 'Canceled',
  },
  'campaign.claim': {
    from: 'campaign.claim',
    to: 'Claim',
    zh: '领取',
    zh2: '领取',
    en: 'Claim',
    en2: 'Claim',
  },
  'campaign.claimed': {
    from: 'campaign.claimed',
    to: 'Claimed',
    zh: '已领取',
    zh2: '已领取',
    en: 'Claimed',
    en2: 'Claimed',
  },
  'activity.type_create_airdrop': {
    from: 'activity.type_create_airdrop',
    to: 'airdrop.create_airdrop',
    zh: '创建空投',
    zh2: '创建空投',
    en: 'Create Airdrop',
    en2: 'Create Airdrop',
  },
  'dca.total_amount': {
    from: 'dca.total_amount',
    to: 'airdrop.total_amount',
    zh: '总金额',
    zh2: '总金额',
    en: 'Total Amount',
    en2: 'Total Amount',
  },
  'activity.type_retrieve_airdrop': {
    from: 'activity.type_retrieve_airdrop',
    to: 'airdrop.retrieve_unclaimed_airdrop',
    zh: '取回未领取空投',
    zh2: '取回未领取空投',
    en: 'Retrieve Unclaimed Airdrop',
    en2: 'Retrieve Unclaimed Airdrop',
  },
  'airdrop.my_airdrop_creation': {
    from: 'airdrop.my_airdrop_creation',
    to: 'countdown.my_countdown_plan',
    zh: '我的创建',
    zh2: '我的创建',
    en: 'My Creations',
    en2: 'My Creations',
  },
  'airdrop.cannot_earlier_than_current_time': {
    from: 'airdrop.cannot_earlier_than_current_time',
    to: 'countdown.cannot_earlier_than_current_time',
    zh: '不能早于当前时间',
    zh2: '不能早于当前时间',
    en: 'Cannot be before current time',
    en2: 'Cannot be before current time',
  },
  side: {
    from: 'side',
    to: 'Side',
    zh: '方向',
    zh2: '方向',
    en: 'Side',
    en2: 'Side',
  },
  disconnect: {
    from: 'disconnect',
    to: 'Disconnect',
    zh: '断开连接',
    zh2: '断开连接',
    en: 'Disconnect',
    en2: 'Disconnect',
  },
  'account.deposit_search': {
    from: 'account.deposit_search',
    to: 'trade.pair_search',
    zh: '搜索币种、合约地址',
    zh2: '搜索币种、合约地址',
    en: 'Search token, contract address',
    en2: 'Search token, contract address',
  },
  'orders.ongoingOrders': {
    from: 'orders.ongoingOrders',
    to: 'open_orders',
    zh: '当前订单',
    zh2: '当前订单',
    en: 'Open Orders',
    en2: 'Open Orders',
  },
  'gridOrders.tab_open_orders': {
    from: 'gridOrders.tab_open_orders',
    to: 'open_orders',
    zh: '当前订单',
    zh2: '当前订单',
    en: 'Open Orders',
    en2: 'Open Orders',
  },
  'gridOrders.th_prices': {
    from: 'gridOrders.th_prices',
    to: 'gridOrders.detail_prices',
    zh: '价格区间',
    zh2: '价格区间',
    en: 'Price Range',
    en2: 'Price Range',
  },
  'gridOrders.th_levels': {
    from: 'gridOrders.th_levels',
    to: 'number_of_grids',
    zh: '网格数',
    zh2: '网格数',
    en: 'Number of Grids',
    en2: 'Number of Grids',
  },
  'orders.th_pair': {
    from: 'orders.th_pair',
    to: 'Pair',
    zh: '交易对',
    zh2: '交易对',
    en: 'Pair',
    en2: 'Pair',
  },
  'info.th_pair': {
    from: 'info.th_pair',
    to: 'Pair',
    zh: '交易对',
    zh2: '交易对',
    en: 'Pair',
    en2: 'Pair',
  },
  'gridOrders.grid_profit_24': {
    from: 'gridOrders.grid_profit_24',
    to: 'm.grid_profit_24',
    zh: '24小时收益',
    zh2: '24小时收益',
    en: '24h Profit',
    en2: '24h Profit',
  },
  'activity.type_chain_cancel_grid': {
    from: 'activity.type_chain_cancel_grid',
    to: 'on_chain_order_cancellation',
    zh: '链上取消订单',
    zh2: '链上取消订单',
    en: 'On-Chain Order Cancellation',
    en2: 'On-Chain Order Cancellation',
  },
  'activity.type_chain_cancel_dca': {
    from: 'activity.type_chain_cancel_dca',
    to: 'on_chain_order_cancellation',
    zh: '链上取消订单',
    zh2: '链上取消订单',
    en: 'On-Chain Order Cancellation',
    en2: 'On-Chain Order Cancellation',
  },
  'mining.pools_th_pairs': {
    from: 'mining.pools_th_pairs',
    to: 'Pair',
    zh: '交易对',
    zh2: '交易对',
    en: 'Pair',
    en2: 'Pair',
  },
};

export default map;
