const zhCN = {
  language: 'zh-CN',
  'kline.time_Line': '分时',
  'kline.time_1s': '1秒',
  'kline.time_5s': '5秒',
  'kline.time_15s': '15秒',
  'kline.time_30s': '30秒',
  'kline.time_1m': '1分钟',
  'kline.time_3m': '3分钟',
  'kline.time_5m': '5分钟',
  'kline.time_15m': '15分钟',
  'kline.time_30m': '30分钟',
  'kline.time_1H': '1小时',
  'kline.time_2H': '2小时',
  'kline.time_4H': '4小时',
  'kline.time_6H': '6小时',
  'kline.time_1D': '日线',
  'kline.time_1W': '周线',
  'kline.time_1M': '月线',
  'kline.tab_line': '走势图',
  'kline.tab_depth': '深度图',
  'kline.chartType_Bars': '美国线',
  'kline.chartType_Candles': 'K线图',
  'kline.chartType_Hollow_Candles': '空心K线图',
  'kline.chartType_Line': '线形图',
  'kline.chartType_Area': '面积图',
  'kline.chartType_Heikin_Ashi': '平均K线图',
  degate_account: 'DeGate账户',
  Trade: '交易',
  Order: '订单',
  Grid: '网格策略',
  Campaign: '活动',
  DCA: '定投',
  Advanced: '高级',
  Add: '划入',
  Add_Funds: '划入资金',
  external_wallet_receive_guide: 'DeGate钱包没有资产，请从外部钱包转入。',
  external_wallet_add_funds_guide: 'DeGate内没有资金，请从外部钱包添加资金。',
  eth_added_1: '1 ETH已划入',
  eth_sent_1: '1 ETH已发送',
  Send: '发送',
  Internal_Transfer: '内部转账',
  Miscellaneous: '其他',
  Mining: '挖矿',
  Liquidity_Mining: '流动性挖矿',
  Analytics: '数据',
  Support: '帮助',
  Help: '帮助',
  Tips: '提示',
  Statistics: '业务统计',
  Coming_soon: '即将到来',
  Faucet: '领测试币',
  more: '更多',
  hide: '收起',
  change: '更换',
  'Wrong Network': '网络错误',
  avbl: '可用：',

  insufficient_balance_AAA: '您钱包里的AAA余额不足。请检查后重试。',
  insufficient_balance: '余额不足',
  wallet_denied_sign: '你拒绝了消息签名。',
  common_err: '似乎出了点问题，请稍后重试',
  common_err_ledger_version:
    '发生错误。请确保您的Ledger Ethereum app已更新至1.9.10或更高版本，或稍后再试。',
  network_1: '以太坊主网',
  network_err: '网络异常，请稍后再试',
  rate_limit_err: '访问频率过高，请在1分钟后重试',
  error_InsufficientGasFunds: '您钱包内的Gas不足',
  notification_transaction_send: '已转账',
  view_on_explorer: '在区块链浏览器查看',
  view_address: '查看地址',
  switch_network: '切换网络',
  switch_to_Arbitrum: '切换到Arbitrum网络以继续',
  switch_to_MAINNET_in_metamask: '请到Metamask切换至MAINNET',
  switch_to_MAINNET: '请切换至MAINNET',
  switch_network_in_walletconnect: '请到WalletConnect钱包切换网络',
  Retry: '重试',
  wallet_tips: '请到钱包内授权',
  wallet_ledger_tips: '请到Ledger硬件中授权',
  wallet_metamask_tips: '请到MetaMask授权',
  wallet_walletconnect_tips: '请到WalletConnect钱包授权',
  wallet_cancelled_tips: '您已取消签名',
  Close: '关闭',
  Closed: '已关闭',
  copied: '已复制',
  Details: '详情',
  view_details: '查看详情',
  turbo_range_view_live_status: '查看实时状态',
  Share: '分享',
  view_graph: '查看图示',
  Dismiss: '我再想想',
  Cancel: '取消',
  End: '关闭',
  End_grid: '关闭策略',
  Confirm: '确认',
  Cancel_all: '全部取消',
  cancel_all_tips: '是否要取消所有现货挂单',
  Submit: '提交',
  no_data: '没有数据',
  all_data_displayed: '已显示所有数据',
  no_data_within_90_days: '90天内无数据。',
  only_display_90_days: '仅显示最近90天数据',
  displayed_90_days: '已显示最近90天数据',
  only_data_beyond_90_days_trade:
    '90天之前的数据请点击「查看全部」后使用「导出数据」功能。',
  only_data_beyond_90_days_grid_detail: '暂不支持90天之前历史查询。',
  only_data_beyond_90_days_spot_history:
    '90天之前的数据请使用表格右上方「导出数据」功能。',
  View: '查看',
  service_unavailable_for_region_REGION: '该服务在REGION不可用',
  service_unavailable: '服务暂不可用',
  service_error: '请稍后重试',
  service_maintenance: '该功能维护中',
  connect_wallet: '连接钱包',
  switch_address: '切换地址',
  wallet_wc: '已连接WalletConnect',
  wallet_ledger: '已连接Ledger',
  register_dexAccount: '开通',
  deposit_ETH: '划入ETH',
  initialize: '初始化',
  initialization: '初始化',
  invalid_signature: '签名无效',
  possible_cause: '可能原因：',
  locale_time_error: '您的本地设备时间不准确。',
  authorization_mode: '授权模式',
  authorization_mode_standard: '免签名',
  authorization_mode_single_use: '单次签名',
  turn_on: '开启',
  turn_on_signature_free_mode: '开启免签名模式',
  signatre_free_mode: '免签名模式',
  turn_on_signature_free_mode_tips:
    '本模式下您可免签名下单。切换模式，请在交易按钮下方的"设置"中完成。',
  turn_on_signature_free_mode_tips_grid:
    '本模式下您可免签名创建网格策略。切换模式，请在交易按钮下方的"设置"中完成。',
  turn_on_signature_free_mode_tips_dca:
    '本模式下您可免签名创建定投计划。切换模式，请在交易按钮下方的"设置"中完成。',
  yes: '是',
  no: '否',
  free_mode_on: '免签名模式已开启',
  view_balance: '查看余额',
  delete_asset_key: '删除资产密钥',
  delete_asset_key_desc:
    '一旦您的浏览器中的资产密钥被删除，将会关闭免签名模式。',
  no_asset_key_tips: '您的浏览器中未找到资产密钥',
  turn_off_standard_mode: '并关闭免签名模式',
  reset_asset_key: '重置资产密钥',
  view_asset_key: '查看资产密钥',
  lock_success: '资产密钥已删除',
  reset: '重置资产私钥',
  delete: '删除',
  withdraw_ETH: '发送ETH',
  transfer_ETH: '内部转账ETH',
  history: '历史',
  view_history: '查看历史',
  internal_transfer: '内部转账',
  assets_record_link: '资产记录',
  other: '其他',
  login_success: '已连接至钱包',
  Account: '账户',
  Address: '地址',
  Disconnect: '断开连接',
  copy_address: '复制地址',
  copy_grid: '复制策略',
  Copy: '复制',
  btn_search: '搜索',
  btn_reset: '重置',
  btn_confirm: '关闭',
  btn_max: '最大',
  btn_ok: '知道了',
  spot_trade: '现货',
  grid_trade: '网格',
  err_balance_title: '下单失败',
  err_balance_content: '账户可用余额不足，请确认后重新创建',
  order_failed: '下单失败',
  insufficient_order_value: '订单价值不足',
  grid_failed: '网格策略创建失败',
  err_eth_gas: '以太坊网络严重拥堵',
  err_insufficient_balance_TOKEN1: 'TOKEN1余额不足',
  err_insufficient_balance_TOKEN1_TOKEN2: 'TOKEN1和TOKEN2余额不足',
  please_add_funds_before_ordering: '下单前请先向DeGate余额划入资金',
  err_balance_content_spot: '余额不足，下单失败',
  err_balance_content_grid: '余额不足，网格策略创建失败',
  trade_min_volume_tips_XXX: '最少为XXX',
  grid_min_volume_tips: '每格数量不满足最小下单量要求，请重新下单',
  trade_risk_orders_tips: '下单失败，当前挂单过多',
  gas_token_tips: '选择矿工费代币',
  add_favorite_tooltip: '加入自选',
  remove_favorite_tooltip: '移出自选',
  expire_tips_X: '订单将于X失效',
  today: '今天',
  now: '现在',
  time_D_day: 'D天',
  time_D_day_H_hour: 'D天H小时',
  time_last_24_hrs: '最近24小时',
  time_last_hour: '最近1小时',
  time_H_hour_M_minute: 'H小时M分钟',
  time_M_minute_S_second: 'M分钟S秒',
  time_S_second: 'S秒',
  around: '约',
  time_now: '刚刚',
  time_before: '前',
  time_before_ago: '前',
  time_1_minute: '1分钟',
  time_1_hour: '1小时',
  time_1_day: '1天',
  time_1_year: '1年',
  time_M_minutes: 'M分钟',
  time_M_m: 'M分钟',
  time_H_hours: 'H小时',
  time_H_h: 'H小时',
  time_D_days: 'D天',
  time_Y_years: 'Y年',
  time_Y_y: 'Y年',
  time_D_d: 'D天',
  time_M_mo: 'M月',
  fee_change_tips: '价格已更新',
  no_pairs: '没有交易对',
  register_new_pair: '添加新交易对',
  register_pair: '添加交易对',
  add_pair: '添加交易对',
  tips_hide_forever: '下次不再显示',
  Select_Token: '选择币种',
  token: '币种',
  action: '操作',
  more_actions: '更多操作',
  gas_fee: '矿工费',
  'orders.detail_gas': '实际矿工费',
  trade_fee: '手续费',
  about_degate: '关于DeGate',
  metrics: '数据统计',
  fees: '费率',
  document: '文档',
  join_us: '加入我们',
  feedback: '反馈',
  email_optional: '电子邮件地址（可选）',
  Upload: '上传',
  feedback_upload_tip: '请输入反馈内容，可拖动文件添加附件',
  feedback_upload_tip_mobile: '请输入反馈内容',
  image_upload_tip: '松开后添加',
  feedback_success: '您的反馈振聋发聩！',
  feedback_success_2: '非常感谢',
  feedback_failed: '提交失败，请稍后重试',
  image_upload_rule_1: '仅支持PNG, JPG, JPEG格式的附件',
  image_upload_rule_2: '单个不超过20MB',
  image_upload_rule_3: '最多5个',
  image_upload_rule_2_3: '单个不超过20MB，最多5个',
  no_pair: '未找到交易对',
  no_token: '未找到此币种',
  choose_base_token: '选择币种',
  choose_quote_token: '选择货币',
  get_test_token: '领测试币',
  faucet: '测试币',
  expire_in: '有效期',
  expire_in_empty_err: '请设置有效期',
  go_back: '返回',
  max_XXX: '最大为XXX',
  min_XXX: '最小为XXX',
  fill_in: '填入',
  my_balance: '我的余额',
  deGate_insufficient_fees: 'DeGate余额不足以支付矿工费',
  wallet_balance: '钱包余额',
  your_wallet_balance: '我的钱包余额',
  degate_balance: 'DeGate余额',
  wallet_insufficient_fees: '钱包余额不足',
  wallet_insufficient_balance: '钱包余额不足',
  insuffficient_wallet_balance: '钱包余额不足',
  degate_insufficient_balance: '可用余额不足',
  open_discord: '去Discord社区',
  err_valid_until: '请调整当前设备本地时间至标准时间',
  tips_gas: '执行交易上链所需的矿工费将会从您的DeGate余额扣除',
  maker_free: '挂单免费',
  trading_fee_rate: '手续费率',
  Free: '免费',
  stop_service_1: '站点正在维护',
  stop_service_2: '预计恢复时间',
  stop_upgrade: '新版本测试网正在迁移中',
  stop_trading_1: '系统升级中',
  stop_trading_2: '交易功能暂停使用',
  sell: '卖出',
  buy: '买入',
  SELL: '卖出',
  BUY: '买入',
  Sell: '卖出',
  Buy: '买入',
  sell_order: '卖单',
  buy_order: '买单',
  edit: '修改',
  status_processing: '进行中',
  status_processed: '待处理',
  status_pending: '等待入块',
  status_confirming: '确认中',
  status_success: '成功',
  status_completed: '已完成',
  status_failed: '失败',
  status_speeding_up: '加速中',
  status_canceling: '取消中',
  status_canceled: '已取消',
  in_progress: '进行中',
  limit_order: '限价',
  market_order: '市价',
  stop_limit_order: '止盈止损',
  balance: '余额',
  empty_connect: '请先连接钱包',
  empty_register: '请先完成初始化',
  empty_months3: '最近3个月无数据',
  show_months3: '仅展示3个月内的数据',
  view_all: '查看全部',
  H1: '1小时',
  D1: '1天',
  D5: '5天',
  M1: '1月',
  M3: '3月',
  M6: '6月',
  YTD: 'YTD',
  Y1: '1年',
  all: '全部',
  paste: '粘贴',
  clear: '清空',
  total: '总计',
  amount: '数量',
  order_amount: '订单数量',
  price: '价格',
  order_total: '订单金额',
  filledAmount: '成交数量',
  tradeFilledTotal: '成交金额',
  orderFilledTotal: '成交额',
  filledAmount_amount: '已成交/订单数量',
  profit: '收益',
  incompatible_token: '该代币的技术规格与DeGate协议不兼容。',
  next: '前往',
  token_not_verified: '未验证',
  token_not_verified_tips:
    '合约地址、图标和代币名未经验证。请检查合约地址是否来自官方渠道，以避免诈骗。',
  token_verified: '已验证',
  token_verified_tips: '合约地址、图标和代币名是互相匹配的。',
  deposit_tips_region:
    '请注意：您正在从REGION访问DeGate，资金划入后无法交易和内部转账。',
  complete_time: '完成时间',
  unable_to_initialize: '无法初始化',
  filter_base: '币种',
  filter_quote: '货币',
  filter_type: '类型',
  filter_role: '角色',
  option_maker: 'Maker',
  option_taker: 'Taker',
  start_data: '开始日期',
  end_data: '结束日期',
  added_to_favorites: '成功加入自选',
  removed_to_favorites: '移出自选成功',
  show_recents_50: '已显示最近50条数据',
  terms_of_service: '用户协议',
  tips_small_unfilled:
    '由于系统设计精度原因，极小量未成交部分已退回您的DeGate余额',
  notification: '通知',
  server_message_SystemRecovery:
    '系统故障恢复后，您的部分订单状态发生改变，请知悉',
  learn_more: '了解更多',
  connect_ledger: '连接Ledger',
  ledger_disconnect:
    "Failed to execute 'transferOut' on 'USBDevice': The device was disconnected.",
  gas_fee_expired: '矿工费已过期，请重新提交',
  scroll_down_to_refresh: '下拉刷新',
  release_to_refresh_immediately: '松开立即刷新',
  no_more: '已经全部加载完毕',
  loading: '正在加载...',
  force_withdrawing_token_tips:
    '正在处理您的强制提现请求，所以无法完成当前操作。',
  speed_up: '加速',
  transaction_submitted: '交易已提交',
  tx_speed_up: '加速交易',
  tx_cancel: '取消交易',
  none: '无',
  Language: '语言',
  page: '/页',
  go_to: '跳至',
  icon_indicators: '技术指标',
  icon_back: '回退',
  icon_forward: '前进',
  icon_full_screen: '全屏',
  icon_exit_full_screen: '退出全屏',
  icon_buy_sell_orders: '买卖盘',
  icon_buy_orders: '买盘',
  icon_sell_orders: '卖盘',
  icon_enable: '点击打开',
  icon_disable: '点击关闭',
  icon_copy: '复制地址',
  icon_view_explorer: '区块链浏览器查看',
  icon_display_by_profit: '按收益展示',
  icon_display_by_time: '按时间顺序展示',
  icon_switch: '切换',
  eth_code_tips: '以太坊原生代币，无合约地址',
  TBD: '待定',
  TVL: '总锁定价值',
  go_to_discord: '或者去Discord创建工单',
  release: '版本号：',
  security: '安全',
  colon: '：',
  zero_balance: '零余额',
  ledger_app_version_tips:
    '为了查看待签名消息，请升级您的Ledger Ethereum app至v1.9.19或更高',
  ledger_contract_data_tips:
    '请在Ethereum app设置中开启Blind Signing/Contract Data',
  input_auto_corrected_tooltips: '超过了最大位数限制，您的输入已被自动修改',
  maximum_decimal_reached: '超出最大小数位',
  verify_ownership: '验证身份',
  enable_trading: '开启交易',
  learn_more_about_signatures_link: '了解签名请求 >',
  learn_more_about_signatures: '了解签名请求',
  sign: '去签名',
  sign_step1: '请到钱包内签名',
  sign_step2: '完成第二次签名',
  not_now: '暂不',
  view_on_block_explorer: '区块链浏览器查看\t',
  view_in_history: '去历史记录查看',
  continue_to_place_order: '继续下单',
  Save: '保存',
  sign_to_view: '签名后查看',
  available_degate_balance: '可用DeGate余额',
  Back: '返回',
  token_has_not_listed: '该币种还未上架DeGate',
  list_now: '立即上币',
  spread_15: '价差 >15%',
  connected: '已连接',
  self_list_token: '自主上币',
  claim_REBASE: '领取REBASE',
  time: '时间',
  time_updated: '更新时间',
  show_in_X_m: '约X分钟后显示',
  max_gas: '最大矿工费',
  total_required: '共需',
  Required: '必填',
  available_balance: '可用余额',
  please_add_funds: '请先向DeGate余额划入资金',
  Side: '方向',
  pending: '待确认',
  active: '运行中',
  ended: '已关闭',
  name: '名称',
  yield: '分红',
  time_created: '创建时间',
  time_ended: '结束时间',
  frequency: '频率',
  chain_cancel: '链上取消',
  status: '状态',
  status_chainCancelProgressing: '正在链上取消',
  status_chainCancelCompleted: '已链上取消',
  filled_total: '已成交/总金额',
  start_time: '开始时间',
  end_time: '结束时间',
  Summary: '摘要',
  Orders: '订单',
  Tutorial: '教程',
  top_winner_24h: '24小时冠军',
  ID: '序号',
  Select: '选择',
  Create: '创建',
  Review: '预览',
  Airdrop: '空投',
  Airdrops: '空投',
  Countdown: '首发',
  Day: '天',
  Hour: '小时',
  Minute: '分钟',
  Second: '秒',
  Days: '天',
  Hours: '小时',
  Minutes: '分钟',
  Seconds: '秒',
  Claim: '领取',
  Expired: '已过期',
  Claimed: '已领取',
  Welcome: '欢迎',
  gas_tips_for_amount_exceed_6_digits:
    '成交的数量超过6位数字限制，因此需支付额外费用',
  input_auto_corrected_minStep_tips: '您的输入已被自动修改，以符合最小精度',
  order_max_limit: '已超出最大限制',
  order_min_limit: '已超出最小限制',
  order_faild_min_limit: '下单失败：已超出最小限制',
  order_faild_max_limit: '下单失败：已超出最大限制',
  disconnect_m: '断开',
  'account.account_manage': '账户安全',
  'account.account_manage_more': '关于授权模式和资产密钥 >',
  'account.what_is_asset_key': '关于授权模式和资产密钥',
  'account.total_value': '总资产',
  'account.hide_small_balances': '隐藏小额资产',
  'account.add_to_metamask': '添加币种到钱包',
  'account.assets_balance_total': '全部',
  available: '可用',
  'account.assets_market': '市值',
  'account.transfer_to_degate_balance': '划转至DeGate余额',
  'account.search_tokens': '搜索币种',
  'account.deposit_title':
    '充值资产会被存入您在DeGate的去中心化账户，完全由您掌控。',
  'account.deposit_tips': '划入的资金仍由您完全掌控',
  'account.deposit_confirm_btn': '划入资金',
  'account.deposit_approved_btn': '已授权',
  'account.deposit_1_ETH': '向DeGate余额划入1 ETH',
  'account.deposit_status_pending': '等待入块',
  'account.deposit_status_pay_pending': '待支付',
  'account.deposit_status_pay_waiting': '付费交易待打包',
  'account.deposit_status_pay_confirming': '付费入账确认中',
  'account.deposit_tips_block': '等待交易入块',
  'account.deposit_status_pay_btn': '去付费',
  'account.pay_deposit_warning': '划入资金可能需要支付额外的矿工费',
  'account.pay_deposit_warning_tips':
    '资金划入产生协议运行成本，这部分补贴当前已达上限，用户可能需要自行承担。',
  'account.deposit_pending_tips': '如果等待时间超过5分钟，请去钱包加速交易',
  'account.deposit_pending_tips_ledger': '如果等待时间超过5分钟，请加速交易',
  'account.deposit_contract_tips_over_AMOUNT': '金额超过AMOUNT美元需要高级方式',
  'account.deposit_contract_tips_only_all': '暂时仅支持高级资金划入方式',
  'account.suggest_100': '建议≥$100',
  'account.suggest_100_tips': '下限价单建议金额大于$100',
  'account.deposit_failed': '交易失败',
  'account.deposit_failed_tips': '划入资金的链上交易已失败',
  'account.payment_due': '等待付费入账',
  'account.payment_due_tips':
    '需要额外支付费用才能将本次划入资金计入您的DeGate余额',
  'account.register_token_code_placeholder': '输入合约地址',
  'account.register_token_code': '合约地址',
  'account.register_token_symbol': '代币',
  'account.register_token_check': '查看上币进度',
  'account.register_token_code_err_added': '正在上架该币种',
  'account.register_token_next_step': '下一步',
  'account.register_token_tips1': '上币无需审核，您可以在链上立即完成上币',
  'account.register_token_btn': '立即上币',
  'account.list_token': '上架',
  'account.withdraw_warning_XXX': '由于协议繁忙，发送资产现在大约需要XXX',
  'account.withdraw_status_pending': '处理中',
  'account.tansferred_1_ETH': '1 ETH 已转出',
  'account.transfer_status_sent': '已发送',
  'account.transfer_status_received': '已接收',
  'account.th_me': '我',
  'account.th_tx_hash': '交易号',
  'account.th_time': '时间',
  'account.locked_order': '限价挂单',
  Sending: '正在发送',
  'account.locked_claimable': '待领取',
  'account.locked_grid': '网格策略挂单',
  'account.personal_sign_reason': '可能原因',
  'account.personal_sign_reason1': '1. Metamask连接了硬件钱包',
  'account.personal_sign_reason2': '2. Metamask版本过低',
  'account.personal_sign_reason3': '3. 其他原因',
  'account.personal_sign_btn': '重新签名',
  'account.deposit_arrive_in_30s': '约30秒到账',
  'account.deposit_arrive_in_30s_s': '到账时间约30秒',
  'account.account_completed_time_XXX': '约XXX到账',
  'account.search_result_no_token': '找不到此资产',
  'account.search_result_invalid_code': '合约地址不存在',
  'account.search_result_not_listed': '此资产还未上线DeGate',
  'account.search_result_tips_register': '您可以输入合约地址立即完成上币',
  'account.search_result_not_find': '还是没找到？',
  'account.search_pair_tips3': '此资产还没有交易对',
  'account.search_pair_tips3_add': '请先添加',
  'account.register_token': '免审核上币',
  'account.search_again': '重新搜索\t',
  'account.deposit_type': '划入方式',
  'account.deposit_type_standard': '标准',
  'account.switch_account_tips': '已切换至',
  'account.switch_account_tips_register': '请先初始化账户',
  'account.initialize_success': '初始化成功',
  'account.approve': '授权',
  'account.reset_USDT': '重置USDT授权',
  'account.reset_USDT_tips': 'USDT授权额度不够时需要先重置授权。',
  'account.next_step': '下一步',
  'account.profit_total': '总收益',
  'account.profit_history': '收益历史',
  'account.tab_mining_rewards': '挖矿奖励',
  'account.yield_total': '总分红',
  'account.yield_24h': '24小时分红',
  claimable: '可领取',
  'account.yield_history': '分红历史',
  'account.total_grid_profit': '网格总收益',
  'account.grid_strategies': '网格策略',
  'account.total_rewards': '挖矿总奖励',
  'account.rewards_24h': '24小时挖矿奖励',
  'account.rewards': '奖励',
  'menu.register_err':
    '您的地址没有任何区块链操作记录，请完成一笔链上操作后重试，例如：转入任意数量的资金。',
  'menu.reset_post_success_withOrders':
    '开始重置资产密钥，所有进行中订单和网格策略已被取消',
  'menu.reset_post_success': '开始重置资产密钥',
  'menu.reset_processing_title': '正在重置资产密钥',
  'menu.reset_processing_desc': '请等待完成后再操作',
  'trade.choose_token': '选择币种',
  'trade.token_info': '代币信息',
  'trade.token_address': '代币信息',
  'trade.price_range_24h': '24小时价格区间',
  'trade.vol_24h': '24小时量',
  'trade.item_price_TOKEN': '价格(TOKEN)',
  'trade.item_amount_TOKEN': '数量(TOKEN)',
  'trade.order_book_title': '订单簿',
  'trade.order_book_total': '合计',
  latest_trades: '最新成交',
  'trade.trade_history_time': '时间',
  'trade.market_placeholder_price': '市价',
  'trade.what_is_stop_limit': '什么是止盈止损',
  'trade.what_is_stop_limit_link': '什么是止盈止损 >',
  'trade.placeholder_total': '成交额',
  'trade.more_settings': '设置',
  'trade.expire_in_tips': '订单到期后将被自动取消',
  'trade.period_day_s': '天',
  'trade.period_hour_s': '小时',
  'trade.period_minute_s': '分钟',
  'trade.period_err_input_tips': '请输入有效数字',
  'trade.post_only_label': 'Maker-Only',
  'trade.post_only_tips':
    'Maker-Only模式确保只以Maker订单进入订单簿。如果订单任何部分会以Taker订单成交，则整个订单会被退回。Maker-Only模式下免矿工费和手续费。',
  'trade.post_only_fail_title': '无法创建订单',
  'trade.post_only_fail_desc': '请调整价格或关闭Maker-Only',
  'trade.max_gas_fee_tips':
    '矿工费用于支付交易的上链结算。此费用由Taker支付，Maker免费。多余的费用会被退还。',
  'trade.auto': '自动',
  'trade.custom': '手动',
  'trade.enough_for_XX_trades': '足够成交 XX 笔',
  'trade.gas_fee_per_trade': '单次成交矿工费',
  'trade.gas_fee_per_trade_tips':
    'Taker按每笔成交支付矿工费，用以完成链上结算。矿工费随以太坊网络情况波动。',
  'trade.max_number_of_trades': '最大成交次数',
  'trade.btn_buy_ETH': '买入ETH',
  'trade.btn_sell_ETH': '卖出ETH',
  'trade.max_buy_fee_deducted_NUM': '已减去矿工费，最多买入NUM',
  'trade.notification_limit_order_title': '限价单已下单',
  'trade.notification_stop_limit_order_title': '止盈止损单已下单',
  'trade.err_price': '请输入价格',
  'trade.err_amount_total': '请输入数量或成交额',
  'trade.err_amount': '请输入数量',
  insufficientFee_gas_fee: '矿工费不足',
  'trade.err_insufficientFee_desc': '请检查最大矿工费设置和您的DeGate余额。',
  'trade.cancel_order_success': '订单已取消',
  'trade.pair_favorite': '自选',
  'trade.pair_search': '搜索币种、合约地址',
  'trade.pair_last_price': '最新价',
  'trade.pair_change': '涨跌',
  'trade.url_parse_err_title': '该交易对不存在',
  'trade.risk_tips': '风险提示',
  'trade.base_is_not_default_token_tips':
    '在交易前请通过官方渠道验证代币合约地址，以避免欺诈。',
  'trade.chain_cancel': '链上取消订单',
  'trade.chain_cancel_no_need_tips': '此订单无需链上取消',
  'trade.chain_cancel_success': '请求已发送',
  'trade.depth_empty': '暂无订单',
  'trade.depth_empty_asks': '没有卖单',
  'trade.depth_empty_bids': '没有买单',
  'trade.depth_empty_tips': '由于订单簿挂单不足，市价单下单失败',
  'trade.history_empty': '暂无成交',
  'trade.err_price_stable': '价格已失效，请重试',
  'trade.price_warning': '您输入的价格已偏离市场价，请确认后再下单',
  'trade.order_value_tips':
    '最小订单价值为<b>QUOTE_A</b>或<b>BASE_A</b>，相当于MINUSD美元。市价单可免于此限制。',
  'trade.order_value_tips_quote':
    '最小订单价值为<b>QUOTE_A</b>，相当于MINUSD美元。市价单可免于此限制。',
  'trade.order_value_tips_stable_quote':
    '最小订单价值为<b>QUOTE_A</b>。市价单可免于此限制。',
  'trade.system_limit': '已超出系统限制',
  'trade.stop_limit_untriggered_tips':
    '由于未达到触发价，此订单还没有提交至订单簿',
  'trade.stop_limit_triggered_tips_TIME': '此订单于TIME提交至订单簿',
  'trade.flow_of_funds': '资金流向',
  'trade.flow_of_funds_tip2':
    '下单成功。订单资金会计入您的DeGate余额，而不是您的钱包余额。',
  'orders.show_current_pair_orders': '仅显示本交易对',
  'orders.orderHistory': '历史订单',
  'orders.th_time': '时间',
  'orders.th_average_price': '平均价格',
  'orders.th_stop_price': '触发价',
  'orders.th_limit_price': '委托价',
  'orders.th_filled_price': '成交价格',
  'orders.th_filled_amount': '成交数量',
  'orders.th_filled_total': '成交额',
  'orders.th_trade_reconciliation': '对账修正',
  'orders.th_trade_reconciliation_tips':
    '由于DeGate撮合和链上结算采用了不同的计算模式，这两个计算结果之间可能存在细微的数值差异。 如果发生这种情况，系统将以链上数值为准来补上DeGate余额的不足。',
  'orders.hide_cancelled_expired_orders': '隐藏取消/过期',
  'orders.status_open': '进行中',
  'orders.status_pending': '待确认',
  'orders.status_completed': '已成交',
  'orders.status_completed_part': '部分成交',
  'orders.status_expired': '已过期',
  'orders.detail_price': '均价/价格',
  'orders.average_price': '均价',
  'orders.detail_type': '订单类型',
  'orders.detail_trade_fee': '手续费：',
  'orders.gas_preAuth': '最大矿工费：',
  'orders.fee_reconciliation': '对账修正：',
  'orders.gas_paid': '矿工费已支付：',
  'orders.gas': '矿工费：',
  'orders.trades_N': '成交(N)',
  'orders.detail_filled_total': '成交额',
  'orders.detail_filled_detail': '成交明细',
  'orders.detail_filled_time': '时间',
  'orders.order_maker_free': 'Maker方免费',
  'orders.openOrders_empty': '没有当前订单',
  'orders.export_orders_1_year': '导出最近1年订单数据',
  'orders.export_trades_1_year': '导出最近1年成交数据',
  'orders.export_data': '导出数据',
  'orders.export': '导出',
  'orders.export_processing': '正在处理，请耐心等候',
  'orders.export_tips_100_percent': '进度100%后会自动下载文件',
  'orders.sign_to_view_balance': '签名以查看余额',
  'orders.sign_to_view_history': '签名以查看历史',
  'orders.sign_to_view_security_options': '签名以查看安全选项',
  'gridTrade.automatic_strategy': '一键创建',
  'gridTrade.manual_strategy': '手动创建',
  'gridTrade.placeholder_amount': '请输入数量',
  'gridTrade.low_price': '最低价格',
  'gridTrade.high_price': '最高价格',
  'gridTrade.initial_investment': '投资额',
  'gridTrade.grid_levels_tips': '用于确定价格区间内的订单数量',
  'gridTrade.profit_per_grid': '每格收益',
  'gridTrade.profit_per_grid_tips':
    '这是网格策略盈利性的一个重要参数。每个网格的利润 = (较高价格 - 较低价格) / 较低价格。较高和较低价格指的是网格策略中两条相邻网格线的价格。',
  'gridTrade.min_grid_volume_XXX_ETH': '每格数量最少为XXX ETH',
  'gridTrade.min_grid_volume_err': '请增加投资额或减少网格数',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    '无法创建网格策略，因为此交易对挂单不够。',
  'gridTrade.grid_to_spot_trade': '去现货交易',
  'gridTrade.grid_level_over_err': '请减少网格数量',
  'gridTrade.grid_prices_err': '请扩大价格区间',
  'gridTrade.grid_create_err': '无法创建网格，请调整参数后重试',
  'gridTrade.tips_grid_profit': '收益直接计入DeGate可用余额',
  'gridTrade.tips_grid_balance_0_BASE':
    '市场价上涨导致网格策略下均为买单，因此BASE当前余额为0。',
  'gridTrade.tips_grid_balance_0_BASE_2':
    '市场价上涨导致网格策略下均为买单，而这些买单存在部分成交的情况，因此导致BASE当前余额不为0。',
  'gridTrade.tips_grid_balance_0_QUOTE':
    '市场价下跌导致网格策略下均为卖单，因此QUOTE当前余额为0。',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    '市场价下跌导致网格策略下均为卖单，而这些卖单存在部分成交的情况，因此导致QUOTE当前余额不为0。',
  'gridTrade.grid_param_err': '请完整输入网格策略参数',
  'gridTrade.tv_buy': '买单',
  'gridTrade.tv_sell': '卖单',
  'gridTrade.tv_waiting': '等待',
  'gridTrade.chain_cancel_no_need_tips': '此网格策略无需链上取消',
  'gridTrade.grid_over_max_number_err':
    '无法创建，您运行中的网格策略数量已达数量上限',
  'gridTrade.preview_orders_in_graph': '显示订单',
  'gridTrade.greate_news': '好消息：',
  'gridTrade.min_amount_required_XXX': '最少需要XXX',
  'gridTrade.highest_grid_apy': '最高网格收益率',
  'gridTrade.for_the_last_7_days': '基于过去7日',
  'gridTrade.min_investment': '最小投资额',
  'gridTrade.grid_need_XXX': '网格需要 $XXX',
  'gridTrade.mining_need_XXX': '挖矿需要 $XXX',
  'gridTrade.recommended_params_cannot_be_applied':
    '由于投资额不足，推荐参数无法适用。您可以在手动模式下进行调整。',
  'gridTrade.copy_params_to_manual': '把参数填入手动创建',
  'gridOrders.grid_recents': '我的最新成交',
  'gridOrders.th_created_time': '时间',
  'gridOrders.grid_profit': '网格收益',
  'gridOrders.grid_cancel': '关闭策略',
  open_orders: '当前订单',
  'gridOrders.tab_history_orders': '已完成订单',
  'gridOrders.tab_trade_history': '历史成交',
  'gridOrders.detail_current_balance': '当前余额',
  'gridOrders.detail_ending_balance': '结束余额',
  'gridOrders.detail_ending_balance_tips': '此网格策略关闭时的资产余额',
  'gridOrders.detail_in_order_funds': '挂单中的资金：',
  'gridOrders.detail_on_hold_funds': '待挂单的资金（来自已部分成交的订单）：',
  'gridOrders.detail_transactions': '订单完成总数',
  'gridOrders.detail_investment': '初始投资',
  'gridOrders.detail_running_time': '运行时长',
  'gridOrders.detail_prices': '价格区间',
  number_of_grids: '网格数',
  'gridOrders.detail_expire_time': '剩余有效期',
  'gridOrders.detail_expire_time_tooltip': '网格策略下所有订单会在此时间后过期',
  'gridOrders.detail_valid_period': '有效期设置',
  'gridOrders.open_orders_sell': '卖单',
  'gridOrders.open_orders_buy': '买单',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': '金额',
  'gridOrders.history_orders_filled': '数量：',
  'gridOrders.history_orders_price': '价格：',
  'gridOrders.history_orders_time': '时间',
  'gridOrders.history_orders_filled_price': '成交均价',
  'gridOrders.history_orders_filled_amount': '成交数量',
  'gridOrders.history_orders_filled_total': '成交金额',
  'gridOrders.history_orders_profit_tips':
    '收益来自于低买高卖一次循环后的价格差。例如 4000 USDC价格买入1 ETH的网格订单成交后，若网格间距是50 USDC，系统将自动生成4050 USDC卖出1 ETH的订单，当此订单也成交后，您获得了50 USDC的收益。',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    '价格在PRICE的买单成交后将显示收益',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    '价格在PRICE的卖单成交后将显示收益',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    '价格PRICE的订单完全成交后会在此显示',
  'gridOrders.grid_cancel_title': '关闭网格策略',
  'gridOrders.grid_cancel_content': '该策略下所有订单都会被立即取消',
  'gridOrders.grid_cancel_content2':
    '该网格策略正在挖矿。如果现在关闭，您将会放弃挖矿奖励，所有网格订单会立即被取消。',
  'gridOrders.copy_grid_title': '将复制下列网格策略参数',
  'gridOrders.copy_grid_btn': '复制到面板',
  'gridOrders.copy_grid_success': '网格策略已复制',
  'gridOrders.grid_init_funds_XXX': '初始投资价值: $XXX',
  'gridOrders.grid_init_funds_tips':
    '根据初始投入币种的初始价格计算而来，用于计算收益率。',
  'gridOrders.tab_m_trade': '网格',
  grid_apy: '网格年化收益率',
  grid_apy_tips: '仅通过网格交易的年化利润率。不包括浮动盈利。',
  'gridOrders.tab_mining_profit': '挖矿收益率',
  'gridOrders.tab_mining_profit_tips':
    '根据挖矿总收益、初始投入价值和挖矿时长计算得到的年化收益率',
  'gridOrders.mining_rewards': '奖励：',
  'gridOrders.open_orders_empty_tips': '正在加载数据，请稍候',
  'gridOrders.market_value': '市值：',
  'gridOrders.market_value_details': '明细',
  'gridOrders.fund_details': '资金明细',
  'gridOrders.m_in_order_funds': '挂单中的资金',
  'gridOrders.m_in_order_funds_tips': '该网格策略下所有挂单的资金总和',
  'gridOrders.m_on_hold_funds': '待挂单的资金',
  'gridOrders.m_on_hold_funds_tips': '来自部分成交的订单',
  'gridOrders.initial_value': '初始价值',
  'mining.my_title': '我的矿池',
  'mining.index_desc': '创建网格策略，赚网格和挖矿收益',
  'mining.apply': '项目申请',
  'mining.claimable_rewards_box': '可领取奖励',
  'mining.rewards_more': '及更多',
  'mining.tab_pools': '矿池',
  'mining.tab_my': '我的挖矿统计',
  'mining.pools_tab_live': '进行中',
  'mining.pools_tab_upcoming': '即将开始',
  'mining.pools_funds': '总锁定价值',
  'mining.pools_funds_tips': '满足最小订单价值$120的网格订单总价值',
  'mining.pools_mining_funds': '挖矿锁定价值',
  'mining.mining_apr': '年化收益率',
  'mining.mining_apr_tips': '根据挖矿奖励和挖矿锁定价值预估出的年化收益率',
  'mining.view_rule_link': '挖矿规则',
  'mining.pools_info_to_confirm': '待确定',
  'mining.pools_no_wait': '没有计划的矿池',
  'mining.my_mining_funds': '我的挖矿资金',
  'mining.my_mining_rewards': '我的挖矿奖励',
  'mining.my_th_profit_token_price': '最新价格',
  'mining.my_th_total_rewards': '累计奖励',
  'mining.my_th_24h_rewards': '24小时奖励',
  'mining.my_grids': '我的挖矿',
  'mining.only_show_mining_grids': '仅正在挖矿',
  'mining.my_th_mining_status': '挖矿状态',
  'mining.status_framing': '正在挖矿',
  'mining.status_over_price': '已超出价格区间',
  'mining.status_mining_over': '挖矿已结束',
  'mining.status_grid_closed': '策略已关闭',
  'mining.status_grid_expired': '策略已过期',
  'mining.empty_no_faring_grids': '当前没有挖矿的网格策略',
  'mining.go_mining_pool': '查看矿池',
  'mining.go_mining': '去挖矿',
  'mining.go_to_grid': '去网格策略',
  'mining.mining_help': '如何挖矿',
  'mining.mining_available': '满足',
  'mining.mining_available_tips': '满足订单价值要求',
  'mining.mining_unavailable': '不满足',
  'mining.mining_partially_available': '部分满足',
  'mining.mining_unavailable_tips': '未满足订单价值要求',
  'mining.mining_preview': '挖矿预览',
  'mining.mining_total_profit': '挖矿收益',
  'mining.mining_24h_profit': '24小时挖矿收益',
  'mining.profit_unable_display': '无法显示',
  'mining.mining_funds': '挖矿资金',
  'mining.mining_funds_tips':
    '在该交易对中，所有网格策略下满足挖矿订单价值要求的订单的资金总和',
  'mining.tab_mining_profit_details': '最近奖励明细',
  'mining.tab_mining_orders': '挖矿订单',
  'mining.th_rewards': '奖励',
  'mining.th_rewards_origin': '奖励来源',
  'mining.th_rewards_origin_tips':
    '该订单价格位于订单簿奖励价格范围内（最高买单价格*0.99 ~ 最低卖单价格*1.01），因此获得挖矿奖励。',
  'mining.th_rewards_origin_tips_stable':
    '该订单价格位于订单簿奖励价格范围内（最高买单价格 ~ 最低卖单价格），因此获得挖矿奖励。',
  'mining.th_time': '时间',
  'mining.plan_title': 'ETH/USDC 矿池详情',
  'mining.phase_cur': '当前阶段',
  'mining.phase_range_N_XX': '阶段N (XX)',
  'mining.phase_index_N': '阶段N',
  'mining.phase_reward': '每日奖励',
  'mining.phase_to_release': '等待公布',
  'mining.my_rewards': '我的奖励',
  'mining.claimable_rewards': '可领取',
  'mining.locked_rewards': '冻结',
  'mining.locker_rewards_tips': '网格策略运行满12小时后可领取挖矿奖励',
  'mining.claimed_success': '领取成功',
  'mining.claimed_tips': '稍后您将通过内部转账收到款项',
  'mining.claimed_view_btn': '查看',
  'mining.mining_plan': '矿池计划',
  'mining.phase_unpublished': '待公布',
  'mining.all_pools': '全部矿池',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    '卖出 AMOUNT BASE @ PRICE QUOTE',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    '买入 AMOUNT BASE @ PRICE QUOTE',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT': '卖出 AMOUNT BASE',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT': '买入 AMOUNT BASE',
  'notification.cancel_grid_desc_PAIR_PRICES': 'PAIR：PRICES',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    '以QUOTE卖出AMOUNT BASE',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    '以TOTAL QUOTE卖出BASE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    '以QUOTE买入AMOUNT BASE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    '以TOTAL QUOTE买入BASE',
  'notification.cancel_limit': '限价订单已取消',
  'notification.cancel_stop_limit': '止盈止损订单已取消',
  'notification.cancel_market': '市价单已取消',
  'notification.cancel_grid': '网格策略已关闭',
  'notification.cancel_limit_expired': '限价单已过期',
  'notification.cancel_stop_limit_expired': '止盈止损订单已过期',
  'notification.cancel_grid_expired': '网格策略已过期',
  'notification.cancel_limit_order_for_gas_desc':
    '您订单的矿工费已用完。订单已部分成交，剩余部分被取消。',
  'notification.cancel_limit_order_for_gas_filled_amount': '已成交',
  'notification.cancel_limit_order_for_gas_amount': '订单数量',
  'notification.view_history_orders': '查看历史订单',
  'notification.cancel_market_for_depth_title': '订单部分成交并已取消',
  'notification.price_slippage_protection': '价格滑点保护',
  'notification.price_slippage_protection_desc':
    'DeGate市价单自动包括10%的价格滑点保护，以限制在市场波动大和流动性低的情况下的损失。若无需价格保护，请使用限价单。',
  'notification.cancel_market_for_depth_warning':
    'DeGate市价单引入了价格保护机制，使用户在价格波动剧烈和低流动性的市场中减少损失。如不想触发价格保护，请使用限价模式。',
  'notification.dca_plan_ended': '定投计划已关闭',
  'notification.cancel_dca_desc_PAIR': 'PAIR',
  'notification.trade_limit_partially': '限价单部分成交',
  'notification.trade_limit_filled': '限价单完全成交',
  'notification.trade_market_partially': '市价单部分成交',
  'notification.trade_market_filled': '市价单完全成交',
  'notification.trade_stop_limit_partially': '止盈止损部分成交',
  'notification.trade_stop_limit_filled': '止盈止损完全成交',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    '订单完全成交，收到AMOUNT TOKEN',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    '订单部分成交，收到AMOUNT TOKEN',
  'info.overview': '概况',
  'info.accounts': '总用户',
  'info.pairs': '交易对',
  'info.turnover': '累计成交额',
  'info.turnover_24': '24小时成交额',
  'info.dg_supply': 'DG流通量',
  'info.top_movers_no_increased': '24小时内无币种上涨',
  'info.top_movers_no_decreased': '24小时内无币种下跌',
  'info.top_pairs': '热门交易对',
  Pair: '交易对',
  'info.th_change': '24小时涨跌',
  'info.th_l_up_2': '+2%深度',
  'info.th_l_down_2': '-2%深度',
  'info.th_turnover_24': '24小时成交额',
  'info.tvl': '总锁定价值',
  'm.home': '首页',
  'm.grid': '网格',
  'm.browser_wallet': '手机钱包',
  'm.choose_pair': '选择交易对',
  'm.orderBook_default': '默认',
  'm.orderBook_bids': '仅买单',
  'm.orderBook_asks': '仅卖单',
  'm.decimals': '小数位',
  'm.lowest_price_24h': '24h最低',
  'm.highest_price_24h': '24h最高',
  'm.vol_24h': '24h量',
  'm.orderbook_buy': '买',
  'm.orderbook_sell': '卖',
  'm.go_to_trade': '去交易',
  'm.choose_token': '选择币种',
  'm.from_address': '付款地址',
  'm.to_address': '收款地址',
  'm.transfer_send': '转出',
  'm.transfer_receive': '收到',
  'm.my_grid': '我的网格策略',
  'm.grid_profit_24': '24小时收益',
  trades_24h: '24小时成交',
  'm.grid_profit_total': '累计收益',
  'm.grid_over_prices': '超出价格区间',
  'm.create_grid': '创建网格策略',
  'm.grid_history': '历史记录',
  'm.grid_empty': '没有正在运行的网络策略',
  'm.grid_tutorial': '网格教程',
  'm.grid_params_to_manual': '把参数填入手动创建',
  'm.balance_err': '余额不足，当前可用：',
  'm.preview_grid': '预览订单',
  last_price: '最新价格',
  'm.grid_desc':
    '网格交易是一种交易策略，在设定的价格区间内自动地低买高卖产生盈利。',
  'm.view_tutorial': '查看教程',
  'm.grid_profit_tips_sell': '卖单完全成交后计算',
  'm.grid_profit_tips_buy': '买单完全成交后计算',
  'm.hot': '热门',
  'm.all': '全部',
  'm.vol_24': '24h成交量',
  'm.transfer_t1': '内部转账',
  'm.transfer_t2': ' ',
  'activity.th_date': '时间',
  'activity.th_type': '类别',
  'activity.th_fee': '费用',
  'activity.th_content': '内容',
  'activity.type_register_token': '上币',
  'activity.type_register_pair': '添加交易对',
  'activity.type_pay_deposit': '付费入账',
  'activity.type_reset_account': '重置资产私钥',
  on_chain_order_cancellation: '链上取消订单',
  'activity.count_N': '第N次',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    'SELLAMOUNT BASE，价格PRICE QUOTE',
  'activity.order_market_desc_SELL_AMOUNT_BASE': 'SELLAMOUNT BASE',
  'activity.reset_status_restting': '正在重置',
  'activity.to_trade': '去交易',
  'dca.dca_plan': '定投计划',
  'dca.dca_explain': ' ',
  'dca.daily': '每天',
  'dca.weekly': '每周',
  'dca.custom': '自定义',
  'dca.every': '每',
  'dca.amount_per_order': '每笔订单金额',
  'dca.price_limit': '价格限制',
  'dca.maximum_price': '最高买入价格',
  'dca.minimum_price': '最低卖出价格',
  'dca.number_of_orders': '订单数',
  'dca.create_dca_plan': '创建定投计划',
  'dca.max_gas_fee_per_order': '单笔订单最大矿工费',
  'dca.maximum_plan_order_limit_reached': '已达到计划订单的最大数量限制',
  'dca.end_time_should_be_set_after_the_current_time':
    '结束时间应设定在当前时间之后',
  'dca.please_enter_amount_per_order': '请输入每笔订单金额',
  'dca.please_enter_maximum_price': '请输入最高买入价格',
  'dca.please_enter_minimum_price': '请输入最低卖出价格',
  'dca.order_placement_failed_open_order_limit_exceeded':
    '下单失败：进行中订单达到上限',
  'dca.total': '总金额',
  'dca.filled': '已成交',
  'dca.received': '已收到',
  'dca.time_to_end': '计划到期时间',
  'dca.cancel_on_chain': '链上取消',
  'dca.filled_amount': '已成交/数量',
  'dca.status_executed': '已执行',
  'dca.status_scheduled': '待执行',
  'dca.status_failed': '失败',
  'dca.order_cancled_by_user': '订单已取消，因为用户关闭了定投计划。',
  'dca.order_cancled_by_access': '订单已取消，因为您的DeGate访问受限。',
  'dca.order_cancled_by_gas': '下单失败：矿工费不足。',
  'dca.order_cancled_by_order_book': '下单失败：订单簿没有可匹配订单。',
  'dca.order_cancled_by_balance': '下单失败：DeGate余额不足。',
  'dca.order_cancled_by_min_value': '下单失败：未达到$100最小订单价值。',
  'dca.order_cancled_by_system_error': '由于系统故障，下单失败。',
  'dca.chain_cancel_no_need_tips': '此定投计划无需链上取消',
  'dca.end_dca_plan': '关闭定投计划',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    '此定投计划中的所有订单将被立即取消',
  'dca.no_active_dca_plan': '无运行中的定投计划',
  'dca.time_scheduled': '计划时间',
  'campaign.event_period': '活动时间：',
  'campaign.grid2401_time':
    '2024年1月22日 20:00:00 - 2024年1月29日 20:00:00 (UTC+8)',
  'campaign.event_has_ended': '活动已结束',
  'campaign.current_apy': '当前年化收益率',
  'campaign.grid_strategy_income': '网格策略收益 + 奖池瓜分收益',
  'campaign.tvl_participating': '活动总锁定价值',
  'campaign.share_of_tvl': '我的份额',
  'campaign.my_profit': '我的收益',
  'campaign.grid_strategy_profit': '网格策略收益',
  'campaign.share_of_prize_pool': '奖池瓜分收益',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    '获得的网格策略收益已进入可用余额',
  'campaign.shared_income_from_usdc_prize_pool': 'USDC奖池瓜分收益',
  'campaign.is_black_tips': '你不具备瓜分奖池的资格',
  'campaign.calculating': '计算中',
  'campaign.claim_after_end': '奖励将在活动结束后开放领取',
  'campaign.how_to_participate': '如何参加',
  'campaign.rule': '创建网格策略分享奖池',
  'campaign.step1': '步骤1',
  'campaign.step2': '步骤2',
  'campaign.step3': '步骤3',
  'campaign.grid2401_step1': '准备ETH和USDC，可通过划入资金或通过交易获得。',
  'campaign.grid2401_step2_PAIR': '在PAIR交易对创建下列参数的网格策略',
  'campaign.grid2401_step2_desc1_pre': '价格区间: 待公布',
  'campaign.grid2401_step2_desc2_pre': '网格数: 待公布',
  'campaign.copy_strategy': '复制策略',
  'campaign.grid2401_step3':
    '本期活动结束后可在本活动页面Claim收益，请在该期活动结束后30天内领取。',
  'campaign.what_is_grid': '什么是网格策略',
  'campaign.notes': '参与须知',
  'campaign.notes_1_title': '资格:',
  'campaign.notes_1_desc':
    '创建的网格策略在创建时只有在价格区间和网格数与上述活动要求完全一致的情况下，才有资格获得奖池奖励。',
  'campaign.notes_2_title': '限制:',
  'campaign.notes_3_title': '领取:',
  'campaign.notes_3_desc':
    '奖励领取将在活动结束后开放，请在活动结束后30天内领取。',
  'campaign.faq': '常见问题',
  'campaign.grid2401_faq_1': '1. 奖励如何计算?',
  'campaign.grid2401_faq_2': '2. 我参与活动中需要咨询，如何能够获得帮助？',
  'campaign.grid2401_faq_3': '3. 我持有USDT, 我如何获得ETH和USDC？',
  'campaign.grid2401_faq_4': '4. 我通过网格策略完成的交易需要支付手续费么？',
  'campaign.grid2401_faq_4_res':
    'DeGate 中所有Maker订单均为免手续费，网格策略所产生的订单均为Maker订单，所以DeGate中开设网格策略是完全免费的。',
  'campaign.grid2401_faq_5': '5. 活动结束后我的网格还有收益么？',
  'campaign.grid2401_faq_5_res':
    '有，活动结束后，只要当时的价格还在你的网格策略区间内，该策略就会持续不断的产生收益。活动结束后你也可以对网格策略进行参数调整，创建更适合你自己喜好的策略持续获得收益。',
  'campaign.grid2401_faq_others': '其他活动细则:',
  'campaign.grid2401_faq_others_1':
    '1. 本活动仅支持每位用户使用单个钱包进行参与，若发现恶意刷取奖励的行为，DeGate有权取消参与者的获得的奖励。',
  'campaign.grid2401_faq_others_2':
    '2. 在活动还在正常进行的过程中，网格处在超出范围状态也会被计算权重。',
  'campaign.grid2401_faq_others_3':
    '3. DeGate保留在极端情况下提前结束活动的权利。',
  'campaign.grid2401_faq_others_4':
    '4. 活动结束后超过30天没有被领取的奖励会被回收。',
  'campaign.invest_max_5000': '最大投入 $5000',
  'campaign.invest_mininum': '最小投入',
  'airdrop.create_airdrop': '创建空投',
  'airdrop.important_note': '重要提示：任何人都可以无需审核地创建空投',
  'airdrop.my_airdrop': '我的空投',
  'airdrop.time_limited': '限时',
  'airdrop.no_airdrop': '当前没有可领取的空投',
  'airdrop.claim_airdrop': '领取空投',
  'airdrop.recipients_number': '地址总数',
  'airdrop.total_amount': '总金额',
  'airdrop.retrieve': '取回',
  Unclaimed: '未领取',
  'airdrop.retrieve_successful': '取回成功',
  'airdrop.claim_successful': '领取成功',
  'airdrop.retrieve_unclaimed_airdrop': '取回未领取空投',
  'airdrop.airdrop_token': '空投币种',
  'airdrop.token_not_meet_criteria': '币种不符合空投的要求',
  'airdrop.airdrop_list': '空投列表',
  'airdrop.download_template': '下载模版',
  'airdrop.click_or_drag_upload_list': '点击或拖动上传列表',
  'airdrop.validation_passed': '已验证',
  'airdrop.must_earlier_than_end_time': '必须早于结束时间',
  'airdrop.cannot_more_than_2_years_from_now': '从现在起最多2年',
  'airdrop.cannot_parse_file': '无法解析文件，请使用列表模版。',
  'airdrop.format_requirement_not_met': '不符合格式要求',
  'airdrop.view_error_repost': '查看错误报告',
  'airdrop.error_report': '错误报告',
  'airdrop.line': '行数',
  'airdrop.reason': '原因',
  'airdrop.duplicated_address': '重复的地址',
  incorrect_address_format: '地址格式不正确',
  'airdrop.incorrect_amount_format': '数量格式不正确',
  'airdrop.airdrop_plan_created': '空投计划已创建',
  'airdrop.max_50000': '最多50000个地址',
  'airdrop.upload_file_rule': '仅支持CSV格式的附件。',
  'airdrop.to_check_airdrop_eligibility': '请连接钱包以查看空投',
  'airdrop.complete_initialization_to_claim_airdrops': '完成初始化以领取空投',
  'airdrop.complete_initialization_to_view_airdrops': '完成初始化以查看空投',
  'airdrop.you_are_eligible_for': '您可领取：',
  'airdrop.and_more': '以及更多',
  'airdrop.congratulations': '恭喜!',
  'airdrop.airdrop_fee': '空投费',
  'countdown.countdown_plan': '首发计划',
  'countdown.create_countdown_plan': '创建首发计划',
  'countdown.my_countdown_plan': '我的创建',
  'countdown.countdown_trading_pair': '倒计时交易对',
  'countdown.countdown_display': '显示倒计时',
  'countdown.token_not_meet_criteria': '币种不符合首发要求',
  'countdown.countdown_tips': '勾选的交易对会在交易页面显示倒计时',
  'countdown.max_30_days': '从现在起最多30天',
  'countdown.review_countdown_plan': '检查首发计划',
  'countdown.countdown_fee': '首发费',
  'countdown.countdown_plan_created': '首发计划已创建',
  'countdown.trading_will_start_in': '交易开始倒计时',
  'countdown.trading_will_start_at_YYYY': '交易将在YYYY后开放',
  'countdown.cannot_earlier_than_current_time': '不能早于当前时间',
  'dca.price_limit_buy_tips':
    '一旦开启，您的买单将只在等于或低于最高价时执行。本功能与零费用选项兼容。',
  'dca.price_limit_sell_tips':
    '一旦开启，您的卖单将只在等于或高于最低价时执行。本功能与零费用选项兼容。',
  'dca.zero_fee': '零费用',
  'dca.zero_fee_buy_tips':
    '开启「零费用」后，定投订单将作为Maker-Only的限价单处理。每个订单的买入价格将在下单后成为订单簿中的最高出价。请注意，您的订单可能不会立即成交，或可能根本无法成交。',
  'dca.zero_fee_sell_tips':
    '开启「零费用」后，定投订单将作为Maker-Only的限价单处理。每个订单的卖出价格将在下单后成为订单簿中的最低卖价。请注意，您的订单可能不会立即成交，或可能根本无法成交。',
  'dca.order_canceled_post_only_buy_failed':
    '由于订单簿缺乏买单，无法确定您订单的买入价格，导致下单失败。',
  'dca.order_canceled_post_only_sell_failed':
    '由于订单簿缺乏卖单，无法确定您订单的卖出价格，导致下单失败。',
  start_time_cannot_before_current_time: '开始时间不能早于当前时间',
  start_time_must_before_end_time: '开始时间必须早于结束时间',
  list_token: '上币',
  contract_address_does_not_exist: '合约地址不存在',
  token_listed: '此代币已完成上币',
  XXX_is_listed: '正在上币XXX',
  view_progress: '查看进度',
  pair_create_tips: '交易对可以在DeGate上即刻添加，无需任何人的批准。',
  base_token: '币种',
  quote_token: '货币',
  existing_pair: '已存在',
  trade_now: '立即交易',
  pair_XXX_added_successfully: 'XXX添加成功',
  qty_per_grid: '每格数量',
  grid_minimum_not_reached: '未达到最小值',
  total_profit: '总体收益',
  total_apy: '总体年化收益率',
  float_profit: '浮动盈利',
  grid_profit_24h: '24小时网格收益',
  pnl: '损益',
  eligibility: '资格条件',
  rewards: '奖励',
  view_mining_statistics: '查看挖矿统计',
  your_entry: '您的输入',
  refunded: '已返还',
  large_price_spread: '订单簿价差大',
  large_price_spread_tips:
    '订单簿显示最低卖价和最高买价之间的价差较大，存在亏损风险。建议采用双资产模式进行投资。',
  continue_anyway: '仍然继续',
  insufficient_order_book_liquidity_decrease_investment:
    '订单簿流动性不足，请减少投资额',
  initial_buy: '初始购买',
  closing_sell: '关闭卖出',
  No: '不',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    '执行定投订单时如果<b>$XXX</b>价格低于<b>$PRICE</b>，订单将会失败。',
  zero_fee: '零费用',
  minimum_order_value_is_VALUE: '最小订单价值为<b>$VALUE</b>。',
  Note: '提示',
  Continue: '继续',
  estimated_apy: '预估收益率',
  based_on_data_from_last_7_days: '根据过去7天数据',
  top_gainers_24h: '24小时涨幅',
  top_losers_24h: '24小时跌幅',
  listed_tokens: '上架币种',
  vol: '成交量',

  let_s_go: '出发',
  reject: '拒绝',
  maximum_N_due_to_price_ticks: '由于价格精度限制，最大值为N',
  Saved: '已保存',
  minimum_order_value_$100_$QUOTE: '最小订单价值为<b>$100 $QUOTE</b>',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    '最小订单价值为<b> $AMOUNT $QUOTE</>(~$$100)',
  no_restriction_with_market_order: '<b>市价单</b>没有该限制',
  go_to_market_order: '去下市价单',

  Mining_Eligibility: '挖矿资格',
  How_to_earn_mining_rewards: ' 如何获取挖矿奖励',
  Order_Value: '订单价值',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    '在策略创建时，网格订单至少为<b>BV BASE</b> 或者 <b>QV QUOTE</b>',
  'mining.mining_tips_QV_QUOTE': '在策略创建时，网格订单至少为<b>QV QUOTE</b>',
  Mining_Price_Range: '挖矿价格范围',
  'mining.status_over_price_tips':
    '网格订单价格必须在<b>挖矿价格范围之内</b>，即：订单簿最高买入价格*0.99 ～ 订单簿最低卖出价格*1.01。',
  'mining.status_over_price_tips_stable':
    '网格订单价格必须在<b>挖矿价格范围之内</b>，即：订单簿最高买入价格 ～ 订单簿最低卖出价格。',
  Eligible_for_Mining: '可以挖矿',
  Mining_Satus: '挖矿状态',
  Mining_Satus_Mining: '正在挖矿',
  Mining_Satus_Standby: '等待中',
  Mining_Satus_Ineligible: '不符合要求',
  mining_price_range: '挖矿奖励范围',
  rewards_tips_stable:
    '策略创建时满足挖矿订单价值的网格订单，如果其价格在挖矿价格范围之内可以获得挖矿奖励（最高买单价格 ~ 最低卖单价格）',
  rewards_tips:
    '策略创建时满足挖矿订单价值的网格订单，如果其价格在挖矿价格范围之内可以获得挖矿奖励（最高买单价格*0.99 ~ 最低卖单价格*1.01）',

  wrap: '跨链',
  Wrap: '跨链',
  websites_for_more_information: '获取更多信息：',
  official_site: '官方网站',
  wrap_site: '跨链网站',
  tips_third_party_site: '你即将离开DeGate并访问第三方站点：',
  wrap_unwrap: '跨链兑换',

  Receive: '收款',
  Network: '网络',
  Token_Contract: '币种合约',
  Contract: '合约',
  please_select_network: '请选择网络',
  maximum_amount: '最大数量',
  send_USDC_to_this_address: '发送USDC到该地址',
  arpa_airdrop: '$ARPA 空投',
  Failed_to_proceed: '无法继续',
  Please_select_the_Ethereum_network: '请选择以太坊网络',
  NATIVE_USDC_ONLY: '只接受原生USDC',
  NEVER_send_bridged_USDC: '请勿发跨链USDC',
  I_understand: '我已理解',
  recipient_address: '接收地址',

  chain_0: 'DeGate L2',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum One',
  chain_421614: 'Arbitrum One',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    '包含该操作的rollup交易还没有提交到以太坊。在此之前，DGSCAN<b>不会</b>显示该操作。',
  Best_Liquidity: '流动性最佳',
  order_partially_filled: '订单部分成交',
  order_partially_filled_for_liquidity:
    '由于订单簿流动性突然下降，您的剩余订单已被取消。这一保护措施是为了防止订单以不利的价格成交。',
  'orders.export_data_2_year': '导出最近2年数据',
  Community: '社区',

  complete_in_seconds: '立即完成',
  failed_to_send: '发送失败，请重试',
  failed_to_send_try_other_networks: '发送失败，请尝试其他网络',
  gas_fee_deducted: '已扣除矿工费：',
  sum_XXX: '合计 XXX',
  chart_control_7d: '7天',
  chart_control_30d: '30天',
  chart_control_all: '全部',
  chart_control_day: '日',
  chart_control_week: '周',
  chart_control_month: '月',

  Coming: '即将开始',
  leave_survey_title: '嘿，看起来你要离开DeGate了',
  leave_survey_subtitle: '我们可以通过您的反馈做得更好\n请选择所有适用的选项',
  leave_survey_not_leaving: '我不离开，我会回来的',
  leave_survey_other_is_fine: 'Binance/OKX/Kraken等对我来说够了',
  leave_survey_bad_experience: '交易体验不好',
  leave_survey_no_yield: '没有找到任何收益机会',
  leave_survey_no_needed_token: '没有找到想要交易的代币',
  leave_survey_other_reason: '其他（请在下面的框中告诉我们）',
  leave_survey_thanks_for_feedback: '感谢您的反馈',
  Submitted: '已提交',

  doc_title:
    'DeGate: 去中心化订单薄交易所 | 免费提供数字货币网格和定投交易机器人',
  doc_desc:
    'DeGate是一个领先的去中心化的订单薄交易所，支持数百种数字货币极低费率交易，提供免费的限价单交易，网格交易，定投策略机器人。',
  doc_title_spot: ' | 去中心化订单薄交易所 | DeGate DEX',
  doc_title_grid: ' | 去中心化网格交易机器人 | DeGate DEX',
  doc_title_dca: ' | 去中心化定投机器人 | DeGate DEX',
  doc_title_swap: '',

  Notification: '通知',
  read_all: '全部已读',
  important: '重要',
  general: '通用',
  view_more: '查看更多',
  thats_all: '暂时没有更多了',
  XXX_fund_addition_processing: 'XXX 资金划入处理中',
  add_AMOUNT_XXX_to_DeGate: '划入 AMOUNT XXX 至 DeGate',
  XXX_fund_addition_successful: 'XXX 资金划入成功',
  XXX_send_successful: 'XXX 发送成功',
  send_AMOUNT_XXX_to_DeGate: '发送 AMOUNT XXX 至 DeGate(内部转账)',
  send_AMOUNT_XXX_to_Ethereum: '发送 AMOUNT XXX 至 Ethereum',
  you_have_received_a_new_airdrop: '您已收到新的空投！',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD:
    'AMOUNT XXX 能够在 YYYY-MM-DD 后领取',
  MARKET_Chart: 'MARKET 图表',
  grid_free: '网格策略交易<b>免费<b/>',
  maker_free_tips: '挂单方交易<b>免费<b/>',
  Audit: '审计',
  Tool: '工具',
  About: '关于',

  // 1.16
  list_token_tips: '输入合约地址在DeGate上架币种',
  login_to_view: '登录后查看',
  login_to_view_balance: '登录后查看余额',
  login_to_view_history: '登录后查看历史',
  login_to_view_security_options: '登录后查看安全选项',
  i_accept: '我接受',
  degate_terms_of_service: 'DeGate服务条款',
  privy_terms_of_service: 'Privy服务条款',
  agree: '同意',
  about_asset_key: '关于资产密钥',
  explantion_asset_key_privy:
    '资产密钥与用户的地址绑定，是在首次Email登录时生成的。DeGate协议采用资产密钥来授权交易。<br><br><h4>重置资产密钥</h4>用户可以自由地重置资产密钥。在重置过程中：<br><br>1. 所有进行中的订单和网格策略将被取消。<br>2. 所有操作功能都将暂停，例如交易、发送、内部转账。<br><br>一旦DeGate在以太坊上完成下一次 zk-rollup 上链，重置便完成。<br><br><h4>查看资产密钥</h4>DeGate SDK的用户会需要查看资产密钥。将资产密钥导入SDK后，用户就可以在不使用degate.com网页的情况下完成操作。务必保护好资产密钥，请勿泄露。',
  privy_account_balance_tips:
    '您正在通过邮箱登录使用DeGate，这种方式仅适用于低价值交易。',
  privy_account_balance_tips2:
    '为了提高安全性，我们强烈建议切换到自托管钱包，如MetaMask、Ledger、imToken或类似选项。',
  dont_show_again_for_30_days: '30天内不再提示',
  dont_show_again_for_60_days: '60天内不再提示',
  privy_feature_disabled_tips:
    '邮箱登录不支持本功能，请切换到其他钱包连接方式。',
  Execution: '执行',
  Executed_Orders: '已执行订单数',
  Failed_Orders: '失败订单数',
  Remaining_Orders: '剩余订单数',
  avg_price: '均价',
  Campaigns: '活动',
  all_Campaigns: '所有活动',
  join_now: '立即参加',
  pools: '矿池',
  you: '我的',
  per_day: '每天',

  marketplace: '广场',
  latest_grid_orders_filled: '网格订单最新成交',
  cumulative_grid_profit: '全站网格累计收益',
  total_fees_saved: '手续费节省',
  compared_to_CEX: '与CEX相比',
  earn_XX_more_with_DeGate: '在DeGate多赚XX%',
  your_profit_with_CEX: '在CEX能赚的收益',
  total_fees_saved_with_DeGate: '在DeGate额外节省的手续费',
  earn_grid_profit_now: '立即开赚',
  top_strategies: '排行榜',
  ROI: '收益率',
  roi_desc: '收益率 = 总收益 / 初始投资额',
  '24h_filled_orders': '24小时成交订单数',

  // 1.17
  Swap: '兑换',
  liquidity: '流动性',
  market_cap: '总市值',
  data_collected_from_DEX: '数据采集自 DEX',
  my_history: '我的历史',
  pay: '支付',
  receive: '收到',
  max_slippage: '最大滑点',
  minimum_receive: '最少收到',
  minimum_TOKEN: '最少 TOKEN',
  order_value_limit_reached: '订单价值限制',
  maximum_order_value_over_time_XXXX_USDC:
    '最大订单价值为XXXXUSDC，该限制随时间动态变化。',
  swap_order_placed: '兑换订单已下单',
  swap_order_filled: '兑换订单已成交',
  swap_order_failed: '兑换订单失败',
  swapping: '兑换中',
  available_network: '支持网络',
  minimum_receive_XXX_TOKEN: '最少收到 XXX TOKEN',
  Website: '网站',
  Twitter: '推特',
  Telegram: '电报',
  status_filled: '已成交',
  status_fail: '失败',
  tips_DeGate_balance_1: 'DeGate余额为您的私钥在DeGate控制的资产总价值。',
  tips_DeGate_balance_2:
    '划入资金后，您可以实时地完成订单簿交易，也可以将该资产发送至同一网络下的任意地址。',
  scan_SOLANA: 'Solscan',
  chain_SOLANA: 'Solana',
  swap_deposit_not_support_yet: '暂不支持此币种划入，将会于未来版本支持。',
  insufficient_pool_liquidity: '流动性不足',
  tips_DCAMinTips_limit_buy_XXX:
    '如果订单执行时市场价超过$XXX，执行可能会失败，因为您的订单未达到最小订单价值 $MIN USDC。是否想要继续？',
  tips_DCAMinTips_limit_sell_XXX:
    '如果订单执行时市场价低于$XXX，执行可能会失败，因为您的订单未达到最小订单价值 $MIN USDC。是否想要继续？',
  no_live_mining_campaign: '没有进行中的挖矿活动',
  minimum_quantity_per_grid_25: '最低每格数量：$25',
  minimum_investment: '最低投资额：',

  telegram_optional: 'Telegram用户名',
  feedback_tips: '感谢反馈。如果您想要得到答复，请填写联络方式。',
  est_receive: '预估收到',

  swap_max_slippage_exceeded: '超出最大滑点',
  transaction_timeout: '交易超时',
  please_increase_the_max_slippage_setting: '请增加最大滑点设置。',

  total_filled_orders: '总成交订单数',
  message_limit_order_expired: '限价单已过期并取消',
  message_stop_limit_order_expired: '止盈止损单已过期并取消',
  message_grid_expired: '网格策略已过期并取消',

  iframe_network_error_message: '由于网络问题，图表无法显示',

  no_token_contract: '无代币合约',
  native_token_of_XXX_chain: 'XXX链的原生代币',
  N_found_in_Swap: '兑换中找到N个',
  N_found_in_Orderbook_Trade: '订单簿交易中找到N个',
  Show_all: '显示全部',
  sync_to_DeGate_app: '同步到DeGate App',

  top_guns: '钞能力',
  moneybags: '王炸',
  strategy_value: '策略价值',
  whales: '巨鲸',
  hot_pairs: '热门交易对',
  apy_kings: 'APY大佬',
  apy_king: 'APY大佬',
  total_grid_capital: '网格总资金',
  including_grid_strategy_orders: '包括网格策略订单',

  Grid_Strategy_Creation_Failed: '网格策略创建失败',
  Grid_Strategy_Creation_Failed_1:
    '网格策略的初始买入订单部分成交，但由于订单簿流动性突然下降，其余部分被取消。',
  Grid_Strategy_Creation_Failed_2: '更多信息请参见网格策略详情。',
  grid_apy_estimate_tips:
    'APY 的预估根据过去7天的数据计算得出。<br/><br/>只有当您新建网格策略的价格范围完全涵盖或被过去7天的历史价格范围完全涵盖时，才会提供此预估。<br/><br/>举例来说，假设您的价格范围是<b>5-10</b>:<br/>- 如果历史价格范围是<b>6-9</b>（完成涵盖）或<b>4-11</b>（被完全涵盖），则会进行预估。<br/>- 如果历史价格范围是<b>8-12</b>（部分重叠）或<b>12-14</b>（无重叠），则不会给出预估，因为这样的预估并不准确。',
  auto_suggested_profit: '推荐每格利润：根据过去7天数据计算',

  referral_code_optional: '推荐码（可选）',
  invalid_referral_code: '推荐码无效',
  DeGate_Referral_Program: 'DeGate反佣计划',
  Referral_Program: '推荐计划',
  Referral_Program_Desc_V2: '成为认证合作伙伴，从您的推荐网络中持续赚钱佣金',
  Referral_Program_Desc_V2_text2: '全链透明、链上记录，打造长期收益',
  Referral_Program_Desc:
    '将您的影响力变现，加入一个紧密团结的生态。我们是长期主义者，在此真诚希望您的社区和DeGate能互相帮助和成长！您可以邀请好友/跟随者并获取手续费返佣，赚取被动收入。交易量越高，返佣越高。',
  Apply_Now: '立即申请',
  Commission_Earned: '已赚取佣金',
  Unclaimed_Commission: '未领取佣金',
  Invites: '邀请数',
  Commission_Rate: '佣金比例',
  referral_commission_rate_tips:
    '您可从直接邀请用户获得一级佣金，也可从他们邀请的用户获得二级佣金。',
  Share_my_referral_link: '分享我的推荐链接',
  Claimable_Commission: '可领取佣金',
  Referral_Details: '推荐详情',
  Level: '级别',
  Level_1: '一级',
  Level_2: '二级',
  Type: '类型',
  Activity: '活动',
  Credited: '已入账',
  referral_trading_fee: '交易手续费',
  referral_level_1_commission: '一级佣金',
  referral_pending_commission_tips:
    '该金额正在处理中，系统兑换为USDC后会自动入账。',
  your_referral_link_is_expired: '您的推荐链接已失效',
  claim_value: '市值',
  My_Invites: '我的邀请',
  Referee: '被推荐人',
  Commission: '佣金',
  Transaction: '交易',
  Time_Joined: '加入时间',

  one_order: '1笔订单',
  N_Orders: 'N笔订单',
  Filled: '成交',
  out_of_range: '超出范围',

  show_chart: '显示图表',
  please_enter_grid_parameters_first: '请先输入网络参数',
  go_to_app_store: 'Go to App Store',
  go_to_google_play: 'Go to Google Play',
  scan_to_download_app: '扫描下载App',
  get_DeGate_app_now: '立即获取DeGate App',
  install_beta_version: '安装内测版',
  how_to_install_beta_version: '如何安装内测版',
  download_testflight_from_app_store: '从App Store下载 TestFlight',
  click_to_download_testflight: '点击下载 TestFlight',
  come_back_for_next_step_after_testflight_is_installed:
    '安装 TestFlight 后返回进行下一步',
  download_DeGate_in_testflight: '在 TestFlight 下载 DeGate',
  click_to_download_DeGate: '点击下载 DeGate',
  click_install: '点击 "安装"',

  low_liquidity: '警告：低流动性',
  low_liquidity_tips: '检测到订单簿流动性不足。请核实以避免潜在损失。',

  min_receive_tips:
    '如果价格进一步下滑，您的交易将被取消。以下是您保证能收到的最低金额。',
  est: '预估',
  hide_other_tokens: '仅显示当前币种',
  share: '分享',
  more_trading_methods_here: '这里有更多的交易方式',

  pool_liquidity: '池流动性',
  '24h_pool_volume': '24h池成交',
  mkt_cap: '市值',
  pool_info: '池信息',
  DEX: 'DEX',
  pool: '池',
  pool_address: '池地址',
  pool_created: '池创建时间',

  beta_test_tips: '联系我们参与此功能内测',
  swap_success_receive_AMOUNT_TOKEN: '兑换成功，收到AMOUNT_TOKEN',
  hide_balances_less_than_10: '隐藏<$10余额',

  Sender: '发送方',
  Recipient: '接收方',
  My_CHAIN_Address: '我的CHAIN地址',
  CHAIN_Address: 'CHAIN地址',
  From: '来自',
  To: '至',
  send_status_help: `<b>處理中</b> <br />處理發送請求。<br /><br /><b>成功</b> <br />資產已成功交付至接收方地址。<br /><br /><b>已完成</b><br /> 包含此交易的区块已达到最终性。`,

  minimum_buy: '最少购入',
  minimum_sell: '最少卖出',

  check_wallet_compatibility: '检查钱包兼容性',
  wallet_incompatible: '钱包不兼容',
  wallet_incompatible_tips:
    '您正在使用非标准钱包（例如，多方计算（MPC）钱包），DeGate 不支持此类钱包。请切换至标准钱包。',
  initialization_desc_step3: '您将会收到三次签名请求，签名不会产生费用。',

  records_are_unavailable_yet: '目前尚不支持展示记录',
  receive_history_tips:
    '请到APP首页复制您的钱包地址，并到区块链浏览器中查看这些记录。',

  rate_limit_tips: '请求频繁，请稍后再试',

  // 1.23
  Warning: '警告',
  Error_fetching_data: '获取数据出错',
  Connection_Status: '连接状态',
  Market_Info: '市场信息',
  Market_Info_tips: '例如价格、24小时变化(%)、市值、流动性、成交量等',
  Last_updated: '最近更新',
  TIME_ago: 'TIME前',
  Asset_Info: '资产信息',
  Your_available_balance: '您的可用余额',
  Disconnected: '已断开',

  Earn: '理财',
  Portfolio: '投资组合',
  My_Portfolio: '我的投资组合',
  My: '我的',
  Total_Deposits: '总投资',
  Claimable_Rewards: '可领取奖励',
  My_Deposit: '我的投资',
  APY: '年化收益率',
  Base_APY: '基础年化收益率',
  Bonus_APY: '奖励年化收益率',
  native_Apy: '本金年化收益率',
  Total_APY: '总体年化收益率',
  performance_fee: 'Performance Fee',
  About_Vault: '关于金库',
  Protocol: '协议',
  Vault: '金库',
  Asset: '资产',
  Chain_Details: '链的详情',
  Deposit: '充值',
  Withdraw: '提现',
  Est_Daily_Rewards: '预计每日奖励',
  Accruing: '累积中',
  It_becomes_claimable_upon_maturity: '到期后可被领取',
  Tokens: '币种',
  Value: '价值',
  XXX_available_in: '可用的XXX',
  maximum_XXX: '最大：$XXX',
  minimum_XXX: '最少：$XXX',

  earn_deposit_sol_balance_tips: '您至少需持有 0.05 SOL 以继续操作',
  claim_rewards: '领取奖励',
  Return: '返回',
  usdc_supplied_from: 'USDC使用情况',

  multi_chain: '多链',
  multi_chain_tips:
    '多链代币提升了用户体验，使用户无需复杂的资金跨链操作即可在任何链上进行投资。它还可用于支付所有链上的网络费用。',
  multi_chain_balances: '多链余额',
  convert_to_multi_chain_usdc_tips: '您可以通过跨链转换成<b>多链USDC</b>',
  Bridge: '跨链桥',
  multi_chain_usdc: '多链USDC指Solana和Base网络上的USDC',
  explantion_fees:
    '<h4>兑换费率</h4><ul><li>参考 <a href="https://docs.degate.com/about-degate/swap">费率表</a></li></ul> <br><h4>网络费</h4><ul><li>根据实时的链上成本计算得出</li></ul>',
  search_history: '搜索历史',
  '24h_txns': '24h交易',
  Markets: 'Markets',

  warning_excessive_balance_detected: '警告：检测到过量余额',
  warning_excessive_balance_detected_tips1:
    '您当前的 DeGate 账户并非设计用于存储大量资产。您的余额已超过我们建议的上限 XXX 美元。',
  warning_excessive_balance_detected_tips2:
    '请立即减少您的持仓，以在账户被盗等情况下降低资产损失的风险。',
  warning_excessive_balance_detected_tips2_app:
    '为更好地保护您的资金，我们强烈建议您安装 DeGate App，并在应用内创建或导入钱包。',
  download_app: '下载App',
  receive_data_tips:
    '点击右上角的"查看地址"，然后将其粘贴到区块链浏览器中以查看交易记录。',

  verify_account: '验证账户',
  est_network_fee: '预估网络费',
  arrival_time: '到账时间',
  gas_refund_tips: '退款金额可能会以多链USDC和/或原生区块链代币的形式返还。',
  network_fee: '网络费',
  estimated_fee: '预估费用',
  actual_fee: '实际费用',
  refund: '退款',

  Browser: '浏览器',
  transaction_details: '交易详情',
  smart_contract_interaction: '智能合约交互',
  interact_with: '交互合约',

  // 1.26
  Raffle: '抽奖',
  round_N: '第N轮',
  pick_your_number: '猜中数字',
  win_1_million: '百万美元等你拿',
  participating: '正在参与',
  become_a_millionaire_now: '立刻成为百万富翁',
  get_free_tickets: '免费领取奖券',
  verify_1_million_prize_fund: '验证100万美元奖金',
  lucky_number: '幸运数字',
  winning_bitcoin_block: '比特币开奖区块',
  block_hash: '区块哈希值',
  participated: '已参与',

  ticket_redemption_phase_ends_in_XXX: '距离兑换截止还有XXX',
  redemption: '兑换',
  pending_draw: '等待开奖',
  announcement: '宣布结果',
  my_tickets_total: '我的奖券 / 全部',
  view_rules: '查看规则',
  earn_up_to_200_thousand_dollars_bonus: '最高赢取<b>20万美元奖金！</b>',
  invite_friends_now: '<b>立即邀请</b>好友参与！',
  prizes: '奖项',
  grand_prize: '头奖',
  second_prize: '二等奖',
  third_prize: '三等奖',
  fourth_prize: '四等奖',
  fifth_prize: '五等奖',
  sixth_prize: '六等奖',
  seventh_prize: '七等奖',
  eighth_prize: '八等奖',

  draw_starts_once_the_bitcoin_block_is_confirmed:
    '一旦比特币区块确认，立即进行开奖。',
  ticket_redemption_closed: '奖券兑换已结束',
  congratulations: '恭喜！',
  you_ve_won: '您赢得了',
  good_luck_for_next_round: '祝您下一轮好运',
  you_weren_t_in_this_round: '错过本轮？',
  join_the_next_round: '快来参加下一轮！',

  tickets_in_round_N: '第N轮奖券',
  my_tickets: '我的奖券',
  total_tickets: '全部奖券',
  total_tickets_tips:
    '奖券兑换结束后，我们会将所有奖券号码的加密哈希值发布到 Base 区块链上。这确保了整个开奖过程的完全透明与防篡改。',
  hash_of_total_tickets: '全部奖券号码的哈希值',
  hash_value_tips:
    '哈希值 = SHA256(Ticket1, Ticket2, …, TicketN)，其中 Ticket1 到 TicketN 表示本轮所有已兑换的奖券号码，且按照从小到大的顺序排列。',
  verify_hash: '验证哈希值',

  reviewing: '审核中',
  manual_review_in_progress_payout_will_follow_shortly:
    '正在进行人工审核，奖励将在稍后发放。',
  received: '已收到',
  points: '积分',
  no_prize_this_time: '本次未中奖',
  all_winners: '所有赢家',
  winning_ticket: '1 获奖奖券',
  winning_tickets_N: 'N 获奖奖券',

  Pick_your_ticket_number: '挑选您的奖券号码',
  Manual: '手动',
  Range: '批量',
  Random: '随机',
  Feeling_lucky: '试试手气',
  Redeem: '兑换',
  Invalid_number: '号码无效',
  Ticket_already_taken: '该奖券号码已被使用，换一个吧！',
  N_Ticket: 'N张奖券',
  N_Tickets: 'N张奖券',

  Points_needed: '需要积分',
  Points_available: '可用积分',
  Redemption_Successful: '兑换成功',
  Ticket_Unavailable: '奖券不可用',
  N_Ticket_Unavailable: 'N张奖券不可用',
  N_Tickets_Unavailable: 'N张奖券不可用',

  Looks_like_someone_just_grabbed_this_number:
    '有人刚刚选走了这个号码，换一个吧！',
  Insufficient_Points: '积分不足',
  You_have_0_point_and_cannot_redeem_tickets: '您当前积分为 0，无法兑换彩票。',
  You_have_POINTS_points_and_can_redeem_a_maximum_of_TICKETS_tickets:
    '您当前积分为 POINTS，最多可兑换 TICKETS 张彩票。',
  How_to_acquire_points: '如何获取积分？',
  Number_Start: '起始',
  Number_End: '结束',
  Please_enter_the_start_number_and_end_number: '请输入起始号码和结束号码',
  End_number_must_be_greater_than_start_number:
    '结束号码需大于起始号码，请重新输入。',
  Those_tickets_have_already_been_taken: '这些号码已被其他用户选走。',
  Looks_like_someone_just_grabbed_some_of_the_tickets:
    '看起来有些号码刚被别人抢走了，请重试。',

  Number_of_tickets: '奖券数量',
  Generate: '生成',
  Please_enter_the_number_of_tickets: '请输入奖券数量',
  N_random_tickets: 'N张随机奖券',
  N_random_ticket: 'N张随机奖券',
  Generate_Again: '重新生成',
  Dashboard: '个人面板',
  My_Points: '我的积分',

  My_Participations: '我的参与记录',
  N_rounds: 'N轮',
  N_round: 'N轮',

  My_Winnings: '我的中奖记录',

  Invite_Friends_and_Earn_20_Extra_on_Their_USDC_Winnings:
    '邀请好友，赚取他们 USDC 奖励的<b>额外 20%</b> 分成',
  They_win_more_you_earn_more_and_there_is_no_cap:
    '他们赢得越多，你赚得越多 —— 没有上限！',
  Invite_your_friends_to_DeGate:
    '邀请好友加入 DeGate，每当他们在抽奖中赢得 USDC，你都能额外获得 20% 的奖励。',
  My_Referral_Link: '我的邀请链接',
  Copy_Link: '复制链接',
  Total_Invited: '累计邀请',
  Total_Rewards: '我的奖励',

  Points: '积分',
  Tickets: '奖券',
  Winnings: '奖励',
  Points_can_be_earned_by_using_the_DeGate_Swap_feature:
    '使用 DeGate 的兑换功能可赚取积分。',
  Go_to_Swap: '前往',
  Winning: '抽奖奖励',
  Redeem_tickets: '兑换奖券',
  Gift: '赠送',
  // Swap: '交易',
  // Invites: '邀请',
  Rewards: '奖励',
  Invite_Rewards: '邀请奖励',

  How_to_Join: '如何参加？',
  Step_N: '第N步',
  Earn_points_by_swapping_on_DeGate: '在 DeGate 兑换赚取积分',
  Use_your_points_to_redeem_raffle_tickets_during_the_redemption_phase:
    '在兑换阶段用积分兑换抽奖券，参与抽奖。',
  Check_the_results_after_the_round_ends_your_lucky_moment_might_be_waiting:
    '开奖结束后记得查看，说不定大奖就是你的！',

  Digits_Matched: '匹配位数',
  All_Match: '匹配全部8位',
  Matches_Last_N: '匹配最后N位',
  Winner: '赢家',
  Prize: '奖品',
  FAQ: '常见问题',
  Rules: '规则',
  How_does_it_Work: '玩法介绍',
  how_to_participate: '如何参加？',

  N_Point: '+N 积分',
  N_Points: '+N 积分',
  You_just_earned_points_from_your_swap: '您刚刚通过兑换交易获得了积分',
  Use_them_to_redeem_raffle_tickets_to_win_1_million_dollars:
    '使用积分兑换抽奖券，赢取 <br/><b>100 万美元大奖！</b>',
  Join_Raffle: '参加抽奖',

  please_enter_amount: '请输入金额',

  claim_prizes: '领取奖金',
  claim_your_prizes: '领取您的奖金',
  all_unclaimed_usdc_will_be_sent_to_your_base_address_shortly:
    '所有未领取USDC稍候会发到您的Base地址',
  Claim_your_invite_rewards: '领取您的邀请奖励',
  Claim_Invite_Rewards: '领取邀请奖励',
  amount_needed: '所需数量',

  download_apk: '下载APK',
  download_app_get: '下载',
  download_page_app_store: 'App Store',
  download_page_google_play: 'Google Play',
  download_page_apk: 'APK',
  download_page_scan_to_download: '扫码下载',
  download_page_partners: '合作伙伴',
  Matches_for_8th_Prize: '最后一位数字 或 最后一位 ±1',
  Select_Network: '选择网络',
  All_Networks: '所有网络',
  Filtering_with_CHAIN_network: '通过CHAIN进行筛选。',
  Claim_History: '领奖记录',
  My_Dashboard: '我的仪表板',
  Claim_Winnings: '领取奖金',
  team_up_to_boost_your_odds_of_winning_1_million_usdc:
    '组队提升获胜几率<div>赢取 1,000,000 USDC ！</div>',
  Create_a_Team_Now: '立即创建队伍',
  Leader: '队长',
  Leader_Bonus: '队长奖励',
  Leader_Bonus_tips: '创建队伍，在你的队伍获胜后，将获得额外 10% USDC！',
  Team_Tickets: '队伍奖券',
  Create_Team: '创建队伍',
  Enter_Team_Name: '输入你的队伍名称',
  Please_enter_a_team_name: '请输入队伍名称',
  Name_already_taken_try_different_one: '名称已被使用，请尝试其他名字。',
  Team_created: '队伍创建成功',
  Invite: '邀请',
  Invite_Team_Members: '邀请队员',
  Team_Details: '队伍详情',
  Team_Points: '队伍积分',
  Pool_My_Points: '投入我的积分',
  Rewards_are_split_by_points_contributed:
    '奖励将按每位成员贡献的积分比例分配。',
  pool_points_tips: '转移我的积分到队伍池，奖励将按贡献比例分配。',
  Please_enter_a_number_that_is_a_multiple_of_10: '请输入 10 的倍数',
  Insufficient_points: '积分不足',
  Added_POINTS_points_to_TEAM: '已为队伍增加积分',
  Join_the_team_to_boost_your_odds_of_winning_1_million_usdc:
    '加入团队，提升您赢得<br/> <b>1,000,000 USDC 的几率！</b>',
  Congratulations_You_ve_joined_the_team: '恭喜！你已加入该队伍。',
  You_re_already_in_this_team: '你已是该队成员',
  Solo: '单人',
  Team: '组队',
  Select_Team: '选择队伍',
  My_Teams: '我的队伍',
  team_tickets_total: '队伍奖券 / 总数',
  how_it_works: '怎么参与？',
  how_to_play_as_a_team: '如何组队参与？',
  invite_tips1: '每当他们在抽奖中赢得 USDC，你将额外获得 20%。',
  invite_tips2: '每当他们通过兑换获得积分，你将获得他们积分的 20%。',
  distribution: '分配',
  new_rule_1_1:
    '<b>1.赚取积分</b><br/> <b>兑换即可赚取积分</b><br/>每次在DeGate上兑换，您都会自动获得积分。',
  new_rule_2_1:
    '<b>2.如何赢取奖金</b><br/> <b>兑换彩票</b><br/>在兑换阶段，使用10个积分可获得1张彩票。',
  new_rule_2_2:
    '<b>选择您的号码</b><br/>每张彩票都有一个唯一的8位数字（00000000–99999999）。您可以选择它，也可以让系统随机为您选择。',
  new_rule_2_3:
    '<b>匹配幸运号码</b><br/>将您的彩票与本轮的幸运号码进行比较。匹配的数字越多（从末尾开始），您的奖金就越大。',
  new_rule_2_4: '举例：当幸运号是 12345678：',
  match_pattern: '匹配规则',
  winning_tickets: '中奖票券',
  represents_any_digit: '✱ 代表任意数字',
  new_rule_3: '<b>3.可验证的公平性</b>',
  new_rule_3_1:
    '<b>区块链驱动的随机性</b><br/>幸运号码基于比特币的一个真实区块 —— 为兑换结束后的第六个区块。它无法被预测或更改。',
  new_rule_3_2:
    '<b>开源算法</b><br/>中奖的比特币区块 Hash 将通过开源代码转换为幸运号码 —— 你可以在 GitHub 上查看并验证。',
  new_rule_3_3:
    '<b>奖金资金证明</b><br/>超过 1.2M USDC 已预先储存在以下钱包地址，且皆可查证：<a href="https://basescan.org/address/0xdB5c7E18FB657F6a8f193024D7F0Aa251Df8C7d6" target="_blank">0xdB5...8C7d6</a> 和 <a href="https://basescan.org/address/0x1c7F26c156caEA62Ad11F6a634051Df43129A656" target="_blank">0x1c7...9A656</a>',
  team_rule_1:
    '<b>1.加入或创建队伍</b><br/>组队可提升赢得 1,000,000 USDC 大奖的几率。',
  team_rule_2: '<b>2.合并你的积分</b><br/>每轮将你的积分加入队伍池。',
  team_rule_3:
    '<b>3.一起兑换</b><br/>任何成员都可以使用队伍积分为队伍兑换票券。',
  team_rule_4:
    '<b>4.不浪费</b><br/>每轮结束时，剩余的队伍积分将自动转换为随机票券。',
  team_rule_5:
    '<b>5.公平分配</b><br/>如果你的队伍中奖，奖励将根据每位成员的贡献积分进行分配。',
  prize: '奖项',
  all_8_digits: '完全匹配 8 位',
  last_N_digits: '匹配后 N 位',
  no_luck: '未中奖',
  Team_Points_Breakdown: '队伍积分详情',
  member: '成员',
  Points_Contributed: '贡献积分',
  you_didnt_win_this_round_better_luck_next_time: '本轮未中奖，祝你下次好运！',
  Rewards_Received: '已领取奖励',
  Points_can_be_earned_by_using_the_DeGate_Swap:
    '使用 DeGate Swap 可赚取积分。',
  Add_to_Team: '加入队伍',
  Team_Refund: '团队退款',
  Receive_from_Team: '从团队获得',
  from_invitee_winnings: '来自受邀者的奖金',
  from_invitee_points: '来自受邀者的兑换',
  draw_starts_once_the_winning_bitcoin_block_is_fully_confirmed:
    '中奖比特币区块完全确认后，抽奖开始。',

  Invite_Friends_and_Earn_20_Extra: '邀请好友，赚取<b>20%额外奖励</b>',
  Team_Points_Available: '可用队伍积分',
  me: '我',

  Stocks: '股票',

  est_account_rent_CHAIN_NUM: '$NUM为CHAIN链租金',
  est_transaction_cost_NUM: '$NUM为交易费用',

  filter_by_network: '按网络筛选',
  manage_tokens_title: '币种管理',
  manage_tokens_short: '管理',
  manage_menu_status_on: '开启',
  manage_menu_status_off: '关闭',
  manage_tokens_my_assets: '我的资产',
  manage_tokens_other_assets: '其他资产',
  manage_tokens_add_btn: '添加币种',
  manage_tokens_contract_address: '合约地址',
  manage_tokens_contract_address_placeholder: '输入合约地址',
  manage_tokens_symbol: '符号',
  manage_tokens_decimal: '精度',
  manage_tokens_not_found: '未找到币种，请检查合约地址和网络。',
  manage_tokens_added: '{TOKEN}已在您的币种列表内。',
  manage_tokens_remove_confirm_title: '移除币种',
  manage_tokens_remove_confirm_desc: '将{TOKEN}从您的币种列表中删除？',
  manage_tokens_remove_confirm_btn: '移除',
  Mainnet: '主网',
  Testnet: '测试网',

  More_Services: '更多服务',
  current_block: '当前区块',
  fully_confirmed: '完全确认',

  create_account: '创建账户',
  create_account_tips: '新用户请先创建账户， 大约<b>30秒</b>完成。',
  account_created: '账户已创建',
  please_create_account_first: '请先创建账户',
  unable_to_create_account: '无法创建账户',

  this_asset_is_self_custodied_in_your_CHAIN_address:
    '该资产由您自行托管，存放于您的 <b>CHAIN 地址</b>',

  generate_wallet_address: 'DeGate 现已支持以下新链。',
  generate_wallet_address_tips: '点击“确认”生成您的钱包地址。',
  updating: '正在更新',
  please_wait: '请等待',
  close_this_window_to_resume_what_you_were_doing:
    '关闭此窗口以继续您之前的操作',
  Funds: '资金',
  Route: '路径',

  free_team_tickets: '免费团队奖券',
  free_team_tickets_tips: '达成里程碑可让团队奖券<b>翻倍</b>',
  if_the_target_isn_t_met_this_round_progress_resets:
    '若本轮未达目标，进度将重置',
  n_tickets_to_claim: '待领取 N 张奖券',
  claim_bonus: '领取奖励',
  any_unclaimed_tickets_will_be_automatically_claimed_when_the_redemption_phase_ends:
    '兑换阶段结束时，所有未领取奖券将自动领取',
  n_tickets_claimed: '已领取 N 张奖券',
  n_tickets_to_claim_m_claimed: '待领取 N 张奖券（已领取 M 张）',
  all_n_tickets_claimed: 'N 张奖券已全部领取',
  generate_N_tickets: '生成 N 张奖券',

  // flash
  TRY_YOUR_LUCK_NOW: '立即试手气',
  ENTER_WIN_BIG: '参与赢大奖！',
  FEELING_LUCKY: '觉得自己够幸运？',
  HIT_THAT_000000: '冲击 000000！',
  Enter: '立即参与',
  N_Points_for_1_Entry: 'N 积分兑换 1 次抽奖',
  awaiting: '等待开奖…',
  numbers_incoming: '号码生成中…',
  HOLD_TIGHT_GOOD_LUCK: '稍等，祝你好运！',
  Entry: '参与',
  Refund: '退款',
  how_to_earn_points: '如何赚取积分？',
  how_to_earn_points_tips: '在DeGate交易Meme、做兑换可赚取积分',
  Go_to_meme: '前往Meme',
  Verify: '验证抽奖',
  Winning_Block: '中奖区块',
  Entry_Time: '参与时间',
  Points_History: '积分历史',
  Raffle_History: '抽奖历史',

  Verify_Raffle_Results: '验证抽奖结果',
  Fair_play_proof_in_3_steps: '三步验证公平性',
  Proof_of_fair_play_in_3_steps: '三步验证公平性',
  verify_tips_1: '1. 公布 Secret 指纹',
  verify_tips_1_1:
    '抽奖前公开 Secret 的哈希（“指纹”），哈希固定后 Secret 无法被替换。',
  verify_tips_2: '2. 下一区块定胜负',
  verify_tips_2_1:
    '点击 “参与” 后，Secret 与下一个Base链区块共同生成 6位幸运号码。',
  verify_tips_3: '3. 揭示并验证',
  verify_tips_3_1:
    '打开抽奖记录，点击“揭示并验证”，比对哈希并重新计算；结果一致即证明无人篡改。',
  verify_tips_4: 'Secret一经揭示，系统生成新的Secret用于之后的抽奖',
  hash_of_secret: 'Secret 哈希值',
  secret: 'Secret',
  winning_block: '中奖区块',
  keccak256: 'keccak256(Secret, Block hash) % 1000000',
  hash_of_secret_for_next_entry: '下一次抽奖的 Secret 哈希值',
  proof: '证明',
  entry_time: '参与时间',
  not_revealed: '未揭示',
  download_tickets: '下载奖券',
  Total_Winnings: '总奖金',

  time_limited: '限时',
  Exclusive_Friend_Rewards: '专享好友奖励',
  Register_an_account_You_and_your_friend_get_10_FREE_entries_each:
    '开户即送 - <br/><b>您和好友各得 10 次免费抽奖机会</b>',
  Get_Rewards: '立即领取',
  You_re_eligible_for_10_FREE_Entries: '您符合条件，可获 <b>10 次免费抽奖</b>',
  Expires_in_XXX: '过期时间： XXX',
  Invite_a_friend_to_join_DeGate: '邀请好友加入 DeGate',
  invite_text_1:
    '我收到 DeGate 的邀请活动——我们各有 10 次免费抽奖机会（最高可赢 5000 美元），限时哦，赶紧来！',
  you_received: '您已收到',
  free_entries_10: '10 次免费抽奖',
  Free_Entries_times_N: '免费抽奖次数：N',

  EXPIRED: '已过期',
  flash_op_create_account_tips: '创建账户 - 您和好友各得 10 次免费抽奖机会',
  offer_is_expired: '本活动已过期',
  offer_is_limited_to_new_users_only: '本活动仅限新用户',
  get_rewards_now: '立即领取奖励',
  Later: '稍后再说',
  so_close_try_again: '差一点！再来一次？',
  no_luck_try_again: '这次没中，再试试？',
  no_route_fund: '未找到兑换路径 — 请尝试更改金额或稍后再试。',

  trading_restriction_notice: '交易限制通知',
  trading_restriction_notice_tips:
    '根据 <a href="https://assets.backed.fi/legal-documentation/restricted-countries" target="_blank">Backed</a> 的受限国家/地区清单，您所在地区不可交易此链上股票代币：',
  trading_restriction_notice_tips_2:
    '此限制仅适用于 Backed 发行的部分代币；您仍可交易其他代币。',
  btn_got_id: '我知道了',
  Invalid_SOL_rent: '剩余SOL不足支付租金',

  stocks: {
    Hot_Stocks: '热门股票',
    Last: '最新价',
    Chg: '涨跌',
    Chg_Percent: '涨跌幅',
    Stock_Heatmap: '热力图',
    Stock_Heatmap_AUM: '股票热力图（AUM）',

    Holders_per_Stock: '持币人数',
    Holders_per_Stock_top_20: '持币人数（Top 20）',
    Trades_per_Stock: '成交笔数',
    Trading_volume_DEX_per_Stock: '成交量(DEX)',
    Trading_vol: '交易量',
    Daily_Trading_Accounts_per_Stock: '各股每日交易账户数',
    Token_Holders_AUM: '持币人数&AUM',
    Issuer: '发行人',
    Onchain_AUM: '链上AUM',
    Valuation: '估值',
    Dex_Trading_Vol: '24H DEX成交量',
    Onchain_Supply: '链上供应量',
    Onchain_Holders: '链上持币人数',
    Audit_URL: '审计URL',
    Dex_Liquidity: 'DEX流动性',
    Websites: '网站',
    News_Flow: '新闻',
    Trading_Vol_Dex_Liquidity: '成交量&DEX流动性',
    AUM_desc: 'AUM',
    Onchain_Opportunity: '链上机会',
    '24h APY': '24小时年化收益率',
    stocks_doc_title: '链上股票仪表盘 | 收益洞察与策略',
    total_aum: '总AUM',
    total_unique_holders: '去重持币人数',
    total_dex_volume: 'DEX交易总量',
    total_tvl: '链上资金池流动性',
    total_assets: 'xStock资产数量',
    Trade_with_ZERO_FEES: '零手续费交易',
    Legal_Info: '法律信息',
  },
  swap_error: {
    Swap_failed_return_below_minimum_receive:
      '兑换失败：预估到手数量低于最小接收量。',
    Insufficient_liquidity_for_this_token_reduce_amount_and_try_again_later:
      '该代币流动性不足。请减少数量后重试。',
    Swap_failed_price_impact_exceeds_limit: '兑换失败：价格影响超过限制。',
    Swap_failed_honeypot_or_high_risk_token_detected:
      '兑换失败：检测到蜜罐或高风险代币。',
    Swap_failed_insufficient_sol_for_rent:
      '兑换失败：SOL 余额不足以支付租金。请充值少量 SOL 后重试。',
    Return_below_minimum_receive: '预估到手数量低于最小接收量',
    Insufficient_liquidity_for_this_token: '该代币流动性不足',
    Price_impact_exceeds_limit: '价格影响超过限制',
    Honeypot_or_high_risk_token_detected: '检测到蜜罐或高风险代币',
    Insufficient_sol_for_rent: 'SOL 余额不足以支付租金',
    Swap_failed_insufficient_funds_for_gas: '兑换失败：余额不足支付gas',
    Insufficient_funds_for_gas: '余额不足支付gas',
    Estimated_network_fee_is_less_than_the_actual_amount_required:
      '预估网络费低于实际所需',
  },
  gift: {
    Gift_Box: '礼盒',
    View_Gift_Box: '查看礼盒',
    Download_App: '下载应用',
    Your_gift_awaits: '您的礼品已就绪',
    Open_Now: '立即打开',
    Cash_Gift_for_CopyTrade: '自动跟单现金礼',
    Receive_gift_in_DeGate_App: '在 DeGate App 领取礼品',
    This_gift_box_was_claimed_by_a_different_account_you_previously_used:
      '该礼盒已被您之前使用的其他账户领取',
    Youve_received_a_Cash_Gift_for_CopyTrade: '您已收到{GIFT TYPE}',
    has_been_sent_to_your_CopyTrade_account: '已发送至您的自动跟单账户',
    View_My_Account: '查看我的账户',
    claim_your_gift_please_create_a_DeGate_account:
      '领取礼品前，请先创建 DeGate 账户',
    Total_Gift_Amount: '礼品总额',
    Expired_at_DATE: '于 DATE 过期',
    Gifts_claimed_CLAIMED_TOTAL: '礼品（已领取 CLAIMED/TOTAL）',
    Today: '今天',
    Youve_received_your_gift_cash_Outgoing_transfers_will_be_enabled_after_your_Copy_Trade_bot_completes_its_first_trade:
      '您已收到现金礼。自动跟单机器人完成第一笔交易后即可转出。',
    Others_were_faster_Try_again_next_time: '别人更快一步。下次再试吧！',
    Connect_wallet_to_claim: '连接钱包后领取',
    Expired_in_DATE: '在 DATE后过期',
  },
  turboRange: {
    Turbo_Range: '区间宝',
    my_positions: '我的持仓',
    my_turbo_range: '我的区间宝',
    yesterday_yield: '昨日收益',
    total_yield: '总收益',
    Details: '详情',
    all_products: '全部产品',
    invert_USDC: '投入USDC',
    apy_7D: '7日年化收益率',
    you_have_no_position: '您没有持仓',
    invest: '投入',
    create_position: '创建仓位',
    price_range: '价格区间',
    earn_yield_while_TSLA_price_stays_in_your_range:
      '{TSLA}的价格在您设定的区间内，即可赚取收益',
    earn_yield_while_price_stays_in_your_range:
      '在您设定的价格区间内，即可赚取收益',
    est_apy: '预计年化收益率',
    estimated_annual_percentage_yield_based_on_last_7_days_data:
      '预计年化收益率，基于最近7日数据',
    est_annual_yield: '预计年收益',
    enter_amount_to_continue: '请输入数量',
    set_price_range: '设置价格区间',
    current_price: '当前价格',
    current: '当前',
    min_price: '最低价格',
    max_price: '最高价格',
    please_enter_an_amount: '请输入数量',
    maximum_500000: '最大 500000',
    adjust_the_input_to_proceed: '请调整输入',
    please_reduce_amount: '请减少数量',
    not_enough_balance_to_proceed: '余额不足',
    processing_deposit_to_liquidity_pool: '正在将资金存入流动性池',
    you_can_close_this_window_we_ll_handle_it:
      '您可以关掉这个窗口，剩下的我们来处理。',
    investment_successful: '投入成功',
    invested: '实际投入',
    returned: '已返还',
    view_my_position: '查看我的持仓',
    investment_failed: '投入失败',
    about_turbo_range: '关于区间宝',
    turbo_range_puts_your_funds_into_a_liquidity_pool_within_the_price_range_you_set_when_others_trade_in_that_range_you_earn_fees:
      '<b>区间宝</b>会把您的资金投入到一个价格区间内的流动性池中。当其他人在这个区间内交易时，您将赚取他们支付的手续费。',
    example: '举个例子',
    let_s_say_you_invest_1000_USDC_in_the_TSLA_USDC_pool_and_set_a_range_of_270_330_TSLA_s_current_price_is_300:
      '您用 1000 USDC 投入 TSLA/USDC 流动性池，并设置价格区间为 270 ~ 330（假设当前TSLA价格是 300）。',
    step1: '1. 系统会自动计算，用约 476 USDC 买入 约1.59 TSLA；',
    step2: '2. 因此，您现在持有约 524 USDC 和 约1.59 TSLA；',
    step3: '3. 这两个资产刚好可以投入到您设定的区间里。',
    what_happens_in_different_price_scenarios: '区间内外会发生什么？',
    desc_1: '情况一：价格在 270 ~ 330 之间波动',
    desc_1_1: '您持续赚取手续费，无需操作。',
    desc_2: '情况二：价格跌破 270',
    desc_2_1:
      '您持仓会变成全是 TSLA（约 3.43 个），加上赚到的手续费。您可以选择继续持有，等价格涨回来。',
    desc_3: '情况三：价格涨超 330',
    desc_3_1:
      '您持仓会变成全是 USDC（约 1023 USDC），加上手续费收入。您已经赚了约 23 USDC + 手续费。',
    underlying_on_chain_assets: '底层链上资产',
    principal: '本金',
    unclaimed_yield: '未领取收益',
    in_range: '在区间内',
    out_of_range: '在区间外',
    total_pnl: '总盈亏',
    underlying_assets: '底层资产',
    initial_principal: '初始本金',
    closed_principal: '结束本金',
    principal_pnl: '本金盈亏',
    created_at: '创建于',
    closed_at: '结束于',
    claim_yield: '领取收益',
    all_TSLA_will_be_converted_to_USDC: '所有的{TSLA}会转换成{USDC}',
    est_receive: '预计收到',
    claim_successful: '领取成功',
    has_been_added_to_your_account: '已存入您的账户',
    claim_failed: '领取失败',
    convert_TSLA_to_USDC_and_receive_USDC_only:
      '将 {TSLA} 兑换为 {USDC}，并仅接收 {USDC}',
    receive_both: '同时接收两种代币',
    convert_TSLA_to_USDC_and_receive_USDC:
      '将 {TSLA} 兑换为 {USDC}，并接收 {USDC}',
    receive_TSLA: '接收 {TSLA}',
    withdrawing: '正在提现',
    withdrawal_successful: '提现成功',
    withdrawal_failed: '提现失败',
    Simple_Earn: '单币理财',
    view_in_turbo_range: '在区间宝查看',
    position_history: '仓位历史',
    initial_investment: '初始投入',
    click_history_above_for_details: '点击上方ICON历史查看详情',
    how_does_turbo_range_earn_yield: '区间宝如何赚收益？',
    transaction_in_progress: '1笔交易进行中',
    transaction_successful: '1笔交易成功',
    transaction_failed: '1笔交易失败',
    N_transactions_in_progress: 'N笔交易进行中',
    N_transactions_successful: 'N笔交易成功',
    N_transactions_failed: 'N笔交易失败',
    position: '持仓',
    my_position: '我的持仓',
    all_time_yield: '总收益',
    yesterday_apy: '昨日年化收益率',
    duration: '运行时长',
    all_time_apy: '累计年化收益率',
    updating: '更新中…',
    will_be_calculated_on_DATE: '将于 DATE 计算',
    returned_to_your_wallet: '返还至您的钱包',
    principal_upon_closure: '关闭时本金',
    est_apy_tips: '年化收益率按照所选区间的历史数据计算',
    invalid_range: '区间无效',
    faq_1: '什么是流动性池？',
    faq_1_text:
      '流动性池是部署在区块链上的智能合约，用于存放两种代币，例如 ETH 和 USDC。用户可以直接通过该智能合约在这两种代币之间进行交易。任何人都可以将自己的代币存入池中提供流动性，并按比例获得交易手续费分成。',
    faq_2: '如何通过提供流动性来赚费用？',
    faq_3: '区间宝作为一种投资，有什么优势？',
    faq_3_text1:
      '相比传统的“买入并持有“（例如买特斯拉股票，必须涨才能赚钱），区间宝的优势在于：横盘也能赚钱，上涨还能赚得更多。',
    faq_3_text2: '<b>横盘时：</b> 持续赚取区间内的交易手续费',
    faq_3_text3: '<b>上涨时：</b> 本金随价格上涨而升值，同时继续赚取手续费',
    put_simply: '简单来说：',
    put_simply_text: '不只涨的时候赚钱，横盘的时候也在赚钱。',
    faq_4: 'DeGate能控制我的区间宝仓位吗？',
    faq_4_text:
      '不能。你的区间宝仓位完全在链上，且保存在你自己的钱包里。只有你本人可以访问或提取你的资金。',
    faq_4_n: '如何用区间宝进行抄底？',
    faq_4_n_text:
      '假设某个资产当前价格为100，而你希望在大约75的位置买入，那么你可以创建一个50–100的区间宝，当价格在这个区间内波动时，区间宝会持续产生收益，从而帮助你拉低平均买入成本。',
    faq_4_n_text2:
      '当价格跌到 50 时，记得关闭区间宝。如果不关闭，价格回到 50 以上时，该仓位会再次开始买入。',
    faq_6: '价格跑出区间后，区间宝会自动关闭吗？',
    faq_6_text:
      '不会，它不会自动关闭。若价格再次回到区间内，区间宝会继续产生收益。若要停止已出区间的区间宝，您需要手动关闭。',
    websites: '网站',
    liquidity_pool: '流动性池',
    liquidity_pool_age: '流动性池年龄',
    total_value_locked_of_raydium: '{Raydium}总锁定价值',
    XX_as_of_DATE: '截至{DATE}：{XX}美元',
    market_cap_of_paxg: '{PAXG}总市值',
    desc_xstocks:
      'TSLAx 是由 Backed Assets (JE) Limited 发行的 xStock。xStock 的发行符合瑞士法律，并已于 2025 年 5 月 8 日获得列支敦士登金融市场管理局（FMA）的批准。',
    desc_gold:
      'PAXG 是由 Paxos Trust Company 发行的数字资产。每枚 PAXG 由存放在伦敦 LBMA 金库的1盎司（troy ounce）黄金作为背书。Paxos 受纽约州金融服务署（NYDFS）监管。',
    desc_btc:
      'cbBTC 是由 Coinbase 发行、以比特币作背书的代币。每枚 cbBTC 对应 Coinbase 托管的一枚比特币，并可按 1:1 赎回。Coinbase 为美国上市公司，受美国监管机构监管。',
    desc_native_coin_ETH_NETWORK: '{ETH} 是{NETWORK}网络的原生代币',
    legal_documentation: '法律文件',
    factsheet: '资产概览',
    audit_reports: '审计报告',
    Onesheet: '资产概览',
    on_chain_assets_and_protocol: '链上资产和协议',

    entry_price: '入场价',
    initial_entry_price: '初始建仓价格',
    last_24h_yield: '过去24小时收益',
    last_24h_apy: '过去24小时年化收益率',
    last_24h: '过去24小时',
    xx_until_now: '从 XX 至今',
    view_hourly_breakdown: '查看每小时明细 \u2192',
    hourly_breakdown: '每小时明细',
    overall_24h_apy: '过去24小时年化收益率',
    show_less: '收起',
    active_capital: '在投资金',
    withdraw_and_close: '提现并关闭',
    withdraw_and_claim: '提现并领取收益',
    incl_unclaimed_yield: '含未领取收益',
    capital_withdrawn: '已提现资金',
    yield_claimed: '已领取收益',
    fee_pre_charged: '此费用在您开仓时已预先扣除，关闭持仓时会返还到您的钱包。',

    price_is_out_of_range_see_tips: '价格已出区间，查看提示',
    what_do_you_think_XXX_s_price_will_do_next: '您认为{XXX}的价格接下来会…',
    rise_and_move_back_into_my_price_range: '上涨并回到我的价格区间',
    move_sideways_around_the_current_price: '在当前价格附近横盘',
    keep_falling: '继续下跌',
    if_you_think_XXX_s_price_will_rise_and_move_back_into_your_price_range:
      '如果您认为{XXX}的价格会上涨并回到您的价格区间…',
    you_will: '您可以',
    hold_and_wait: '继续持有和等待',
    if_you_think_XXX_s_price_will_move_sideways_around_the_current_price:
      '如果您认为{XXX}的价格会在当前价格附近横盘…',
    close_your_position_and_open_a_new_one: '关闭您的仓位后再新开一个',
    close_position: '关闭持仓',
    if_you_think_XXX_s_price_will_keep_falling:
      '如果您认为{XXX}的价格会继续下跌…',
    close_position_and_withdraw_USDC: '关闭持仓并提现USDC',
    adjust_price_range: '调整价格区间',
    adjust_now: '立即调整',
    increase_investment: '追加投入',
    increasing_investment: '正在追加投入',
    investment_increased: '已追加投入',
    investment_increase: '追加投入',
    increase_failed: '追加失败',
    total_principal: '总本金',
    total_withdrawal_and_claim: '总提现与领取',

    investModeSingle: '单币',
    investModeDual: '双币',
    nagative_invest_tips:
      '该负数表示资金已退回至您的钱包。详情请查看仓位历史。',

    APY_Backtest: '年化收益率回测',
    Historical_APY_desc:
      '此处显示的历史年化收益率为回测结果，基于所选时间段的历史数据计算，反映了若在该时段开始时进行投资所能获得的年化收益率。',
    Historical_APY: '历史年化收益率',
    XXX_Overall_APY: 'XXX 总年化收益率',
    Partially_in_range: '部分在区间内',
    In_range: '在区间内',
    Out_of_range: '在区间外',

    // Strategies Marketplace
    strategies: '策略广场',
    top_apy: '年化效率',
    hot_today: '今日热门',
    best_returns: '历史战绩',
    roi: '总回报率',
    total_return: '总回报',
    connect_wallet_to_see_positions: '连接钱包后查看您的持仓',
    re_open: '重新开仓',
    view_details: '查看详情',
    copy: '复制',
    initial_price: '初始价格',
  },
  Product: '产品',
  filter: '筛选',
  Failed: '失败',
  History_currently_unavailable: '目前无法显示历史记录',
  History_currently_unavailable_tips:
    '请前往「首页」分页复制您的钱包地址，并在区块链浏览器查看交易记录。',
  Approval: '授权',
  Contract_Call: '合约调用',
  Unlimited: '无限',
  APY_1: '年化1',
  External_Sites: '外部站点',
  XXX_Refundable: 'XXX 可返还',
  Refundable_on_data_release: '数据释放时返还',
  est_time: '预估时间',
  Refundable_when_position_is_closed: '持仓关闭时退还',

  go_to_turbo_range: '前往区间宝',
  go_to_earn: '前往单币理财',
  in_address: '地址余额',
  in_copy_trade: '自动跟单账户',

  move_usdc_across_chains: '按 1:1 比例跨链转移 USDC',
  bridge_successful: '跨链成功',
  no_result_found: '没有数据',
  enter_address: '请输入地址',
  scan: '扫码',
  check_address_format: '请检查地址格式',
  invalid_address: '地址格式不正确',
  estimated_network_fee: '预估网络费',
  incl_solana_rent_of_XXX: '包含Solana租金 $XXX',
  check_my_balance: '查看余额',
  moving_your_USDC_to_destination_network: '正在将您的USDC转至目标网络…',
  you_don_t_have_enough_USDC_to_pay_for_the_network_fee:
    '您没有足够的USDC来支付网络费',
  change_fee_token: '更改付费币种',
  estimated: '预估',
  actual: '实际',
  receive_usdc: '收款USDC',
  from_other_wallets: '从其他钱包',
  bridge_usdc: '跨链USDC',
  consolidate_to_one_chain: '合并到一条链',
  simple_earn_disabled_deposit_tips: '该金库的抵押资产波动剧烈，请谨慎操作。',
  Time_to_complete: '完成时间',
  You_Pay: '您需支付',
  Returned_to_your_wallet_when_position_is_closed:
    '当仓位关闭时将退回至您的钱包',
  Refundable_Fee: '可返还费用',
  Fee_Refunded: '费用已返还',
  Claiming: '领取中',
  Reinvesting: '复投中',
  Withdrawing: '提现中',
  Adding: '追加中',

  Cash_Buy: '购买',
  Buy_with_cash_card: '以现金/银行卡购买',

  est_gas_needed_for_network_fee: '$EST_GAS USDC 作为网络费预留',
  available_amount: '可用数量',
  current_balance: '当前余额',
  reserved_for_network_fee: '网络费预留',
  maximum_available: '最大可用',
  use_max: '使用最大值',
  edit_amount: '修改数量',
  insufficient_network_fee: '网络费不足',
  separator_comma: '、',
  insufficient_network_fee_tips:
    '需要支付网络费 $FEE  。您可以使用 $XXX、USDC、USDT 或其他代币支付。',
  pay_with_another_token: '用其他币种支付',
  History_is_currently_unavailable_for_CHAIN:
    '{CHAIN} 的历史记录当前不可用。详情请前往区块链浏览器查看。',
  Check_on_Explorer: '浏览器查看',
  Min: '最小',
  Max: '最大',
  enable_notifications: '开启通知？',
  receive_notification_when_out_of_price_range: '超出价格区间时接收通知',
  we_ll_notify_you_when_your_turbo_range_goes_out_of_range:
    '当区间宝超出价格区间时您会收到通知',

  referral: '返佣',
  referral_code: '推荐码',
  your_referrer: '您的推荐人',
  please_confirm_within_10_seconds: '请在10秒内完成确认',
  confirmation_expired: '确认已过期，请重新尝试。',

  select_Open_in_Default_Browser_from_the_menu: '从菜单中选择“默认浏览器打开”',
  you_need_a_DeGate_account_to_continue: '您需要一个DeGate账户',
  claim_now: '立刻领取',
  please_wait_it_takes_xx_seconds: '请稍候，大约需要xx秒',
  you_have_received_a_Turbo_Range_position_worth_XXX:
    '您收到了价值约$XXX的区间宝持仓',
  view_my_balance: '查看我的余额',
  sorry_youve_already_claimed_once: '抱歉，您已领取过礼品卡',
  gift_card_expired: '礼品卡已过期',
  gift_card_has_not_been_activated: '礼品卡未激活',
  gift_card_has_been_claimed: '礼品卡已被领取',
  please_open_this_page_on_your_mobile_phone: '请用您的手机打开本页面',
  open_with_DeGate_App: '用 DeGate App 打开',
  sign_in: '登录',
  Show_more: '显示更多',

  signature_free_mode_tips:
    '在此模式下，您可以无需签名即可兑换代币。要切换模式，请点击右上角的设置图标。',
  invite_to_degate_experience_enhancement_program:
    '您受邀参与 DeGate 体验提升计划',
  as_a_selected_user_youll_get: '作为特邀用户，您将享有：',
  a_smoother_app_experience: '更流畅的 App 使用体验',
  dedicated_one_on_one_support: '专属的一对一服务',
  private_client_desk: '私享客户专席',
  private_client_desk_upperCase: '私享客户专席',
  through_this_desk_you_may: '通过本专席，您可享受：',
  receive_priority_operational_support: '优先运营支持',
  direct_communication_with_our_strategy_and_operations_team:
    '直连我们的战略与运营团队',
  early_access_to_new_products: '抢先体验新产品',
  access_exclusive_privileges_and_customized_benefits:
    '尊享专属权益与定制化福利',
  private_client_desk_access_path_intro: '您可通过以下路径访问私享客户专席：',
  private_client_desk_access_path_home_menu: '首页 > 菜单 > 私享客户专席',
  private_client_desk_access_path_home_settings: '首页 > 设置 > 私享客户专席',
  private_client_desk_access_bottom_left_corner: '您可在左下角访问私享客户专席',
  WhatsApp: 'WhatsApp',
  Signal: 'Signal',
  Email: '邮箱',
  welcome_aboard: '欢迎加入！',
  youre_now_among_a_select_group_enjoying_an_enhanced_degate_experience:
    '你已加入少数享有更优 DeGate 体验的用户群',
  link_expired: '链接已过期',

  please_update_your_app_to_the_latest_version: '请升级到最新App版本',
  chart_is_currently_unavailable: '图表暂不可用',
};

export default zhCN;
