const zhTW = {
  language: 'zh-TW',
  'kline.time_Line': '分時',
  'kline.time_1s': '1秒',
  'kline.time_5s': '5秒',
  'kline.time_15s': '15秒',
  'kline.time_30s': '30秒',
  'kline.time_1m': '1分鐘',
  'kline.time_3m': '3分鐘',
  'kline.time_5m': '5分鐘',
  'kline.time_15m': '15分鐘',
  'kline.time_30m': '30分鐘',
  'kline.time_1H': '1小時',
  'kline.time_2H': '2小時',
  'kline.time_4H': '4小時',
  'kline.time_6H': '6小時',
  'kline.time_1D': '1天',
  'kline.time_1W': '週線',
  'kline.time_1M': '月線',
  'kline.tab_line': '圖表',
  'kline.tab_depth': '深度圖',
  'kline.chartType_Bars': '線',
  'kline.chartType_Candles': 'K線圖',
  'kline.chartType_Hollow_Candles': '空心K線圖',
  'kline.chartType_Line': '線段',
  'kline.chartType_Area': '區域',
  'kline.chartType_Heikin_Ashi': '平均K線圖',
  degate_account: 'DeGate帳號',
  Trade: '交易',
  Order: '訂單',
  Grid: '網格策略',
  Campaign: '活動',
  DCA: '定投計劃',
  Advanced: '進階',
  Add: '添加',
  Add_Funds: '添加資金',
  external_wallet_receive_guide: 'DeGate 錢包沒有資產，請從外部錢包轉入。',
  external_wallet_add_funds_guide: 'DeGate 內沒有資金，請從外部錢包添加資金。',
  eth_added_1: '已添加 1 ETH',
  eth_sent_1: '已發送 1 ETH',
  Send: '發送',
  Internal_Transfer: '內部轉帳',
  Miscellaneous: '其他',
  Mining: '挖礦',
  Liquidity_Mining: '流動性挖礦',
  Analytics: '統計',
  Support: '支援',
  Help: '幫助',
  Tips: '提示',
  Statistics: '統計資料',
  Coming_soon: '即將推出',
  Faucet: '水龍頭',
  more: '更多',
  hide: '隱藏',
  change: '調整',
  'Wrong Network': '錯誤網路',
  avbl: '可用餘額',

  insufficient_balance_AAA: '您的錢包裡 AAA 不足。 請確認餘額並重試。',
  insufficient_balance: '餘額不足',
  wallet_denied_sign: '簽名訊息被拒絕',
  common_err: '出了些問題。請稍後再試',
  common_err_ledger_version:
    '發生了錯誤。請確保您的 Ledger Ethereum應用程式是最新的（1.9.10 或更高版本），或者您可以稍後重試。',
  network_1: 'Ethereum(主網)',
  network_err: '不支援的網路，請稍後再試',
  rate_limit_err: '連線頻率過高，請一分鐘後重試。',
  error_InsufficientGasFunds: '錢包Gas Fee餘額不足',
  notification_transaction_send: '交易已發送',
  view_on_explorer: '請在區塊鏈瀏覽器上查看',
  view_address: '查看錢包地址',
  switch_network: '切換網路',
  switch_to_Arbitrum: '請切換至 Arbitrum 網路以繼續',
  switch_to_MAINNET_in_metamask: '請在 MetaMask 切換為 MAINNET',
  switch_to_MAINNET: '請切換為 MAINNET',
  switch_network_in_walletconnect:
    '請前往您的錢包，並使用 WalletConnect 切換網路',
  Retry: '請重試',
  wallet_tips: '請在瀏覽器錢包中確認',
  wallet_ledger_tips: '請在 Ledger 冷錢包中確認',
  wallet_metamask_tips: '請在 MetaMask 中確認',
  wallet_walletconnect_tips: '請前往您的錢包，並使用 WalletConnect 確認',
  wallet_cancelled_tips: '您已取消簽名',
  Close: '關閉',
  Closed: '已關閉',
  copied: '已複製',
  Details: '詳細資訊',
  view_details: '查看詳細資訊',
  turbo_range_view_live_status: '查看即時狀態',
  Share: '分享',
  view_graph: '在圖表中查看',
  Dismiss: '關閉',
  Cancel: '取消',
  End: '關閉',
  End_grid: '關閉',
  Confirm: '確認',
  Cancel_all: '取消全部',
  cancel_all_tips: '取消全部掛單',
  Submit: '送出',
  no_data: '查無資料',
  all_data_displayed: '已經顯示所有資料',
  no_data_within_90_days: '過去90天內無資料',
  only_display_90_days: '僅顯示過去90天的資料',
  displayed_90_days: '顯示過去90天的資料',
  only_data_beyond_90_days_trade:
    '要取得超過90天的資料，請選擇「查看全部」，然後選擇「匯出資料」功能。',
  only_data_beyond_90_days_grid_detail: '目前不支援超過最近90天的資料查詢',
  only_data_beyond_90_days_spot_history:
    '要取得超過90天的資料，請使用「匯出資料」功能。',
  View: '查看',
  service_unavailable_for_region_REGION: '此服務在 REGION 無法使用。',
  service_unavailable: '服務無法使用',
  service_error: '請稍後再試',
  service_maintenance: '此服務正在進行維護',
  connect_wallet: '連接錢包',
  switch_address: '切換地址',
  wallet_wc: '已與 WalletConnect 連接',
  wallet_ledger: '已與 Ledger 冷錢包連接',
  register_dexAccount: '註冊',
  deposit_ETH: '添加 ETH',
  initialize: '初始化',
  initialization: '初始化',
  invalid_signature: '無效簽名',
  possible_cause: '可能的原因',
  locale_time_error: '您的本機時間不準確',
  authorization_mode: '授權模式',
  authorization_mode_standard: '免簽名',
  authorization_mode_single_use: '單次簽名',
  turn_on: '開啟',
  turn_on_signature_free_mode: '開啟免簽名模式',
  signatre_free_mode: '開啟免簽名模式',
  turn_on_signature_free_mode_tips:
    '在此模式下，您可以在不簽名的情況下下單。要切換模式，請至「交易按鈕」下方進行設定。',
  turn_on_signature_free_mode_tips_grid:
    '在此模式下，您可以在不簽名的情況下建立網格策略。要切換模式，請至「交易按鈕」下方進行設定',
  turn_on_signature_free_mode_tips_dca:
    '在此模式下，您可以在不簽名的情況下建立定投計劃。要切換模式，請至「交易按鈕」下方進行設定。',
  yes: '是',
  no: '否',
  free_mode_on: '免簽名模式已開啟',
  view_balance: '查看餘額',
  delete_asset_key: '刪除資產金鑰',
  delete_asset_key_desc: '一旦從瀏覽器中刪除資產金鑰，標準授權模式將被關閉。',
  no_asset_key_tips: '在您的瀏覽器中找不到任何資產金鑰',
  turn_off_standard_mode: '關閉免簽名模式',
  reset_asset_key: '重設資產金鑰',
  view_asset_key: '查看資產金鑰',
  lock_success: '資產金鑰已刪除',
  reset: '重設資產金鑰',
  delete: '刪除',
  withdraw_ETH: '發送 ETH',
  transfer_ETH: '內部轉帳 ETH',
  history: '歷史紀錄',
  view_history: '在歷史紀錄中查看',
  internal_transfer: '轉帳',
  assets_record_link: '歷史紀錄',
  other: '其他',
  login_success: '連接成功',
  Account: '帳戶',
  Address: '地址',
  Disconnect: '中斷連接',
  copy_address: '複製地址',
  copy_grid: '複製策略',
  Copy: '複製',
  btn_search: '搜尋',
  btn_reset: '重設',
  btn_confirm: '關閉',
  btn_max: '最大值',
  btn_ok: '知道了',
  spot_trade: '現貨',
  grid_trade: '網格',
  err_balance_title: '下單失敗',
  err_balance_content: '可用餘額不足。請驗證後再試一次。',
  order_failed: '下單失敗',
  insufficient_order_value: '訂單金額不足',
  grid_failed: '建立失敗',
  err_eth_gas: 'Ethereum網路嚴重擁擠',
  err_insufficient_balance_TOKEN1: 'TOKEN1 餘額不足',
  err_insufficient_balance_TOKEN1_TOKEN2: 'TOKEN1 和 TOKEN2 餘額不足',
  please_add_funds_before_ordering: '在下單之前，請轉入資金至 DeGate 餘額',
  err_balance_content_spot: '由於餘額不足，無法下單',
  err_balance_content_grid: '由於餘額不足，無法建立網格策略',
  trade_min_volume_tips_XXX: '最小值 XXX',
  grid_min_volume_tips: '每筆訂單的數量不符合最低金額。請再試一次',
  trade_risk_orders_tips: '由於您有太多未完成訂單，無法下單',
  gas_token_tips: '選擇Gas Fee代幣',
  add_favorite_tooltip: '新增至收藏夾',
  remove_favorite_tooltip: '從收藏夾中移除',
  expire_tips_X: '此訂單將於X到期',
  today: '現在',
  now: '現在',
  time_D_day: 'D天',
  time_D_day_H_hour: 'D天 H小時',
  time_last_24_hrs: '最近24小時',
  time_last_hour: '最近1小時',
  time_H_hour_M_minute: 'H小時 M分鐘',
  time_M_minute_S_second: 'M分鐘 S秒',
  time_S_second: 'S秒',
  around: '~',
  time_now: '現在',
  time_before: '之前',
  time_before_ago: '之前',
  time_1_minute: '1分鐘',
  time_1_hour: '1小時',
  time_1_day: '1天',
  time_1_year: '1年',
  time_M_minutes: 'M分鐘',
  time_M_m: 'M分鐘',
  time_H_hours: 'H小時',
  time_H_h: 'H小時',
  time_D_days: 'D天',
  time_Y_years: 'Y年',
  time_Y_y: 'Y年',
  time_D_d: 'D天',
  time_M_mo: 'M月',
  fee_change_tips: '價格已更新',
  no_pairs: '未找到交易對',
  register_new_pair: '新增新交易對',
  register_pair: '新增交易對',
  add_pair: '新增交易對',
  tips_hide_forever: '不再顯示',
  Select_Token: '選擇幣種',
  token: '代幣',
  action: '操作',
  more_actions: '更多',
  gas_fee: 'Gas Fee',
  'orders.detail_gas': '實際Gas Fee',
  trade_fee: '手續費',
  about_degate: '關於DeGate',
  metrics: '指標',
  fees: '費用',
  document: '文件',
  join_us: '加入我們',
  feedback: '回饋',
  email_optional: '您的電子郵件地址(可選)',
  Upload: '上傳',
  feedback_upload_tip: '請分享您的回饋。拖動檔案以附加',
  feedback_upload_tip_mobile: '請分享您的回饋',
  image_upload_tip: '拖放圖片以上傳',
  feedback_success: '我們聽到您的聲音了',
  feedback_success_2: '謝謝您',
  feedback_failed: '送出失敗。請稍後再試',
  image_upload_rule_1: '僅支援PNG、JPG、JPEG',
  image_upload_rule_2: '每個檔案的最大限制為20MB',
  image_upload_rule_3: '最多5個',
  image_upload_rule_2_3: '每個檔案的最大限制為20MB，最多5個',
  no_pair: '未找到代幣對',
  no_token: '未找到代幣',
  choose_base_token: '選擇基準代幣',
  choose_quote_token: '選擇報價代幣',
  get_test_token: '取得測試網代幣',
  faucet: '水龍頭',
  expire_in: '過期時間',
  expire_in_empty_err: '請輸入數字',
  go_back: '返回',
  max_XXX: '最大值 XXX',
  min_XXX: '最小值 XXX',
  fill_in: '填寫',
  my_balance: '我的餘額',
  deGate_insufficient_fees: 'DeGate餘額不足以支付Gas Fee',
  wallet_balance: '錢包餘額',
  your_wallet_balance: '您的錢包餘額',
  degate_balance: 'DeGate餘額',
  wallet_insufficient_fees: '錢包餘額不足',
  wallet_insufficient_balance: '餘額不足',
  insuffficient_wallet_balance: '錢包餘額不足',
  degate_insufficient_balance: '可用餘額不足',
  open_discord: '前往Discord社群',
  err_valid_until: '請在您的裝置上將本機時間調整為標準時間',
  tips_gas: '用於執行此鏈上交易的Gas Fee將從您的 DeGate 餘額中扣除。',
  maker_free: '掛單免費',
  trading_fee_rate: '交易費率',
  Free: '免費',
  stop_service_1: '網站正在維護中',
  stop_service_2: '預計恢復時間',
  stop_upgrade: '測試網的新版本正在遷移',
  stop_trading_1: '系統升級',
  stop_trading_2: '交易暫停',
  sell: '賣',
  buy: '買',
  SELL: '賣',
  BUY: '買',
  Sell: '賣',
  Buy: '買',
  sell_order: '賣單',
  buy_order: '買單',
  edit: '編輯',
  status_processing: '處理中',
  status_processed: '待處理',
  status_pending: '等待中',
  status_confirming: '確認中',
  status_success: '成功',
  status_completed: '已完成',
  status_failed: '失敗',
  status_speeding_up: '加速中',
  status_canceling: '取消中',
  status_canceled: '已取消',
  in_progress: '進行中',
  limit_order: '限價',
  market_order: '市價',
  stop_limit_order: '限價止損',
  balance: '餘額',
  empty_connect: '請先連接錢包',
  empty_register: '請先初始化',
  empty_months3: '過去3個月無資料',
  show_months3: '僅顯示過去3個月內資料',
  view_all: '查看全部',
  H1: '1小時',
  D1: '1日',
  D5: '5日',
  M1: '1個月',
  M3: '3個月',
  M6: '6個月',
  YTD: '年初至今',
  Y1: '1年',
  all: '全部',
  paste: '貼上',
  clear: '清空',
  total: '總計',
  amount: '數量',
  order_amount: '訂單數量',
  price: '價格',
  order_total: '總計',
  filledAmount: '數量',
  tradeFilledTotal: '價值',
  orderFilledTotal: '總計',
  filledAmount_amount: '已成交/數量',
  profit: '利潤',
  incompatible_token: '此代幣的技術規格與 DeGate 協議不相容。',
  next: '下一步',
  token_not_verified: '未驗證',
  token_not_verified_tips:
    '合約地址、圖示和符號未經驗證。請檢查合約地址以避免假代幣詐騙。',
  token_verified: '已驗證',
  token_verified_tips: '合約地址、圖示和符號相符。',
  deposit_tips_region: '請注意，您正在 REGION 中使用 DeGate。',
  complete_time: '完成時間',
  unable_to_initialize: '無法初始化',
  filter_base: '基準',
  filter_quote: '報價',
  filter_type: '類型',
  filter_role: '角色',
  option_maker: '掛單',
  option_taker: '吃單',
  start_data: '開始日期',
  end_data: '結束日期',
  added_to_favorites: '已新增到收藏夾',
  removed_to_favorites: '從收藏夾中刪除',
  show_recents_50: '已顯示最新的 50 條資料。',
  terms_of_service: '服務條款',
  tips_small_unfilled:
    '根據系統設計中指定的精度，部分未成交的訂單已退回到您的DeGate餘額。',
  notification: '通知',
  server_message_SystemRecovery: '請注意，系統恢復後，您的訂單狀態已更改。',
  learn_more: '了解更多',
  connect_ledger: '連接 Ledger 冷錢包',
  ledger_disconnect:
    "在 'USB 裝置' 上執行 'transferOut' 失敗：裝置已中斷連接。",
  gas_fee_expired: 'Gas Fee已過期。請重新送出。',
  scroll_down_to_refresh: '向下捲動以重新整理',
  release_to_refresh_immediately: '釋放以重新整理',
  no_more: '沒有更多資料',
  loading: '正在載入...',
  force_withdrawing_token_tips: '正在處理您的強制提款要求，無法執行此操作。',
  speed_up: '加速',
  transaction_submitted: '交易已送出',
  tx_speed_up: '加速交易',
  tx_cancel: '取消交易',
  none: '無',
  Language: '語言',
  page: '/頁',
  go_to: '前往',
  icon_indicators: '指標',
  icon_back: '返回',
  icon_forward: '前進',
  icon_full_screen: '全螢幕',
  icon_exit_full_screen: '退出全螢幕',
  icon_buy_sell_orders: '買賣訂單',
  icon_buy_orders: '買單',
  icon_sell_orders: '賣單',
  icon_enable: '點選啟用',
  icon_disable: '點選停用',
  icon_copy: '複製地址',
  icon_view_explorer: '在區塊瀏覽器中查看',
  icon_display_by_profit: '按利潤顯示',
  icon_display_by_time: '按時間顯示',
  icon_switch: '切換',
  eth_code_tips: 'Ethereum的原生代幣。無代幣合約地址。',
  TBD: '待定',
  TVL: 'TVL',
  go_to_discord: '或加入 Discord 社群建立工單',
  release: '釋出：',
  security: '安全',
  colon: '：',
  zero_balance: '零餘額',
  ledger_app_version_tips:
    '請更新您的 Ledger 上的Ethereum應用至 v1.10.0 或更新版本，以預覽要簽署的訊息。',
  ledger_contract_data_tips: '請在Ethereum應用程式設定中啟用盲簽或合約資料。',
  input_auto_corrected_tooltips: '已超過最大位數，系統自動更正您的輸入。',
  maximum_decimal_reached: '已達到最大小數位數',
  verify_ownership: '驗證所有權',
  enable_trading: '啟用交易',
  learn_more_about_signatures_link: '了解更多關於簽名的資訊 >',
  learn_more_about_signatures: '了解更多關於簽名的資訊',
  sign: '簽名',
  sign_step1: '在您的錢包中完成',
  sign_step2: '完成第二次簽名',
  not_now: '不是現在',
  view_on_block_explorer: '在 Block Explorer 中查看',
  view_in_history: '在歷史紀錄中查看',
  continue_to_place_order: '繼續下單',
  Save: '保存',
  sign_to_view: '簽名以查看',
  available_degate_balance: '可用的DeGate餘額',
  Back: '返回',
  token_has_not_listed: '此代幣尚未在 DeGate 上架。',
  list_now: '立即上架',
  spread_15: '價差>15%',
  connected: '已連接',
  self_list_token: '即時上架',
  claim_REBASE: '領取REBASE',
  time: '時間',
  time_updated: '更新時間',
  show_in_X_m: '約 ~X 分鐘後顯示',
  max_gas: '最大Gas Fee',
  total_required: '總計所需',
  Required: '必需的',
  available_balance: '可用餘額',
  please_add_funds: '請將資金存入您的 DeGate 餘額。',
  Side: '方向',
  pending: '待處理',
  active: '進行中',
  ended: '已結束',
  name: '名稱',
  yield: '收益',
  time_created: '建立時間',
  time_ended: '結束時間',
  frequency: '頻率',
  chain_cancel: '在區塊鏈上取消',
  status: '狀態',
  status_chainCancelProgressing: '正在區塊鏈上取消',
  status_chainCancelCompleted: '已在區塊鏈上取消',
  filled_total: '已成交/總量',
  start_time: '開始時間',
  end_time: '結束時間',
  Summary: '總結',
  Orders: '訂單',
  Tutorial: '教學',
  top_winner_24h: '24小時冠軍',
  ID: '序號',
  Select: '選擇',
  Create: '建立',
  Review: '預覽',
  Airdrop: '空投',
  Airdrops: '空投',
  Countdown: '首發',
  Day: '天',
  Hour: '小時',
  Minute: '分鐘',
  Second: '秒',
  Days: '天',
  Hours: '小時',
  Minutes: '分鐘',
  Seconds: '秒',
  Claim: '領取',
  Expired: '已過期',
  Claimed: '已領取',
  Welcome: '歡迎',
  gas_tips_for_amount_exceed_6_digits: '由於金額超過六位數的限制，將會額外收費',
  input_auto_corrected_minStep_tips: '自動調整你的輸入到最低要求的精確度',
  order_max_limit: '超過最高限度',
  order_min_limit: '未達到最低限度',
  order_faild_min_limit: '下單失敗：未達到最低限度',
  order_faild_max_limit: '下單失敗：超過最高限度',
  disconnect_m: '中斷',
  'account.account_manage': '安全',
  'account.account_manage_more': '關於授權模式和資產金鑰 >',
  'account.what_is_asset_key': '關於授權模式和資產金鑰',
  'account.total_value': '總價值',
  'account.hide_small_balances': '隱藏小餘額代幣',
  'account.add_to_metamask': '將代幣添加至錢包',
  'account.assets_balance_total': '總計',
  available: '可用',
  'account.assets_market': '價值',
  'account.transfer_to_degate_balance': '添加到 DeGate 餘額',
  'account.search_tokens': '搜尋代幣',
  'account.deposit_title':
    '資產將存入您的去中心化 DeGate 帳戶。您擁有這些資產完全的控制權。',
  'account.deposit_tips': '您擁有這些資產完全的控制權。',
  'account.deposit_confirm_btn': '添加',
  'account.deposit_approved_btn': '已確認',
  'account.deposit_1_ETH': '添加 1 ETH 到您的 DeGate 餘額',
  'account.deposit_status_pending': '待處理',
  'account.deposit_status_pay_pending': '待付款',
  'account.deposit_status_pay_waiting': '付款交易等待中',
  'account.deposit_status_pay_confirming': '確認付款中',
  'account.deposit_tips_block': '等待交易區塊打包',
  'account.deposit_status_pay_btn': '支付',
  'account.pay_deposit_warning': '添加資金可能會產生額外的Gas Fee',
  'account.pay_deposit_warning_tips':
    '由於 DeGate 的補貼已用完，使用者可能需要承擔添加資金的成本。',
  'account.deposit_pending_tips':
    '如果等待時間超過 5 分鐘，請在您的錢包中加快交易速度。',
  'account.deposit_pending_tips_ledger':
    '如果等待時間超過 5 分鐘，請加快交易速度。',
  'account.deposit_contract_tips_over_AMOUNT':
    '對於超過 AMOUNT 美元的資金添加，僅支援進階方式的資金增加。',
  'account.deposit_contract_tips_only_all': '僅支援進階方式的資金添加',
  'account.suggest_100': '建議不小於 100 美元',
  'account.suggest_100_tips': '在訂單簿上列出的最低訂單價值為 100 美元。',
  'account.deposit_failed': '失敗',
  'account.deposit_failed_tips': '添加資金的鏈上交易失敗。',
  'account.payment_due': '應付費用',
  'account.payment_due_tips': '需要額外的費用才能將資金存入您的 DeGate 餘額。',
  'account.register_token_code_placeholder': '輸入合約地址',
  'account.register_token_code': '合約地址',
  'account.register_token_symbol': '符號',
  'account.register_token_check': '檢查上架進度',
  'account.register_token_code_err_added': '此代幣正在上架',
  'account.register_token_next_step': '下一步',
  'account.register_token_tips1':
    '無需權限即可進行區塊鏈代幣上架。請立即上架您的代幣。',
  'account.register_token_btn': '上架代幣',
  'account.list_token': '上架代幣',
  'account.withdraw_warning_XXX':
    '由於需求增加，目前發送資金需要大約 ~XXX 的時間。',
  'account.withdraw_status_pending': '處理中',
  'account.tansferred_1_ETH': '已轉移 1 ETH',
  'account.transfer_status_sent': '已發送',
  'account.transfer_status_received': '已收到',
  'account.th_me': '我',
  'account.th_tx_hash': '交易哈希',
  'account.th_time': '時間',
  'account.locked_order': '限價訂單',
  Sending: '正在發送',
  'account.locked_claimable': '可領取',
  'account.locked_grid': '網格策略',
  'account.personal_sign_reason': '可能的原因',
  'account.personal_sign_reason1': '1. MetaMask 已連接到硬體錢包',
  'account.personal_sign_reason2': '2. MetaMask 版本過時',
  'account.personal_sign_reason3': '3. 其他',
  'account.personal_sign_btn': '重新簽名',
  'account.deposit_arrive_in_30s': '約 30 秒內到達',
  'account.deposit_arrive_in_30s_s': '約 30 秒',
  'account.account_completed_time_XXX': '約在 XXX 內完成',
  'account.search_result_no_token': '找不到代幣',
  'account.search_result_invalid_code': '無效的合約地址',
  'account.search_result_not_listed': '代幣目前未上架在 DeGate',
  'account.search_result_tips_register': '您可以輸入合約地址以完成代幣上架',
  'account.search_result_not_find': '仍然找不到？',
  'account.search_pair_tips3': '該資產沒有交易對',
  'account.search_pair_tips3_add': '請新增交易對',
  'account.register_token': '無需許可的上架代幣',
  'account.search_again': '重新搜索',
  'account.deposit_type': '方法',
  'account.deposit_type_standard': '標準',
  'account.switch_account_tips': '切換至',
  'account.switch_account_tips_register': '請先初始化',
  'account.initialize_success': '初始化成功',
  'account.approve': '確認',
  'account.reset_USDT': '重設 USDT 確認',
  'account.reset_USDT_tips': '當支出限額太低時，USDT 需要重設確認。',
  'account.next_step': '下一步',
  'account.profit_total': '總盈利',
  'account.profit_history': '盈利歷史',
  'account.tab_mining_rewards': '挖礦獎勵',
  'account.yield_total': '總收益',
  'account.yield_24h': '24小時收益',
  claimable: '可領取',
  'account.yield_history': '收益歷史',
  'account.total_grid_profit': '總網格利潤',
  'account.grid_strategies': '網格策略',
  'account.total_rewards': '總獎勵',
  'account.rewards_24h': '24小時獎勵',
  'account.rewards': '獎勵',
  'menu.register_err':
    '您的地址沒有任何鏈上交易記錄。請完成任意一筆鏈上交易後重試。例如轉帳代幣到該地址。',
  'menu.reset_post_success_withOrders':
    '已啟動資產金鑰重設。您所有的未完成訂單和網格策略已被取消。',
  'menu.reset_post_success': '已啟動資產金鑰重設。',
  'menu.reset_processing_title': '正在進行資產金鑰重設',
  'menu.reset_processing_desc': '請等待完成',
  'trade.choose_token': '選擇代幣',
  'trade.token_info': '代幣資訊',
  'trade.token_address': '代幣地址',
  'trade.price_range_24h': '24小時價格範圍',
  'trade.vol_24h': '24小時成交量',
  'trade.item_price_TOKEN': '價格 (TOKEN)',
  'trade.item_amount_TOKEN': '數量 (TOKEN)',
  'trade.order_book_title': '訂單簿',
  'trade.order_book_total': '總計',
  latest_trades: '最新交易',
  'trade.trade_history_time': '時間',
  'trade.market_placeholder_price': '市場價格',
  'trade.what_is_stop_limit': '什麼是止損限價',
  'trade.what_is_stop_limit_link': '什麼是止損限價 >',
  'trade.placeholder_total': '總計',
  'trade.more_settings': '設置',
  'trade.expire_in_tips': '該訂單將在到期後自動取消。',
  'trade.period_day_s': '天',
  'trade.period_hour_s': '小時',
  'trade.period_minute_s': '分鐘',
  'trade.period_err_input_tips': '請輸入有效數字',
  'trade.post_only_label': '僅限掛單',
  'trade.post_only_tips':
    '僅限掛單模式確保僅掛單訂單進入訂單簿。如果訂單的任何部分可以作為吃單訂單成交，那麼整個訂單將被退回。掛單模式的訂單不會產生任何Gas Fee或交易費用。',
  'trade.post_only_fail_title': '無法建立訂單',
  'trade.post_only_fail_desc': '請調整價格或停用"僅限掛單模式"。',
  'trade.max_gas_fee_tips':
    '最大Gas Fee涵蓋了交易結算的鏈上成本，由吃單方支付並且掛單方免費。超出的費用將被退還。',
  'trade.auto': '自動',
  'trade.custom': '自訂',
  'trade.enough_for_XX_trades': '足夠進行 XX 筆交易',
  'trade.gas_fee_per_trade': '每筆交易的Gas Fee',
  'trade.gas_fee_per_trade_tips':
    '吃單方需支付每筆交易的Gas Fee用，以促進鏈上結算，費用根據Ethereum網路條件波動而變化。',
  'trade.max_number_of_trades': '最大交易次數',
  'trade.btn_buy_ETH': '購買 ETH',
  'trade.btn_sell_ETH': '出售 ETH',
  'trade.max_buy_fee_deducted_NUM': '已扣除Gas Fee。最大為 NUM。',
  'trade.notification_limit_order_title': '已下單限價單',
  'trade.notification_stop_limit_order_title': '已下單止損限價單',
  'trade.err_price': '請輸入價格',
  'trade.err_amount_total': '請輸入數量或總數',
  'trade.err_amount': '請輸入數量',
  insufficientFee_gas_fee: 'Gas Fee不足',
  'trade.err_insufficientFee_desc':
    '請檢查您的最大Gas Fee設置和您的 DeGate 餘額。',
  'trade.cancel_order_success': '訂單已取消',
  'trade.pair_favorite': '收藏',
  'trade.pair_search': '搜尋代幣，合約地址',
  'trade.pair_last_price': '價格',
  'trade.pair_change': '變動',
  'trade.url_parse_err_title': '該交易對不存在。',
  'trade.risk_tips': '風險警告',
  'trade.base_is_not_default_token_tips':
    '在交易之前，請通過官方來源驗證代幣合約地址，以避免詐騙代幣。',
  'trade.chain_cancel': '在鏈上取消訂單',
  'trade.chain_cancel_no_need_tips': '此訂單無需在鏈上取消。',
  'trade.chain_cancel_success': '已發送要求',
  'trade.depth_empty': '暫時無訂單',
  'trade.depth_empty_asks': '無任何賣單',
  'trade.depth_empty_bids': '無任何買單',
  'trade.depth_empty_tips': '市價訂單因訂單簿中的開放訂單不足而失敗',
  'trade.history_empty': '尚無交易',
  'trade.err_price_stable': '價格無效。請重試。',
  'trade.price_warning': '您輸入的價格與市場價格不符，請在下單前確認。',
  'trade.order_value_tips':
    '最小訂單價值為 <b>QUOTE_A</b> 或 <b>BASE_A</b>，相當於 MINUSD 美元。使用市價訂單可繞過此限制。',
  'trade.order_value_tips_quote':
    '最小訂單價值為 <b>QUOTE_A</b>，相當於 MINUSD 美元。使用市價訂單可繞過此限制。',
  'trade.order_value_tips_stable_quote':
    '最小訂單價值為 <b>QUOTE_A</b>。使用市價訂單可繞過此限制。',
  'trade.system_limit': '已超過系統限額',
  'trade.stop_limit_untriggered_tips':
    '訂單尚未送出到訂單簿，因為未達到停止價格。',
  'trade.stop_limit_triggered_tips_TIME': '訂單已在 TIME 送出到訂單簿',
  'trade.flow_of_funds': '資金流向',
  'trade.flow_of_funds_tip2':
    '您已下單成功。訂單資金將進入您的 DeGate 餘額，而不是您的錢包餘額。',
  'orders.show_current_pair_orders': '隱藏其他交易對',
  'orders.orderHistory': '訂單歷史紀錄',
  'orders.th_time': '時間',
  'orders.th_average_price': '平均價格',
  'orders.th_stop_price': '停止價格',
  'orders.th_limit_price': '限價',
  'orders.th_filled_price': '價格',
  'orders.th_filled_amount': '已成交',
  'orders.th_filled_total': '總計',
  'orders.th_trade_reconciliation': '對帳',
  'orders.th_trade_reconciliation_tips':
    '請注意，由於 DeGate 上的撮合和鏈上結算所採用的計算模型不同，因此兩者的計算結果可能存在細微差異。 如果發生這種情況，系統將以鏈上價格為準，並補上 DeGate 餘額的差額。',
  'orders.hide_cancelled_expired_orders': '隱藏已取消/已過期',
  'orders.status_open': '開放',
  'orders.status_pending': '待處理',
  'orders.status_completed': '已成交',
  'orders.status_completed_part': '部分成交',
  'orders.status_expired': '已過期',
  'orders.detail_price': '平均/價格',
  'orders.average_price': '平均價格',
  'orders.detail_type': '訂單類型',
  'orders.detail_trade_fee': '手續費：',
  'orders.gas_preAuth': '最大Gas Fee：',
  'orders.fee_reconciliation': '對帳：',
  'orders.gas_paid': '已支付Gas Fee：',
  'orders.gas': 'Gas Fee：',
  'orders.trades_N': '交易次數（N）',
  'orders.detail_filled_total': '總計',
  'orders.detail_filled_detail': '交易詳情',
  'orders.detail_filled_time': '時間',
  'orders.order_maker_free': '掛單費用免費',
  'orders.openOrders_empty': '無未完成訂單',
  'orders.export_orders_1_year': '匯出最近一年的訂單資料',
  'orders.export_trades_1_year': '匯出最近一年的交易資料',
  'orders.export_data': '匯出資料',
  'orders.export': '匯出',
  'orders.export_processing': '處理中，請稍候。',
  'orders.export_tips_100_percent': '進度達到 100％ 後，檔案將自動下載',
  'orders.sign_to_view_balance': '請登錄以查看餘額',
  'orders.sign_to_view_history': '請登錄以查看歷史記錄',
  'orders.sign_to_view_security_options': '請登錄以查看安全選項',
  'gridTrade.automatic_strategy': '自動',
  'gridTrade.manual_strategy': '手動',
  'gridTrade.placeholder_amount': '輸入金額',
  'gridTrade.low_price': '下限',
  'gridTrade.high_price': '上限',
  'gridTrade.initial_investment': '初始分配',
  'gridTrade.grid_levels_tips': '用於確定價格範圍內訂單的數量',
  'gridTrade.profit_per_grid': '每格利潤',
  'gridTrade.profit_per_grid_tips':
    '網格策略盈利能力的重要參數。 每格利潤 =（較高價格 - 較低價格）/ 較低價格。 較高價格和較低價格指的是網格策略中兩個相鄰網格線的價格。',
  'gridTrade.min_grid_volume_XXX_ETH': '每格網格的金額：最小為 XXX ETH',
  'gridTrade.min_grid_volume_err': '請增加投資額度或減少網格數',
  'gridTrade.grid_no_depth_tips_BASE_QUOTE':
    '由於訂單簿中訂單不足，因此無法為此交易對建立網格策略。',
  'gridTrade.grid_to_spot_trade': '前往現貨交易',
  'gridTrade.grid_level_over_err': '請減少網格數量',
  'gridTrade.grid_prices_err': '請擴大價格範圍',
  'gridTrade.grid_create_err': '請調整參數，然後重試。 ',
  'gridTrade.tips_grid_profit': '利潤將直接轉入您的 DeGate 餘額，並立即可用。 ',
  'gridTrade.tips_grid_balance_0_BASE':
    '市場價格上升導致此網格策略下的所有訂單均變為買單。因此現在基礎資產的餘額為 0。',
  'gridTrade.tips_grid_balance_0_BASE_2':
    '市場價格上升導致此網格策略下的所有訂單均變為買單，且其中一些訂單部分成交。因此現在基礎資產的餘額為 >0。',
  'gridTrade.tips_grid_balance_0_QUOTE':
    '市場價格下跌導致此網格策略下的所有訂單均變為賣單。 因此現在報價資產的餘額為 0。',
  'gridTrade.tips_grid_balance_0_QUOTE_2':
    '市場價格下跌導致此網格策略下的所有訂單均變為賣單，且其中一些訂單部分成交。因此現在報價資產的餘額為 >0。',
  'gridTrade.grid_param_err': '請輸入網格策略的參數',
  'gridTrade.tv_buy': '購買',
  'gridTrade.tv_sell': '出售',
  'gridTrade.tv_waiting': '等待中',
  'gridTrade.chain_cancel_no_need_tips': '此網格策略無需上鏈取消。',
  'gridTrade.grid_over_max_number_err':
    '已達到執行中網格策略的最大數量，無法建立新網格策略。',
  'gridTrade.preview_orders_in_graph': '顯示訂單',
  'gridTrade.greate_news': '好消息：',
  'gridTrade.min_amount_required_XXX': '最低需要 XXX',
  'gridTrade.highest_grid_apy': '最高網格年化利率',
  'gridTrade.for_the_last_7_days': '過去 7 天',
  'gridTrade.min_investment': '最低投資',
  'gridTrade.grid_need_XXX': '網格需 $XXX',
  'gridTrade.mining_need_XXX': '挖礦需 $XXX',
  'gridTrade.recommended_params_cannot_be_applied':
    '由於投資不足，無法應用推薦參數。您可以在手動模式下調整',
  'gridTrade.copy_params_to_manual': '複製參數到手動模式',
  'gridOrders.grid_recents': '我的最新交易',
  'gridOrders.th_created_time': '建立時間',
  'gridOrders.grid_profit': '網格利潤',
  'gridOrders.grid_cancel': '結束',
  open_orders: '未完成訂單',
  'gridOrders.tab_history_orders': '已成交訂單',
  'gridOrders.tab_trade_history': '交易歷史',
  'gridOrders.detail_current_balance': '目前餘額',
  'gridOrders.detail_ending_balance': '結束餘額',
  'gridOrders.detail_ending_balance_tips': '網格策略關閉時的資產餘額。',
  'gridOrders.detail_in_order_funds': '訂單資金：',
  'gridOrders.detail_on_hold_funds': '圈存資金（來自部分成交訂單）：',
  'gridOrders.detail_transactions': '已成交訂單數量',
  'gridOrders.detail_investment': '初始分配',
  'gridOrders.detail_running_time': '持續時間',
  'gridOrders.detail_prices': '價格區間',
  number_of_grids: '網格數量',
  'gridOrders.detail_expire_time': '到期時間',
  'gridOrders.detail_expire_time_tooltip': '此網格策略中的訂單將在到期時取消。',
  'gridOrders.detail_valid_period': '到期設定',
  'gridOrders.open_orders_sell': '賣出',
  'gridOrders.open_orders_buy': '買入',
  'gridOrders.open_orders_index': '#',
  'gridOrders.open_orders_total': '總計',
  'gridOrders.history_orders_filled': '已成交：',
  'gridOrders.history_orders_price': '價格：',
  'gridOrders.history_orders_time': '時間',
  'gridOrders.history_orders_filled_price': '平均價格',
  'gridOrders.history_orders_filled_amount': '已成交',
  'gridOrders.history_orders_filled_total': '總計',
  'gridOrders.history_orders_profit_tips':
    '利潤來自於低買高賣的一輪交易週期後的價格差異。 例如，在以4000 USDC的價格成交了購買1 ETH的網格訂單後，如果網格區間為50 USDC，則系統將自動以4050 USDC的價格下達一個新訂單，以出售1 ETH。 當該訂單被成交時，將獲得50 USDC的利潤。',
  'gridOrders.history_orders_buy_flip_order_tips_PRICE':
    '以PRICE價格完成買單後，利潤將會顯示。',
  'gridOrders.history_orders_sell_flip_order_tips_PRICE':
    '以PRICE價格完成賣單後，利潤將會顯示。',
  'gridOrders.m_history_orders_flip_order_tips_PRICE':
    '當以PRICE價格的訂單被成交時，訂單將出現在此。',
  'gridOrders.grid_cancel_title': '關閉網格策略',
  'gridOrders.grid_cancel_content': '此網格策略中的所有訂單將立即取消。',
  'gridOrders.grid_cancel_content2':
    '您正在使用此網格策略進行挖礦。 取消網格策略將放棄挖礦獎勵，並立即取消網格下的所有訂單。',
  'gridOrders.copy_grid_title': '以下網格策略參數將被複製',
  'gridOrders.copy_grid_btn': '複製到面板',
  'gridOrders.copy_grid_success': '網格策略已複製',
  'gridOrders.grid_init_funds_XXX': '初始設定金額：$XXX',
  'gridOrders.grid_init_funds_tips':
    '年化利率基於網格策略建立時的初始設定金額計算。',
  'gridOrders.tab_m_trade': '交易',
  grid_apy: '網格年化收益率',
  grid_apy_tips: '僅限網格交易的年化收益率，不包括浮動利潤。',
  'gridOrders.tab_mining_profit': '挖礦年化利率',
  'gridOrders.tab_mining_profit_tips':
    '基於網格策略建立時設定的初始金額及其持續時間的年化利率。',
  'gridOrders.mining_rewards': '獎勵：',
  'gridOrders.open_orders_empty_tips': '請等待資料載入完成',
  'gridOrders.market_value': '市值：',
  'gridOrders.market_value_details': '詳情',
  'gridOrders.fund_details': '資金詳情',
  'gridOrders.m_in_order_funds': '訂單資金',
  'gridOrders.m_in_order_funds_tips': '此網格策略下所有未完成訂單的總資金。',
  'gridOrders.m_on_hold_funds': '圈存資金',
  'gridOrders.m_on_hold_funds_tips': '部分成交訂單結果。',
  'gridOrders.initial_value': '初始設定金額',
  'mining.my_title': '已參與流動池',
  'mining.index_desc': '建立網格策略。 透過網格交易和挖礦獲得收益。',
  'mining.apply': '新池申請',
  'mining.claimable_rewards_box': '可領取的獎勵',
  'mining.rewards_more': '以及更多',
  'mining.tab_pools': '挖礦池',
  'mining.tab_my': '我的獎勵統計',
  'mining.pools_tab_live': '上線',
  'mining.pools_tab_upcoming': '即將上線',
  'mining.pools_funds': '流動池資金',
  'mining.pools_funds_tips': '符合最低訂單金額120美元的網格訂單的總價值',
  'mining.pools_mining_funds': '挖礦資金',
  'mining.mining_apr': '流動池年化利率',
  'mining.mining_apr_tips': '根據每日獎勵和流動池資金計算的預估年化利率。',
  'mining.view_rule_link': '挖礦規則',
  'mining.pools_info_to_confirm': '待確定',
  'mining.pools_no_wait': '無可用的挖礦池',
  'mining.my_mining_funds': '我的挖礦資金',
  'mining.my_mining_rewards': '我的挖礦獎勵',
  'mining.my_th_profit_token_price': '最新價格',
  'mining.my_th_total_rewards': '歷史累積獎勵',
  'mining.my_th_24h_rewards': '24小時獎勵',
  'mining.my_grids': '我的挖礦',
  'mining.only_show_mining_grids': '僅顯示挖礦中',
  'mining.my_th_mining_status': '挖礦狀態',
  'mining.status_framing': '挖礦中',
  'mining.status_over_price': '超出價格範圍',
  'mining.status_mining_over': '挖礦已結束',
  'mining.status_grid_closed': '策略已取消',
  'mining.status_grid_expired': '策略已過期',
  'mining.empty_no_faring_grids': '沒有可挖掘的網格策略。',
  'mining.go_mining_pool': '前往挖礦池',
  'mining.go_mining': '開始挖礦',
  'mining.go_to_grid': '至網格策略',
  'mining.mining_help': '挖礦指南',
  'mining.mining_available': '符合條件',
  'mining.mining_available_tips': '訂單價值標準已滿足',
  'mining.mining_unavailable': '不符合條件',
  'mining.mining_partially_available': '部分符合條件',
  'mining.mining_unavailable_tips': '訂單價值標準未滿足',
  'mining.mining_preview': '挖礦預覽',
  'mining.mining_total_profit': '挖礦獎勵',
  'mining.mining_24h_profit': '24小時挖礦獎勵',
  'mining.profit_unable_display': 'N/A',
  'mining.mining_funds': '挖礦資金',
  'mining.mining_funds_tips':
    '此交易對的所有已符合挖礦訂單價值標準的網格策略的訂單總價值。',
  'mining.tab_mining_profit_details': '獎勵詳情',
  'mining.tab_mining_orders': '挖礦訂單',
  'mining.th_rewards': '獎勵',
  'mining.th_rewards_origin': '獎勵來源',
  'mining.th_rewards_origin_tips':
    '如果網格訂單價格落在訂單簿獎勵價格範圍內（最高買價 * 0.99 ~ 最低賣價 * 1.01），則會獲得挖礦獎勵。',
  'mining.th_rewards_origin_tips_stable':
    '如果網格訂單價格落在訂單簿獎勵價格範圍內（最高買價 ~ 最低賣價），則會獲得挖礦獎勵。',
  'mining.th_time': '時間',
  'mining.plan_title': 'ETH/USDC 池子詳情',
  'mining.phase_cur': '目前階段',
  'mining.phase_range_N_XX': '第 N 階段：XX',
  'mining.phase_index_N': '第 N 階段',
  'mining.phase_reward': '每日獎勵',
  'mining.phase_to_release': '待公佈',
  'mining.my_rewards': '我的獎勵',
  'mining.claimable_rewards': '可領取',
  'mining.locked_rewards': '鎖定',
  'mining.locker_rewards_tips': '此獎勵金額將在網格策略執行 12 小時後可領取。',
  'mining.claimed_success': '領取成功',
  'mining.claimed_tips': '獎勵將存入您的 DeGate 餘額中。',
  'mining.claimed_view_btn': '去查看',
  'mining.mining_plan': '挖礦計劃',
  'mining.phase_unpublished': '待公佈',
  'mining.all_pools': '所有池子',
  'notification.limit_desc_SELL_BASE_QUOTE_AMOUNT_PRICE':
    '以 PRICE QUOTE 賣出 AMOUNT BASE',
  'notification.limit_desc_BUY_BASE_QUOTE_AMOUNT_PRICE':
    '以 PRICE QUOTE 買進 AMOUNT BASE',
  'notification.stop_limit_desc_SELL_BASE_AMOUNT':
    '以 PRICE QUOTE 賣出 AMOUNT BASE',
  'notification.stop_limit_desc_BUY_BASE_AMOUNT':
    '以 PRICE QUOTE 買進 AMOUNT BASE',
  'notification.cancel_grid_desc_PAIR_PRICES': 'PAIR：PRICES',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_AMOUNT':
    '以 QUOTE 買入 AMOUNT BASE',
  'notification.cancel_market_desc_SELL_BASE_QUOTE_TOTAL':
    '以 TOTAL QUOTE 賣出 BASE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_AMOUNT':
    '以 QUOTE 買入 AMOUNT BASE',
  'notification.cancel_market_desc_BUY_BASE_QUOTE_TOTAL':
    '以 TOTAL QUOTE 賣出 BASE',
  'notification.cancel_limit': '限價訂單已取消',
  'notification.cancel_stop_limit': '停損限價訂單已取消',
  'notification.cancel_market': '市價訂單已取消',
  'notification.cancel_grid': '網格策略已結束',
  'notification.cancel_limit_expired': '限價訂單已過期',
  'notification.cancel_stop_limit_expired': '停損限價單已過期',
  'notification.cancel_grid_expired': '網格策略已過期',
  'notification.cancel_limit_order_for_gas_desc':
    '您的訂單已經用完Gas Fee。 部分訂單成交，其餘訂單已被取消。',
  'notification.cancel_limit_order_for_gas_filled_amount': '已成交',
  'notification.cancel_limit_order_for_gas_amount': '數量',
  'notification.view_history_orders': '查看訂單歷史',
  'notification.cancel_market_for_depth_title': '訂單部分成交並取消',
  'notification.price_slippage_protection': '價格滑點保護',
  'notification.price_slippage_protection_desc':
    'DeGate 市價訂單自動包含 10% 的價格滑點保護，以限制在高波動性和低流動性期間的損失。 請使用限價訂單繞過此保護。',
  'notification.cancel_market_for_depth_warning':
    'DeGate 市價訂單引入了價格保護機制，使使用者能夠在市場情況具有高價格波動性和低流動性時減少損失。 如果您不想觸發價格保護機制，請使用限價訂單模式。',
  'notification.dca_plan_ended': '定投計劃已結束',
  'notification.cancel_dca_desc_PAIR': 'PAIR',
  'notification.trade_limit_partially': '限價訂單部分成交',
  'notification.trade_limit_filled': '限價訂單已成交',
  'notification.trade_market_partially': '市價訂單部分成交',
  'notification.trade_market_filled': '市價訂單已成交',
  'notification.trade_stop_limit_partially': '停損限價訂單部分成交',
  'notification.trade_stop_limit_filled': '停損限價訂單已成交',
  'notification.mobile_trade_filled_AMOUNT_TOKEN':
    '訂單已成交。 收到 AMOUNT TOKEN。',
  'notification.mobile_trade_partially_AMOUNT_TOKEN':
    '訂單部分成交。 收到 AMOUNT TOKEN。',
  'info.overview': '總覽',
  'info.accounts': '總使用者數',
  'info.pairs': '交易對',
  'info.turnover': '歷史交易量',
  'info.turnover_24': '24小時交易量',
  'info.dg_supply': 'DG流通供應量',
  'info.top_movers_no_increased': '24小時內沒有價格上漲的代幣。',
  'info.top_movers_no_decreased': '24小時內沒有價格下跌的代幣。',
  'info.top_pairs': '熱門交易對',
  Pair: '交易對',
  'info.th_change': '24小時變動',
  'info.th_l_up_2': '+2% 深度',
  'info.th_l_down_2': '-2% 深度',
  'info.th_turnover_24': '24小時成交量',
  'info.tvl': 'TVL',
  'm.home': '首頁',
  'm.grid': '網格',
  'm.browser_wallet': '瀏覽器錢包',
  'm.choose_pair': '選擇交易對',
  'm.orderBook_default': '預設',
  'm.orderBook_bids': '買單',
  'm.orderBook_asks': '賣單',
  'm.decimals': '小數點',
  'm.lowest_price_24h': '24小時最低價',
  'm.highest_price_24h': '24小時最低價',
  'm.vol_24h': '24小時成交量',
  'm.orderbook_buy': '買入',
  'm.orderbook_sell': '賣出',
  'm.go_to_trade': '前往交易',
  'm.choose_token': '選擇代幣',
  'm.from_address': '發送地址',
  'm.to_address': '接收地址',
  'm.transfer_send': '發送',
  'm.transfer_receive': '接收',
  'm.my_grid': '我的網格策略',
  'm.grid_profit_24': '24小時利潤',
  trades_24h: '24小時交易',
  'm.grid_profit_total': '總利潤',
  'm.grid_over_prices': '超出價格範圍',
  'm.create_grid': '建立網格策略',
  'm.grid_history': '歷史記錄',
  'm.grid_empty': '沒有有效的的網格策略',
  'm.grid_tutorial': '網格教學',
  'm.grid_params_to_manual': '將參數複製到手動模式',
  'm.balance_err': '餘額不足。 可用餘額：',
  'm.preview_grid': '預覽訂單',
  last_price: '最新價格',
  'm.grid_desc':
    '網格交易是一種交易策略，它在定義的價格範圍內自動進行買入和賣出。',
  'm.view_tutorial': '查看教學',
  'm.grid_profit_tips_sell': '當此賣單完全成交時將進行計算。',
  'm.grid_profit_tips_buy': '當此買單完全成交時將進行計算。',
  'm.hot': '熱門',
  'm.all': '看全部',
  'm.vol_24': '24小時成交量',
  'm.transfer_t1': '內部',
  'm.transfer_t2': '轉帳',
  'activity.th_date': '時間',
  'activity.th_type': '類型',
  'activity.th_fee': '費用',
  'activity.th_content': '內容',
  'activity.type_register_token': '代幣上市',
  'activity.type_register_pair': '新增交易對',
  'activity.type_pay_deposit': '存款結算',
  'activity.type_reset_account': '重設資產金鑰',
  on_chain_order_cancellation: '鏈上訂單取消',
  'activity.count_N': '計數：N',
  'activity.order_desc_SELL_AMOUNT_BASE_PRICE_QUOTE':
    '以 PRICE QUOTE 價格賣出 AMOUNT BASE',
  'activity.order_market_desc_SELL_AMOUNT_BASE': '賣出 AMOUNT BASE',
  'activity.reset_status_restting': '重設中',
  'activity.to_trade': '交易',
  'dca.dca_plan': '定投計劃',
  'dca.dca_explain': '定投均價',
  'dca.daily': '每日',
  'dca.weekly': '每週',
  'dca.custom': '自訂',
  'dca.every': '每',
  'dca.amount_per_order': '每筆金額',
  'dca.price_limit': '價格限制',
  'dca.maximum_price': '最高價格',
  'dca.minimum_price': '最低價格',
  'dca.number_of_orders': '訂單數量',
  'dca.create_dca_plan': '建立定投計劃',
  'dca.max_gas_fee_per_order': '每筆最大Gas Fee',
  'dca.maximum_plan_order_limit_reached': '已達到計劃訂單的最大數量。',
  'dca.end_time_should_be_set_after_the_current_time':
    '結束時間應設定在目前時間之後',
  'dca.please_enter_amount_per_order': '請輸入每筆金額',
  'dca.please_enter_maximum_price': '請輸入最高價格',
  'dca.please_enter_minimum_price': '請輸入最低價格',
  'dca.order_placement_failed_open_order_limit_exceeded':
    '下單失敗：超出開放訂單限制。',
  'dca.total': '總計',
  'dca.filled': '已成交',
  'dca.received': '已接收',
  'dca.time_to_end': '剩餘時間',
  'dca.cancel_on_chain': '取消鏈上',
  'dca.filled_amount': '已成交/金額',
  'dca.status_executed': '已執行',
  'dca.status_scheduled': '已計劃',
  'dca.status_failed': '失敗',
  'dca.order_cancled_by_user': '因使用者終止了定投計劃，訂單已取消。',
  'dca.order_cancled_by_access': '因您對 DeGate 的存取受限，訂單已取消。',
  'dca.order_cancled_by_gas': '因Gas Fee不足，下單失敗。',
  'dca.order_cancled_by_order_book': '因訂單簿中沒有符合的訂單，下單失敗。',
  'dca.order_cancled_by_balance': '因 DeGate 餘額不足，下單失敗。',
  'dca.order_cancled_by_min_value': '因未達100美元的最低訂單價值，下單失敗。',
  'dca.order_cancled_by_system_error': '因系統錯誤，下單失敗。',
  'dca.chain_cancel_no_need_tips': '此定投計畫不需要鏈上取消。',
  'dca.end_dca_plan': '結束定投計劃',
  'dca.all_orders_in_this_dca_plan_will_be_canceled_immediately':
    '此定投計畫中的所有訂單將立即取消。',
  'dca.no_active_dca_plan': '沒有有效的的定投計劃',
  'dca.time_scheduled': '計劃時間',
  'campaign.event_period': '活動週期：',
  'campaign.grid2401_time':
    '2024年1月22日，20:00:00 - 2024年1月29日，20:00:00 (UTC+8)',
  'campaign.event_has_ended': '活動已結束。',
  'campaign.current_apy': '目前年化利率',
  'campaign.grid_strategy_income': '網格策略收益 + 獎金池份額',
  'campaign.tvl_participating': '參與的總鎖倉價值',
  'campaign.share_of_tvl': '總鎖倉價值份額',
  'campaign.my_profit': '我的利潤',
  'campaign.grid_strategy_profit': '網格策略利潤',
  'campaign.share_of_prize_pool': '獎金池份額',
  'campaign.grid_strategy_profit_has_been_added_to_your_available_balance':
    '網格策略利潤已新增到您的可用餘額中。',
  'campaign.shared_income_from_usdc_prize_pool': '來自USDC獎池的共享收入',
  'campaign.is_black_tips': '您不符合獎金池分享資格。',
  'campaign.calculating': '計算中',
  'campaign.claim_after_end': '獎勵可於活動結束時領取',
  'campaign.how_to_participate': '如何參與',
  'campaign.rule': '建立網格策略並按比例分享獎金池。',
  'campaign.step1': '第1步',
  'campaign.step2': '第2步',
  'campaign.step3': '第3步',
  'campaign.grid2401_step1': '透過添加資金或交易準備好您的ETH和USDC',
  'campaign.grid2401_step2_PAIR': '為PAIR設定以下網格策略',
  'campaign.grid2401_step2_desc1_pre': '價格範圍：待公佈',
  'campaign.grid2401_step2_desc2_pre': '網格數量：待公佈',
  'campaign.copy_strategy': '複製策略',
  'campaign.grid2401_step3':
    '活動結束後，您可以在此活動頁面上領取您的收益。 請在活動結束後的30天內進行領取。',
  'campaign.what_is_grid': '什麼是網格策略',
  'campaign.notes': '加入前請注意',
  'campaign.notes_1_title': '資格：',
  'campaign.notes_1_desc':
    '只有當價格範圍和網格數量與建立時完全相同才符合網格策略的資格。',
  'campaign.notes_2_title': '限制：',
  'campaign.notes_3_title': '領取：',
  'campaign.notes_3_desc':
    '獎勵領取將在活動結束時可用，並在活動結束後的30天內有效。',
  'campaign.faq': '常見問題',
  'campaign.grid2401_faq_1': '1. 獎勵如何計算？',
  'campaign.grid2401_faq_2': '2. 如何取得此活動的支援？',
  'campaign.grid2401_faq_3': '3. 我持有USDT，如何取得ETH和USDC？',
  'campaign.grid2401_faq_4': '4. 透過網格策略完成的交易是否需要支付費用？',
  'campaign.grid2401_faq_4_res':
    '在DeGate中，所有掛單都是免費的。由網格策略產生的訂單都是掛單，因此在DeGate中設定網格策略是完全免費的。',
  'campaign.grid2401_faq_5': '5. 活動結束後，我的網格策略是否仍會產生效益？',
  'campaign.grid2401_faq_5_res':
    '是的，活動結束後，只要價格仍在您的網格策略範圍內，該策略就會繼續產生收益。活動結束後，您還可以調整網格策略的參數，以建立更適合自己偏好的策略 ，並繼續獲得收益。',
  'campaign.grid2401_faq_others': '其他活動細節',
  'campaign.grid2401_faq_others_1':
    '1. 每個使用者只能使用一個錢包。如果偵測到惡意的獎勵取得行為，DeGate將保留取消參與者獎勵的權利。',
  'campaign.grid2401_faq_others_2':
    '2. 在活動期間，超出範圍的網格也將計入權重計算。',
  'campaign.grid2401_faq_others_3':
    '3. 在極端情況下，例如市場波動，DeGate保留提前結束活動的權利。',
  'campaign.grid2401_faq_others_4': '4. 活動結束後未領取的獎勵將取消。',
  'campaign.invest_max_5000': '最高投資額為 5000 美元',
  'campaign.invest_mininum': '最低投資額',
  'airdrop.create_airdrop': '建立空投',
  'airdrop.important_note': '重要提醒：任何人都可以無需審核建立空投',
  'airdrop.my_airdrop': '我的空投',
  'airdrop.time_limited': '限時',
  'airdrop.no_airdrop': '目前沒有可領取的空投',
  'airdrop.claim_airdrop': '領取空投',
  'airdrop.recipients_number': '地址總數',
  'airdrop.total_amount': '總金額',
  'airdrop.retrieve': '取回',
  Unclaimed: '未領取',
  'airdrop.retrieve_successful': '取回成功',
  'airdrop.claim_successful': '領取成功',
  'airdrop.retrieve_unclaimed_airdrop': '取回未領取空投',
  'airdrop.airdrop_token': '空投幣種',
  'airdrop.token_not_meet_criteria': '幣種不符合空投的要求',
  'airdrop.airdrop_list': '空投列表',
  'airdrop.download_template': '下載模板',
  'airdrop.click_or_drag_upload_list': '點選或拖曳上傳列表',
  'airdrop.validation_passed': '已驗證',
  'airdrop.must_earlier_than_end_time': '必須早於結束時間',
  'airdrop.cannot_more_than_2_years_from_now': '從現在起最多2年',
  'airdrop.cannot_parse_file': '無法解析檔案，請使用列表模板。',
  'airdrop.format_requirement_not_met': '不符合格式要求',
  'airdrop.view_error_repost': '查看錯誤報告',
  'airdrop.error_report': '錯誤報告',
  'airdrop.line': '行數',
  'airdrop.reason': '原因',
  'airdrop.duplicated_address': '重複的地址',
  incorrect_address_format: '地址格式不正確',
  'airdrop.incorrect_amount_format': '數量格式不正確',
  'airdrop.airdrop_plan_created': '空投計劃已建立',
  'airdrop.max_50000': '最多50000個地址',
  'airdrop.upload_file_rule': '僅支援CSV格式的附件。',
  'airdrop.to_check_airdrop_eligibility': '請連接錢包以查看空投',
  'airdrop.complete_initialization_to_claim_airdrops': '完成初始化以領取空投',
  'airdrop.complete_initialization_to_view_airdrops': '完成初始化以查看空投',
  'airdrop.you_are_eligible_for': '您可領取：',
  'airdrop.and_more': '以及更多',
  'airdrop.congratulations': '恭喜!',
  'airdrop.airdrop_fee': '空投費',
  'countdown.countdown_plan': '首發計劃',
  'countdown.create_countdown_plan': '建立首發計劃',
  'countdown.my_countdown_plan': '我的建立',
  'countdown.countdown_trading_pair': '倒數計時交易對',
  'countdown.countdown_display': '顯示倒數計時',
  'countdown.token_not_meet_criteria': '幣種不符合首發要求',
  'countdown.countdown_tips': '勾選的交易對會在交易頁面顯示倒數計時',
  'countdown.max_30_days': '從現在起最多30天',
  'countdown.review_countdown_plan': '檢查首發計劃',
  'countdown.countdown_fee': '首發費',
  'countdown.countdown_plan_created': '首發計劃已建立',
  'countdown.trading_will_start_in': '交易開始倒數計時',
  'countdown.trading_will_start_at_YYYY': '交易將在YYYY後開放',
  'countdown.cannot_earlier_than_current_time': '不能早於現在時間',
  'dca.price_limit_buy_tips':
    '啟用後，您的買單僅在等於或低於最高價格時執行。此功能與零費用功能相容。',
  'dca.price_limit_sell_tips':
    '啟用後，您的賣單僅在等於或高於最低價格時執行。此功能與零費用功能相容。',
  'dca.zero_fee': '零費用',
  'dca.zero_fee_buy_tips':
    '啟用「零費用」後，定投訂單將僅限掛單。每個買入價格將設在下單後的訂單簿中最高的出價。請注意，您的訂單可能不會立即或根本不會成交。',
  'dca.zero_fee_sell_tips':
    '啟用「零費用」後，定投訂單將僅限掛單。每個賣出價格將設在下單後的訂單簿中最低的要價。請注意，您的訂單可能不會立即或根本不會成交。',
  'dca.order_canceled_post_only_buy_failed':
    '因訂單簿缺乏買單，無法確定您訂單的買價而下單失敗。',
  'dca.order_canceled_post_only_sell_failed':
    '因訂單簿缺乏賣單，無法確定您訂單的賣價而下單失敗。',
  start_time_cannot_before_current_time: '開始時間不能早於目前時間',
  start_time_must_before_end_time: '開始時間必須早於結束時間',
  list_token: '上幣',
  contract_address_does_not_exist: '合約地址不存在',
  token_listed: '此代幣已上架',
  XXX_is_listed: '正在上幣XXX',
  view_progress: '查看進度',
  pair_create_tips: '交易對可以在DeGate上立即新增，無需任何人的核准。',
  base_token: '基礎代幣',
  quote_token: '報價代幣',
  existing_pair: '交易對已存在',
  trade_now: '立即交易',
  pair_XXX_added_successfully: 'XXX新增成功',
  qty_per_grid: '每個網格的數量',
  grid_minimum_not_reached: '未達到最小值',
  total_profit: '總收益',
  total_apy: '總年化收益率',
  float_profit: '浮動盈利',
  grid_profit_24h: '24小時網格利潤',
  pnl: '損益',
  eligibility: '合格條件',
  rewards: '獎勵',
  view_mining_statistics: '查看挖礦資料',
  your_entry: '您的輸入',
  refunded: '已返還',
  large_price_spread: '訂單簿價差大',
  large_price_spread_tips:
    '訂單簿顯示最低賣出和最高買入價格之間存在較大差距，存在損失風險。建議使用雙資產模式進行投資。',
  continue_anyway: '仍然繼續',
  insufficient_order_book_liquidity_decrease_investment:
    '訂單簿流動性不足。減少投資額。',
  initial_buy: '初始購買',
  closing_sell: '關倉賣出',
  No: '否',
  DCA_TRIGGER_FAIL_TIPS_PRICE_XXX:
    '如果在執行時<b>$XXX的價格低於$PRICE</b>，定投訂單將失敗。',
  zero_fee: '零費用',
  minimum_order_value_is_VALUE: '最小訂單價值為<b>$VALUE</b>。',
  Note: '提示',
  Continue: '繼續',
  estimated_apy: '預估年化收益率',
  based_on_data_from_last_7_days: '基於過去7天的資料',
  top_gainers_24h: '24小時漲幅',
  top_losers_24h: '24小時跌幅',
  listed_tokens: '已上架幣種',
  vol: '成交量',

  let_s_go: '前往',
  reject: '拒絕',
  maximum_N_due_to_price_ticks: '由於價格精度限制，最大值為N',
  Saved: '已保存',
  minimum_order_value_$100_$QUOTE: '最小訂單價值為<b>$100 $QUOTE</b>',
  minimum_order_value_$AMOUNT_$QUOTE_$100:
    '最小訂單價值為<b>$AMOUNT $QUOTE</b>(約 $100)',
  no_restriction_with_market_order: '<b>市價單</b>無該限制',
  go_to_market_order: '前往市價單',
  Mining_Eligibility: '挖礦資格',
  How_to_earn_mining_rewards: '如何賺取挖礦獎勵',
  Order_Value: '訂單價值',
  'mining.mining_tips_BV_BASE_QV_QUOTE':
    '在策略建立時，網格訂單必須至少為<b>BV BASE</b>或<b>QV QUOTE</b>',
  'mining.mining_tips_QV_QUOTE':
    '在策略建立時，網格訂單必須至少為<b>QV QUOTE</b>',
  Mining_Price_Range: '挖礦價格範圍',
  'mining.status_over_price_tips':
    '網格訂單價格必須在<b>挖礦價格範圍之內</b>，即：訂單簿最高買入價格*0.99 ～ 訂單簿最低賣出價格*1.01。',
  'mining.status_over_price_tips_stable':
    '網格訂單價格必須在<b>挖礦價格範圍之內</b>，即：訂單簿最高買入價格 ～ 訂單簿最低賣出價格。',
  Eligible_for_Mining: '符合挖礦條件',
  Mining_Satus: '挖礦狀態',
  Mining_Satus_Mining: '挖礦中',
  Mining_Satus_Standby: '等待中',
  Mining_Satus_Ineligible: '條件不符',
  mining_price_range: '挖礦獎勵範圍',
  rewards_tips_stable:
    '策略建立時滿足挖礦訂單價值的網格訂單，如果其價格在挖礦價格範圍之內可以獲得挖礦獎勵（最高買單價格 ~ 最低賣單價格）',
  rewards_tips:
    '策略建立時滿足挖礦訂單價值的網格訂單，如果其價格在挖礦價格範圍之內可以獲得挖礦獎勵（最高買單價格*0.99 ~ 最低賣單價格*1.01）',
  wrap: '跨鏈',
  Wrap: '跨鏈',
  websites_for_more_information: '更多資訊請瀏覽以下網站',
  official_site: '官方網站',
  wrap_site: '跨鏈網站',
  tips_third_party_site: '您即將離開DeGate並進入第三方網站：',
  wrap_unwrap: '跨鏈兌換',

  Receive: '收款',
  Network: '網路',
  Token_Contract: '代幣合約',
  Contract: '合約',
  please_select_network: '請選擇網路',
  maximum_amount: '最大數量',
  send_USDC_to_this_address: '發送USDC到此地址',
  arpa_airdrop: '$ARPA 空投',
  Failed_to_proceed: '無法繼續',
  Please_select_the_Ethereum_network: '請選擇Ethereum網路',
  NATIVE_USDC_ONLY: '僅限原生 USDC',
  NEVER_send_bridged_USDC: '請勿發送跨鏈USDC',
  I_understand: '我了解',
  recipient_address: '接收地址',

  chain_0: 'DeGate L2',
  chain_1: 'Ethereum',
  chain_17000: 'Ethereum',
  chain_42: 'Kovan',
  chain_42161: 'Arbitrum One',
  chain_421614: 'Arbitrum One',
  chain_10: 'Optimism',
  chain_11155420: 'Optimism',
  chain_137: 'Polygon',
  chain_80002: 'Polygon',
  scan_1: 'Etherscan',
  scan_17000: 'Etherscan',
  scan_42161: 'Arbiscan',
  scan_421614: 'Arbiscan',
  scan_10: 'Opscan',
  scan_11155420: 'Opscan',
  scan_tips:
    '包含此操作的rollup交易尚未送到Ethereum主網上。在此之前，DGSCAN 將<b>不會</b>顯示此操作。',
  Best_Liquidity: '流動性最佳',
  order_partially_filled: '訂單部分成交',
  order_partially_filled_for_liquidity:
    '由於訂單簿流動性突然下降，您剩餘的訂單已被取消。這是為了防止訂單以不利價格成交的保護措施。',
  'orders.export_data_2_year': '匯出近2年資料',
  Community: '社群',

  complete_in_seconds: '立即完成',
  failed_to_send: '送出失敗，請再試一次',
  failed_to_send_try_other_networks: '送出失敗，請嘗試其他網路',
  gas_fee_deducted: '已扣除Gas Fee',
  sum_XXX: '總計 XXX',
  chart_control_7d: '7天',
  chart_control_30d: '30天',
  chart_control_all: '全部',
  chart_control_day: '日',
  chart_control_week: '週',
  chart_control_month: '月',

  Coming: '即將開始',
  leave_survey_title: '嘿，看起來你要離開DeGate了',
  leave_survey_subtitle: '我們可以通過您的回饋做得更好\n請選擇所有符合的選項',
  leave_survey_not_leaving: '我沒有要離開，我會回來',
  leave_survey_other_is_fine: 'Binance/OKX/Kraken等對我來說足夠了',
  leave_survey_bad_experience: '交易體驗不好',
  leave_survey_no_yield: '沒有找到任何收益機會',
  leave_survey_no_needed_token: '沒有找到想要交易的代幣',
  leave_survey_other_reason: '其他（請在下面的輸入框中告訴我們）',
  leave_survey_thanks_for_feedback: '感謝您的回饋',
  Submitted: '已送出',

  doc_title: 'DeGate：去中心化訂單簿交易所 | 免費網格和定投加密交易機器人',
  doc_desc:
    'DeGate 是一家頂尖的去中心化訂單簿交易所，提供數百種加密貨幣的极低費率交易，並提供免費的限價單交易、網格交易和定投機器人。',
  doc_title_spot: ' | 去中心化訂單簿交易所 | DeGate DEX',
  doc_title_grid: ' | 去中心化網格交易機器人 | DeGate DEX',
  doc_title_dca: ' | 去中心化定投交易機器人 | DeGate DEX',
  doc_title_swap: '',

  Notification: '通知',
  read_all: '全部已讀',
  important: '重要',
  general: '一般',
  view_more: '更多',
  thats_all: '目前暫無更多內容',
  XXX_fund_addition_processing: 'XXX 資金添加處理中',
  add_AMOUNT_XXX_to_DeGate: '划入 AMOUNT XXX 至 DeGate',
  XXX_fund_addition_successful: 'XXX 資金添加成功',
  XXX_send_successful: 'XXX 發送成功',
  send_AMOUNT_XXX_to_DeGate: '發送 AMOUNT XXX 至 DeGate (內部轉帳)',
  send_AMOUNT_XXX_to_Ethereum: '發送 AMOUNT XXX 至 Ethereum',
  you_have_received_a_new_airdrop: '您已收到新的空投！',
  AMOUNT_XXX_can_be_claimed_after_YYYY_MM_DD:
    'AMOUNT XXX 可於 YYYY-MM-DD 後領取',
  MARKET_Chart: 'MARKET 圖表',
  grid_free: '網格策略交易<b>免費</b>',
  maker_free_tips: '掛單方交易<b>免費</b>',
  Audit: '審計',
  Tool: '工具',
  About: '關於',

  // 1.16
  list_token_tips: '輸入合約地址以在 DeGate 上幣',
  login_to_view: '登錄後查看',
  login_to_view_balance: '登錄後查看餘額',
  login_to_view_history: '登錄後查看歷史記錄',
  login_to_view_security_options: '登錄後查看安全選項',
  i_accept: '我接受',
  degate_terms_of_service: 'DeGate服務條款',
  privy_terms_of_service: 'Privy服務條款',
  agree: '同意',
  about_asset_key: '關於資產密鑰',
  explantion_asset_key_privy:
    '資產密鑰與用戶地址綁定，是在首次使用電子郵件登入時生成。DeGate協議採用該資產密鑰來授權交易。<br><br><h4>重置資產密鑰</h4>用戶可任意重置資產密鑰。在重置過程中：<br><br>1. 所有進行中的訂單和網格策略將被取消。<br>2. 所有操作功能都將暫停：例如交易、發送、內部轉賬。<br><br>重置將在下一次 DeGate 在以太坊上完成 zk-rollup 上鏈。<br><br><h4>查看資產密鑰</h4>DeGate SDK 的用戶會需要查看資產密鑰。將資產密鑰導入SDK後，用戶就可以在不使用degate.com網頁的情況下完成操作。務必保護好資產密鑰，請勿分享給他人。',
  privy_account_balance_tips:
    '您正在通過郵箱登錄使用DeGate，這種方式僅適用於低價值交易。',
  privy_account_balance_tips2:
    '為了提升安全性，我們強烈建議切換至自我託管錢包，如 MetaMask、Ledger、imToken 或類似選項。',
  dont_show_again_for_30_days: '30 天內不再顯示',
  dont_show_again_for_60_days: '60 天內不再顯示',
  privy_feature_disabled_tips:
    '此功能不支援郵箱登錄，請切換至其他錢包連接方式。',
  Execution: '執行',
  Executed_Orders: '已執行訂單',
  Failed_Orders: '失敗訂單',
  Remaining_Orders: '剩餘訂單',
  avg_price: '平均價格',
  Campaigns: '活動',
  all_Campaigns: '所有活動',
  join_now: '立即參加',
  pools: '礦池',
  you: '我的',
  per_day: '每天',

  marketplace: '廣場',
  latest_grid_orders_filled: '最新成交的網格訂單',
  cumulative_grid_profit: '全站累計網格利潤',
  total_fees_saved: '手續費節省',
  compared_to_CEX: '相較於 CEX',
  earn_XX_more_with_DeGate: '在 DeGate 可多賺 XX%',
  your_profit_with_CEX: '在CEX能賺的收益',
  total_fees_saved_with_DeGate: '使用 DeGate 節省的手續費',
  earn_grid_profit_now: '立即賺取',
  top_strategies: '熱門策略',
  ROI: '收益率',
  roi_desc: '收益率 = 網格總收益 / 初始投資金額',
  '24h_filled_orders': '24小時內成交訂單數',

  // 1.17
  Swap: '兌換',
  liquidity: '流動性',
  market_cap: '市值',
  data_collected_from_DEX: '來自 DEX 的數據',
  my_history: '我的歷史記錄',
  pay: '支付',
  receive: '收到',
  max_slippage: '最大滑點',
  minimum_receive: '最少收到',
  minimum_TOKEN: '最少TOKEN',
  order_value_limit_reached: '訂單價值限制',
  maximum_order_value_over_time_XXXX_USDC:
    '最大訂單價值為 XXXX USDC，此限制會隨時間動態變化。',
  swap_order_placed: '兌換訂單已下單',
  swap_order_filled: '兌換訂單已成交',
  swap_order_failed: '兌換訂單失敗',
  swapping: '兌換中',
  available_network: '支持的網絡',
  minimum_receive_XXX_TOKEN: '最少收到 XXX TOKEN',
  Website: '網站',
  Twitter: '推特',
  Telegram: '電報',
  status_filled: '已成交',
  status_fail: '失敗',
  tips_DeGate_balance_1: 'DeGate 餘額為您的私鑰在 DeGate 控管下的資產總價值。',
  tips_DeGate_balance_2:
    '劃入資金後，您可以即時完成訂單簿交易，或將該資產發送至同一網絡下的任意地址。',
  scan_SOLANA: 'Solscan',
  chain_SOLANA: 'Solana',
  swap_deposit_not_support_yet:
    '目前尚不支持此幣種的劃入功能，將會於未來版本支持。',
  insufficient_pool_liquidity: '流動性不足',
  tips_DCAMinTips_limit_buy_XXX:
    '如果市場價格超過 $XXX，則訂單執行可能失敗，因為您的訂單未達到最低訂單金額 $MIN USDC。您是否仍想繼續？',
  tips_DCAMinTips_limit_sell_XXX:
    '如果市場價格低於 $XXX，則訂單執行可能失敗，因為您的訂單未達到最低訂單金額 $MIN USDC。您是否仍想繼續？',
  no_live_mining_campaign: '目前無正在進行的挖礦活動',
  minimum_quantity_per_grid_25: '每格最低金額：$25',
  minimum_investment: '最低投資：',

  telegram_optional: 'Telegram 帳號（選填）',
  feedback_tips: '感謝您的反饋。若希望我們回覆，請留下聯繫方式',
  est_receive: '預計收到',

  swap_max_slippage_exceeded: '超出最大滑點限制',
  transaction_timeout: '交易超時',
  please_increase_the_max_slippage_setting: '請提高最大滑點設置。',

  total_filled_orders: '總成交訂單數',
  message_limit_order_expired: '限價單已過期並取消',
  message_stop_limit_order_expired: '止盈止損單已過期並取消',
  message_grid_expired: '網格策略已過期並已結束',

  iframe_network_error_message: '由於網路問題，無法顯示圖表',
  no_token_contract: '無代幣合約',
  native_token_of_XXX_chain: 'XXX鏈原生代幣',
  N_found_in_Swap: '兌換中發現N个',
  N_found_in_Orderbook_Trade: '訂單簿交易中發現N个',
  Show_all: '顯示全部',
  sync_to_DeGate_app: '同步至DeGate APP',
  top_guns: '頂尖交易',
  moneybags: '資金雄厚',
  strategy_value: '策略價值',
  whales: '鯨魚',
  hot_pairs: '熱門交易對',
  apy_kings: 'APY 大佬',
  apy_king: 'APY 大佬',
  total_grid_capital: '網格總資金',
  including_grid_strategy_orders: '包含網格策略訂單',
  Grid_Strategy_Creation_Failed: '網格策略創建失敗',
  Grid_Strategy_Creation_Failed_1:
    '網格策略的初始買單部分成交，剩餘部分因訂單簿流動性不足而被取消。',
  Grid_Strategy_Creation_Failed_2: '更多資訊請參閱網格策略詳情。',
  grid_apy_estimate_tips:
    'APY 基於過去7天的數據。<br/><br/>僅當您的新網格策略價格範圍完全涵蓋或被過去7天的歷史價格範圍完全涵蓋時，才提供估算。<br/><br/>例如，假設您的價格範圍是<b>5-10</b>：- 若歷史範圍為<b>6-9</b>（完全涵蓋）或<b>4-11</b>（被完全涵蓋），將提供估算。<br/> - 若歷史範圍為<b>8-12</b>（部分重疊）或<b>12-14</b>（無重疊），則不提供估算，因為這樣會不準確。',
  auto_suggested_profit: '基於過去7天數據：建議每格利潤。',
  referral_code_optional: '推薦碼（選填）',
  invalid_referral_code: '無效推薦碼',
  DeGate_Referral_Program: 'DeGate返佣計畫',
  Referral_Program: '推薦計劃',
  Referral_Program_Desc_V2: '成為認證合作夥伴，從您的推薦網路中持續賺取佣金',
  Referral_Program_Desc_V2_text2: '全鏈透明、鏈上記錄，打造長期收益',
  Referral_Program_Desc:
    '將您的影響力變現，加入緊密的生態系。我們堅信長期主義，誠摯期望您的社群與DeGate共同成長。 <br/> <br/> 您可以邀請朋友/粉絲，賺取手續費返佣，創造被動收入。交易量越大，返佣越多！',
  Apply_Now: '立即申請',
  Commission_Earned: '已賺取佣金',
  Unclaimed_Commission: '未領取佣金',
  Invites: '邀請人數',
  Commission_Rate: '佣金比例',
  referral_commission_rate_tips:
    '您可從直接邀請的使用者獲得一級佣金，也可從他們邀請的使用者獲得二級佣金。',
  Share_my_referral_link: '分享我的推薦連結',
  Claimable_Commission: '可領取佣金',
  Referral_Details: '推薦詳情',
  Level: '級別',
  Level_1: '一級',
  Level_2: '二級',
  Type: '類型',
  Activity: '活動',
  Credited: '已入帳',
  referral_trading_fee: '交易手續費',
  referral_level_1_commission: '一級佣金',
  referral_pending_commission_tips:
    '該金額正在處理中，系統兌換為USDC後會自動入帳。',
  your_referral_link_is_expired: '您的推薦連結已失效',
  claim_value: '市值',
  My_Invites: '我的邀請',
  Referee: '被邀請人',
  Commission: '佣金',
  Transaction: '交易',
  Time_Joined: '加入時間',
  one_order: '1筆訂單',
  N_Orders: 'N筆訂單',
  Filled: '已成交',
  out_of_range: '超出範圍',

  show_chart: '顯示圖表',
  please_enter_grid_parameters_first: '請先輸入網格參數',
  go_to_app_store: '前往 App Store',
  go_to_google_play: '前往 Google Play',
  scan_to_download_app: '掃描下載 App',
  get_DeGate_app_now: '立即獲取 DeGate App',
  install_beta_version: '安裝內測版本',
  how_to_install_beta_version: '如何安裝內測版本',
  download_testflight_from_app_store: '在 App Store 下載 TestFlight',
  click_to_download_testflight: '點擊下載 TestFlight',
  come_back_for_next_step_after_testflight_is_installed:
    'TestFlight 安裝完成後返回進行下一步',
  download_DeGate_in_testflight: '在 TestFlight 中下載 DeGate',
  click_to_download_DeGate: '點擊下載 DeGate',
  click_install: '點擊「安裝」',

  low_liquidity: '警告：流動性不足',
  low_liquidity_tips: '檢測到訂單簿流動性不足。請仔細確認以避免潛在損失。',

  min_receive_tips:
    '若價格進一步下跌，您的交易將被取消。以下為您保證收到的最低數量',
  est: '預估',
  hide_other_tokens: '隱藏其他幣種',
  share: '分享',
  more_trading_methods_here: '更多交易方式',

  pool_liquidity: '池流動性',
  '24h_pool_volume': '24h 成交額',
  mkt_cap: '市值',
  pool_info: '池信息',
  DEX: 'DEX',
  pool: '池',
  pool_address: '池地址',
  pool_created: '池創建時間',

  beta_test_tips: '此功能處於內測階段。請聯繫我們參與測試。',
  swap_success_receive_AMOUNT_TOKEN: '兌換成功，收到 AMOUNT_TOKEN',
  hide_balances_less_than_10: '隱藏 <$10 餘額',

  Sender: '發送方',
  Recipient: '接收方',
  My_CHAIN_Address: '我的 CHAIN 地址',
  CHAIN_Address: 'CHAIN 地址',
  From: '來自',
  To: '至',

  send_status_help: `<b>處理中</b> <br />處理發送請求。<br /><br /><b>成功</b> <br />資產已成功交付至接收方地址。<br /><br /><b>已完成</b><br /> 包含此交易的區塊已達到最終性。`,

  minimum_buy: '最少購入',
  minimum_sell: '最少賣出',

  check_wallet_compatibility: '檢查錢包兼容性',
  wallet_incompatible: '錢包不兼容',
  wallet_incompatible_tips:
    '您正在使用非標準錢包（例如，多方計算（MPC）錢包），DeGate 不支持此類錢包。請切換至標準錢包。',
  initialization_desc_step3: `您將會收到三次簽名請求，簽名不會產生費用。`,

  records_are_unavailable_yet: '目前尚未支顯示記錄',
  receive_history_tips:
    '請前往 APP 首頁複製您的錢包地址，並於區塊鏈瀏覽器中查詢這些記錄。',
  rate_limit_tips: '請求過於頻繁，請稍後再試',
  Warning: '警告',
  Error_fetching_data: '取得資料時發生錯誤',
  Connection_Status: '連線狀態',
  Market_Info: '市場資訊',
  Market_Info_tips: '例如價格、24小時變化（%）、市值、流動性、交易量等',
  Last_updated: '最後更新',
  TIME_ago: 'TIME前',
  Asset_Info: '資產資訊',
  Your_available_balance: '您的可用餘額',
  Disconnected: '已斷开',
  Earn: '理財',
  Portfolio: '投資組合',
  My_Portfolio: '我的投資組合',
  My: '我的',
  Total_Deposits: '總存款',
  Claimable_Rewards: '可領取獎勵',
  My_Deposit: '我的存款',
  APY: '年化收益率',
  Base_APY: '基礎年化收益率',
  Bonus_APY: '獎勵年化收益率',
  native_Apy: '本金年化收益率',
  Total_APY: '總年化收益率',
  performance_fee: 'Performance Fee',
  About_Vault: '關於金庫',
  Protocol: '協議',
  Vault: '金庫',
  Asset: '資產',
  Chain_Details: '鏈的詳情',
  Deposit: '充值',
  Withdraw: '提現',
  Est_Daily_Rewards: '預估每日獎勵',
  Accruing: '累積中',
  It_becomes_claimable_upon_maturity: '到期後可被領取',
  Tokens: '幣種',
  Value: '價值',
  XXX_available_in: '可用的XXX',
  maximum_XXX: '最大：$XXX',
  minimum_XXX: '最少：$XXX',
  earn_deposit_sol_balance_tips: '您至少需持有 0.05 SOL 以繼續操作',
  claim_rewards: '領取獎勵',
  Return: '返回',
  usdc_supplied_from: 'USDC 的來源',
  multi_chain: '多鏈',
  multi_chain_tips:
    '多鏈代幣提升用戶體驗，使用戶無需複雜的資金跨鏈操作即可在任何鏈上進行投資。它還可用於支付所有鏈上的網絡費用。',
  multi_chain_balances: '多鏈餘額',
  convert_to_multi_chain_usdc_tips: '您可以透過跨鏈轉為<b>多鏈 USDC</b>',
  Bridge: '跨鏈橋',
  multi_chain_usdc: '「多鏈 USDC」目前指 Solana 與 Base 鏈上的 USDC',
  explantion_fees:
    '<h4>兌換手續費率</h4><ul><li>參考<a href="https://docs.degate.com/about-degate/swap">費率層級</a></li></ul> <br><h4>網路手續費</h4><ul><li>依據鏈上即時費率計算</li></ul>',
  search_history: '搜尋歷史',
  '24h_txns': '24 小時交易',
  Markets: 'Markets',
  warning_excessive_balance_detected: '警告：偵測到過量餘額',
  warning_excessive_balance_detected_tips1:
    '您目前的 DeGate 帳戶並非設計用於儲存大量資產。您的餘額已超過我們建議的上限 XXX 美元。',
  warning_excessive_balance_detected_tips2:
    '請立即減少您的持倉，以在帳戶遭到攻擊等情況下降低資產損失的風險。',
  warning_excessive_balance_detected_tips2_app:
    '為了更好地保護您的資金，我們強烈建議您安裝 DeGate App，並在應用內創建或匯入錢包。',
  download_app: '下載 App',
  receive_data_tips:
    '請點擊右上角的“查看地址”，然後將該地址貼到區塊鏈瀏覽器中以查看交易紀錄。',
  verify_account: '驗證帳戶',
  est_network_fee: '預估網路手續費',
  arrival_time: '到帳時間',
  gas_refund_tips: '退回金額可能為多鏈 USDC 及／或對應鏈原生代幣',
  network_fee: '網路手續費',
  estimated_fee: '預估費用',
  actual_fee: '實際費用',
  refund: '退款',
  Browser: '瀏覽器',
  transaction_details: '交易詳情',
  smart_contract_interaction: '智能合約交互',
  interact_with: '交互合約',

  // 1.26

  Raffle: '抽獎活動',
  round_N: '第 N 輪',
  pick_your_number: '選擇號碼',
  win_1_million: '贏 $1,000,000 美元',
  participating: '正在參與',
  become_a_millionaire_now: '立刻成為百萬富翁',
  get_free_tickets: '獲取免費獎券',
  verify_1_million_prize_fund: '驗證百萬獎金池',
  lucky_number: '幸運號碼',
  winning_bitcoin_block: '比特幣開獎區塊',
  block_hash: '區塊雜湊值',
  participated: '已參與',
  ticket_redemption_phase_ends_in_XXX: '距離兌換截止還有 XXX',
  redemption: '兌換',
  pending_draw: '等待開獎',
  announcement: ' 公告結果',
  my_tickets_total: '我的抽獎券 / 本輪總數',
  view_rules: '查看規則',
  earn_up_to_200_thousand_dollars_bonus: '最多可獲得 <b>20 萬美元獎金！</b>',
  invite_friends_now: '<b>立即邀請</b>好友參與！',
  prizes: '獎項',
  grand_prize: '頭獎',
  second_prize: '二獎',
  third_prize: '三獎',
  fourth_prize: '四獎',
  fifth_prize: '五獎',
  sixth_prize: '六獎',
  seventh_prize: '七獎',
  eighth_prize: '八獎',
  draw_starts_once_the_bitcoin_block_is_confirmed:
    '抽獎會在指定的比特幣區塊確認後開始',
  ticket_redemption_closed: '獎券兌換已結束',
  congratulations: '恭喜中獎！',
  you_ve_won: '您贏得了',
  good_luck_for_next_round: '祝你下輪好運',
  you_weren_t_in_this_round: '本輪未參加',
  join_the_next_round: '馬上加入下一輪！',
  tickets_in_round_N: '第 N 輪獎券',
  my_tickets: '我的獎券',
  total_tickets: '本輪總獎券數',
  total_tickets_tips:
    '當獎券兌換階段結束時，系統會將所有券號的加密雜湊值上傳至 Base 鏈，確保開獎過程透明、不可竄改',
  hash_of_total_tickets: '全部獎券雜湊值',
  hash_value_tips:
    '雜湊值 = SHA256(Ticket1, Ticket2, ..., TicketN)，其中 Ticket1 到 TicketN 代表本輪中所有已兌換的抽獎券號碼，並依照數字由小到大排序後產生的雜湊值',
  verify_hash: '驗證雜湊值',
  reviewing: '審核中',
  manual_review_in_progress_payout_will_follow_shortly:
    '正在進行人工審核，稍後發獎',
  received: '已收到',
  points: '積分',
  no_prize_this_time: '本輪未中獎',
  all_winners: '查看所有中獎名單',
  winning_ticket: '1 張中獎券',
  winning_tickets_N: 'N 張中獎券',
  Pick_your_ticket_number: '挑選您的獎券號碼',
  Manual: '手動',
  Range: '區間',
  Random: '隨機',
  Feeling_lucky: '試試手氣',
  Redeem: '兌換',
  Invalid_number: '無效號碼',
  Ticket_already_taken: '已被選走，請重新選號',
  N_Ticket: 'N 張獎券',
  N_Tickets: 'N 張獎券',
  Points_needed: '需要積分',
  Points_available: '可用積分',
  Redemption_Successful: '兌換成功',
  Ticket_Unavailable: '獎券不可用',
  N_Ticket_Unavailable: 'N 張獎券不可用',
  N_Tickets_Unavailable: 'N 張獎券不可用',
  Looks_like_someone_just_grabbed_this_number:
    '有人剛剛選走了這個號碼，請重新選號',
  Insufficient_Points: '積分不足',
  You_have_0_point_and_cannot_redeem_tickets: '你目前擁有 0 積分，無法兌換獎券',
  You_have_POINTS_points_and_can_redeem_a_maximum_of_TICKETS_tickets:
    '你擁有 POINTS 積分，最多可兌換 TICKETS 張抽獎券',
  How_to_acquire_points: '如何獲得積分？',
  Number_Start: '開始',
  Number_End: '結束',
  Please_enter_the_start_number_and_end_number: '請輸入起始號碼與結束號碼',
  End_number_must_be_greater_than_start_number: '結束號碼必須大於起始號碼',
  Those_tickets_have_already_been_taken: '這些號碼已被選走',
  Looks_like_someone_just_grabbed_some_of_the_tickets:
    '看起來這些號碼剛剛被其他人搶先了，請再試一次',
  Number_of_tickets: '獎券張數',
  Generate: '產生',
  Please_enter_the_number_of_tickets: '請輸入要產生的抽獎券張數',
  N_random_tickets: 'N 張隨機獎券',
  N_random_ticket: 'N 張隨機獎券',
  Generate_Again: '重新產生',
  Dashboard: '個人儀表板',
  My_Points: '我的積分',
  My_Participations: '我的參與紀錄',
  N_rounds: '第 N 輪',
  N_round: '第 N 輪',
  My_Winnings: '我的中獎紀錄',
  Invite_Friends_and_Earn_20_Extra_on_Their_USDC_Winnings:
    '邀請好友並獲得他們中獎 USDC 的 <b>20% 額外獎勵</b>',
  They_win_more_you_earn_more_and_there_is_no_cap:
    '他們中越多，你賺越多，無上限',
  Invite_your_friends_to_DeGate:
    '邀請好友參加 DeGate 抽獎，每當他們中獎，你可獲得 20% 額外獎金',
  My_Referral_Link: '我的邀請連結',
  Copy_Link: '複製連結',
  Total_Invited: '已邀請人數',
  Total_Rewards: '我的獎勵',
  Points: '積分',
  Tickets: '抽獎券',
  Winnings: '中獎金額',
  Points_can_be_earned_by_using_the_DeGate_Swap_feature:
    '積分可透過使用 DeGate 兌換功能獲得',
  Go_to_Swap: '前往',
  Winning: '中獎金額',
  Redeem_tickets: '兌換獎券',
  Gift: '贈送',
  Rewards: '獎勵',
  Invite_Rewards: '邀請獎勵',
  How_to_Join: '如何參加？',
  Step_N: '步驟 N',
  Earn_points_by_swapping_on_DeGate: '使用 DeGate 進行兌換累積積分',
  Use_your_points_to_redeem_raffle_tickets_during_the_redemption_phase:
    '在兌換階段使用積分兌換獎券，參加抽獎。',
  Check_the_results_after_the_round_ends_your_lucky_moment_might_be_waiting:
    '等待開獎結果，也許你就是下一位幸運兒！',
  Digits_Matched: '符合的位數',
  All_Match: '完全符合 8 位號碼',
  Matches_Last_N: '符合最後 N 位',
  Winner: '中獎者',
  Prize: '獎項',
  FAQ: '常見問題',
  Rules: '規則',
  How_does_it_Work: '抽獎機制介紹',
  how_to_participate: '如何參與',

  N_Point: '+N 積分',
  N_Points: '+N 積分',
  You_just_earned_points_from_your_swap: '您剛剛透過兌換賺得積分',
  Use_them_to_redeem_raffle_tickets_to_win_1_million_dollars:
    '使用這些積分兌換獎券，有機會贏得 <br/><b>$1,000,000！</b>',
  Join_Raffle: '參加抽獎',
  please_enter_amount: '請輸入金額',
  claim_prizes: '領取獎金',
  claim_your_prizes: '領取你的獎金',
  all_unclaimed_usdc_will_be_sent_to_your_base_address_shortly:
    '所有未領獎的 USDC 將自動發送至你的Base 鏈地址',
  Claim_your_invite_rewards: '領取您的邀請獎勵',
  Claim_Invite_Rewards: '領取邀請獎勵',
  amount_needed: '所需數量',
  download_apk: '下載 APK',
  download_app_get: '下載',
  download_page_app_store: 'App Store',
  download_page_google_play: 'Google Play',
  download_page_apk: 'APK',
  download_page_scan_to_download: '掃碼下載',
  download_page_partners: '合作夥伴',
  Matches_for_8th_Prize: '尾數或尾數±1',
  Select_Network: '選擇網路',
  All_Networks: '所有網路',
  Filtering_with_CHAIN_network: '透過CHAIN進行篩選。',
  Claim_History: '領獎紀錄',
  My_Dashboard: '我的儀表板',
  Claim_Winnings: '領取獎金',
  team_up_to_boost_your_odds_of_winning_1_million_usdc:
    '組隊提升</div>贏得 1,000,000 USDC </div>的機會',
  Create_a_Team_Now: '立即創建團隊',
  Leader: '隊長',
  Leader_Bonus: '隊長獎勵',
  Leader_Bonus_tips: '創建隊伍，當你的隊伍獲勝後，將獲得額外 10% USDC！',
  Team_Tickets: '團隊抽獎券',
  Create_Team: '建立團隊',
  Enter_Team_Name: '輸入你的團隊名稱',
  Please_enter_a_team_name: '請輸入團隊名稱',
  Name_already_taken_try_different_one: '名稱已被使用，請嘗試其他名稱',
  Team_created: '團隊創建成功',
  Invite: '邀請',
  Invite_Team_Members: '邀請隊員',
  Team_Details: '團隊詳情',
  Team_Points: '團隊積分',
  Pool_My_Points: '加入我的積分',
  Rewards_are_split_by_points_contributed: '獎勵將依據每人貢獻積分比例分配',
  pool_points_tips: '將我的積分轉入團隊共享池，獎勵將按貢獻比例分配',
  Please_enter_a_number_that_is_a_multiple_of_10: '請輸入 10 的倍數',
  Insufficient_points: '積分不足',
  Added_POINTS_points_to_TEAM: '已為團隊增加 POINTS 積分',
  Join_the_team_to_boost_your_odds_of_winning_1_million_usdc:
    '加入隊伍提升贏得<br/> <b>1,000,000 USDC 的機會</b>',
  Congratulations_You_ve_joined_the_team: '恭喜！你已加入該團隊',
  You_re_already_in_this_team: '你已在此團隊中',
  Solo: '個人參與',
  Team: '組隊參與',
  Select_Team: '選擇團隊',
  My_Teams: '我的團隊',
  team_tickets_total: '團隊抽獎券 / 總額',
  how_it_works: '活動說明',
  how_to_play_as_a_team: '團隊玩法說明',
  invite_tips1: '他們抽中 USDC，你可額外獲得 20% 額外獎勵',
  invite_tips2: '他們透過 Swap 賺積分，你可額外拿 20% 積分獎勵',
  distribution: '分配方式',
  new_rule_1_1:
    '<b>1.賺取積分</b><br/> <b>進行 Swap 即可累積積分</b><br/>每次在DeGate上進行Swap，您都會自動獲得積分。',
  new_rule_2_1:
    '<b>2. 如何贏得獎金</b><br/> <b>兌換抽獎券</b><br/>在兌換階段，使用10個積分可獲得1張抽獎券。',
  new_rule_2_2:
    '<b>選擇你的號碼</b><br/>每張抽獎券都有一組獨特的 8 位數號碼 (00000000–99999999)。你可以自行選擇號碼，或讓系統隨機產生。',
  new_rule_2_3:
    '<b>比對中獎號碼</b><br/>將你的抽獎券號碼與本輪的中獎號碼進行比對，匹配的位數越多(從尾數開始)，獎金越高。',
  new_rule_2_4: '例如，當中獎號碼為  <b>12345678：</b>',
  match_pattern: '比對規則',
  winning_tickets: '中獎抽獎券',
  represents_any_digit: '✱ 代表任意數字',
  new_rule_3: '<b>3. 公開透明機制</b>',
  new_rule_3_1:
    '<b>區塊鏈產生隨機數字</b><br/>中獎號碼是根據實際的比特幣區塊產生——為兌換結束後的第 6 個區塊。無法被預測或更改。',
  new_rule_3_2:
    '<b>開源演算法</b><br/>中獎的比特幣區塊哈希會透過開源程式碼轉換為中獎號碼 —— 你可以在 GitHub 上查閱並驗證。',
  new_rule_3_3:
    '<b>獎金資金證明</b><br/>超過 120 萬枚 USDC 已預先儲存，可透過以下錢包地址公開驗證：<a href="https://basescan.org/address/0xdB5c7E18FB657F6a8f193024D7F0Aa251Df8C7d6" target="_blank">0xdB5...8C7d6</a> 和 <a href="https://basescan.org/address/0x1c7F26c156caEA62Ad11F6a634051Df43129A656" target="_blank">0x1c7...9A656</a>',
  team_rule_1:
    '<b>1.加入或建立隊伍</b><br/>組隊參加可提升贏得頭獎 —— 1,000,000 USDC 的機率。',
  team_rule_2:
    '<b>2.加入你的積分</b><br/>每一輪都可以將你的積分加入團隊共享池。',
  team_rule_3:
    '<b>3.一起兌換抽獎券</b><br/>任何隊員都可以使用團隊積分為全隊兌換抽獎券。',
  team_rule_4:
    '<b>4.積分不浪費</b><br/>每輪結束時，未使用的團隊積分將自動轉換為隨機抽獎券。',
  team_rule_5:
    '<b>5.公平分獎</b><br/>若你的隊伍中獎，獎勵將依照每位成員貢獻的積分比例分配。',
  prize: '獎項',
  all_8_digits: '8 位數字全符合',
  last_N_digits: '後 N 位符合',
  no_luck: '未中獎',
  Team_Points_Breakdown: '團隊積分詳情',
  member: '隊員',
  Points_Contributed: '貢獻積分',
  you_didnt_win_this_round_better_luck_next_time: '此輪未中獎 — 下次再接再厲！',
  Rewards_Received: '已領取獎勵',
  Points_can_be_earned_by_using_the_DeGate_Swap: '使用 DeGate Swap 可累積積分',
  Add_to_Team: '加入團隊',
  Team_Refund: '團隊退款',
  Receive_from_Team: '從團隊獲得',
  from_invitee_winnings: '來自受邀者中獎分潤',
  from_invitee_points: '來自受邀者 Swap 獎勵',
  draw_starts_once_the_winning_bitcoin_block_is_fully_confirmed:
    '中獎比特幣區塊完全確認後，抽獎開始。',
  Invite_Friends_and_Earn_20_Extra: '邀請朋友可額外獲得<b>20% 額外獎勵<b>',
  Team_Points_Available: '可用團隊積分',
  me: '我',
  Stocks: '股票',

  // 1.28
  est_account_rent_CHAIN_NUM: '$NUM（用於 CHAIN 鏈租金）',
  est_transaction_cost_NUM: '$NUM（用於交易成本）',
  filter_by_network: '依網路篩選',
  manage_tokens_title: '幣種管理',
  manage_tokens_short: '管理',
  manage_menu_status_on: '開啟',
  manage_menu_status_off: '關閉',
  manage_tokens_my_assets: '我的資產',
  manage_tokens_other_assets: '其他資產',
  manage_tokens_add_btn: '新增幣種',
  manage_tokens_contract_address: '合約地址',
  manage_tokens_contract_address_placeholder: '輸入合約地址',
  manage_tokens_symbol: '符號',
  manage_tokens_decimal: '精度',
  manage_tokens_not_found: '未找到幣種，請檢查合約地址和網路。',
  manage_tokens_added: '{TOKEN}已在您的幣種列表內。',
  manage_tokens_remove_confirm_title: '移除幣種',
  manage_tokens_remove_confirm_desc: '將{TOKEN}從您的幣種列表中刪除？',
  manage_tokens_remove_confirm_btn: '移除',
  Mainnet: '主網',
  Testnet: '測試網',
  More_Services: '更多服務',
  current_block: '目前區塊',
  fully_confirmed: '已完全確認',
  create_account: '建立帳戶',
  create_account_tips:
    '首次使用時，您需要建立帳戶。整個流程約需 <b>30 秒</b>。',
  account_created: '已建立帳戶',
  please_create_account_first: '請先建立帳戶',
  unable_to_create_account: '無法建立帳戶',
  this_asset_is_self_custodied_in_your_CHAIN_address:
    '此資產由您自我託管，存放於您的 <b>CHAIN 位址</b>',
  generate_wallet_address: 'DeGate 現已支援以下新鏈。',
  generate_wallet_address_tips: '點擊「確認」以建立您的錢包地址。',
  updating: '正在更新',
  please_wait: '請稍候',
  close_this_window_to_resume_what_you_were_doing:
    '關閉此視窗以繼續您先前的操作',
  Funds: '資金',
  Route: '路由',
  Meme: 'Meme',
  free_team_tickets: '免費團隊票券',
  free_team_tickets_tips: '達成里程碑後，您的團隊票券<b>翻倍（2 倍）</b>',
  if_the_target_isn_t_met_this_round_progress_resets:
    '本輪未達成目標，進度將重置',
  n_tickets_to_claim: '可領取 N 張票券',
  claim_bonus: '領取獎勵',
  any_unclaimed_tickets_will_be_automatically_claimed_when_the_redemption_phase_ends:
    '兌換階段結束時，任何未領取的票券將自動領取。',
  n_tickets_claimed: '已領取 N 張票券',
  n_tickets_to_claim_m_claimed: '可領取 N 張（已領取 M 張）',
  all_n_tickets_claimed: '已領取全部 N 張票券',
  generate_N_tickets: '生成 N 張票券',
  TRY_YOUR_LUCK_NOW: '現在試試手氣',
  ENTER_WIN_BIG: '參加並贏取大獎！',
  FEELING_LUCKY: '覺得手氣不錯嗎？',
  HIT_THAT_000000: '擊中 000000！',
  Enter: '參加',
  N_Points_for_1_Entry: 'N 點可獲 1 次參加',
  awaiting: '等候中…',
  numbers_incoming: '號碼即將揭曉…',
  HOLD_TIGHT_GOOD_LUCK: '抓緊了，祝你好運！',
  Entry: '參加',
  Refund: '退款',
  how_to_earn_points: '如何獲得點數？',
  how_to_earn_points_tips: '在 DeGate 進行兌換或參與迷因遊戲即可賺取點數。',
  Go_to_meme: '前往迷因',
  Verify: '驗證',
  Winning_Block: '中獎區塊',
  Entry_Time: '參加時間',
  Points_History: '點數紀錄',
  Raffle_History: '抽獎紀錄',
  Verify_Raffle_Results: '驗證抽獎結果',
  Fair_play_proof_in_3_steps: '3 步驟公平性證明',
  Proof_of_fair_play_in_3_steps: '三步驟的公平性證明',
  verify_tips_1: '1. 公告 Secret 的「指紋」',
  verify_tips_1_1:
    '抽獎開始前，我們會先公布 Secret 的哈希（其「指紋」）—— 若不改變該哈希，就無法更換 Secret。',
  verify_tips_2: '2. 下一個區塊決定結果',
  verify_tips_2_1:
    '按下 Enter 後，由 Secret 與下一個 Base 區塊產生 6 位數的幸運號碼。',
  verify_tips_3: '3. 揭露並驗證',
  verify_tips_3_1:
    '打開抽獎紀錄，點擊「揭露」與「驗證」。將其 hash 與已公布的指紋比對並重新計算——數字相同表示沒有舞弊。',
  verify_tips_4: '你揭露 Secret 後，系統會為下一次參加封存新的 Secret。',
  hash_of_secret: 'Secret 的哈希',
  secret: 'Secret',
  winning_block: '中獎區塊',
  keccak256: 'keccak256(Secret, Block hash) % 1000000',
  hash_of_secret_for_next_entry: '下一次參加用的 Secret 哈希',
  proof: '證明',
  entry_time: '參加時間',
  not_revealed: '尚未揭露',
  the_secret_is_a_system_generated_input_used_to_compute_the_lucky_number:
    'Secret 是用於計算幸運號碼的系統生成輸入。為確保公平，DeGate 會事先公布其哈希作為承諾，之後便無法更改。',
  the_next_block_on_base_chain_after_you_click_enter:
    '你按下 Enter 後，Base 鏈上的下一個區塊。',
  reveal_and_verify: '揭露並驗證',
  download_tickets: '下載票券',
  Total_Winnings: '總中獎金額',
  time_limited: '限時',
  Exclusive_Friend_Rewards: '好友限定獎勵',
  Register_an_account_You_and_your_friend_get_10_FREE_entries_each:
    '註冊帳戶 - <br/><b>你和你的好友各可獲 10 次免費參加</b>',
  Get_Rewards: '領取獎勵',
  You_re_eligible_for_10_FREE_Entries: '你符合資格，可獲<b>10 次免費參加</b>',
  Expires_in_XXX: 'XXX 後到期',
  Invite_a_friend_to_join_DeGate: '邀請好友加入 DeGate',
  invite_text_1:
    '我拿到一個 DeGate 邀請活動——我們各有 10 次免費抽獎機會（最高可贏 $5K）。是限時的，所以趕快轉給你。',
  you_received: '你已獲得',
  free_entries_10: '10 次免費參加',
  Free_Entries_times_N: '免費參加次數：N',
  EXPIRED: '已到期',
  flash_op_create_account_tips: '建立帳戶 - 你和你的好友各可獲 10 次免費參加',
  offer_is_expired: '此優惠已到期',
  offer_is_limited_to_new_users_only: '此優惠僅限新用戶',
  get_rewards_now: '立即領取獎勵',
  Later: '稍後',
  so_close_try_again: '就差一點！再試一次？',
  no_luck_try_again: '運氣不佳。再試一次？',
  no_route_fund: '找不到路由——請嘗試不同金額或稍後再試。',
  trading_restriction_notice: '交易限制通知',
  trading_restriction_notice_tips:
    '根據 <a href="https://assets.backed.fi/legal-documentation/restricted-countries" target="_blank">Backed</a> 的受限國家/地區清單，您所在地區不可交易此鏈上股票代幣：',
  trading_restriction_notice_tips_2:
    '此限制僅適用於 Backed 發行的部分代幣；您仍可交易其他代幣。',
  btn_got_id: '知道了',
  Invalid_SOL_rent: '用於租金的 SOL 不足',

  stocks: {
    Hot_Stocks: '熱門股票',
    Last: '最新價',
    Chg: '漲跌',
    Chg_Percent: '漲跌幅',
    Stock_Heatmap: '股票熱力圖',
    Stock_Heatmap_AUM: '股票熱力圖（AUM）',
    Holders_per_Stock: '持有人數',
    Holders_per_Stock_top_20: '持有人數（Top 20）',
    Trades_per_Stock: '成交筆數',
    Trading_volume_DEX_per_Stock: '交易量(DEX)',
    Trading_vol: '交易量',
    Daily_Trading_Accounts_per_Stock: '每檔股票的每日交易帳戶數',
    Token_Holders_AUM: '代幣持有人數＆AUM',
    Issuer: '發行人',
    Onchain_AUM: '鏈上 AUM',
    Valuation: '估值',
    Dex_Trading_Vol: '24H DEX 交易量',
    Onchain_Supply: '鏈上供應量',
    Onchain_Holders: '鏈上持有人數',
    Audit_URL: '審計 URL',
    Dex_Liquidity: 'DEX 流動性',
    Websites: '網站',
    News_Flow: '新聞動態',
    Trading_Vol_Dex_Liquidity: '交易量與 DEX 流動性',
    AUM_desc:
      'AUM（受託資產規模）指由發行方 Backed Fi 在鏈上發行之該股票的美元總價值。',
    Onchain_Opportunity: '鏈上機會',
    '24h APY': '24h 年化報酬率',
    stocks_doc_title: '鏈上股票儀表板｜收益洞察與策略',
    total_aum: '總 AUM',
    total_unique_holders: '不重複持有人總數',
    total_dex_volume: '總 DEX 交易量',
    total_tvl: '鏈上資金池流動性',
    total_assets: 'xStock 資產數量',
    Trade_with_ZERO_FEES: '零手續費交易',
    Legal_Info: '法律資訊',
  },
  swap_error: {
    Swap_failed_return_below_minimum_receive:
      '兌換失敗：返回數量低於最低可接收數量。',
    Insufficient_liquidity_for_this_token_reduce_amount_and_try_again_later:
      '此代幣流動性不足。請降低金額並稍後重試。',
    Swap_failed_price_impact_exceeds_limit: '兌換失敗：價格衝擊超出限制。',
    Swap_failed_honeypot_or_high_risk_token_detected:
      '兌換失敗：偵測到誘餌合約（honeypot）或高風險代幣。',
    Swap_failed_insufficient_sol_for_rent:
      '兌換失敗：用於租金的 SOL 不足。請存入少量 SOL 後再試。',
    Return_below_minimum_receive: '返回數量低於最低可接收數量',
    Insufficient_liquidity_for_this_token: '此代幣流動性不足',
    Price_impact_exceeds_limit: '價格衝擊超出限制',
    Honeypot_or_high_risk_token_detected:
      '偵測到誘餌合約（honeypot）或高風險代幣。',
    Insufficient_sol_for_rent: '用於租金的 SOL 不足',
    Swap_failed_insufficient_funds_for_gas: '兌換失敗：用於 gas 的資金不足。',
    Insufficient_funds_for_gas: '用於 gas 的資金不足',
    Estimated_network_fee_is_less_than_the_actual_amount_required:
      '預估網路費低於實際所需',
  },
  gift: {
    Gift_Box: '禮盒',
    View_Gift_Box: '查看禮盒',
    Download_App: '下載應用',
    Your_gift_awaits: '您的禮物已就緒',
    Open_Now: '立即打開',
    Cash_Gift_for_CopyTrade: '自動跟單現金禮',
    Receive_gift_in_DeGate_App: '在 DeGate App 領取禮物',
    This_gift_box_was_claimed_by_a_different_account_you_previously_used:
      '該禮盒已被您之前使用的其他帳戶領取',
    Youve_received_a_Cash_Gift_for_CopyTrade: '您已收到 {GIFT TYPE}',
    has_been_sent_to_your_CopyTrade_account: '已發送至您的自動跟單帳戶',
    View_My_Account: '查看您的帳戶',
    claim_your_gift_please_create_a_DeGate_account:
      '領取禮物前，請先建立您的 DeGate 帳戶',
    Total_Gift_Amount: '禮物總額',
    Expired_at_DATE: '於 DATE 過期',
    Gifts_claimed_CLAIMED_TOTAL: '禮物（已領取 CLAIMED/TOTAL）',
    Today: '今天',
    Youve_received_your_gift_cash_Outgoing_transfers_will_be_enabled_after_your_Copy_Trade_bot_completes_its_first_trade:
      '您已收到現金禮。自動跟單機器人完成第一筆交易後即可轉出。',
    Others_were_faster_Try_again_next_time: '已被他人搶先，下次再試！',
    Connect_wallet_to_claim: '連接錢包以領取',
    Expired_in_DATE: '已於 DATE 到期',
  },
  turboRange: {
    Turbo_Range: '區間寶',
    my_positions: '我的持倉',
    my_turbo_range: '我的區間寶',
    yesterday_yield: '昨日收益',
    total_yield: '總收益',
    Details: '詳情',
    all_products: '全部產品',
    invert_USDC: '投入USDC',
    apy_7D: '7日年化報酬率',
    you_have_no_position: '您沒有持倉',
    invest: '投入',
    create_position: '建立倉位',
    price_range: '價格區間',
    earn_yield_while_TSLA_price_stays_in_your_range:
      '{TSLA}的價格在您設定的區間內，即可賺取收益',
    earn_yield_while_price_stays_in_your_range:
      '當價格保持在區間內時即可賺取收益',
    est_apy: '預計年化收益率',
    estimated_annual_percentage_yield_based_on_last_7_days_data:
      '預計年化收益率，基於最近7日數據',
    est_annual_yield: '預計年收益',
    enter_amount_to_continue: '請輸入數量',
    set_price_range: '設定價格區間',
    current_price: '目前價格',
    current: '目前',
    min_price: '最低價格',
    max_price: '最高價格',
    please_enter_an_amount: '請輸入數量',
    maximum_500000: '最大 500000',
    adjust_the_input_to_proceed: '請調整輸入',
    please_reduce_amount: '請減少數量',
    not_enough_balance_to_proceed: '餘額不足',
    processing_deposit_to_liquidity_pool: '正在將資金存入流動性池',
    you_can_close_this_window_we_ll_handle_it:
      '您可以關掉這個視窗，剩下的我們來處理。',
    investment_successful: '投入成功',
    invested: '實際投入',
    returned: '已返還',
    view_my_position: '查看我的持倉',
    investment_failed: '投入失敗',
    about_turbo_range: '關於區間寶',
    turbo_range_puts_your_funds_into_a_liquidity_pool_within_the_price_range_you_set_when_others_trade_in_that_range_you_earn_fees:
      '<b>區間寶</b>會將你的資金投入你設定價格區間內的流動池。當其他人在該區間內交易時，你即可賺取手續費。',
    example: '範例',
    let_s_say_you_invest_1000_USDC_in_the_TSLA_USDC_pool_and_set_a_range_of_270_330_TSLA_s_current_price_is_300:
      '假設你投入 1000 USDC 到 TSLA/USDC 流動池，並設定區間為 270–330（假設當前 TSLA 價格為 300）。',
    step1: '1. 系統會計算並分配約 476 USDC 用於購買約 1.59 股 TSLA；',
    step2: '2. 因此，你將持有約 524 USDC 與約 1.59 股 TSLA；',
    step3: '3. 這些資產會在你設定的區間內加入流動池。',
    what_happens_in_different_price_scenarios: '不同價格情境下會發生什麼？',
    desc_1: '1. 價格維持在 270–330 之間',
    desc_1_1: '你會持續賺取交易手續費。',
    desc_2: '2. 價格跌破 270',
    desc_2_1:
      '你的持倉將變為約 3.43 股 TSLA 加上已獲得的手續費。如果你相信價格會回升，可以選擇繼續持有。',
    desc_3: '3. 價格漲破 330',
    desc_3_1:
      '你的持倉將變為約 1023 USDC 加上已獲得的手續費。你獲得了約 23 USDC 的收益，另加手續費。',
    underlying_on_chain_assets: '底層鏈上資產',
    principal: '本金',
    unclaimed_yield: '未領取收益',
    in_range: '在區間內',
    out_of_range: '在區間外',
    total_pnl: '總盈虧',
    underlying_assets: '底層資產',
    initial_principal: '初始本金',
    closed_principal: '結束本金',
    principal_pnl: '本金盈虧',
    created_at: '建立於',
    closed_at: '結束於',
    claim_yield: '領取收益',
    all_TSLA_will_be_converted_to_USDC: '所有的{TSLA}會轉換成{USDC}',
    est_receive: '預計收到',
    claim_successful: '領取成功',
    has_been_added_to_your_account: '已存入您的帳戶',
    claim_failed: '領取失敗',
    convert_TSLA_to_USDC_and_receive_USDC_only:
      '將 {TSLA} 兌換為 {USDC}，並僅接收 {USDC}',
    receive_both: '同時接收兩種代幣',
    convert_TSLA_to_USDC_and_receive_USDC:
      '將 {TSLA} 兌換為 {USDC}，並接收 {USDC}',
    receive_TSLA: '接收 {TSLA}',
    withdrawing: '正在提現',
    withdrawal_successful: '提現成功',
    withdrawal_failed: '提現失敗',
    Simple_Earn: '單幣理財',
    view_in_turbo_range: '在區間寶中查看',
    position_history: '倉位紀錄',
    initial_investment: '初始投入',
    click_history_above_for_details: '點擊上方ICON歷史查看詳情',
    how_does_turbo_range_earn_yield: '區間寶如何產生收益？',
    transaction_in_progress: '1 筆交易處理中',
    transaction_successful: '1 筆交易成功',
    transaction_failed: '1 筆交易失敗',
    N_transactions_in_progress: 'N 筆交易處理中',
    N_transactions_successful: 'N 筆交易成功',
    N_transactions_failed: 'N 筆交易失敗',
    position: '持倉',
    all_time_yield: '累積收益',
    yesterday_apy: '昨日年化報酬率',
    duration: '期間',
    all_time_apy: '累積年化報酬率',
    updating: '更新中…',
    will_be_calculated_on_DATE: '將於 DATE 計算',
    returned_to_your_wallet: '已退回至你的錢包',
    principal_upon_closure: '關閉時退回之本金',
    est_apy_tips: '這裡顯示的預估年化報酬率係依所選期間的歷史數據推算而得。',
    invalid_range: '範圍無效',
    faq_1: '什麼是流動性池？',
    faq_1_text:
      '流動性池是部署在區塊鏈上的智慧合約，用於存放兩種代幣，例如 ETH 與 USDC。使用者可直接透過該智慧合約在這兩種代幣之間進行交易。任何人都能把自己的代幣投入池中提供流動性，並依比例分享交易手續費。',
    faq_2: '我如何透過提供流動性來賺取手續費？',
    faq_3: '投資「區間寶」有哪些優勢？',
    faq_3_text1:
      '傳統投資（例如買入並持有 TSLA 股票）只有在價格上漲時才賺錢。區間寶不同：在盤整或上漲行情都能獲得收益。',
    faq_3_text2: '<b>盤整：</b> 在你設定的價格區間內持續賺取交易手續費',
    faq_3_text3: '<b>上漲：</b> 本金增值，同時持續獲得交易手續費',
    put_simply: '簡單來說：',
    put_simply_text: '不僅價格上漲會獲利，盤整時也能賺錢。',
    faq_4: 'DeGate 會控制我的「區間寶」倉位嗎？',
    faq_4_text:
      '不能。你的「區間寶」倉位完全在鏈上，並保存在你自己的錢包裡。只有你本人可以存取或提領資金。',
    faq_4_n: '如何用區間寶逢低買入？',
    faq_4_n_text:
      '假設某資產目前價格為 100，你想在約 75 附近累積。你可以建立一個價格區間為 50–100 的區間寶。好處是：當價格在此區間內波動時，區間寶會持續產生收益，幫助降低你的平均進場成本。',
    faq_4_n_text2:
      '當價格跌到 50 時，記得關閉區間寶。若不關閉，當價格回到 50 以上時，該倉位會再次開始買入。',
    faq_6: '當價格走出區間時，區間寶會自動關閉嗎？',
    faq_6_text:
      '不會，自動不會關閉。若價格回到區間內，區間寶會恢復產生收益。若要停止已出圈的區間寶，需手動關閉。',
    websites: '網站',
    liquidity_pool: '流動性池',
    liquidity_pool_age: '流動性池運行時長',
    total_value_locked_of_raydium: '{Raydium} 的總鎖倉量（TVL）',
    XX_as_of_DATE: '截至 {DATE}：{XX}',
    market_cap_of_paxg: '{PAXG} 的市值',
    desc_xstocks:
      'TSLAx 為 Backed Assets (JE) Limited 發行之 xStock。xStock 的發行符合瑞士法律，並已於 2025 年 5 月 8 日獲列支敦士登金融市場管理局（FMA）核准。',
    desc_gold:
      'PAXG 為 Paxos Trust Company 發行之數位資產。每枚 PAXG 由存放於倫敦 LBMA 金庫的一金衡盎司黃金作為背書。Paxos 受紐約州金融服務署（NYDFS）監管。',
    desc_btc:
      'cbBTC 為 Coinbase 發行、以比特幣做背書之代幣。每枚 cbBTC 代表 Coinbase 托管的一枚比特幣，並可按 1:1 贖回。Coinbase 為美國上市公司，受美國監管機關監理。',
    desc_native_coin_ETH_NETWORK: '{ETH} 是 {NETWORK} 網路的原生代幣。',
    legal_documentation: '法律文件',
    factsheet: '產品資料概覽',
    audit_reports: '審計報告',
    Onesheet: '單頁簡介',
    on_chain_assets_and_protocol: '鏈上資產與協議',
    entry_price: '入場價格',
    active_capital: '在投資金',
    withdraw_and_close: '提領並關閉',
    withdraw_and_claim: '提領並領取',
    incl_unclaimed_yield: '含未領取收益',
    capital_withdrawn: '已提領資金',
    yield_claimed: '已領取收益',
    fee_pre_charged: '此費用在你開倉時已預先扣除，關閉倉位時會返還到你的錢包。',

    price_is_out_of_range_see_tips: '價格超出區間。查看提示。',
    what_do_you_think_XXX_s_price_will_do_next:
      '你認為 {XXX} 的價格接下來會怎麼走…',
    rise_and_move_back_into_my_price_range: '上漲並回到我的價格區間',
    move_sideways_around_the_current_price: '在當前價格附近橫盤',
    keep_falling: '持續下跌',
    if_you_think_XXX_s_price_will_rise_and_move_back_into_your_price_range:
      '如果你認為 {XXX} 的價格會上漲並回到你的價格區間……',
    you_will: '你可以',
    hold_and_wait: '持倉等待',
    if_you_think_XXX_s_price_will_move_sideways_around_the_current_price:
      '如果你認為 {XXX} 的價格會在當前價位附近橫盤……',
    close_your_position_and_open_a_new_one: '平倉並開啟新的倉位',
    close_position: '平倉',
    if_you_think_XXX_s_price_will_keep_falling:
      '如果你認為 {XXX} 的價格會持續下跌……',
    close_position_and_withdraw_USDC: '平倉並提領 USDC',
    adjust_price_range: '調整價格區間',
    adjust_now: '立即調整',
    increase_investment: '追加投入',
    increasing_investment: '正在追加投入',
    investment_increased: '已追加投入',
    investment_increase: '追加投入',
    increase_failed: '追加失敗',
    total_principal: '總本金',
    total_withdrawal_and_claim: '總提現與領取',
    investModeSingle: '單幣',
    investModeDual: '雙幣',
    nagative_invest_tips:
      '該負數表示資金已退回至您的錢包。詳情請查看倉位歷史。',
    APY_Backtest: 'APY 回測',
    Historical_APY_desc:
      '此處顯示的歷史年化報酬率（APY）為回測結果，基於所選時間段的歷史資料計算，反映了若在該時段開始時進行投資所能獲得的 APY。',
    Historical_APY: '歷史 APY',
    XXX_Overall_APY: 'XXX 整體 APY',
    Partially_in_range: '部分位於區間內',
    In_range: '在區間內',
    Out_of_range: '超出區間',

    // Strategies Marketplace
    strategies: '策略廣場',
    top_apy: '年化效率',
    hot_today: '今日熱門',
    best_returns: '歷史戰績',
    roi: '總回報率',
    total_return: '總回報',
    connect_wallet_to_see_positions: '連接錢包後查看您的持倉',
    re_open: '重新開倉',
    view_details: '查看詳情',
    copy: '複製',
    initial_price: '初始價格',
  },
  Product: '產品',
  filter: '篩選',
  Failed: '失敗',
  History_currently_unavailable: '目前無法顯示歷史紀錄。',
  History_currently_unavailable_tips:
    '請前往「首頁」分頁複製你的錢包地址，並在區塊鏈瀏覽器查看交易記錄。',
  Approval: '授權',
  Contract_Call: '合約调用',
  Unlimited: '無上限',
  APY_1: '1 APY',
  External_Sites: '外部網站',
  XXX_Refundable: 'XXX 可退還',
  Refundable_on_data_release: '數據释放後退還',
  est_time: '預估時間',
  Refundable_when_position_is_closed: '持仓關閉時可退還',

  go_to_turbo_range: '前往區間寶',
  go_to_earn: '前往單币理財',
  in_address: '在地址中',
  in_copy_trade: '在自動跟單中',
  source_network: '',
  destination_network: '',
  move_usdc_across_chains: '以 1:1 比例跨鏈轉移 USDC',
  bridge_successful: '跨鏈成功',
  no_result_found: '查無結果',
  enter_address: '輸入地址',
  scan: '掃描',
  check_address_format: '請檢查位址格式',
  invalid_address: '無效的位址',
  estimated_network_fee: '預估網路手續費',
  incl_solana_rent_of_XXX: '含 Solana 租金 $XXX',
  check_my_balance: '查看我的餘額',
  moving_your_USDC_to_destination_network: '正在將您的 USDC 轉至目標網路…',
  you_don_t_have_enough_USDC_to_pay_for_the_network_fee:
    '您的 USDC 不足以支付網路手續費。',
  change_fee_token: '更換手續費代幣',
  estimated: '預估',
  actual: '實際',
  receive_usdc: '收款 USDC',
  from_other_wallets: '從其他錢包',
  bridge_usdc: '跨鏈 USDC',
  consolidate_to_one_chain: '合併至單一鏈',
  simple_earn_disabled_deposit_tips: '',
  Time_to_complete: '完成所需時間',
  You_Pay: '您需支付',
  Returned_to_your_wallet_when_position_is_closed: '持仓關閉時將退回至您的錢包',
  Refundable_Fee: '可退還費用',
  Fee_Refunded: '費用已退還',
  Claiming: '領取中',
  Reinvesting: '再投資中',
  Withdrawing: '提領中',
  Adding: '新增中',
  Cash_Buy: '購買',
  Buy_with_cash_card: '以現金／卡片購買',

  est_gas_needed_for_network_fee: '已為網路手續費預留 $EST_GAS USDC',
  available_amount: '可用金額',
  current_balance: '目前餘額',
  reserved_for_network_fee: '已預留作網路手續費',
  maximum_available: '最大可用',
  use_max: '使用最大值',
  edit_amount: '編輯金額',
  insufficient_network_fee: '網路手續費不足',
  separator_comma: '，',
  insufficient_network_fee_tips:
    '需要支付 $FEE 的網路手續費。你可以使用 $XXX、USDC、USDT 或其他代幣支付。',
  pay_with_another_token: '使用其他代幣支付',

  History_is_currently_unavailable_for_CHAIN:
    '目前無法取得 {CHAIN} 的歷史記錄。詳情請至區塊鏈瀏覽器查看。',
  Check_on_Explorer: '前往區塊鏈瀏覽器',
  Min: '最小',
  Max: '最大',
  enable_notifications: '啟用通知？',
  receive_notification_when_out_of_price_range: '價格超出區間時接收通知',
  we_ll_notify_you_when_your_turbo_range_goes_out_of_range:
    '當你的區間寶超出設定區間時，我們會通知你。',

  referral: '返佣',
  referral_code: '推薦代碼',
  your_referrer: '你的推薦人',
  please_confirm_within_10_seconds: '請在 10 秒內確認。',
  confirmation_expired: '確認已過期。請重試。',

  select_Open_in_Default_Browser_from_the_menu:
    '從選單選擇「在預設瀏覽器中開啟」。',
  you_need_a_DeGate_account_to_continue: '需要 DeGate 帳戶才能繼續。',
  claim_now: '立即領取',
  please_wait_it_takes_xx_seconds: '請稍候，約需 ~xx 秒。',
  you_have_received_a_Turbo_Range_position_worth_XXX:
    '你已獲得一筆約 ~$XXX 的「區間寶」倉位。',
  view_my_balance: '查看我的餘額',
  sorry_youve_already_claimed_once: '抱歉，你已經領取過一次。',
  gift_card_expired: '禮品卡已過期',
  gift_card_has_not_been_activated: '禮品卡尚未啟用',
  gift_card_has_been_claimed: '禮品卡已被領取',
  please_open_this_page_on_your_mobile_phone: '請在手機上開啟此頁面',
  open_with_DeGate_App: '以 DeGate App 開啟',
  sign_in: '登入',
  Show_more: '顯示更多',
  signature_free_mode_tips:
    '在此模式下，你可以在無需簽名的情況下兌換代幣。要切換模式，點擊右上角的設定圖示。',
  invite_to_degate_experience_enhancement_program:
    '您受邀參與 DeGate 體驗增強計畫',
  as_a_selected_user_youll_get: '作為入選用戶，您將獲得：',
  a_smoother_app_experience: '更流暢的 App 體驗',
  dedicated_one_on_one_support: '專屬一對一客服',
  private_client_desk: '私享客戶專席',
  private_client_desk_upperCase: '私享客戶專席',
  through_this_desk_you_may: '透過本專席,您可享受:',
  receive_priority_operational_support: '優先營運支援',
  direct_communication_with_our_strategy_and_operations_team:
    '直連我們的策略與營運團隊',
  early_access_to_new_products: '搶先體驗新產品',
  access_exclusive_privileges_and_customized_benefits:
    '尊享專屬權益與客製化福利',
  private_client_desk_access_path_intro: '您可透過以下路徑存取私享客戶專席:',
  private_client_desk_access_path_home_menu: '首頁 > 選單 > 私享客戶專席',
  private_client_desk_access_path_home_settings: '首頁 > 設定 > 私享客戶專席',
  private_client_desk_access_bottom_left_corner: '您可在左下角存取私享客戶專席',
  WhatsApp: 'WhatsApp',
  Signal: 'Signal',
  Email: '電子郵件',
  welcome_aboard: '歡迎加入',
  youre_now_among_a_select_group_enjoying_an_enhanced_degate_experience:
    '您現已成為少數享有強化版 DeGate 體驗的用戶。',
  link_expired: '連結已失效',
  please_update_your_app_to_the_latest_version: '請升級到最新App版本',
  chart_is_currently_unavailable: '圖表暫不可用',
};
export default zhTW;
